In [4]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm

import multiprocessing

In [5]:
# Download associaiton file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/regenie_127phenotypes_lofteeHC_mac20.parquet -o /home/dnanexus/data_dir/
# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/loftee_mac20_associations_bh_corrected.parquet -o /home/dnanexus/data_dir/

bt = pl.read_parquet('/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20.parquet')
bt = bt.filter(pl.col('pval_fdr')<=0.05)
bt

dxpy.utils.resolver.ResolutionError: Unable to resolve "regenie_127phenotypes_lofteeHC_mac20.parquet" to a data object or folder name in '/processed_data/REGENIE_results'

shape: (2_289, 21)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ region     ┆ chr ┆ phenotype  ┆ cohort     ┆ … ┆ controls_a ┆ info       ┆ pval_fdr  ┆ pval_bonf │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ lt         ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ i64 ┆ str        ┆ str        ┆   ┆ ---        ┆ str        ┆ f64       ┆ f64       │
│            ┆     ┆            ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ ENSG000001 ┆ 1   ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.000007  ┆ 0.003328  │
│ 32855      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.076632; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=128.00 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.038502  ┆ 1.0       │
│ 52841      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.196317; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=38.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.003376  ┆ 1.0       │
│ 10243      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.094032; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=85.001 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 4.5099e-4 ┆ 1.3530e-4 │
│ 18137      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.173370; ┆ 6         ┆ 4         │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=25.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 12  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.006545  ┆ 1.0       │
│ 73064      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.189177; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=41.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ ENSG000001 ┆ 7   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.02095   ┆ 1.0       │
│ 82095      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.200004; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=24.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.036208  ┆ 1.0       │
│ 64741      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.155565; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=40.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000002 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045581  ┆ 1.0       │
│ 05189      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.156523; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=20.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.027724  ┆ 1.0       │
│ 82752      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.161667; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=36.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045758  ┆ 1.0       │
│ 56586      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.129988; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=29.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [ ]:
# Download annotation file for variant-gene mapping
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fill_na.parquet -o /home/dnanexus/data_dir/

anno = pl.read_parquet(
    '/home/dnanexus/data_dir/annotations_fill_na.parquet', 
    columns=['id', 'region']
)

anno

[===========================================================>] Completed 10,077,386,508 of 10,077,386,508 bytes (100%) /home/dnanexus/data_dir/annotations_fill_na.parquett

shape: (74_534_850, 2)
┌─────────────────────┬─────────────────┐
│ id                  ┆ region          │
│ ---                 ┆ ---             │
│ str                 ┆ str             │
╞═════════════════════╪═════════════════╡
│ chr18:56603287:T:G  ┆ ENSG00000091164 │
│ chr18:56611517:A:G  ┆ ENSG00000091164 │
│ chr19:34340475:G:A  ┆ ENSG00000166398 │
│ chr19:5256210:T:C   ┆ ENSG00000105426 │
│ chr19:5257316:G:C   ┆ ENSG00000105426 │
│ …                   ┆ …               │
│ chr16:179290:T:A    ┆ ENSG00000086506 │
│ chr7:148348869:A:G  ┆ ENSG00000174469 │
│ chr5:138680487:A:G  ┆ ENSG00000044115 │
│ chr4:70839545:A:G   ┆ ENSG00000132463 │
│ chr15:72103067:A:AC ┆ ENSG00000066933 │
└─────────────────────┴─────────────────┘

In [8]:
anno_pheno = (
    anno.join(
        bt.select(['region', 'phenotype']).unique(), 
        on='region', 
        how='inner'
    )
)

anno_pheno

shape: (75_468_554, 3)
┌─────────────────────┬─────────────────┬─────────────────────────────────┐
│ id                  ┆ region          ┆ phenotype                       │
│ ---                 ┆ ---             ┆ ---                             │
│ str                 ┆ str             ┆ str                             │
╞═════════════════════╪═════════════════╪═════════════════════════════════╡
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ seated_height_int               │
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ sitting_height_int              │
│ chr2:215390704:C:T  ┆ ENSG00000115414 ┆ forced_expiratory_volume_in_1s… │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ arm_fat_percentage_left_int     │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ arm_predicted_mass_right_int    │
│ …                   ┆ …               ┆ …                               │
│ chr15:72103059:G:GC ┆ ENSG00000066933 ┆ sitting_height_int              │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ standing_height_int             │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ forced_vital_capacity_fvc_int   │
│ chr2:158525435:T:C  ┆ ENSG00000144283 ┆ hip_circumference_int           │
│ chr15:72103067:A:AC ┆ ENSG00000066933 ┆ sitting_height_int              │
└─────────────────────┴─────────────────┴─────────────────────────────────┘

In [9]:
# Download phenotypes: covariates and PRS corrected
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/phenotypes/corrected_cov_PRS_traits_EUR.parquet -o /home/dnanexus/data_dir/

phenos = (
    pl.read_parquet('/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet')
    .select(['individual'] + bt['phenotype'].unique().to_list())
    .rename({'individual':'sample'})
)

phenos

# long_phenos = (
#     phenos
#     .unpivot(
#         index='sample',
#         on=bt['phenotype'].unique().to_list(),
#         variable_name='phenotype',
#         value_name='pheno_value'
#     )
#     .drop_nulls()
# )

# print(long_phenos['phenotype'].value_counts(sort=True))
# long_phenos

Error: path "/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet"
already exists but -f/--overwrite was not set

shape: (502_408, 122)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample  ┆ hand_grip_ ┆ reticuloc ┆ weight_im ┆ … ┆ glycated_ ┆ pulse_rat ┆ forced_ex ┆ forced_ex │
│ ---     ┆ strength_r ┆ yte_perce ┆ pedance_i ┆   ┆ haemoglob ┆ e_int     ┆ piratory_ ┆ piratory_ │
│ str     ┆ ight_int   ┆ ntage_int ┆ nt        ┆   ┆ in_hba1c_ ┆ ---       ┆ volume_in ┆ volume_in │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ int       ┆ f64       ┆ _1s…      ┆ _1s…      │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ ---       ┆           ┆ ---       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1000020 ┆ -0.013968  ┆ -0.909716 ┆ -0.879798 ┆ … ┆ 0.285142  ┆ null      ┆ 0.375105  ┆ -0.336233 │
│ 1000107 ┆ 0.136971   ┆ -0.205456 ┆ -0.561876 ┆ … ┆ -0.863708 ┆ null      ┆ -0.023328 ┆ -0.159696 │
│ 1000161 ┆ -0.100593  ┆ 0.608602  ┆ -0.875212 ┆ … ┆ -0.085335 ┆ -0.525995 ┆ 0.20756   ┆ -0.800259 │
│ 1000172 ┆ -1.299507  ┆ null      ┆ -0.882824 ┆ … ┆ -0.186041 ┆ 2.147343  ┆ -0.910427 ┆ -0.843187 │
│ 1000199 ┆ 0.181297   ┆ -1.344078 ┆ 0.495026  ┆ … ┆ 0.193317  ┆ 0.021232  ┆ 0.409832  ┆ 0.080928  │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2277715 ┆ -0.659119  ┆ -1.095749 ┆ -1.136784 ┆ … ┆ -0.165814 ┆ -0.373664 ┆ null      ┆ null      │
│ 5348683 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2332162 ┆ 0.041775   ┆ 1.033763  ┆ 0.846444  ┆ … ┆ -1.359996 ┆ null      ┆ -0.885237 ┆ 0.431337  │
│ 4594543 ┆ -1.774773  ┆ null      ┆ null      ┆ … ┆ -1.201779 ┆ null      ┆ null      ┆ null      │
│ 9999993 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# Download genotype (long gt) file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/gt_long.parquet -o /home/dnanexus/data_dir/

long_gt = (
    pl.scan_parquet('/home/dnanexus/data_dir/gt_long.parquet')
    .select(['id', 'sample', 'gt'])
)
long_gt.head().collect()

[===========================================================>] Completed 27,974,638,284 of 27,974,638,284 bytes (100%) /home/dnanexus/data_dir/gt_long.parquett                                                        ] Downloaded 603,979,776 of 27,974,638,284 bytes (2%) /home/dnanexus/data_dir/gt_long.parquet[==========>                                                 ] Downloaded 5,033,164,800 of 27,974,638,284 bytes (17%) /home/dnanexus/data_dir/gt_long.parquet[============================================>               ] Downloaded 21,038,628,864 of 27,974,638,284 bytes (75%) /home/dnanexus/data_dir/gt_long.parquet

shape: (5, 3)
┌────────────────────────────┬─────────┬─────┐
│ id                         ┆ sample  ┆ gt  │
│ ---                        ┆ ---     ┆ --- │
│ str                        ┆ str     ┆ i8  │
╞════════════════════════════╪═════════╪═════╡
│ chr10:20020006:C:T         ┆ 5317620 ┆ 1   │
│ chr10:20020007:TTTTCTTGC:T ┆ 5546988 ┆ 1   │
│ chr10:20020010:T:C         ┆ 2793793 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1722739 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1139673 ┆ 1   │
└────────────────────────────┴─────────┴─────┘

In [ ]:
# Get the list of phenotype columns (names) for aggregation
pheno_cols = [c for c in phenos.collect_schema().names() if c != "sample"]

# 2. The Main Pipeline
result = (
    long_gt
    .filter(pl.col("gt") == 1)

    # A. Join Genotypes with ALL Phenotypes at once (Wide)
    #    Row count stays same as long_gt! No explosion.
    .join(
        phenos.lazy(), 
        on="sample", 
        how="inner"
    )
    
    # B. Group by Variant ID
    .group_by("id")
    .agg(
        # C. Compute stats for ALL phenotype columns simultaneously
        #    This is extremely fast in Polars
        pl.col(pheno_cols).count().name.suffix("_n"),
        pl.col(pheno_cols).mean().name.suffix("_mean"),
        pl.col(pheno_cols).std().name.suffix("_std"),
    )
    
    # C. Pack triplets into Structs
    #    We create one column per phenotype, e.g., 'height' = {n: 10, mean: 1.5, std: 0.2}
    .select(
        pl.col("id"),
        *[
            pl.struct(
                n    = pl.col(f"{p}_n"),
                mean = pl.col(f"{p}_mean"),
                std  = pl.col(f"{p}_std")
            ).alias(p) 
            for p in pheno_cols
        ]
    )
    
    # D. Unpivot the Struct columns
    #    This turns columns "height", "bmi" -> rows under column "phenotype"
    #    The values are carried in the "stats" struct.
    .unpivot(
        index="id",
        on=pheno_cols,          # The struct columns we just made
        variable_name="phenotype",
        value_name="stats"
    )
    
    # E. Unnest the stats
    #    Expands the struct {n, mean, std} into three actual columns
    .unnest("stats")

    .sink_parquet('/home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrelated_appv.parquet', engine="streaming")
    # .collect(engine="streaming")
)

result

## Old code

In [15]:
sel_pheno = 'standing_height_int'

tmp = (
    anno_pheno.filter(pl.col('phenotype')==sel_pheno)
    .lazy()
    .join(
        long_gt,
        on='id',
        how='inner'
    )

    .join(
        long_phenos.filter(pl.col('phenotype')==sel_pheno).lazy(),
        on=['sample', 'phenotype'],
        how='inner'
    )

    .group_by(['id', 'region', 'phenotype'])
    .agg(
        n_individuals = pl.len().cast(pl.Int32),
        mean_pheno_value = pl.col('pheno_value').mean().cast(pl.Float32),
        std_pheno_value = pl.col('pheno_value').std().cast(pl.Float32),
    )

    .collect(engine='streaming')
)

tmp

shape: (4_307_050, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ id             ┆ region         ┆ phenotype      ┆ n_individuals ┆ mean_pheno_va ┆ std_pheno_val │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ lue           ┆ ue            │
│ str            ┆ str            ┆ str            ┆ i32           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆               ┆ f32           ┆ f32           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ chr11:48078046 ┆ ENSG0000014917 ┆ standing_heigh ┆ 14            ┆ 0.203621      ┆ 0.680058      │
│ :GT:G          ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr11:48070210 ┆ ENSG0000014917 ┆ standing_heigh ┆ 10            ┆ 0.163916      ┆ 0.327801      │
│ :G:A           ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr11:48079038 ┆ ENSG0000014917 ┆ standing_heigh ┆ 1             ┆ -0.729936     ┆ null          │
│ :T:A           ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr11:48076801 ┆ ENSG0000014917 ┆ standing_heigh ┆ 1             ┆ -1.780711     ┆ null          │
│ :G:A           ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr11:48076294 ┆ ENSG0000014917 ┆ standing_heigh ┆ 1             ┆ 0.398215      ┆ null          │
│ :T:C           ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ chr11:14682021 ┆ ENSG0000015227 ┆ standing_heigh ┆ 2             ┆ 0.066053      ┆ 0.076738      │
│ :TTACAA:T      ┆ 0              ┆ t_int          ┆               ┆               ┆               │
│ chr11:47995254 ┆ ENSG0000014917 ┆ standing_heigh ┆ 1             ┆ 0.400572      ┆ null          │
│ :TATC:T        ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr11:47998675 ┆ ENSG0000014917 ┆ standing_heigh ┆ 7             ┆ -0.291961     ┆ 0.758731      │
│ :G:A           ┆ 7              ┆ t_int          ┆               ┆               ┆               │
│ chr10:12246413 ┆ ENSG0000016603 ┆ standing_heigh ┆ 1             ┆ -1.320655     ┆ null          │
│ 7:A:C          ┆ 3              ┆ t_int          ┆               ┆               ┆               │
│ chr11:14676164 ┆ ENSG0000015227 ┆ standing_heigh ┆ 1             ┆ 0.381092      ┆ null          │
│ :A:G           ┆ 0              ┆ t_int          ┆               ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘