In [58]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm

from plotnine import *
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

from anngeno import AnnGeno
# pl.Config.set_tbl_rows(15)

In [59]:
# Configuration and paths
or_threshold_pheno = 0.95
or_threshold_anno = 0.95

eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'

maf=1e-3
n = !wc -l $eur_samples_path
n_eur = int(n[0].split(' ')[0])
mac = maf*(2*n_eur)

config_path = "/home/dnanexus/ukbgym/config_wgs.yaml"
with open(config_path) as f:
    config = yaml.safe_load(f)

# Read the variant consequence configuration
records = []
for group, consequences in config["variant_consequences"].items():
    for consequence in consequences:
        records.append({'variant_class': group, 'vep_consequence': consequence})
var_cons = pl.DataFrame(records)


# Use a list comprehension to flatten the nested dictionary into records
records = [
    {
        "category": category,
        "annotation": anno,
        "color": props["color"],
        "label": props["label"],
        "annotation_dir": props.get("direction", 1),
    }
    for category, annos in config["rare_variant_annotations"].items()
    for anno, props in annos.items()
]

# Create the DataFrame directly from the list of records
anno_config_df = pl.DataFrame(records)
all_annotation_list = anno_config_df.select(pl.col("annotation")).to_series().to_list()

anno_config_df

shape: (15, 5)
┌───────────────────┬──────────────────────────────┬─────────┬─────────────────┬────────────────┐
│ category          ┆ annotation                   ┆ color   ┆ label           ┆ annotation_dir │
│ ---               ┆ ---                          ┆ ---     ┆ ---             ┆ ---            │
│ str               ┆ str                          ┆ str     ┆ str             ┆ i64            │
╞═══════════════════╪══════════════════════════════╪═════════╪═════════════════╪════════════════╡
│ plof              ┆ loftee_hc                    ┆ #DD4344 ┆ LOFTEE HC       ┆ 1              │
│ missense          ┆ am_pathogenicity             ┆ #feb72d ┆ AlphaMissense   ┆ 1              │
│ missense          ┆ esmscoremissense             ┆ #feb72d ┆ ESM1v           ┆ -1             │
│ genetic_diversity ┆ cadd_raw                     ┆ #1f77b4 ┆ CADD Raw        ┆ 1              │
│ conservation      ┆ gpn_star_llr_calibrated_mean ┆ #942c80 ┆ GPN-Star        ┆ -1             │
│ …                 ┆ …                            ┆ …       ┆ …               ┆ …              │
│ splicing          ┆ absplice_dna_max             ┆ #28a745 ┆ AbSplice (max)  ┆ 1              │
│ splicing          ┆ absplice2_max                ┆ #28a745 ┆ AbSplice2 (max) ┆ 1              │
│ regulatory_nondir ┆ promoterai_abs               ┆ #00A99D ┆ PromoterAI abs  ┆ 1              │
│ regulatory_nondir ┆ abexp_min                    ┆ #00A99D ┆ AbExp min       ┆ -1             │
│ regulatory        ┆ promoterai                   ┆ #00A99D ┆ PromoterAI      ┆ 1              │
└───────────────────┴──────────────────────────────┴─────────┴─────────────────┴────────────────┘

In [60]:
exp_annos_df = pl.DataFrame({
    "category": ['non-coding indel', 'non-coding indel', 'non-coding indel', 'non-coding indel'],
    'annotation': ['noncoding_indel', 'intronic_indel', 'utr5_indel', 'utr3_indel'],
    "color": ['gray', 'gray', 'gray', 'gray'],
    'label': ['non-coding indel', 'non-coding indel', 'non-coding indel', 'non-coding indel'],
    'annotation_dir': [1, 1, 1, 1],
})

anno_config_df = pl.concat([anno_config_df, exp_annos_df])

In [ ]:
anno = pl.scan_parquet("/home/dnanexus/data_dir/genebass394genes_olink371genes_variants_union_annotated_genocode_251103.parquet")

# existing_annos = [c for c in all_annotation_list if c in anno.collect_schema().names()]

existing_annos = ['loftee_hc', 'am_pathogenicity', 'noncoding_indel', 'intronic_indel', 'utr5_indel', 'utr3_indel']

# Filter variant classes
variant_class = "coding"
consequences_for_group = var_cons.filter(
    pl.col('variant_class') == variant_class
)['vep_consequence'].to_list()
filter_expression = pl.any_horizontal(
    (pl.col(c) == 1) for c in consequences_for_group if c in anno.collect_schema().names()
)

min_range = -2000
max_range = +0

anno = (
    anno
    .with_columns(
        noncoding_indel = (pl.col('vep_gencode_non_coding')==True) & ((pl.col('ref').str.len_chars()!=1) | (pl.col('alt').str.len_chars()!=1))
    )
    .with_columns(
        intronic_indel = pl.col('noncoding_indel') & (pl.col('consequence_intron_variant')==1),
        utr5_indel = pl.col('noncoding_indel') & (pl.col('consequence_5_prime_utr_variant')==1),
        utr3_indel = pl.col('noncoding_indel') & (pl.col('consequence_3_prime_utr_variant')==1),
    )
    .select(
        set(['id', 'region', 'TSS', 'Strand', 'gene_length', 'gene_name', 'dist_to_tss', 'vep_gencode_non_coding']).union(set(existing_annos))
    )
    .collect(engine='streaming')
    # .drop_nulls()
)

anno

shape: (25_373_677, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ utr3_inde ┆ gene_name ┆ region    ┆ intronic_ ┆ … ┆ loftee_hc ┆ gene_leng ┆ utr5_inde ┆ id       │
│ l         ┆ ---       ┆ ---       ┆ indel     ┆   ┆ ---       ┆ th        ┆ l         ┆ ---      │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ i8        ┆ ---       ┆ ---       ┆ str      │
│ bool      ┆           ┆           ┆ bool      ┆   ┆           ┆ i64       ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ false     ┆ LRP2      ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 235427    ┆ false     ┆ chr2:169 │
│           ┆           ┆ 081479    ┆           ┆   ┆           ┆           ┆           ┆ 197167:T │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :G       │
│ false     ┆ LRP2      ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 235427    ┆ false     ┆ chr2:169 │
│           ┆           ┆ 081479    ┆           ┆   ┆           ┆           ┆           ┆ 204292:A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :T       │
│ false     ┆ ABCB11    ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 115828    ┆ false     ┆ chr2:169 │
│           ┆           ┆ 073734    ┆           ┆   ┆           ┆           ┆           ┆ 030531:C │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :T       │
│ false     ┆ ABCB11    ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 115828    ┆ false     ┆ chr2:168 │
│           ┆           ┆ 073734    ┆           ┆   ┆           ┆           ┆           ┆ 910825:T │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :G       │
│ false     ┆ ABCB11    ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 115828    ┆ false     ┆ chr2:168 │
│           ┆           ┆ 073734    ┆           ┆   ┆           ┆           ┆           ┆ 969544:T │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :C       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ false     ┆ ZNF770    ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 9948      ┆ false     ┆ chr15:34 │
│           ┆           ┆ 198146    ┆           ┆   ┆           ┆           ┆           ┆ 974609:A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CTTCT:A  │
│ false     ┆ SETX      ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 93632     ┆ false     ┆ chr9:132 │
│           ┆           ┆ 107290    ┆           ┆   ┆           ┆           ┆           ┆ 358570:C │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :A       │
│ false     ┆ DLC1      ┆ ENSG00000 ┆ true      ┆ … ┆ 0         ┆ 521251    ┆ false     ┆ chr8:132 │
│           ┆           ┆ 164741    ┆           ┆   ┆           ┆           ┆           ┆ 00986:C: │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CA       │
│ false     ┆ BCL7A     ┆ ENSG00000 ┆ false     ┆ … ┆ 0         ┆ 42624     ┆ false     ┆ chr12:12 │
│           ┆           ┆ 110987    ┆           ┆   ┆           ┆           ┆           ┆ 2065447: │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ G:A      │
│ false     ┆ GFPT2     ┆ ENSG00000 ┆ true      ┆ … ┆ 0         ┆ 52640     ┆ false     ┆ chr5:180 │
│           ┆           ┆ 131459    ┆           ┆   ┆           ┆           ┆           ┆ 321761:G │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ GTTTTGTT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ TTGTTT…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [62]:
melted_anno = (
    anno
    .with_columns(
        am_pathogenicity = pl.col('am_pathogenicity') >= 0.95
    )

    .unpivot(
        index=["id", "region"],
        on=existing_annos,
        variable_name="annotation",
        value_name="annotation_score"
    )
    .with_columns(
        pl.col("annotation_score").cast(pl.Float32),
        pl.col("region").cast(pl.Utf8),
    )

    # Merge with annotation configuration to get direction and filter
    .join(
        anno_config_df,
        on="annotation",
        how="left"
    )
    .with_columns(
        annotation_score_dircor = pl.col('annotation_score') * pl.col("annotation_dir")
    )
)

melted_anno

shape: (152_242_062, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ id         ┆ region    ┆ annotatio ┆ annotatio ┆ … ┆ color   ┆ label     ┆ annotatio ┆ annotatio │
│ ---        ┆ ---       ┆ n         ┆ n_score   ┆   ┆ ---     ┆ ---       ┆ n_dir     ┆ n_score_d │
│ str        ┆ str       ┆ ---       ┆ ---       ┆   ┆ str     ┆ str       ┆ ---       ┆ ircor     │
│            ┆           ┆ str       ┆ f32       ┆   ┆         ┆           ┆ i64       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ chr2:16919 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #DD4344 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 7167:T:G   ┆ 081479    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16920 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #DD4344 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 4292:A:T   ┆ 081479    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16903 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #DD4344 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 0531:C:T   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16891 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #DD4344 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 0825:T:G   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16896 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #DD4344 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 9544:T:C   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ chr15:3497 ┆ ENSG00000 ┆ utr3_inde ┆ 0.0       ┆ … ┆ gray    ┆ non-codin ┆ 1         ┆ 0.0       │
│ 4609:ACTTC ┆ 198146    ┆ l         ┆           ┆   ┆         ┆ g indel   ┆           ┆           │
│ T:A        ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr9:13235 ┆ ENSG00000 ┆ utr3_inde ┆ 0.0       ┆ … ┆ gray    ┆ non-codin ┆ 1         ┆ 0.0       │
│ 8570:C:A   ┆ 107290    ┆ l         ┆           ┆   ┆         ┆ g indel   ┆           ┆           │
│ chr8:13200 ┆ ENSG00000 ┆ utr3_inde ┆ 0.0       ┆ … ┆ gray    ┆ non-codin ┆ 1         ┆ 0.0       │
│ 986:C:CA   ┆ 164741    ┆ l         ┆           ┆   ┆         ┆ g indel   ┆           ┆           │
│ chr12:1220 ┆ ENSG00000 ┆ utr3_inde ┆ 0.0       ┆ … ┆ gray    ┆ non-codin ┆ 1         ┆ 0.0       │
│ 65447:G:A  ┆ 110987    ┆ l         ┆           ┆   ┆         ┆ g indel   ┆           ┆           │
│ chr5:18032 ┆ ENSG00000 ┆ utr3_inde ┆ 0.0       ┆ … ┆ gray    ┆ non-codin ┆ 1         ┆ 0.0       │
│ 1761:GGTTT ┆ 131459    ┆ l         ┆           ┆   ┆         ┆ g indel   ┆           ┆           │
│ TGTTTTGTTT ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ …          ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [63]:
appv = pl.scan_parquet("/home/dnanexus/data_dir/appv_files/avg_pheno_per_var_quantitative_EUR_genebass1e6_PRScorr_with_percentiles.parquet")

# Create a lazy frame with the unique keys
anno_keys = anno.select(pl.col('id').unique()).lazy()

# Chain the filter and the much faster semi join
appv = (
    appv
        .join(
        anno_keys, on='id', how='semi'
    )
    .filter(
        pl.col('n_individuals') <= mac
    )
    .select(
        ['id', 'phenotype', 'mean_pheno_value_ptile', 'n_individuals']
    )
)

# unique_phenotypes = appv.select('phenotype').unique().collect(engine='streaming').to_series()

In [64]:
# Get gene trait associations

plof = pl.read_parquet('/home/dnanexus/data_dir/association_files/rvat_EUR_500k_regenie.parquet').with_columns(
    phenotype = (pl.col('trait') + '_int'),
    region = pl.col('gene_id'),
    rvat_pval = (10** -pl.col("neg_log10p")),
).filter(
    (pl.col('trait_type') == 'quantitative')
)

loftee_corr = pl.read_parquet("/home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_wgs_EUR_genebass1e6_maf1e3_snp_consistent.parquet")

gene_trait_df = loftee_corr.join(plof[['region', 'phenotype', 'beta', 'rvat_pval']], on=['region', 'phenotype'], how='inner').filter(
    pl.col('loftee_corr')*pl.col('beta') > 0
).with_columns(
    corr_dir = pl.col('loftee_corr')/pl.col('loftee_corr').abs()
)

# gene_trait_df = gene_trait_df.head()
gene_trait_df

shape: (1_176, 8)
┌────────────┬───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬──────────┐
│ region     ┆ gene_name ┆ phenotype  ┆ loftee_cor ┆ n_variants ┆ beta      ┆ rvat_pval ┆ corr_dir │
│ ---        ┆ ---       ┆ ---        ┆ r          ┆ ---        ┆ ---       ┆ ---       ┆ ---      │
│ str        ┆ str       ┆ str        ┆ ---        ┆ u64        ┆ f64       ┆ f64       ┆ f64      │
│            ┆           ┆            ┆ f64        ┆            ┆           ┆           ┆          │
╞════════════╪═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪══════════╡
│ ENSG000001 ┆ PAPPA2    ┆ arm_fatfre ┆ -0.014747  ┆ 82603      ┆ -0.195409 ┆ 9.1637e-8 ┆ -1.0     │
│ 16183      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ COPB1     ┆ arm_fatfre ┆ -0.014338  ┆ 13594      ┆ -0.397279 ┆ 0.006626  ┆ -1.0     │
│ 29083      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ KIAA0586  ┆ arm_fatfre ┆ -0.010787  ┆ 28541      ┆ -0.058463 ┆ 0.000305  ┆ -1.0     │
│ 00578      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ ACAN      ┆ arm_fatfre ┆ -0.036259  ┆ 20244      ┆ -0.436618 ┆ 6.0395e-1 ┆ -1.0     │
│ 57766      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆ 1         ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ IGF1R     ┆ arm_fatfre ┆ -0.013644  ┆ 82469      ┆ -0.412619 ┆ 2.8609e-8 ┆ -1.0     │
│ 40443      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ …          ┆ …         ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …        │
│ ENSG000001 ┆ RHAG      ┆ reticulocy ┆ 0.033239   ┆ 9849       ┆ 0.952411  ┆ 1.8038e-4 ┆ 1.0      │
│ 12077      ┆           ┆ te_count_i ┆            ┆            ┆           ┆ 1         ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000000 ┆ ANK1      ┆ reticulocy ┆ 0.02685    ┆ 54620      ┆ 0.656849  ┆ 2.1682e-1 ┆ 1.0      │
│ 29534      ┆           ┆ te_count_i ┆            ┆            ┆           ┆ 0         ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ VPS13A    ┆ reticulocy ┆ 0.003971   ┆ 55477      ┆ 0.176348  ┆ 2.1188e-7 ┆ 1.0      │
│ 97969      ┆           ┆ te_count_i ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ LRP5      ┆ heel_bone_ ┆ -0.024278  ┆ 21119      ┆ -0.794196 ┆ 5.5055e-1 ┆ -1.0     │
│ 62337      ┆           ┆ mineral_de ┆            ┆            ┆           ┆ 0         ┆          │
│            ┆           ┆ nsity_bmd_ ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ …          ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ SMAD6     ┆ heel_bone_ ┆ -0.029893  ┆ 12754      ┆ -0.43297  ┆ 0.000005  ┆ -1.0     │
│ 37834      ┆           ┆ mineral_de ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ nsity_bmd_ ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ …          ┆            ┆            ┆           ┆           ┆          │
└────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴──────────┘

In [65]:
gene_trait_df['region'].n_unique(), gene_trait_df.shape[0]

(352, 1176)

In [66]:
# --- 1. Lazily prepare the filter keys ---
region_keys = gene_trait_df.lazy().select(pl.col('region').unique())
anno_ids_lazy = melted_anno.lazy().join(
    region_keys, on='region', how='semi'
).select(pl.col('id').unique())


# --- Build main query (same as before, but stop before group_by) ---
gp_lazy = (
    appv
    .join(anno_ids_lazy, on="id", how="semi")
    .join(
        melted_anno.lazy().drop([c for c in melted_anno.columns if 'is_nan' in c]), 
        on="id", 
        how="inner"
    )
    .join(
        gene_trait_df.lazy(), 
        on=["region", "phenotype"], 
        how="inner"
    )
    .with_columns(
        mean_pheno_value_dircor_ptile = pl.when(pl.col('corr_dir') == -1)
            .then(1 - pl.col('mean_pheno_value_ptile'))
            .otherwise(pl.col('mean_pheno_value_ptile')),
    )
    
    .group_by(["annotation", "region", "gene_name", "phenotype"])
    .agg(
        n_dis_above_cutoff = (
            (pl.col("annotation_score_dircor") == 1) & 
            (pl.col("mean_pheno_value_dircor_ptile") >= or_threshold_pheno)
        ).sum(),
        n_notdis_above_cutoff = (
            (pl.col("annotation_score_dircor") == 1) & 
            (pl.col("mean_pheno_value_dircor_ptile") < or_threshold_pheno)
        ).sum(),
        n_dis_below_cutoff = (
            (pl.col("annotation_score_dircor") == 0) & 
            (pl.col("mean_pheno_value_dircor_ptile") >= or_threshold_pheno)
        ).sum(),
        n_notdis_below_cutoff = (
            (pl.col("annotation_score_dircor") == 0) & 
            (pl.col("mean_pheno_value_dircor_ptile") < or_threshold_pheno)
        ).sum()
    )
    .with_columns(
        # odds_ratio = ((pl.col("n_dis_above_cutoff") + 1) / (pl.col("n_notdis_above_cutoff")+1)) / (1 - or_threshold_pheno)
        odds_ratio = (pl.col("n_dis_above_cutoff") / pl.col("n_notdis_above_cutoff")) / (pl.col("n_dis_below_cutoff") / pl.col("n_notdis_below_cutoff"))
    )
)

# Execute
print("Executing with odds ratios...")
or_df = gp_lazy.collect(engine='streaming')
or_df

Executing with odds ratios...

shape: (7_056, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ annotatio ┆ region    ┆ gene_name ┆ phenotype ┆ … ┆ n_notdis_ ┆ n_dis_bel ┆ n_notdis_ ┆ odds_rat │
│ n         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ above_cut ┆ ow_cutoff ┆ below_cut ┆ io       │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ off       ┆ ---       ┆ off       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ ---       ┆ u64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆           ┆ u64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ utr5_inde ┆ ENSG00000 ┆ RTEL1     ┆ red_blood ┆ … ┆ 0         ┆ 814       ┆ 16035     ┆ NaN      │
│ l         ┆ 258366    ┆           ┆ _cell_ery ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ throcyte_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ cou…      ┆   ┆           ┆           ┆           ┆          │
│ noncoding ┆ ENSG00000 ┆ SPTB      ┆ reticuloc ┆ … ┆ 2583      ┆ 1647      ┆ 29982     ┆ 0.845715 │
│ _indel    ┆ 070182    ┆           ┆ yte_perce ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ntage_int ┆   ┆           ┆           ┆           ┆          │
│ utr5_inde ┆ ENSG00000 ┆ NF1       ┆ shbg_int  ┆ … ┆ 0         ┆ 3309      ┆ 60074     ┆ NaN      │
│ l         ┆ 196712    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ am_pathog ┆ ENSG00000 ┆ PAPPA2    ┆ standing_ ┆ … ┆ 39        ┆ 4774      ┆ 86016     ┆ 4.157907 │
│ enicity   ┆ 116183    ┆           ┆ height_in ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆           ┆          │
│ intronic_ ┆ ENSG00000 ┆ COL27A1   ┆ trunk_fat ┆ … ┆ 2457      ┆ 1909      ┆ 34995     ┆ 1.171371 │
│ indel     ┆ 196739    ┆           ┆ free_mass ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _int      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ intronic_ ┆ ENSG00000 ┆ ANKRD12   ┆ red_blood ┆ … ┆ 4364      ┆ 2126      ┆ 36350     ┆ 0.928549 │
│ indel     ┆ 101745    ┆           ┆ _cell_ery ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ throcyte_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ dis…      ┆   ┆           ┆           ┆           ┆          │
│ utr5_inde ┆ ENSG00000 ┆ NPR2      ┆ trunk_pre ┆ … ┆ 0         ┆ 342       ┆ 5730      ┆ NaN      │
│ l         ┆ 159899    ┆           ┆ dicted_ma ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ss_int    ┆   ┆           ┆           ┆           ┆          │
│ utr5_inde ┆ ENSG00000 ┆ PLIN1     ┆ hdl_chole ┆ … ┆ 0         ┆ 281       ┆ 5703      ┆ NaN      │
│ l         ┆ 166819    ┆           ┆ sterol_in ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ IRS1      ┆ whole_bod ┆ … ┆ 38        ┆ 1015      ┆ 17621     ┆ 8.680296 │
│           ┆ 169047    ┆           ┆ y_fatfree ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _mass_int ┆   ┆           ┆           ┆           ┆          │
│ am_pathog ┆ ENSG00000 ┆ IRS1      ┆ whole_bod ┆ … ┆ 68        ┆ 1025      ┆ 17591     ┆ 2.271435 │
│ enicity   ┆ 169047    ┆           ┆ y_fatfree ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _mass_int ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [67]:
(    
    or_df
    .filter(
        (pl.col('annotation') == 'loftee_hc') &
        (pl.col("odds_ratio").is_finite())
    )
    .drop_nans()
    
)

shape: (1_173, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ annotatio ┆ region    ┆ gene_name ┆ phenotype ┆ … ┆ n_notdis_ ┆ n_dis_bel ┆ n_notdis_ ┆ odds_rat │
│ n         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ above_cut ┆ ow_cutoff ┆ below_cut ┆ io       │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ off       ┆ ---       ┆ off       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ ---       ┆ u64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆           ┆ u64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ loftee_hc ┆ ENSG00000 ┆ RASA2     ┆ lymphocyt ┆ … ┆ 121       ┆ 1688      ┆ 30956     ┆ 3.485899 │
│           ┆ 155903    ┆           ┆ e_count_i ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ nt        ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ ARHGAP21  ┆ leg_fatfr ┆ … ┆ 28        ┆ 1839      ┆ 34605     ┆ 6.048415 │
│           ┆ 107863    ┆           ┆ ee_mass_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ight_int  ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ FBXL16    ┆ whole_bod ┆ … ┆ 4         ┆ 389       ┆ 6963      ┆ 17.89974 │
│           ┆ 127585    ┆           ┆ y_fat_mas ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆           ┆           ┆ s_int     ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ FCGRT     ┆ calcium_i ┆ … ┆ 5         ┆ 415       ┆ 7825      ┆ 30.16867 │
│           ┆ 104870    ┆           ┆ nt        ┆   ┆           ┆           ┆           ┆ 5        │
│ loftee_hc ┆ ENSG00000 ┆ HBB       ┆ mean_sphe ┆ … ┆ 5         ┆ 223       ┆ 3965      ┆ 32.00448 │
│           ┆ 244734    ┆           ┆ red_cell_ ┆   ┆           ┆           ┆           ┆ 4        │
│           ┆           ┆           ┆ volume_in ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ loftee_hc ┆ ENSG00000 ┆ ALPL      ┆ alkaline_ ┆ … ┆ 6         ┆ 1188      ┆ 17994     ┆ 93.40319 │
│           ┆ 162551    ┆           ┆ phosphata ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆           ┆           ┆ se_int    ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ SCUBE3    ┆ leg_predi ┆ … ┆ 34        ┆ 561       ┆ 9904      ┆ 2.596204 │
│           ┆ 146197    ┆           ┆ cted_mass ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _left_int ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ RIF1      ┆ forced_vi ┆ … ┆ 49        ┆ 1416      ┆ 26063     ┆ 4.131976 │
│           ┆ 080345    ┆           ┆ tal_capac ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ity_fvc_i ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ nt        ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ GGT1      ┆ gamma_glu ┆ … ┆ 9         ┆ 667       ┆ 10607     ┆ 33.57204 │
│           ┆ 100031    ┆           ┆ tamyltran ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆           ┆           ┆ sferase_i ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ nt        ┆   ┆           ┆           ┆           ┆          │
│ loftee_hc ┆ ENSG00000 ┆ IRS1      ┆ whole_bod ┆ … ┆ 38        ┆ 1015      ┆ 17621     ┆ 8.680296 │
│           ┆ 169047    ┆           ┆ y_fatfree ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _mass_int ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [68]:
plt_df = (
    or_df
    .drop_nans()
    .filter(pl.col("odds_ratio").is_finite())
    .with_columns(
        n_gene_phenos = pl.len().over('annotation'),
        med_odds_ratio = pl.col('odds_ratio').median().over('annotation'),
        avg_odds_ratio = pl.col('odds_ratio').mean().over('annotation'),
        std_odds_ratio = pl.col('odds_ratio').std().over('annotation'),
    )
    .with_columns(
        std_ci_upper = pl.col('avg_odds_ratio') + 1.96 * (pl.col('std_odds_ratio')),
        std_ci_lower = pl.col('avg_odds_ratio') - 1.96 * (pl.col('std_odds_ratio')),
    )
    .select(['annotation', 'n_gene_phenos', 'med_odds_ratio', 'avg_odds_ratio', 'std_odds_ratio', 'std_ci_upper', 'std_ci_lower'])
    .unique()
)
plt_df

shape: (6, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ annotation   ┆ n_gene_phen ┆ med_odds_ra ┆ avg_odds_ra ┆ std_odds_ra ┆ std_ci_uppe ┆ std_ci_lowe │
│ ---          ┆ os          ┆ tio         ┆ tio         ┆ tio         ┆ r           ┆ r           │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ u64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ utr3_indel   ┆ 45          ┆ 0.0         ┆ 0.763942    ┆ 1.133648    ┆ 2.985892    ┆ -1.458008   │
│ utr5_indel   ┆ 14          ┆ 0.0         ┆ 0.417885    ┆ 0.854846    ┆ 2.093383    ┆ -1.257613   │
│ loftee_hc    ┆ 1173        ┆ 3.728214    ┆ 9.468731    ┆ 24.415344   ┆ 57.322804   ┆ -38.385342  │
│ am_pathogeni ┆ 1055        ┆ 2.290545    ┆ 4.130714    ┆ 8.591089    ┆ 20.969248   ┆ -12.70782   │
│ city         ┆             ┆             ┆             ┆             ┆             ┆             │
│ intronic_ind ┆ 1144        ┆ 0.945846    ┆ 0.950659    ┆ 0.326459    ┆ 1.590518    ┆ 0.3108      │
│ el           ┆             ┆             ┆             ┆             ┆             ┆             │
│ noncoding_in ┆ 1176        ┆ 0.937843    ┆ 0.935231    ┆ 0.16711     ┆ 1.262766    ┆ 0.607695    │
│ del          ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [69]:
melted_anno.select(['id', 'annotation', 'annotation_score']).unique().filter(pl.col('annotation') == 'noncoding_indel').select('annotation_score').sum()

shape: (1, 1)
┌──────────────────┐
│ annotation_score │
│ ---              │
│ f32              │
╞══════════════════╡
│ 2.338927e6       │
└──────────────────┘

In [32]:
melted_anno.select(['id', 'annotation', 'annotation_score']).unique().filter(pl.col('annotation') == 'am_pathogenicity').select('annotation_score').sum()

shape: (1, 1)
┌──────────────────┐
│ annotation_score │
│ ---              │
│ f32              │
╞══════════════════╡
│ 27778.0          │
└──────────────────┘

In [33]:
melted_anno.select(['id', 'annotation', 'annotation_score']).unique().filter(pl.col('annotation') == 'loftee_hc').select('annotation_score').sum()

shape: (1, 1)
┌──────────────────┐
│ annotation_score │
│ ---              │
│ f32              │
╞══════════════════╡
│ 21519.0          │
└──────────────────┘