In [1]:
import os
import yaml
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm
from huggingface_hub import hf_hub_download

from plotnine import *
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'

# ClinVar

In [2]:
BENCH_DIR = "/s/project/deeprvat/ukb_gym/other_benchmarks"

In [3]:
# Download ClinVar VCF (GRCh38) and its index
!mkdir -p {BENCH_DIR}/clinvar
!wget -nc https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz -O {BENCH_DIR}/clinvar/clinvar.vcf.gz
!wget -nc https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz.tbi -O {BENCH_DIR}/clinvar/clinvar.vcf.gz.tbi

--2026-01-26 17:40:02--  https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 2607:f220:41e:250::31, 2607:f220:41e:250::7, 2607:f220:41e:250::13, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|2607:f220:41e:250::31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 186228201 (178M) [application/x-gzip]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/clinvar/clinvar.vcf.gz’

/s/project/deeprvat 100%[===================>] 177.60M  15.8MB/s    in 12s

2026-01-26 17:40:15 (14.5 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/clinvar/clinvar.vcf.gz’ saved [186228201/186228201]

--2026-01-26 17:40:15--  https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz.tbi
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 2607:f220:41e:250::31, 2607:f220:41e:250::7, 2607:f220:41e:250::13, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|2607:f220:41e:250::31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 608666 (594K) [application/x-gzip]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/clinvar/clinvar.vcf.gz.tbi’

/s/project/deeprvat 100%[===================>] 594.40K  1.01MB/s    in 0.6s

2026-01-26 17:40:16 (1.01 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/clinvar/clinvar.vcf.gz.tbi’ saved [608666/608666]

In [4]:
# 1. Create a dummy dataframe with your example string (added CLNSIG for demonstration)
data = {
    "info_col": [
        ".11:g.917887G>T;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=LINC02593:100130417;MC=SO:0001627|intron_variant;ORIGIN=0",
        "CLNVC=single_nucleotide_variant;CLNSIG=Likely_benign;MC=SO:0001583|missense_variant;ORIGIN=1",
        "CLNVC=deletion;CLNSIG=Pathogenic;MC=SO:0001587|stop_gained;ORIGIN=1"
    ]
}
df = pl.DataFrame(data)

# 2. Extract the fields using Regex
# We create two new columns by parsing the 'info_col'
df.with_columns(
    # Regex explanation for MC: 
    # Look for "MC=", skip characters until pipe "|", capture text until next comma or semicolon
    variant_region = pl.col("info_col").str.extract(r"MC=[^|]+\|([^;,]+)", 1),
    
    # Regex explanation for CLNSIG: 
    # Look for "CLNSIG=", capture everything until the next semicolon
    clinical_significance = pl.col("info_col").str.extract(r"CLNSIG=([^;]+)", 1)
)

shape: (3, 3)
┌─────────────────────────────────┬──────────────────┬───────────────────────┐
│ info_col                        ┆ variant_region   ┆ clinical_significance │
│ ---                             ┆ ---              ┆ ---                   │
│ str                             ┆ str              ┆ str                   │
╞═════════════════════════════════╪══════════════════╪═══════════════════════╡
│ .11:g.917887G>T;CLNVC=single_n… ┆ intron_variant   ┆ null                  │
│ CLNVC=single_nucleotide_varian… ┆ missense_variant ┆ Likely_benign         │
│ CLNVC=deletion;CLNSIG=Pathogen… ┆ stop_gained      ┆ Pathogenic            │
└─────────────────────────────────┴──────────────────┴───────────────────────┘

In [23]:
clinvar = (
    pl.read_csv(f"{BENCH_DIR}/clinvar/clinvar.vcf.gz", comment_prefix="##", separator="\t", ignore_errors=True)
    .with_columns(
        chrom = pl.col("#CHROM").fill_null("NA"),
    
        # Look for "CLNSIG=", capture everything until the next semicolon
        clinical_significance = pl.col("INFO").str.extract(r"CLNSIG=([^;]+)", 1),
    )
    .with_columns(
        id = pl.col("chrom").cast(str) + ":" + pl.col("POS").cast(str) + ":" + pl.col("REF") + ":" + pl.col("ALT"),

        # Look for "MC=", skip characters until pipe "|", capture text until next comma or semicolon
        variant_region = pl.col("INFO").str.extract(r"MC=[^|]+\|([^;,]+)", 1),

        pathogenic = (
            pl.when(pl.col("clinical_significance").is_in(["Pathogenic", "Likely_pathogenic"])).then(1)
            .otherwise(pl.when(pl.col("clinical_significance").is_in(["Benign", "Likely_benign"])).then(0).otherwise(None))
        ),

        benchmark = pl.lit("ClinVar"),
    )
)

clinvar

shape: (4_280_453, 14)
┌────────┬────────┬─────────┬─────┬───┬───────────────┬───────────────────┬────────────┬───────────┐
│ #CHROM ┆ POS    ┆ ID      ┆ REF ┆ … ┆ id            ┆ variant_region    ┆ pathogenic ┆ benchmark │
│ ---    ┆ ---    ┆ ---     ┆ --- ┆   ┆ ---           ┆ ---               ┆ ---        ┆ ---       │
│ i64    ┆ i64    ┆ i64     ┆ str ┆   ┆ str           ┆ str               ┆ i32        ┆ str       │
╞════════╪════════╪═════════╪═════╪═══╪═══════════════╪═══════════════════╪════════════╪═══════════╡
│ 1      ┆ 66926  ┆ 3385321 ┆ AG  ┆ … ┆ 1:66926:AG:A  ┆ intron_variant    ┆ null       ┆ ClinVar   │
│ 1      ┆ 69134  ┆ 2205837 ┆ A   ┆ … ┆ 1:69134:A:G   ┆ missense_variant  ┆ 0          ┆ ClinVar   │
│ 1      ┆ 69241  ┆ 4562067 ┆ C   ┆ … ┆ 1:69241:C:T   ┆ missense_variant  ┆ null       ┆ ClinVar   │
│ 1      ┆ 69308  ┆ 3925305 ┆ A   ┆ … ┆ 1:69308:A:G   ┆ missense_variant  ┆ null       ┆ ClinVar   │
│ 1      ┆ 69314  ┆ 3205580 ┆ T   ┆ … ┆ 1:69314:T:G   ┆ missense_variant  ┆ null       ┆ ClinVar   │
│ …      ┆ …      ┆ …       ┆ …   ┆ … ┆ …             ┆ …                 ┆ …          ┆ …         │
│ null   ┆ 274185 ┆ 3778023 ┆ C   ┆ … ┆ NA:274185:C:T ┆ intron_variant    ┆ 0          ┆ ClinVar   │
│ null   ┆ 274366 ┆ 2206666 ┆ G   ┆ … ┆ NA:274366:G:C ┆ missense_variant  ┆ null       ┆ ClinVar   │
│ null   ┆ 275068 ┆ 2241971 ┆ T   ┆ … ┆ NA:275068:T:C ┆ missense_variant  ┆ null       ┆ ClinVar   │
│ null   ┆ 434928 ┆ 4502385 ┆ C   ┆ … ┆ NA:434928:C:G ┆ intron_variant    ┆ null       ┆ ClinVar   │
│ null   ┆ 83614  ┆ 17735   ┆ TC  ┆ … ┆ NA:83614:TC:T ┆ frameshift_varian ┆ 0          ┆ ClinVar   │
│        ┆        ┆         ┆     ┆   ┆               ┆ t                 ┆            ┆           │
└────────┴────────┴─────────┴─────┴───┴───────────────┴───────────────────┴────────────┴───────────┘

# TraitGym

In [63]:
# Download the file to your local cache and get the path
file_path = hf_hub_download(
    repo_id="songlab/TraitGym", 
    filename="mendelian_traits_matched_9/test.parquet",
    repo_type="dataset"
)

# 1. Define the mapping dictionary
ccre_to_vep = {
    # Promoters
    "PLS": "promoter_variant",
    
    # Enhancers (Proximal and Distal)
    "pELS": "enhancer_variant",
    "dELS": "enhancer_variant",
    "dELS_flank": "regulatory_region_variant", # Generic regulatory term for flanking regions
    
    # Transcription Factors
    "CTCF-only": "TF_binding_site_variant",
    
    # Ambiguous / Poised regions
    "DNase-H3K4me3": "regulatory_region_variant" 
}


# Read the local file
trait_gym_m = (
    pl.read_parquet(file_path)
    .with_columns(
        id = pl.concat_str([
            pl.col("chrom").cast(pl.Utf8),
            pl.lit(":"),
            pl.col("pos").cast(pl.Utf8),
            pl.lit(":"),
            pl.col("ref"),
            pl.lit(":"),
            pl.col("alt")
        ]),
        variant_region = (
            pl.when(pl.col("consequence").is_in(ccre_to_vep.keys()))
            .then(pl.col("consequence").replace(ccre_to_vep, default=None))
            .otherwise(pl.col("consequence"))
        ),
        pathogenic = pl.col('label'),
        benchmark = pl.lit("TraitGym mendelian traits (matched)")
    )
)
trait_gym_m

/scratch/tmp/lond/ipykernel_101434/837040322.py:41: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)

shape: (3_380, 13)
┌───────┬───────────┬─────┬─────┬───┬────────────────┬────────────────┬────────────┬───────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ … ┆ id             ┆ variant_region ┆ pathogenic ┆ benchmark     │
│ ---   ┆ ---       ┆ --- ┆ --- ┆   ┆ ---            ┆ ---            ┆ ---        ┆ ---           │
│ str   ┆ i64       ┆ str ┆ str ┆   ┆ str            ┆ str            ┆ bool       ┆ str           │
╞═══════╪═══════════╪═════╪═════╪═══╪════════════════╪════════════════╪════════════╪═══════════════╡
│ 1     ┆ 1425822   ┆ C   ┆ G   ┆ … ┆ 1:1425822:C:G  ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆                ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ 1     ┆ 1615869   ┆ C   ┆ T   ┆ … ┆ 1:1615869:C:T  ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆                ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ 1     ┆ 1659060   ┆ G   ┆ A   ┆ … ┆ 1:1659060:G:A  ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆                ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ 1     ┆ 1659114   ┆ A   ┆ G   ┆ … ┆ 1:1659114:A:G  ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆                ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ 1     ┆ 2050958   ┆ T   ┆ C   ┆ … ┆ 1:2050958:T:C  ┆ 5_prime_UTR_va ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆                ┆ riant          ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ …     ┆ …         ┆ …   ┆ …   ┆ … ┆ …              ┆ …              ┆ …          ┆ …             │
│ X     ┆ 155613005 ┆ C   ┆ T   ┆ … ┆ X:155613005:C: ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆ T              ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ X     ┆ 155719093 ┆ C   ┆ A   ┆ … ┆ X:155719093:C: ┆ 5_prime_UTR_va ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆ A              ┆ riant          ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ X     ┆ 155881342 ┆ A   ┆ C   ┆ … ┆ X:155881342:A: ┆ promoter_varia ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆ C              ┆ nt             ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ X     ┆ 155881414 ┆ C   ┆ T   ┆ … ┆ X:155881414:C: ┆ 5_prime_UTR_va ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆ T              ┆ riant          ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
│ X     ┆ 156020793 ┆ A   ┆ G   ┆ … ┆ X:156020793:A: ┆ upstream_gene_ ┆ false      ┆ TraitGym      │
│       ┆           ┆     ┆     ┆   ┆ G              ┆ variant        ┆            ┆ mendelian     │
│       ┆           ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…  │
└───────┴───────────┴─────┴─────┴───┴────────────────┴────────────────┴────────────┴───────────────┘

In [65]:
# Download the file to your local cache and get the path
file_path = hf_hub_download(
    repo_id="songlab/TraitGym", 
    filename="complex_traits_matched_9/test.parquet",
    repo_type="dataset"
)

# Read the local file
trait_gym_c = (
    pl.read_parquet(file_path)
    .with_columns(
        id = pl.concat_str([
            pl.col("chrom").cast(pl.Utf8),
            pl.lit(":"),
            pl.col("pos").cast(pl.Utf8),
            pl.lit(":"),
            pl.col("ref"),
            pl.lit(":"),
            pl.col("alt")
        ]),
        variant_region = (
            pl.when(pl.col("consequence").is_in(ccre_to_vep.keys()))
            .then(pl.col("consequence").replace(ccre_to_vep, default=None))
            .otherwise(pl.col("consequence"))
        ),
        pathogenic = pl.col('label'),
        benchmark = pl.lit("TraitGym mendelian traits (matched)")
    )
)
trait_gym_c

/scratch/tmp/lond/ipykernel_101434/3739900729.py:23: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)

shape: (11_400, 16)
┌───────┬──────────┬─────┬─────┬───┬────────────────┬────────────────┬────────────┬────────────────┐
│ chrom ┆ pos      ┆ ref ┆ alt ┆ … ┆ id             ┆ variant_region ┆ pathogenic ┆ benchmark      │
│ ---   ┆ ---      ┆ --- ┆ --- ┆   ┆ ---            ┆ ---            ┆ ---        ┆ ---            │
│ str   ┆ i64      ┆ str ┆ str ┆   ┆ str            ┆ str            ┆ bool       ┆ str            │
╞═══════╪══════════╪═════╪═════╪═══╪════════════════╪════════════════╪════════════╪════════════════╡
│ 1     ┆ 867476   ┆ C   ┆ T   ┆ … ┆ 1:867476:C:T   ┆ non_coding_tra ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆                ┆ nscript_exon_v ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆ ar…            ┆            ┆ traits (mat…   │
│ 1     ┆ 868052   ┆ T   ┆ C   ┆ … ┆ 1:868052:T:C   ┆ non_coding_tra ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆                ┆ nscript_exon_v ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆ ar…            ┆            ┆ traits (mat…   │
│ 1     ┆ 868635   ┆ A   ┆ G   ┆ … ┆ 1:868635:A:G   ┆ non_coding_tra ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆                ┆ nscript_exon_v ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆ ar…            ┆            ┆ traits (mat…   │
│ 1     ┆ 870176   ┆ T   ┆ A   ┆ … ┆ 1:870176:T:A   ┆ non_coding_tra ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆                ┆ nscript_exon_v ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆ ar…            ┆            ┆ traits (mat…   │
│ 1     ┆ 1052930  ┆ A   ┆ G   ┆ … ┆ 1:1052930:A:G  ┆ non_coding_tra ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆                ┆ nscript_exon_v ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆ ar…            ┆            ┆ traits (mat…   │
│ …     ┆ …        ┆ …   ┆ …   ┆ … ┆ …              ┆ …              ┆ …          ┆ …              │
│ 22    ┆ 50368376 ┆ T   ┆ C   ┆ … ┆ 22:50368376:T: ┆ enhancer_varia ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆ C              ┆ nt             ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…   │
│ 22    ┆ 50571623 ┆ C   ┆ T   ┆ … ┆ 22:50571623:C: ┆ enhancer_varia ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆ T              ┆ nt             ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…   │
│ 22    ┆ 50671289 ┆ G   ┆ A   ┆ … ┆ 22:50671289:G: ┆ pELS_flank     ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆ A              ┆                ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…   │
│ 22    ┆ 50713837 ┆ C   ┆ G   ┆ … ┆ 22:50713837:C: ┆ enhancer_varia ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆ G              ┆ nt             ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…   │
│ 22    ┆ 50783672 ┆ G   ┆ T   ┆ … ┆ 22:50783672:G: ┆ promoter_varia ┆ false      ┆ TraitGym       │
│       ┆          ┆     ┆     ┆   ┆ T              ┆ nt             ┆            ┆ mendelian      │
│       ┆          ┆     ┆     ┆   ┆                ┆                ┆            ┆ traits (mat…   │
└───────┴──────────┴─────┴─────┴───┴────────────────┴────────────────┴────────────┴────────────────┘

# ProteinGym

In [37]:
VERSION = "v1.3"
FILENAME = "DMS_ProteinGym_substitutions.zip"
TARGET_DIR = f"{BENCH_DIR}/protein_gym"
TARGET_FILE = f"{TARGET_DIR}/{FILENAME}"

# 1. Create Directory
!mkdir -p {TARGET_DIR}

# 2. Download only if missing
if not os.path.exists(TARGET_FILE):
    print("File not found. Downloading...")
    !curl -o {TARGET_FILE} https://marks.hms.harvard.edu/proteingym/ProteinGym_{VERSION}/{FILENAME}
else:
    print("File already exists. Skipping download.")

# 3. Unzip with "Yes to All" (-o)
# We use -o to overwrite if it exists, avoiding the interactive prompt
print("Unzipping...")
!unzip -o {TARGET_FILE} -d {TARGET_DIR}

File already exists. Skipping download.
Unzipping...
Archive:  /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions.zip
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SDA_BACSU_Tsuboyama_2023_1PV0.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PAI1_HUMAN_Huttinger_2021.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/S22A1_HUMAN_Yee_2023_activity.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HIS7_YEAST_Pokusaeva_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/AMIE_PSEAE_Wrenbeck_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ACE2_HUMAN_Chan_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RDRP_I33A0_Li_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CASP3_HUMAN_Roychowdhury_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RL40A_YEAST_Roscoe_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SRC_HUMAN_Chakraborty_2023_binding-DAS_25uM.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TRPC_SACS2_Chan_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/GLPA_HUMAN_Elazar_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BLAT_ECOLX_Jacquier_2013.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/LYAM1_HUMAN_Elazar_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PABP_YEAST_Melamed_2013.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q2N0S5_9HIV1_Haddox_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DOCK1_MOUSE_Tsuboyama_2023_2M0Y.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SCN5A_HUMAN_Glazer_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MYO3_YEAST_Tsuboyama_2023_2BTT.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CBPA2_HUMAN_Tsuboyama_2023_1O6X.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RAD_ANTMA_Tsuboyama_2023_2CJJ.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A4D664_9INFA_Soh_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CATR_CHLRE_Tsuboyama_2023_2AMI.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SERC_HUMAN_Xie_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SRBS1_HUMAN_Tsuboyama_2023_2O2W.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PPARG_HUMAN_Majithia_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/AICDA_HUMAN_Gajula_2014_3cycles.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/AACC1_PSEAI_Dandage_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A4_HUMAN_Seuma_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RS15_GEOSE_Tsuboyama_2023_1A32.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/P53_HUMAN_Giacomelli_2018_WT_Nutlin.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/VG08_BPP22_Tsuboyama_2023_2GP8.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/OXDA_RHOTO_Vanella_2023_expression.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BLAT_ECOLX_Firnberg_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/AMFR_HUMAN_Tsuboyama_2023_4G3O.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RL40A_YEAST_Roscoe_2013.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DYR_ECOLI_Thompson_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MTHR_HUMAN_Weile_2021.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TPOR_HUMAN_Bridgford_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SR43C_ARATH_Tsuboyama_2023_2N88.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MSH2_HUMAN_Jia_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NPC1_HUMAN_Erwood_2022_RPE1.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A192B1T2_9HIV1_Haddox_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MET_HUMAN_Estevam_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HCP_LAMBD_Tsuboyama_2023_2L6Q.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CCR5_HUMAN_Gill_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SPA_STAAU_Tsuboyama_2023_1LP1.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/FECA_ECOLI_Tsuboyama_2023_2D1U.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A140D2T1_ZIKV_Sourisseau_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PHOT_CHLRE_Chen_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SPG1_STRSG_Olson_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TADBP_HUMAN_Bolognesi_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/OXDA_RHOTO_Vanella_2023_activity.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NKX31_HUMAN_Tsuboyama_2023_2L9R.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HSP82_YEAST_Mishra_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/EPHB2_HUMAN_Tsuboyama_2023_1F0M.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TAT_HV1BR_Fernandes_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HXK4_HUMAN_Gersing_2022_activity.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/KKA2_KLEPN_Melnikov_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q837P4_ENTFA_Meier_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ANCSZ_Hobbs_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SCIN_STAAR_Tsuboyama_2023_2QFF.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PA_I34A1_Wu_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MLAC_ECOLI_MacRae_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DLG4_HUMAN_Faure_2021.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ENV_HV1BR_Haddox_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CCDB_ECOLI_Tripathi_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/F7YBW8_MESOW_Ding_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/P53_HUMAN_Giacomelli_2018_Null_Etoposide.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ESTA_BACSU_Nutschel_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HSP82_YEAST_Flynn_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PKN1_HUMAN_Tsuboyama_2023_1URF.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RASK_HUMAN_Weng_2022_abundance.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CASP7_HUMAN_Roychowdhury_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/UBE4B_HUMAN_Tsuboyama_2023_3L1X.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/P53_HUMAN_Giacomelli_2018_Null_Nutlin.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DYR_ECOLI_Nguyen_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CP2C9_HUMAN_Amorosi_2021_activity.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/UBR5_HUMAN_Tsuboyama_2023_1I2T.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A2Z5U3Z0_9INFA_Wu_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SHOC2_HUMAN_Kwon_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/IF1_ECOLI_Kelsic_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DNJA1_HUMAN_Tsuboyama_2023_2LO1.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/POLG_HCVJF_Qi_2014.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A1I9GEU1_NEIME_Kennouche_2019.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BRCA1_HUMAN_Findlay_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/GCN4_YEAST_Staller_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CSN4_MOUSE_Tsuboyama_2023_1UFM.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BCHB_CHLTE_Tsuboyama_2023_2KRU.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RFAH_ECOLI_Tsuboyama_2023_2LCL.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CALM1_HUMAN_Weile_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HEM3_HUMAN_Loggerenberg_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/P84126_THETH_Chan_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/GAL4_YEAST_Kitzman_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A247D711_LISMN_Stadelmann_2021.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/I6TAH8_I68A0_Doud_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NUSA_ECOLI_Tsuboyama_2023_1WCL.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/P53_HUMAN_Kotler_2018.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CAR11_HUMAN_Meitlis_2020_lof.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/POLG_DEN26_Suphatrakul_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/VRPI_BPT7_Tsuboyama_2023_2WNM.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/UBC9_HUMAN_Weile_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RCRO_LAMBD_Tsuboyama_2023_1ORC.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SAV1_MOUSE_Tsuboyama_2023_2YSB.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ILF3_HUMAN_Tsuboyama_2023_2L33.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SPTN1_CHICK_Tsuboyama_2023_1TUD.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NRAM_I33A0_Jiang_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q837P5_ENTFA_Meier_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CBS_HUMAN_Sun_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/DN7A_SACS2_Tsuboyama_2023_1JIC.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RBP1_HUMAN_Tsuboyama_2023_2KWH.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HECD1_HUMAN_Tsuboyama_2023_3DKM.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SPIKE_SARS2_Starr_2020_expression.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/REV_HV1H2_Fernandes_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SYUA_HUMAN_Newberry_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/YAP1_HUMAN_Araya_2012.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NCAP_I34A1_Doud_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/D7PM05_CLYGR_Somermeyer_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TRPC_THEMA_Chan_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/HSP82_YEAST_Cote-Hammarlof_2020_growth-H2O2.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BLAT_ECOLX_Deng_2012.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/VKOR1_HUMAN_Chiasson_2020_abundance.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TNKS2_HUMAN_Tsuboyama_2023_5JRT.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SQSTM_MOUSE_Tsuboyama_2023_2RRU.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/BBC1_YEAST_Tsuboyama_2023_1TG0.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/GFP_AEQVI_Sarkisyan_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/NUD15_HUMAN_Suiter_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/UBE4B_MOUSE_Starita_2013.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MTH3_HAEAE_RockahShmuel_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/KCNE1_HUMAN_Muhammad_2023_expression.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ENVZ_ECOLI_Ghose_2023.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SRC_HUMAN_Nguyen_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A4GRB6_PSEAI_Chen_2020.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/MAFG_MOUSE_Tsuboyama_2023_1K1V.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ARGR_ECOLI_Tsuboyama_2023_1AOY.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SPIKE_SARS2_Starr_2020_binding.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/R1AB_SARS2_Flynn_2022.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RASK_HUMAN_Weng_2022_binding-DARPin_K55.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ODP2_GEOSE_Tsuboyama_2023_1W4G.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/CCDB_ECOLI_Adkar_2012.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q59976_STRSQ_Romero_2015.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/SBI_STAAM_Tsuboyama_2023_2JVG.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/THO1_YEAST_Tsuboyama_2023_2WQG.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/A0A2Z5U3Z0_9INFA_Doud_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/POLG_CXB3N_Mattenberger_2021.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/ENV_HV1B9_DuenasDecamp_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RPC1_BP434_Tsuboyama_2023_1R69.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/TPK1_HUMAN_Weile_2017.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/RL40A_YEAST_Mavor_2016.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q53Z42_HUMAN_McShan_2019_binding-TAPBPR.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/Q53Z42_HUMAN_McShan_2019_expression.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/PRKN_HUMAN_Clausen_2023.csv

In [28]:
VERSION = "v1.3"
FILENAME = "DMS_ProteinGym_indels.zip"
TARGET_DIR = f"{BENCH_DIR}/protein_gym"
TARGET_FILE = f"{TARGET_DIR}/{FILENAME}"

# 1. Create Directory
!mkdir -p {TARGET_DIR}

# 2. Download only if missing
if not os.path.exists(TARGET_FILE):
    print("File not found. Downloading...")
    !curl -o {TARGET_FILE} https://marks.hms.harvard.edu/proteingym/ProteinGym_{VERSION}/{FILENAME}
else:
    print("File already exists. Skipping download.")

# 3. Unzip with "Yes to All" (-o)
# We use -o to overwrite if it exists, avoiding the interactive prompt
print("Unzipping...")
!unzip -o {TARGET_FILE} -d {TARGET_DIR}

File not found. Downloading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6552k  100 6552k    0     0  5305k      0  0:00:01  0:00:01 --:--:-- 5305k 567k      0  0:00:11 --:--:--  0:00:11  567k
Unzipping...
Archive:  /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels.zip
   creating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SDA_BACSU_Tsuboyama_2023_1PV0_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PR40A_HUMAN_Tsuboyama_2023_1UZC_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/BBC1_YEAST_Tsuboyama_2023_1TG0_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/MBD11_ARATH_Tsuboyama_2023_6ACV_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/YNZC_BACSU_Tsuboyama_2023_2JVD_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/HCP_LAMBD_Tsuboyama_2023_2L6Q_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/B1LPA6_ECOSM_Russ_2020_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/Q8EG35_SHEON_Campbell_2022_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/OTU7A_HUMAN_Tsuboyama_2023_2L2D_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/MYO3_YEAST_Tsuboyama_2023_2BTT_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/RCD1_ARATH_Tsuboyama_2023_5OAO_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SR43C_ARATH_Tsuboyama_2023_2N88_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/FECA_ECOLI_Tsuboyama_2023_2D1U_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PKN1_HUMAN_Tsuboyama_2023_1URF_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CSN4_MOUSE_Tsuboyama_2023_1UFM_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CAPSD_AAV2S_Sinai_2021_designed_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/AMFR_HUMAN_Tsuboyama_2023_4G3O_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PTEN_HUMAN_Mighell_2018_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SQSTM_MOUSE_Tsuboyama_2023_2RRU_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/MAFG_MOUSE_Tsuboyama_2023_1K1V_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/DNJA1_HUMAN_Tsuboyama_2023_2LO1_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/VRPI_BPT7_Tsuboyama_2023_2WNM_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/NUSG_MYCTU_Tsuboyama_2023_2MI6_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PIN1_HUMAN_Tsuboyama_2023_1I6C_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/NUSA_ECOLI_Tsuboyama_2023_1WCL_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/UBR5_HUMAN_Tsuboyama_2023_1I2T_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/OBSCN_HUMAN_Tsuboyama_2023_1V1C_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/S22A1_HUMAN_Yee_2023_abundance_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PSAE_PICP2_Tsuboyama_2023_1PSE_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/EPHB2_HUMAN_Tsuboyama_2023_1F0M_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/S22A1_HUMAN_Yee_2023_activity_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/PITX2_HUMAN_Tsuboyama_2023_2L7M_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/VG08_BPP22_Tsuboyama_2023_2GP8_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CAPSD_AAV2S_Sinai_2021_library_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CATR_CHLRE_Tsuboyama_2023_2AMI_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/ILF3_HUMAN_Tsuboyama_2023_2L33_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CUE1_YEAST_Tsuboyama_2023_2MYX_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/KCNJ2_MOUSE_Macdonald_2022_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SRBS1_HUMAN_Tsuboyama_2023_2O2W_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/A4_HUMAN_Seuma_2022_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SOX30_HUMAN_Tsuboyama_2023_7JJK_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/POLG_PESV_Tsuboyama_2023_2MXD_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SAV1_MOUSE_Tsuboyama_2023_2YSB_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/HECD1_HUMAN_Tsuboyama_2023_3DKM_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/DOCK1_MOUSE_Tsuboyama_2023_2M0Y_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/TCRG1_MOUSE_Tsuboyama_2023_1E0L_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/TNKS2_HUMAN_Tsuboyama_2023_5JRT_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/ODP2_GEOSE_Tsuboyama_2023_1W4G_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/RD23A_HUMAN_Tsuboyama_2023_1IFY_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/P53_HUMAN_Kotler_2018_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/ARGR_ECOLI_Tsuboyama_2023_1AOY_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/UBE4B_HUMAN_Tsuboyama_2023_3L1X_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/RS15_GEOSE_Tsuboyama_2023_1A32_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/THO1_YEAST_Tsuboyama_2023_2WQG_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SPG2_STRSG_Tsuboyama_2023_5UBS_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/DN7A_SACS2_Tsuboyama_2023_1JIC_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/VILI_CHICK_Tsuboyama_2023_1YU5_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/BCHB_CHLTE_Tsuboyama_2023_2KRU_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/RAD_ANTMA_Tsuboyama_2023_2CJJ_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/RPC1_BP434_Tsuboyama_2023_1R69_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/BLAT_ECOLX_Gonzalez_2019_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/HIS7_YEAST_Pokusaeva_2019_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/NKX31_HUMAN_Tsuboyama_2023_2L9R_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/SPTN1_CHICK_Tsuboyama_2023_1TUD_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CBX4_HUMAN_Tsuboyama_2023_2K28_indels.csv
  inflating: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/CBPA2_HUMAN_Tsuboyama_2023_1O6X_indels.csv

In [ ]:
# csv_pattern = f"{TARGET_DIR}/**/*HUMAN*.csv"
csv_pattern = f"{TARGET_DIR}/DMS_ProteinGym_substitutions/*HUMAN*.csv"

print(f"Scanning files matching: {csv_pattern}")

# 2. Scan and Compile
# 'include_file_paths' creates a column with the file path, which is 
# critical to distinguish which assay the variants come from.
proteingym_snp = (
    pl.scan_csv(csv_pattern, include_file_paths="source_file")
    .with_columns(
        # Extract just the assay name (remove path and extension)
        assay_id = pl.col("source_file")
                    .str.split("/")
                    .list.last()
                    .str.strip_suffix(".csv")
    )
    .collect()

    .with_columns(
        # 1. Flag Bottom 1%
        is_bottom_1pct = pl.col("DMS_score") <= pl.col("DMS_score").quantile(0.01).over("assay_id"),
        
        # 2. Flag Top 1%
        is_top_1pct = pl.col("DMS_score") >= pl.col("DMS_score").quantile(0.99).over("assay_id")
    )
    .with_columns(
        id = pl.col('mutant'),
        variant_region = pl.lit("missense_variant"),
        pathogenic = pl.col("is_bottom_1pct") | pl.col("is_top_1pct"),
        benchmark = pl.lit("ProteinGym SNP (Human)"),
    )
)

proteingym_snp

Scanning files matching: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_substitutions/*HUMAN*.csv

shape: (485_830, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ mutant    ┆ mutated_s ┆ DMS_score ┆ DMS_score ┆ … ┆ id        ┆ variant_r ┆ pathogeni ┆ benchmar │
│ ---       ┆ equence   ┆ ---       ┆ _bin      ┆   ┆ ---       ┆ egion     ┆ c         ┆ k        │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ i64       ┆   ┆           ┆ str       ┆ bool      ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A673C     ┆ MLPGLALLL ┆ -1.018869 ┆ 1         ┆ … ┆ A673C     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ LAAWTARAL ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ EVPTDGNAG ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ LLA…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A673D     ┆ MLPGLALLL ┆ -0.605052 ┆ 1         ┆ … ┆ A673D     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ LAAWTARAL ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ EVPTDGNAG ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ LLA…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A673E     ┆ MLPGLALLL ┆ -0.590857 ┆ 1         ┆ … ┆ A673E     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ LAAWTARAL ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ EVPTDGNAG ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ LLA…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A673E:A69 ┆ MLPGLALLL ┆ -2.443601 ┆ 0         ┆ … ┆ A673E:A69 ┆ missense_ ┆ false     ┆ ProteinG │
│ 2E        ┆ LAAWTARAL ┆           ┆           ┆   ┆ 2E        ┆ variant   ┆           ┆ ym SNP   │
│           ┆ EVPTDGNAG ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ LLA…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A673E:A69 ┆ MLPGLALLL ┆ -3.049893 ┆ 0         ┆ … ┆ A673E:A69 ┆ missense_ ┆ false     ┆ ProteinG │
│ 2T        ┆ LAAWTARAL ┆           ┆           ┆   ┆ 2T        ┆ variant   ┆           ┆ ym SNP   │
│           ┆ EVPTDGNAG ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ LLA…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ R203H     ┆ MDPGQQPPP ┆ 0.124027  ┆ 0         ┆ … ┆ R203H     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ QPAPQGQGQ ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ PPSQPPQGQ ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ GPP…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ R203G     ┆ MDPGQQPPP ┆ 0.150523  ┆ 0         ┆ … ┆ R203G     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ QPAPQGQGQ ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ PPSQPPQGQ ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ GPP…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ R203D     ┆ MDPGQQPPP ┆ 0.138661  ┆ 0         ┆ … ┆ R203D     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ QPAPQGQGQ ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ PPSQPPQGQ ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ GPP…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ R203S     ┆ MDPGQQPPP ┆ 0.16786   ┆ 0         ┆ … ┆ R203S     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ QPAPQGQGQ ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ PPSQPPQGQ ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ GPP…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ R203P     ┆ MDPGQQPPP ┆ 0.061895  ┆ 0         ┆ … ┆ R203P     ┆ missense_ ┆ false     ┆ ProteinG │
│           ┆ QPAPQGQGQ ┆           ┆           ┆   ┆           ┆ variant   ┆           ┆ ym SNP   │
│           ┆ PPSQPPQGQ ┆           ┆           ┆   ┆           ┆           ┆           ┆ (human)  │
│           ┆ GPP…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# csv_pattern = f"{TARGET_DIR}/**/*HUMAN*.csv"
csv_pattern = f"{TARGET_DIR}/DMS_ProteinGym_indels/*HUMAN*.csv"

print(f"Scanning files matching: {csv_pattern}")

# 2. Scan and Compile
# 'include_file_paths' creates a column with the file path, which is 
# critical to distinguish which assay the variants come from.
proteingym_indel = (
    pl.scan_csv(csv_pattern, include_file_paths="source_file")
    .with_columns(
        # Extract just the assay name (remove path and extension)
        assay_id = pl.col("source_file")
                    .str.split("/")
                    .list.last()
                    .str.strip_suffix(".csv")
    )
    .collect()

    .with_columns(
        # 1. Flag Bottom 1%
        is_bottom_1pct = pl.col("DMS_score") <= pl.col("DMS_score").quantile(0.01).over("assay_id"),
        
        # 2. Flag Top 1%
        is_top_1pct = pl.col("DMS_score") >= pl.col("DMS_score").quantile(0.99).over("assay_id")
    )
    .with_columns(
        id = pl.col('mutated_sequence'),
        variant_region = pl.lit("frameshift_variant"),
        pathogenic = pl.col("is_bottom_1pct") | pl.col("is_top_1pct"),
        benchmark = pl.lit("ProteinGym indel (Human)")
    )
)

proteingym_indel

Scanning files matching: /s/project/deeprvat/ukb_gym/other_benchmarks/protein_gym/DMS_ProteinGym_indels/*HUMAN*.csv

shape: (6_944, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ mutated_s ┆ DMS_score ┆ DMS_score ┆ source_fi ┆ … ┆ id        ┆ variant_r ┆ pathogeni ┆ benchmar │
│ equence   ┆ ---       ┆ _bin      ┆ le        ┆   ┆ ---       ┆ egion     ┆ c         ┆ k        │
│ ---       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ i64       ┆ str       ┆   ┆           ┆ str       ┆ bool      ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MLPGLALLL ┆ -3.311444 ┆ 0         ┆ /s/projec ┆ … ┆ MLPGLALLL ┆ frameshif ┆ false     ┆ ProteinG │
│ LAAWTARAL ┆           ┆           ┆ t/deeprva ┆   ┆ LAAWTARAL ┆ t_variant ┆           ┆ ym indel │
│ EVPTDGNAG ┆           ┆           ┆ t/ukb_gym ┆   ┆ EVPTDGNAG ┆           ┆           ┆ (human)  │
│ LLA…      ┆           ┆           ┆ /ot…      ┆   ┆ LLA…      ┆           ┆           ┆          │
│ MLPGLALLL ┆ -3.36364  ┆ 0         ┆ /s/projec ┆ … ┆ MLPGLALLL ┆ frameshif ┆ false     ┆ ProteinG │
│ LAAWTARAL ┆           ┆           ┆ t/deeprva ┆   ┆ LAAWTARAL ┆ t_variant ┆           ┆ ym indel │
│ EVPTDGNAG ┆           ┆           ┆ t/ukb_gym ┆   ┆ EVPTDGNAG ┆           ┆           ┆ (human)  │
│ LLA…      ┆           ┆           ┆ /ot…      ┆   ┆ LLA…      ┆           ┆           ┆          │
│ MLPGLALLL ┆ -3.413797 ┆ 0         ┆ /s/projec ┆ … ┆ MLPGLALLL ┆ frameshif ┆ false     ┆ ProteinG │
│ LAAWTARAL ┆           ┆           ┆ t/deeprva ┆   ┆ LAAWTARAL ┆ t_variant ┆           ┆ ym indel │
│ EVPTDGNAG ┆           ┆           ┆ t/ukb_gym ┆   ┆ EVPTDGNAG ┆           ┆           ┆ (human)  │
│ LLA…      ┆           ┆           ┆ /ot…      ┆   ┆ LLA…      ┆           ┆           ┆          │
│ MLPGLALLL ┆ -3.352993 ┆ 0         ┆ /s/projec ┆ … ┆ MLPGLALLL ┆ frameshif ┆ false     ┆ ProteinG │
│ LAAWTARAL ┆           ┆           ┆ t/deeprva ┆   ┆ LAAWTARAL ┆ t_variant ┆           ┆ ym indel │
│ EVPTDGNAG ┆           ┆           ┆ t/ukb_gym ┆   ┆ EVPTDGNAG ┆           ┆           ┆ (human)  │
│ LLA…      ┆           ┆           ┆ /ot…      ┆   ┆ LLA…      ┆           ┆           ┆          │
│ MLPGLALLL ┆ 0.235065  ┆ 1         ┆ /s/projec ┆ … ┆ MLPGLALLL ┆ frameshif ┆ false     ┆ ProteinG │
│ LAAWTARAL ┆           ┆           ┆ t/deeprva ┆   ┆ LAAWTARAL ┆ t_variant ┆           ┆ ym indel │
│ EVPTDGNAG ┆           ┆           ┆ t/ukb_gym ┆   ┆ EVPTDGNAG ┆           ┆           ┆ (human)  │
│ LLA…      ┆           ┆           ┆ /ot…      ┆   ┆ LLA…      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRQALGGER ┆ -1.300614 ┆ 0         ┆ /s/projec ┆ … ┆ HRQALGGER ┆ frameshif ┆ false     ┆ ProteinG │
│ LYPRVQAMQ ┆           ┆           ┆ t/deeprva ┆   ┆ LYPRVQAMQ ┆ t_variant ┆           ┆ ym indel │
│ PAFASKITG ┆           ┆           ┆ t/ukb_gym ┆   ┆ PAFASKITG ┆           ┆           ┆ (human)  │
│ MLL…      ┆           ┆           ┆ /ot…      ┆   ┆ MLL…      ┆           ┆           ┆          │
│ HRQALGRLY ┆ -0.619357 ┆ 0         ┆ /s/projec ┆ … ┆ HRQALGRLY ┆ frameshif ┆ false     ┆ ProteinG │
│ PRVQAMQPA ┆           ┆           ┆ t/deeprva ┆   ┆ PRVQAMQPA ┆ t_variant ┆           ┆ ym indel │
│ FASKITGML ┆           ┆           ┆ t/ukb_gym ┆   ┆ FASKITGML ┆           ┆           ┆ (human)  │
│ LEL…      ┆           ┆           ┆ /ot…      ┆   ┆ LEL…      ┆           ┆           ┆          │
│ HRQGALGER ┆ -0.421069 ┆ 1         ┆ /s/projec ┆ … ┆ HRQGALGER ┆ frameshif ┆ false     ┆ ProteinG │
│ LYPRVQAMQ ┆           ┆           ┆ t/deeprva ┆   ┆ LYPRVQAMQ ┆ t_variant ┆           ┆ ym indel │
│ PAFASKITG ┆           ┆           ┆ t/ukb_gym ┆   ┆ PAFASKITG ┆           ┆           ┆ (human)  │
│ MLL…      ┆           ┆           ┆ /ot…      ┆   ┆ MLL…      ┆           ┆           ┆          │
│ HRQLGERLY ┆ 0.003641  ┆ 1         ┆ /s/projec ┆ … ┆ HRQLGERLY ┆ frameshif ┆ false     ┆ ProteinG │
│ PRVQAMQPA ┆           ┆           ┆ t/deeprva ┆   ┆ PRVQAMQPA ┆ t_variant ┆           ┆ ym indel │
│ FASKITGML ┆           ┆           ┆ t/ukb_gym ┆   ┆ FASKITGML ┆           ┆           ┆ (human)  │
│ LEL…      ┆           ┆           ┆ /ot…      ┆   ┆ LEL…      ┆           ┆           ┆          │
│ RQALGERLY ┆ 0.102864  ┆ 1         ┆ /s/projec ┆ … ┆ RQALGERLY ┆ frameshif ┆ true      ┆ ProteinG │
│ PRVQAMQPA ┆           ┆           ┆ t/deeprva ┆   ┆ PRVQAMQPA ┆ t_variant ┆           ┆ ym indel │
│ FASKITGML ┆           ┆           ┆ t/ukb_gym ┆   ┆ FASKITGML ┆           ┆           ┆ (human)  │
│ LEL…      ┆           ┆           ┆ /ot…      ┆   ┆ LEL…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# GeneticGym

In [46]:
!mkdir -p {BENCH_DIR}/genetics_gym
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/dd-with-combined-controls.tsv.bgz -O {BENCH_DIR}/genetics_gym/dd-with-combined-controls.tsv.bgz
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/asd-with-combined-controls.tsv.bgz -O {BENCH_DIR}/genetics_gym/asd-with-combined-controls.tsv.bgz
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/chd-with-combined-controls.tsv.bgz -O {BENCH_DIR}/genetics_gym/chd-with-combined-controls.tsv.bgz

!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/schema_evaluation_table.tsv.bgz -O {BENCH_DIR}/genetics_gym/schema_evaluation_table.tsv.bgz
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/asc_evaluation_table.tsv.bgz -O {BENCH_DIR}/genetics_gym/asc_evaluation_table.tsv.bgz
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/epi25_evaluation_table.tsv.bgz -O {BENCH_DIR}/genetics_gym/epi25_evaluation_table.tsv.bgz


!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/genebass_evaluation_table.tsv.bgz -O {BENCH_DIR}/genetics_gym/genebass_evaluation_table.tsv.bgz
!wget -nc https://storage.googleapis.com/genetics-gym/evaluation_tables/gnomad-independent-set.tsv.bgz -O {BENCH_DIR}/genetics_gym/gnomad-independent-set.tsv.bgz

File ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/dd-with-combined-controls.tsv.bgz’ already there; not retrieving.
--2026-01-26 18:35:57--  https://storage.googleapis.com/genetics-gym/evaluation_tables/asd-with-combined-controls.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:804::201b, 2a00:1450:4001:80d::201b, 2a00:1450:4001:831::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:804::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 95112 (93K) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/asd-with-combined-controls.tsv.bgz’

/s/project/deeprvat 100%[===================>]  92.88K   580KB/s    in 0.2s

2026-01-26 18:35:58 (580 KB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/asd-with-combined-controls.tsv.bgz’ saved [95112/95112]

--2026-01-26 18:35:58--  https://storage.googleapis.com/genetics-gym/evaluation_tables/chd-with-combined-controls.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:814::201b, 2a00:1450:4001:831::201b, 2a00:1450:4001:80d::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:814::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49728 (49K) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/chd-with-combined-controls.tsv.bgz’

/s/project/deeprvat 100%[===================>]  48.56K  --.-KB/s    in 0.04s

2026-01-26 18:35:59 (1.23 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/chd-with-combined-controls.tsv.bgz’ saved [49728/49728]

File ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/schema_evaluation_table.tsv.bgz’ already there; not retrieving.
--2026-01-26 18:36:00--  https://storage.googleapis.com/genetics-gym/evaluation_tables/asc_evaluation_table.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:814::201b, 2a00:1450:4001:831::201b, 2a00:1450:4001:80d::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:814::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2995986 (2.9M) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/asc_evaluation_table.tsv.bgz’

/s/project/deeprvat 100%[===================>]   2.86M  12.5MB/s    in 0.2s

2026-01-26 18:36:00 (12.5 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/asc_evaluation_table.tsv.bgz’ saved [2995986/2995986]

--2026-01-26 18:36:01--  https://storage.googleapis.com/genetics-gym/evaluation_tables/epi25_evaluation_table.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:814::201b, 2a00:1450:4001:831::201b, 2a00:1450:4001:80d::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:814::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14273301 (14M) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/epi25_evaluation_table.tsv.bgz’

/s/project/deeprvat 100%[===================>]  13.61M  12.7MB/s    in 1.1s

2026-01-26 18:36:02 (12.7 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/epi25_evaluation_table.tsv.bgz’ saved [14273301/14273301]

--2026-01-26 18:36:03--  https://storage.googleapis.com/genetics-gym/evaluation_tables/genebass_evaluation_table.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:814::201b, 2a00:1450:4001:831::201b, 2a00:1450:4001:80d::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:814::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1124676 (1.1M) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/genebass_evaluation_table.tsv.bgz’

/s/project/deeprvat 100%[===================>]   1.07M  3.00MB/s    in 0.4s

2026-01-26 18:36:03 (3.00 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/genebass_evaluation_table.tsv.bgz’ saved [1124676/1124676]

--2026-01-26 18:36:04--  https://storage.googleapis.com/genetics-gym/evaluation_tables/gnomad-independent-set.tsv.bgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:814::201b, 2a00:1450:4001:831::201b, 2a00:1450:4001:80d::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:814::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 285887196 (273M) [application/octet-stream]
Saving to: ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/gnomad-independent-set.tsv.bgz’

/s/project/deeprvat 100%[===================>] 272.64M  37.4MB/s    in 8.0s

2026-01-26 18:36:12 (34.1 MB/s) - ‘/s/project/deeprvat/ukb_gym/other_benchmarks/genetics_gym/gnomad-independent-set.tsv.bgz’ saved [285887196/285887196]

In [44]:
geneticsgym_ddd = (
    pl.read_csv(f"{BENCH_DIR}/genetics_gym/dd-with-combined-controls.tsv.bgz", separator="\t")
    
)
geneticsgym_ddd

shape: (31_963, 5)
┌──────────────────────┬───────────┬─────┬─────┬───────────┐
│ chrom                ┆ pos       ┆ ref ┆ alt ┆ is_pos_dd │
│ ---                  ┆ ---       ┆ --- ┆ --- ┆ ---       │
│ str                  ┆ i64       ┆ str ┆ str ┆ bool      │
╞══════════════════════╪═══════════╪═════╪═════╪═══════════╡
│ chr1                 ┆ 935836    ┆ G   ┆ A   ┆ true      │
│ chr1                 ┆ 942482    ┆ T   ┆ C   ┆ true      │
│ chr1                 ┆ 942642    ┆ G   ┆ A   ┆ true      │
│ chr1                 ┆ 945120    ┆ G   ┆ C   ┆ true      │
│ chr1                 ┆ 948519    ┆ T   ┆ C   ┆ true      │
│ …                    ┆ …         ┆ …   ┆ …   ┆ …         │
│ chrX                 ┆ 154773227 ┆ G   ┆ A   ┆ true      │
│ chrX                 ┆ 154776317 ┆ G   ┆ A   ┆ true      │
│ chrX                 ┆ 154906457 ┆ C   ┆ T   ┆ false     │
│ chrX                 ┆ 154906494 ┆ A   ┆ G   ┆ true      │
│ chr22_KI270879v1_alt ┆ 273568    ┆ G   ┆ A   ┆ true      │
└──────────────────────┴───────────┴─────┴─────┴───────────┘

In [47]:
geneticsgym = pl.read_csv(f"{BENCH_DIR}/genetics_gym/gnomad-independent-set.tsv.bgz", separator="\t")
geneticsgym

shape: (96_711_739, 5)
┌───────┬───────────┬─────┬─────┬────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ is_pos │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---    │
│ str   ┆ i64       ┆ str ┆ str ┆ bool   │
╞═══════╪═══════════╪═════╪═════╪════════╡
│ chr1  ┆ 65431     ┆ C   ┆ A   ┆ true   │
│ chr1  ┆ 65431     ┆ C   ┆ G   ┆ true   │
│ chr1  ┆ 65431     ┆ C   ┆ T   ┆ true   │
│ chr1  ┆ 65432     ┆ A   ┆ C   ┆ true   │
│ chr1  ┆ 65432     ┆ A   ┆ G   ┆ true   │
│ …     ┆ …         ┆ …   ┆ …   ┆ …      │
│ chrX  ┆ 156010408 ┆ A   ┆ C   ┆ true   │
│ chrX  ┆ 156010408 ┆ A   ┆ G   ┆ true   │
│ chrX  ┆ 156010408 ┆ A   ┆ T   ┆ true   │
│ chrX  ┆ 156010409 ┆ G   ┆ A   ┆ true   │
│ chrX  ┆ 156010409 ┆ G   ┆ T   ┆ true   │
└───────┴───────────┴─────┴─────┴────────┘

# Compile all datasets

In [67]:
common_cols = ['id', 'variant_region', 'pathogenic', 'benchmark']

oth_bmrk = pl.concat([
        clinvar.select(common_cols), #.drop_nulls(subset=['pathogenic']),
        trait_gym_m.select(common_cols),
        trait_gym_c.select(common_cols),
        proteingym_snp.select(common_cols),
        proteingym_indel.select(common_cols),
    ],
    how="vertical_relaxed"
)

oth_bmrk_plot = (
    oth_bmrk
    .with_columns(
        n_variants = pl.len().over("benchmark"),
        n_pathogenic = pl.col("pathogenic").cast(pl.Int64).sum().over("benchmark")
    )
    .with_columns(
        n_variants_region = pl.len().over(["benchmark", "variant_region"]),
        n_pathogenic_region = pl.col("pathogenic").cast(pl.Int64).sum().over(["benchmark", "variant_region"])
    )
    .with_columns(
        frac_pathogenic = pl.col("n_pathogenic") / pl.col("n_variants"),
        frac_pathogenic_region = pl.col("n_pathogenic_region") / pl.col("n_variants_region"),
    )
    .filter(pl.col("pathogenic").is_not_null())
    .select([
        "benchmark",
        "variant_region",
        "n_variants",
        "n_pathogenic",
        "n_variants_region",
        "n_pathogenic_region",
        "frac_pathogenic",
        "frac_pathogenic_region"
    ])
    .unique()
)

oth_bmrk_plot

shape: (36, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ benchmark  ┆ variant_re ┆ n_variants ┆ n_pathoge ┆ n_variant ┆ n_pathoge ┆ frac_path ┆ frac_path │
│ ---        ┆ gion       ┆ ---        ┆ nic       ┆ s_region  ┆ nic_regio ┆ ogenic    ┆ ogenic_re │
│ str        ┆ ---        ┆ u64        ┆ ---       ┆ ---       ┆ n         ┆ ---       ┆ gion      │
│            ┆ str        ┆            ┆ i64       ┆ u64       ┆ ---       ┆ f64       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆ i64       ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ClinVar    ┆ genic_upst ┆ 4280453    ┆ 286303    ┆ 863       ┆ 54        ┆ 0.066886  ┆ 0.062572  │
│            ┆ ream_trans ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ cript_vari ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ ClinVar    ┆ 3_prime_UT ┆ 4280453    ┆ 286303    ┆ 72266     ┆ 275       ┆ 0.066886  ┆ 0.003805  │
│            ┆ R_variant  ┆            ┆           ┆           ┆           ┆           ┆           │
│ TraitGym   ┆ PLS_flank  ┆ 14780      ┆ 1478      ┆ 170       ┆ 17        ┆ 0.1       ┆ 0.1       │
│ mendelian  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ traits     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ (mat…      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ProteinGym ┆ missense_v ┆ 485830     ┆ 12821     ┆ 485830    ┆ 12821     ┆ 0.02639   ┆ 0.02639   │
│ SNP        ┆ ariant     ┆            ┆           ┆           ┆           ┆           ┆           │
│ (human)    ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ClinVar    ┆ null       ┆ 4280453    ┆ 286303    ┆ 19909     ┆ 1783      ┆ 0.066886  ┆ 0.089557  │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ ClinVar    ┆ stop_lost  ┆ 4280453    ┆ 286303    ┆ 1642      ┆ 273       ┆ 0.066886  ┆ 0.166261  │
│ ClinVar    ┆ no_sequenc ┆ 4280453    ┆ 286303    ┆ 595       ┆ 2         ┆ 0.066886  ┆ 0.003361  │
│            ┆ e_alterati ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ on         ┆            ┆           ┆           ┆           ┆           ┆           │
│ ClinVar    ┆ intron_var ┆ 4280453    ┆ 286303    ┆ 654752    ┆ 3781      ┆ 0.066886  ┆ 0.005775  │
│            ┆ iant       ┆            ┆           ┆           ┆           ┆           ┆           │
│ ClinVar    ┆ inframe_in ┆ 4280453    ┆ 286303    ┆ 5480      ┆ 443       ┆ 0.066886  ┆ 0.080839  │
│            ┆ sertion    ┆            ┆           ┆           ┆           ┆           ┆           │
│ TraitGym   ┆ upstream_g ┆ 14780      ┆ 1478      ┆ 210       ┆ 21        ┆ 0.1       ┆ 0.1       │
│ mendelian  ┆ ene_varian ┆            ┆           ┆           ┆           ┆           ┆           │
│ traits     ┆ t          ┆            ┆           ┆           ┆           ┆           ┆           │
│ (mat…      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
(
    
)