In [1]:
import yaml
import numpy as np
import polars as pl
from tqdm import tqdm
import statsmodels.api as sm

from plotnine import *
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'

In [2]:
# Configuration and paths
mac = 20
pheno_list_type = None
# pheno_list_type = 'biochemistry'
# pheno_list_type = 'overall_phenotype'

new_anno_df_path = None

# Load phenotype configuration
pheno_config_path = "/home/dnanexus/ukbgym/phenotype_config.yaml"
with open(pheno_config_path) as f:
    pheno_config = yaml.safe_load(f)

if pheno_list_type is not None:
    pheno_list = pheno_config[pheno_list_type]

eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'

# Load annotation configuration
config_path = "/home/dnanexus/ukbgym/config_odds.yaml"
with open(config_path) as f:
    config = yaml.safe_load(f)

records = [
    {
        "category": category,
        "annotation": anno,
        "color": props["color"],
        "label": props["label"],
        "annotation_dir": props.get("direction", 1),
    }
    for category, annos in config["rare_variant_annotations"].items()
    for anno, props in annos.items()
]

# Create the DataFrame directly from the list of records
anno_config_df = pl.DataFrame(records).with_columns(
    pl.col("annotation_dir").cast(pl.Int8)
)

all_annotation_list = anno_config_df.select(pl.col("annotation")).to_series().to_list()

anno_config_df

shape: (14, 5)
┌───────────────────┬──────────────────────────────┬─────────┬─────────────────┬────────────────┐
│ category          ┆ annotation                   ┆ color   ┆ label           ┆ annotation_dir │
│ ---               ┆ ---                          ┆ ---     ┆ ---             ┆ ---            │
│ str               ┆ str                          ┆ str     ┆ str             ┆ i8             │
╞═══════════════════╪══════════════════════════════╪═════════╪═════════════════╪════════════════╡
│ missense          ┆ am_pathogenicity             ┆ #FFCA28 ┆ AlphaMissense   ┆ 1              │
│ missense          ┆ esmscoremissense             ┆ #FB8C00 ┆ ESM1v           ┆ -1             │
│ missense          ┆ score_pai3d                  ┆ #D84315 ┆ PrimateAI-3D    ┆ 1              │
│ genetic_diversity ┆ cadd_raw                     ┆ #1f77b4 ┆ CADD Raw        ┆ 1              │
│ conservation      ┆ gpn_star_llr_calibrated_mean ┆ #942c80 ┆ GPN-Star        ┆ -1             │
│ …                 ┆ …                            ┆ …       ┆ …               ┆ …              │
│ splicing          ┆ absplice_dna_max             ┆ #00838F ┆ AbSplice (max)  ┆ 1              │
│ splicing          ┆ absplice2_max                ┆ #26C6DA ┆ AbSplice2 (max) ┆ 1              │
│ regulatory_nondir ┆ promoterai_abs               ┆ #00A99D ┆ PromoterAI abs  ┆ -1             │
│ regulatory_nondir ┆ abexp_abs_max                ┆ #80CBC4 ┆ AbExp abs max   ┆ 1              │
│ regulatory        ┆ promoterai                   ┆ #00A99D ┆ PromoterAI      ┆ 1              │
└───────────────────┴──────────────────────────────┴─────────┴─────────────────┴────────────────┘

In [3]:
# new_anno_df_path = '/home/dnanexus/data_dir/flashzoi_proximal_variants_gencode40_avg_score.parquet'

# new_anno_df = (
#     pl.read_parquet(new_anno_df_path)
#     .with_columns(
#         fz_blood = (pl.col('RNA:blood_7531') + pl.col('RNA:blood_7532') + pl.col('RNA:blood_7533'))/3
#     )
#     .with_columns(
#         max_fz_blood = pl.col('fz_blood').abs()
#     )
#     .select(['id', 'region', 'fz_blood', 'max_fz_blood'])
#     .lazy()
# )

# new_anno_df.head().collect()

In [4]:
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fillna_ukbgym.parquet -o /home/dnanexus/data_dir/annotations_fillna_ukbgym.parquet

# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_ukbgym.parquet -o /home/dnanexus/data_dir/annotations_ukbgym.parquet

Error: path "/home/dnanexus/data_dir/annotations_fillna_ukbgym.parquet"
already exists but -f/--overwrite was not set

In [5]:
anno = pl.scan_parquet("/home/dnanexus/data_dir/annotations_fillna_ukbgym.parquet")

min_range = -500
max_range = +500

# Join new annotation if specified above
if new_anno_df_path is not None:
    anno = (
        anno
        .join(
            new_anno_df,
            on=['id', 'region'],
            how='left'
        )
    )

existing_annos = [c for c in all_annotation_list if c in anno.collect_schema().names()]
fillna_cols = [c+'_is_na' for c in existing_annos]

anno = (
    anno
    # .with_columns(
    #     encode_eh_pr = pl.any_horizontal((pl.col(c) == 1) for c in ['encode_pls', 'encode_pels', 'encode_dels']),
    #     encode_all_tf = pl.any_horizontal((pl.col(c) == 1) for c in ['encode_tf', 'encode_ca_tf']),
    # )
    .filter(
        # Choose CDS
        # (pl.col('vep_cds_relaxed')==True) &
        # ((pl.col('vep_cds_relaxed')==True) | (pl.col('mane_cds')==True)) &
        # (pl.col('non_mane_cds')==False) &

        # Choose non CDS only
        # ((pl.col('vep_cds_relaxed')==False) & (pl.col('mane_cds')==False) & (pl.col('non_mane_cds')==False)) &

        # Choose VEP consequence
        # (pl.col('consequence_synonymous_variant') == True) &
        # (pl.col('consequence_missense_variant') == True) &
        # (pl.col('consequence_upstream_gene_variant') == True) &
        # (pl.col('consequence_downstream_gene_variant') == True) &
        # (pl.col('consequence_intron_variant') == True) &

        # Choose pLoF variants
        # (pl.col('loftee_hc') == True) &

        # Choose protein domain
        # (pl.col('ted_domain') == True) &
        # (pl.col('mobi_curated_disorder_priority') == True) &
        # (pl.col('mobi_lip_full') == True) &
        # (pl.col('low_complexity_domain') == True) &

        # Choose regulatory region
        # (pl.col('not_in_encode') == False) &
        # (pl.col('encode_eh_pr') == True) &
        # (pl.col('encode_all_tf') == True) &

        # Choose Gene Body
        ((pl.col('consequence_upstream_gene_variant') == False) & (pl.col('consequence_downstream_gene_variant') == False)) &

        # Distance to TSS range
        # (pl.col('dist_to_tss') >= min_range) &
        # (pl.col('dist_to_tss') <= max_range) &

        # Only SNPs
        (pl.col('ref').str.len_chars()==1) & (pl.col('alt').str.len_chars()==1)
    )
    .select(
        set(['id', 'region', 'tss', 'strand', 'gene_length', 'gene_name', 'dist_to_tss']).union(set(existing_annos))
    )
    .collect(engine='streaming')

)

anno

shape: (59_774_470, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ region    ┆ absplice_ ┆ gene_leng ┆ promotera ┆ … ┆ esmscorem ┆ delta_sco ┆ absplice2 ┆ tss      │
│ ---       ┆ dna_max   ┆ th        ┆ i         ┆   ┆ issense   ┆ re        ┆ _max      ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64      │
│           ┆ f32       ┆ i64       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ f32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ 0.0       ┆ 766461    ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4467273  │
│ 144455    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.00057   ┆ 106911    ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 70554193 │
│ 163235    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.0       ┆ 521708    ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 79611051 │
│ 167281    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.00057   ┆ 124730    ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 10302888 │
│ 115756    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.001     ┆ 39208     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 52416373 │
│ 136114    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ 0.001     ┆ 55751     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 60402883 │
│ 182718    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.001     ┆ 37422     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 11313623 │
│ 111344    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ ENSG00000 ┆ 0.0       ┆ 288606    ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 10539930 │
│ 135250    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ ENSG00000 ┆ 0.001     ┆ 99650     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.000033  ┆ 37095997 │
│ 080839    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ 0.0       ┆ 1163126   ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 21253884 │
│ 178568    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
anno_fillna = pl.scan_parquet("/home/dnanexus/data_dir/annotations_fillna_ukbgym.parquet")
fillna_cols = set([c+'_is_na' for c in existing_annos]).intersection(set(anno_fillna.collect_schema().names()))

anno_fillna_melted = (
    anno_fillna
    .select(['id', 'region'] + list(fillna_cols))
    .join(
        anno.select(['id', 'region']).lazy(), 
        on=['id', 'region'], 
        how='semi'
    )
    .unpivot(
        index=["id", "region"],
        on=list(fillna_cols),
        variable_name="annotation",
        value_name="annotation_is_na"
    )
    .filter(
        pl.col('annotation_is_na') == False
    )
    .with_columns(
        annotation = pl.col('annotation').str.replace('_is_na$', '')
    )
    # .collect(engine='streaming')
)

anno_fillna_melted.head().collect()

shape: (5, 4)
┌─────────────────────┬─────────────────┬───────────────┬──────────────────┐
│ id                  ┆ region          ┆ annotation    ┆ annotation_is_na │
│ ---                 ┆ ---             ┆ ---           ┆ ---              │
│ str                 ┆ str             ┆ str           ┆ i8               │
╞═════════════════════╪═════════════════╪═══════════════╪══════════════════╡
│ chr3:4371441:T:G    ┆ ENSG00000144455 ┆ abexp_abs_max ┆ 0                │
│ chr2:70468778:G:T   ┆ ENSG00000163235 ┆ abexp_abs_max ┆ 0                │
│ chr2:10307124:C:T   ┆ ENSG00000115756 ┆ abexp_abs_max ┆ 0                │
│ chr13:52400884:G:C  ┆ ENSG00000136114 ┆ abexp_abs_max ┆ 0                │
│ chr13:101658988:C:T ┆ ENSG00000198542 ┆ abexp_abs_max ┆ 0                │
└─────────────────────┴─────────────────┴───────────────┴──────────────────┘

In [7]:
selected_annos = anno_config_df.filter(
    # (pl.col('category').is_in(['missense', 'genetic_diversity', 'conservation', 'splicing'])) # CDS
    # pl.col('category').is_in(['missense', 'genetic_diversity', 'conservation', 'regulatory_nondir']) # missense
    # pl.col('category').is_in(['genetic_diversity', 'conservation', 'splicing']) # 'splicing'

    # (pl.col('category').is_in(['genetic_diversity', 'splicing', 'conservation', 'regulatory_nondir'])) # non coding
    # (pl.col('category').is_in(['genetic_diversity', 'splicing', 'conservation'])) # introns
    # (pl.col('annotation').is_in(['am_pathogenicity', 'esmscoremissense', 'gpn_star_llr_calibrated_mean', 'cadd_raw', 'pangolin_score', 'abexp_abs_max']))
    (pl.col('annotation').is_in(['am_pathogenicity', 'esmscoremissense', 'gpn_score', 'cadd_raw', 'pangolin_score', 'abexp_abs_max']))
)['annotation'].to_list()

melted_anno = (
    anno.lazy()

    .select(
        set(['id', 'region', 'gene_name']).union(set(selected_annos))
    )

    .unpivot(
        index=["id", "region", "gene_name"],
        on=selected_annos,
        variable_name="annotation",
        value_name="annotation_score"
    )
    .with_columns(
        pl.col("annotation_score").cast(pl.Float32),
        pl.col("region").cast(pl.Utf8),
    )

    # Merge with annotation configuration to get direction and filter
    .join(
        anno_config_df.select(["annotation", "category", "annotation_dir"]).lazy(),
        on="annotation",
        how="left"
    )

    # Remove null annotation scores
    .drop_nulls('annotation_score')

    # Correct scores by annotation direction
    .with_columns(
        annotation_score_dircor = pl.col('annotation_score') * pl.col("annotation_dir").cast(pl.Float32)
    )
    
    # Implement filtering based on the defined percentile
    .with_columns(
        annotation_score_dircor_rank_desc = pl.col('annotation_score_dircor').rank(method="max", descending=True).over(["annotation"]).cast(pl.Float32)
    )
    .drop(['annotation_score_dircor'])

    # Keep variants that don't have fillna annotation
    .join(
        anno_fillna_melted,
        on=['id', 'region', 'annotation'],
        how='semi'
    )

    .collect(engine='streaming')
)

melted_anno

shape: (226_750_159, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ region     ┆ gene_name ┆ annotation ┆ annotatio ┆ category  ┆ annotatio ┆ annotatio │
│ ---        ┆ ---        ┆ ---       ┆ ---        ┆ n_score   ┆ ---       ┆ n_dir     ┆ n_score_d │
│ str        ┆ str        ┆ str       ┆ str        ┆ ---       ┆ str       ┆ ---       ┆ ircor_ran │
│            ┆            ┆           ┆            ┆ f32       ┆           ┆ i8        ┆ k_d…      │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ ---       │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ f32       │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr2:15169 ┆ ENSG000001 ┆ NEB       ┆ abexp_abs_ ┆ 0.019552  ┆ regulator ┆ 1         ┆ 7.48783e6 │
│ 1610:T:C   ┆ 83091      ┆           ┆ max        ┆           ┆ y_nondir  ┆           ┆           │
│ chr21:2131 ┆ ENSG000001 ┆ NCAM2     ┆ abexp_abs_ ┆ 0.005501  ┆ regulator ┆ 1         ┆ 5.291878e │
│ 8231:G:T   ┆ 54654      ┆           ┆ max        ┆           ┆ y_nondir  ┆           ┆ 7         │
│ chr17:7947 ┆ ENSG000001 ┆ RBFOX3    ┆ abexp_abs_ ┆ 0.006358  ┆ regulator ┆ 1         ┆ 2.4311636 │
│ 2318:A:G   ┆ 67281      ┆           ┆ max        ┆           ┆ y_nondir  ┆           ┆ e7        │
│ chr7:20466 ┆ ENSG000000 ┆ MAD1L1    ┆ abexp_abs_ ┆ 0.006189  ┆ regulator ┆ 1         ┆ 3.9118328 │
│ 03:T:G     ┆ 02822      ┆           ┆ max        ┆           ┆ y_nondir  ┆           ┆ e7        │
│ chr3:18873 ┆ ENSG000001 ┆ LPP       ┆ abexp_abs_ ┆ 0.014604  ┆ regulator ┆ 1         ┆ 9.399867e │
│ 4593:C:T   ┆ 45012      ┆           ┆ max        ┆           ┆ y_nondir  ┆           ┆ 6         │
│ …          ┆ …          ┆ …         ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ chr1:17185 ┆ ENSG000001 ┆ DNM3      ┆ pangolin_s ┆ 0.0       ┆ splicing  ┆ 1         ┆ 5.9774472 │
│ 2954:T:A   ┆ 97959      ┆           ┆ core       ┆           ┆           ┆           ┆ e7        │
│ chr15:6035 ┆ ENSG000001 ┆ ANXA2     ┆ pangolin_s ┆ 0.0       ┆ splicing  ┆ 1         ┆ 5.9774472 │
│ 8397:G:C   ┆ 82718      ┆           ┆ core       ┆           ┆           ┆           ┆ e7        │
│ chr12:1131 ┆ ENSG000001 ┆ RASAL1    ┆ pangolin_s ┆ 0.0       ┆ splicing  ┆ 1         ┆ 5.9774472 │
│ 26824:C:T  ┆ 11344      ┆           ┆ core       ┆           ┆           ┆           ┆ e7        │
│ chr7:10527 ┆ ENSG000001 ┆ SRPK2     ┆ pangolin_s ┆ 0.0       ┆ splicing  ┆ 1         ┆ 5.9774472 │
│ 0439:C:A   ┆ 35250      ┆           ┆ core       ┆           ┆           ┆           ┆ e7        │
│ chr20:3700 ┆ ENSG000000 ┆ RBL1      ┆ pangolin_s ┆ 0.0       ┆ splicing  ┆ 1         ┆ 5.9774472 │
│ 9651:C:G   ┆ 80839      ┆           ┆ core       ┆           ┆           ┆           ┆ e7        │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [8]:
anno['gene_name'].value_counts(sort=True)

shape: (3_468, 2)
┌───────────┬────────┐
│ gene_name ┆ count  │
│ ---       ┆ ---    │
│ str       ┆ u64    │
╞═══════════╪════════╡
│ CNTNAP2   ┆ 548862 │
│ FHIT      ┆ 399955 │
│ ROBO2     ┆ 399693 │
│ NRXN3     ┆ 350037 │
│ CNTN5     ┆ 340776 │
│ …         ┆ …      │
│ UPK3BL1   ┆ 189    │
│ AHSP      ┆ 188    │
│ HBA2      ┆ 176    │
│ CCL27     ┆ 171    │
│ OMP       ┆ 159    │
└───────────┴────────┘

In [9]:
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/ukbgym/avg_pheno_per_var/loftee_mac20_quant_pheno_assocs_EURunrelated_appv_percentiles.parquet -o /home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrelated_appv_percentiles.parquet

appv = pl.scan_parquet("/home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrelated_appv_percentiles.parquet")

# Create a lazy frame with the unique keys
anno_keys = anno.select(pl.col('id').unique()).lazy()

# Chain the filter and the much faster semi join
appv = (
    appv
    .join(
        anno_keys, on='id', how='semi'
    )
    .filter(
        pl.col('n_individuals') <= mac
    )
    .select(
        ['id', 'phenotype', 'mean_pheno_value_ptile', 'n_individuals']
    )
)
# unique_phenotypes = appv.select('phenotype').unique().collect(engine='streaming').to_series()

Error: path "/home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrela
ted_appv_percentiles.parquet" already exists but -f/--overwrite was not set

In [10]:
# Get gene trait associations
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/regenie_127phenotypes_lofteeHC_mac20_EUR.parquet -o /home/dnanexus/data_dir/
# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/loftee_mac20_associations_bh_corrected.parquet -o /home/dnanexus/data_dir/

!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/regenie_127phenotypes_mac20_lofteeHC_EUR_correlations.parquet -o /home/dnanexus/data_dir/

gene_trait_df = (
    pl.read_parquet('/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20_EUR.parquet')
    .filter(pl.col('pval_fdr')<=0.05)
    .select(['region', 'phenotype', 'pval_fdr'])
)

loftee_corrs = (
    pl.read_parquet('/home/dnanexus/data_dir/regenie_127phenotypes_mac20_lofteeHC_EUR_correlations.parquet')
    .with_columns(
        loftee_corr = pl.col('correlation'),
        loftee_corr_abs = pl.col('correlation').abs(),
        loftee_corr_dir = pl.col('correlation')/pl.col('correlation').abs(),
    )
    .select(['region', 'phenotype', 'loftee_corr', 'loftee_corr_abs', 'loftee_corr_dir']) 
)

gene_trait_df = (
    gene_trait_df
    .join(loftee_corrs, on=['region', 'phenotype'], how='inner')
    .drop_nans()
    # .sort('loftee_corr_abs', descending=True)
    # .sort('pval_fdr')
    # .unique(subset=["region"], keep="first", maintain_order=True)
)
gene_trait_df

Error: path
"/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20_EUR.parquet"
already exists but -f/--overwrite was not set
Error: path "/home/dnanexus/data_dir/regenie_127phenotypes_mac20_lofteeHC_EUR_
correlations.parquet" already exists but -f/--overwrite was not set

shape: (2_283, 6)
┌─────────────────┬───────────────────┬──────────┬─────────────┬─────────────────┬─────────────────┐
│ region          ┆ phenotype         ┆ pval_fdr ┆ loftee_corr ┆ loftee_corr_abs ┆ loftee_corr_dir │
│ ---             ┆ ---               ┆ ---      ┆ ---         ┆ ---             ┆ ---             │
│ str             ┆ str               ┆ f64      ┆ f64         ┆ f64             ┆ f64             │
╞═════════════════╪═══════════════════╪══════════╪═════════════╪═════════════════╪═════════════════╡
│ ENSG00000067900 ┆ lymphocyte_count_ ┆ 0.015659 ┆ -0.097882   ┆ 0.097882        ┆ -1.0            │
│                 ┆ int               ┆          ┆             ┆                 ┆                 │
│ ENSG00000145386 ┆ mean_corpuscular_ ┆ 0.000096 ┆ -0.059845   ┆ 0.059845        ┆ -1.0            │
│                 ┆ haemoglobin_i…    ┆          ┆             ┆                 ┆                 │
│ ENSG00000164944 ┆ trunk_predicted_m ┆ 0.015511 ┆ -0.04623    ┆ 0.04623         ┆ -1.0            │
│                 ┆ ass_int           ┆          ┆             ┆                 ┆                 │
│ ENSG00000107863 ┆ trunk_predicted_m ┆ 0.033889 ┆ -0.122605   ┆ 0.122605        ┆ -1.0            │
│                 ┆ ass_int           ┆          ┆             ┆                 ┆                 │
│ ENSG00000121966 ┆ eosinophill_perce ┆ 0.000392 ┆ -0.075765   ┆ 0.075765        ┆ -1.0            │
│                 ┆ ntage_int         ┆          ┆             ┆                 ┆                 │
│ …               ┆ …                 ┆ …        ┆ …           ┆ …               ┆ …               │
│ ENSG00000142208 ┆ arm_predicted_mas ┆ 0.009537 ┆ -0.049973   ┆ 0.049973        ┆ -1.0            │
│                 ┆ s_right_int       ┆          ┆             ┆                 ┆                 │
│ ENSG00000101670 ┆ cholesterol_int   ┆ 0.000099 ┆ 0.035791    ┆ 0.035791        ┆ 1.0             │
│ ENSG00000017427 ┆ weight_int        ┆ 0.000158 ┆ -0.170599   ┆ 0.170599        ┆ -1.0            │
│ ENSG00000106105 ┆ alkaline_phosphat ┆ 0.010566 ┆ 0.103998    ┆ 0.103998        ┆ 1.0             │
│                 ┆ ase_int           ┆          ┆             ┆                 ┆                 │
│ ENSG00000243477 ┆ haemoglobin_conce ┆ 0.024743 ┆ -0.060161   ┆ 0.060161        ┆ -1.0            │
│                 ┆ ntration_int      ┆          ┆             ┆                 ┆                 │
└─────────────────┴───────────────────┴──────────┴─────────────┴─────────────────┴─────────────────┘

In [11]:
# Get gene trait associations - OLD

# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/association_files/rvat_EUR_500k_regenie.parquet -o /home/dnanexus/data_dir/association_files/rvat_EUR_500k_regenie.parquet
# plof = pl.read_parquet('/home/dnanexus/data_dir/association_files/rvat_EUR_500k_regenie.parquet').with_columns(
#     phenotype = (pl.col('trait') + '_int'),
#     region = pl.col('gene_id'),
#     rvat_pval = (10** -pl.col("neg_log10p")),
# ).filter(
#     (pl.col('trait_type') == 'quantitative')
# )

# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/association_files/loftee_correlation_quantitative_wgs_EUR_genebass1e6_maf1e3_snp_consistent.parquet -o /home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_wgs_EUR_genebass1e6_maf1e3_snp_consistent.parquet
# loftee_corr = pl.read_parquet("/home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_wgs_EUR_genebass1e6_maf1e3_snp_consistent.parquet")

# gene_trait_df = loftee_corr.join(plof[['region', 'phenotype', 'beta', 'rvat_pval']], on=['region', 'phenotype'], how='inner').filter(
#     pl.col('loftee_corr')*pl.col('beta') > 0
# ).with_columns(
#     loftee_corr_dir = pl.col('loftee_corr')/pl.col('loftee_corr').abs()
# )

# if pheno_list_type is not None:
#     gene_trait_df = gene_trait_df.filter(pl.col('phenotype').is_in(pheno_list))

# gene_trait_df

## Odds ratio computation

In [12]:
n_steps = 101
min_rank_cutoff = 100
max_rank_cutoff = 10_000_000
max_rank_cutoff = np.min([max_rank_cutoff, anno.shape[0]])
or_threshold_pheno = 0.99

# We assume that all models score the same number of variants (all the variants in 'anno')
log_steps = np.geomspace(min_rank_cutoff, max_rank_cutoff, n_steps)

cutoffs_lazy = pl.LazyFrame({"rank_cutoff": log_steps.astype(int)})

cutoffs_lazy.collect()

shape: (101, 1)
┌─────────────┐
│ rank_cutoff │
│ ---         │
│ i64         │
╞═════════════╡
│ 100         │
│ 112         │
│ 125         │
│ 141         │
│ 158         │
│ …           │
│ 6309573     │
│ 7079457     │
│ 7943282     │
│ 8912509     │
│ 10000000    │
└─────────────┘

In [ ]:
# --- 1. Lazily prepare the filter keys ---
region_keys = gene_trait_df.lazy().select(pl.col('region').unique())
anno_ids_lazy = melted_anno.lazy().join(
    region_keys, on='region', how='semi'
).select(pl.col('id').unique())


# --- Build main query (same as before, but stop before group_by) ---
gp_lazy = (
    appv
    .join(
        anno_ids_lazy, 
        on="id", 
        how="semi"
    )
    .join(
        melted_anno.lazy().drop([c for c in melted_anno.columns if 'is_nan' in c]), 
        on="id", 
        how="inner"
    )
    .join(
        gene_trait_df.lazy(), 
        on=["region", "phenotype"], 
        how="inner"
    )
    .with_columns(
        mean_pheno_value_dircor_ptile = pl.when(pl.col('loftee_corr_dir') == -1)
            .then(1 - pl.col('mean_pheno_value_ptile'))
            .otherwise(pl.col('mean_pheno_value_ptile')),
    )
)

# Cross join with cutoffs and compute odds ratios
or_lazy = (
    gp_lazy
    # .select(["annotation", "region", "gene_name", "phenotype", "n_vars_above_ptile", "mean_pheno_value_dircor_ptile"])
    .select(["annotation", "region", "gene_name", "phenotype", "annotation_score_dircor_rank_desc", "mean_pheno_value_dircor_ptile"])
    .join(cutoffs_lazy, how="cross")
    .group_by(["annotation", "region", "gene_name", "phenotype", "rank_cutoff"])
    .agg(
        n_dis_above_cutoff = (
            (pl.col("annotation_score_dircor_rank_desc") <= pl.col("rank_cutoff")) & 
            (pl.col("mean_pheno_value_dircor_ptile") >= or_threshold_pheno)
        ).sum(),
        n_notdis_above_cutoff = (
            (pl.col("annotation_score_dircor_rank_desc") <= pl.col("rank_cutoff")) &
            (pl.col("mean_pheno_value_dircor_ptile") < or_threshold_pheno)
        ).sum(),
        n_dis_below_cutoff = (
            (pl.col("annotation_score_dircor_rank_desc") > pl.col("rank_cutoff")) &
            (pl.col("mean_pheno_value_dircor_ptile") >= or_threshold_pheno)
        ).sum(),
        n_notdis_below_cutoff = (
            (pl.col("annotation_score_dircor_rank_desc") > pl.col("rank_cutoff")) &
            (pl.col("mean_pheno_value_dircor_ptile") < or_threshold_pheno)
        ).sum()
    )
    .with_columns(
        odds_ratio = (pl.col("n_dis_above_cutoff") / pl.col("n_notdis_above_cutoff")) / (pl.col("n_dis_below_cutoff") / pl.col("n_notdis_below_cutoff"))
    )
)

# Execute
print("Executing with odds ratios...")
or_df = or_lazy.collect(engine='streaming').sort('rank_cutoff', descending=True)

or_df

Executing with odds ratios...

## Plotting

In [ ]:
print('unique percentile cutoffs:', or_df['rank_cutoff'].n_unique())

plt_df = (
    or_df
    .drop_nans()
    .filter(pl.col("odds_ratio").is_finite())
    .with_columns(
        n_gene_phenos = pl.len().over(['rank_cutoff', 'annotation']),
        log_rank_cutoff = np.log10(pl.col('rank_cutoff')),
        log_rank_cutoff_inv = np.log10(1/pl.col('rank_cutoff')),
    )
    .with_columns(
        med_odds_ratio = pl.col('odds_ratio').median().over(['rank_cutoff', 'annotation']),
        avg_odds_ratio = pl.col('odds_ratio').mean().over(['rank_cutoff', 'annotation']),
        se_odds_ratio = pl.col('odds_ratio').std().over(['rank_cutoff', 'annotation'])/(pl.col('n_gene_phenos').sqrt()),
    )
    .with_columns(
        std_ci_upper = pl.col('avg_odds_ratio') + 1.96 * (pl.col('se_odds_ratio')),
        std_ci_lower = pl.col('avg_odds_ratio') - 1.96 * (pl.col('se_odds_ratio')),
    )
    .select(['annotation', 'log_rank_cutoff', 'rank_cutoff', 'log_rank_cutoff_inv', 'n_gene_phenos', 'med_odds_ratio', 'avg_odds_ratio', 'se_odds_ratio', 'std_ci_upper', 'std_ci_lower'])
    .unique()
    .join(
        anno_config_df.select(['annotation', 'color', 'label', 'category']),
        on='annotation',
        how='left'
    )
    .sort('log_rank_cutoff')
    
    # Remove data points without ci or with or=0
    .filter(
        (pl.col('std_ci_upper').is_not_null()) &
        (pl.col('std_ci_lower').is_not_null()) &
        (pl.col('n_gene_phenos') >= 20) &
        (pl.col('avg_odds_ratio') > 0) &
        (pl.col('std_ci_lower') > 0)
    )
)

plt_df

unique percentile cutoffs: 101

shape: (463, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ annotation ┆ log_rank_ ┆ rank_cuto ┆ log_rank_ ┆ … ┆ std_ci_lo ┆ color   ┆ label     ┆ category  │
│ ---        ┆ cutoff    ┆ ff        ┆ cutoff_in ┆   ┆ wer       ┆ ---     ┆ ---       ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ v         ┆   ┆ ---       ┆ str     ┆ str       ┆ str       │
│            ┆ f64       ┆ i64       ┆ ---       ┆   ┆ f64       ┆         ┆           ┆           │
│            ┆           ┆           ┆ f64       ┆   ┆           ┆         ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ pangolin_s ┆ 2.849419  ┆ 707       ┆ -2.849419 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ gpn_score  ┆ 2.899821  ┆ 794       ┆ -2.899821 ┆ … ┆ 0.067582  ┆ pink    ┆ GPN-MSA   ┆ conservat │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ ion       │
│ pangolin_s ┆ 2.899821  ┆ 794       ┆ -2.899821 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ pangolin_s ┆ 2.949878  ┆ 891       ┆ -2.949878 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ abexp_abs_ ┆ 2.949878  ┆ 891       ┆ -2.949878 ┆ … ┆ 2.059246  ┆ #80CBC4 ┆ AbExp abs ┆ regulator │
│ max        ┆           ┆           ┆           ┆   ┆           ┆         ┆ max       ┆ y_nondir  │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ pangolin_s ┆ 7.0       ┆ 10000000  ┆ -7.0      ┆ … ┆ 1.051985  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ abexp_abs_ ┆ 7.0       ┆ 10000000  ┆ -7.0      ┆ … ┆ 1.051863  ┆ #80CBC4 ┆ AbExp abs ┆ regulator │
│ max        ┆           ┆           ┆           ┆   ┆           ┆         ┆ max       ┆ y_nondir  │
│ esmscoremi ┆ 7.0       ┆ 10000000  ┆ -7.0      ┆ … ┆ 0.333196  ┆ #FB8C00 ┆ ESM1v     ┆ missense  │
│ ssense     ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ cadd_raw   ┆ 7.0       ┆ 10000000  ┆ -7.0      ┆ … ┆ 1.078804  ┆ #1f77b4 ┆ CADD Raw  ┆ genetic_d │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ iversity  │
│ gpn_score  ┆ 7.0       ┆ 10000000  ┆ -7.0      ┆ … ┆ 1.085596  ┆ pink    ┆ GPN-MSA   ┆ conservat │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ ion       │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [ ]:
plot_df = (
    plt_df
    .filter(
        # (pl.col('log_rank_cutoff_inv') <= -4) &

        # (pl.col('annotation').is_in(['am_pathogenicity', 'score_pai3d', 'esmscoremissense', 'gpn_star_llr_calibrated_mean']))
        (pl.col('annotation').is_in(['am_pathogenicity', 'gpn_score', 'cadd_raw']))
        # (pl.col('annotation').is_in(['am_pathogenicity', 'gpn_star_llr_calibrated_mean', 'cadd_raw', 'abexp_abs_max', 'pangolin_score']))
        # (pl.col('annotation').is_in(['gpn_star_llr_calibrated_mean', 'pangolin_score', 'abexp_abs_max']))
        # (pl.col('annotation').is_in(['gpn_star_llr_calibrated_mean', 'cadd_raw', 'abexp_abs_max', 'promoterai_abs', 'max_fz_blood']))
        # (pl.col('category').is_in(['missense', 'genetic_diversity']))
    )
)

# Generate breaks and labels for x-axis
start_exp = int(np.log10(1/max_rank_cutoff))
end_exp = int(np.log10(1/min_rank_cutoff))
breaks_linear = np.arange(start_exp, end_exp + 1)
labels_sci = [f"1e{-b}" for b in breaks_linear]

# Determine legend order based on final average odds ratio
legend_order = (
    plot_df.sort("log_rank_cutoff_inv")
    .group_by("label", maintain_order=True)
    .last()
    .sort("avg_odds_ratio", descending=True)
    ['label']
    .to_list()
)

color_dict = dict(zip(plt_df['label'], plt_df['color']))
pheno_label = round((1 - or_threshold_pheno) * 100, 1)

loftee_or = pl.DataFrame({
    'region': ['gene_body', 'cds'],
    'n_vars': [-np.log10(131_682), -np.log10(131_682)],
    'mean_or': [4.291864, 3.707762],
    'se_or': [0.192267, 0.130931],
}).with_columns(
    ci_low_pheno = pl.col('mean_or') - 1.96 * pl.col('se_or'),
    ci_high_pheno = pl.col('mean_or') + 1.96 * pl.col('se_or'),
)

(
    ggplot(
        plot_df,
        aes(x='log_rank_cutoff_inv', y='avg_odds_ratio')
    )
    + geom_hline(aes(yintercept=1), color='black', linetype='dotted')
    + geom_line(aes(color='label'), size=1)
    + geom_ribbon(aes(ymin='std_ci_lower', ymax='std_ci_upper', fill='label'), alpha=0.1)
    + geom_point(
        loftee_or.filter(pl.col('region')=='gene_body'), 
        aes(x='n_vars', y='mean_or'),
        color='black',
        size=2
    )
    + geom_errorbar(
        loftee_or.filter(pl.col('region')=='gene_body'),
        aes(ymin='ci_low_pheno', ymax='ci_high_pheno'),
        width=0.2,
    )
    + scale_fill_manual(values=color_dict, limits=legend_order)
    + scale_color_manual(values=color_dict, limits=legend_order)
    + labs(
        title=f"{pheno_list_type} {or_df[['gene_name', 'phenotype']].unique().shape[0]} associations",
        y=f"Average Odds Ratio for\nExtreme Phenotype (Top {pheno_label}%)",
        x="Top N variants",
        color="Annotation",
        fill="Annotation",
    )
    + scale_x_continuous(
        breaks=breaks_linear,
        labels=labels_sci
    )
    + scale_y_log10()
    + annotation_logticks(sides="lb")
    + theme_minimal()
    + theme(
        figure_size=(8, 5.5),
        axis_text=element_text(size=13),
        axis_title=element_text(size=13),
        legend_text=element_text(size=13),
        legend_title=element_text(size=13),
        plot_background=element_rect(fill="white", color="white"),
    )
)

NameError: name 'plt_df' is not defined

In [ ]:
plt_df.head()

shape: (5, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ annotation ┆ log_rank_ ┆ rank_cuto ┆ log_rank_ ┆ … ┆ std_ci_lo ┆ color   ┆ label     ┆ category  │
│ ---        ┆ cutoff    ┆ ff        ┆ cutoff_in ┆   ┆ wer       ┆ ---     ┆ ---       ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ v         ┆   ┆ ---       ┆ str     ┆ str       ┆ str       │
│            ┆ f64       ┆ i64       ┆ ---       ┆   ┆ f64       ┆         ┆           ┆           │
│            ┆           ┆           ┆ f64       ┆   ┆           ┆         ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ pangolin_s ┆ 2.849419  ┆ 707       ┆ -2.849419 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ pangolin_s ┆ 2.899821  ┆ 794       ┆ -2.899821 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ gpn_score  ┆ 2.899821  ┆ 794       ┆ -2.899821 ┆ … ┆ 0.067582  ┆ pink    ┆ GPN-MSA   ┆ conservat │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ ion       │
│ pangolin_s ┆ 2.949878  ┆ 891       ┆ -2.949878 ┆ … ┆ 0.606999  ┆ #2E7D32 ┆ Pangolin  ┆ splicing  │
│ core       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ abexp_abs_ ┆ 2.949878  ┆ 891       ┆ -2.949878 ┆ … ┆ 2.059246  ┆ #80CBC4 ┆ AbExp abs ┆ regulator │
│ max        ┆           ┆           ┆           ┆   ┆           ┆         ┆ max       ┆ y_nondir  │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘