In [1]:
import yaml
import numpy as np
import polars as pl
import polars.selectors as cs
from tqdm import tqdm
import statsmodels.api as sm
from scipy import stats

from plotnine import *
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'

In [3]:
# Configuration and paths
mac = 20
pheno_list_type = None
# pheno_list_type = 'biochemistry'
# pheno_list_type = 'overall_phenotype'

# Load phenotype configuration
pheno_config_path = "/home/dnanexus/ukbgym/phenotype_config.yaml"
with open(pheno_config_path) as f:
    pheno_config = yaml.safe_load(f)

if pheno_list_type is not None:
    pheno_list = pheno_config[pheno_list_type]

eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'

# Load annotation configuration
config_path = "/home/dnanexus/ukbgym/config_wgs.yaml"
with open(config_path) as f:
    config = yaml.safe_load(f)

records = [
    {
        "category": category,
        "annotation": anno,
        "color": props["color"],
        "label": props["label"],
        "annotation_dir": props.get("direction", 1),
    }
    for category, annos in config["rare_variant_annotations"].items()
    for anno, props in annos.items()
]

# Create the DataFrame directly from the list of records
anno_config_df = pl.DataFrame(records).with_columns(
    pl.col("annotation_dir").cast(pl.Int8)
)

all_annotation_list = anno_config_df.select(pl.col("annotation")).to_series().to_list()

anno_config_df

shape: (54, 5)
┌───────────────────┬─────────────────────────────┬─────────┬─────────────────────┬────────────────┐
│ category          ┆ annotation                  ┆ color   ┆ label               ┆ annotation_dir │
│ ---               ┆ ---                         ┆ ---     ┆ ---                 ┆ ---            │
│ str               ┆ str                         ┆ str     ┆ str                 ┆ i8             │
╞═══════════════════╪═════════════════════════════╪═════════╪═════════════════════╪════════════════╡
│ plof              ┆ loftee_hc                   ┆ #E31A1C ┆ LOFTEE HC           ┆ 1              │
│ plof_consequences ┆ consequence_frameshift_vari ┆ #E31A1C ┆ VEP Frameshift      ┆ 1              │
│                   ┆ ant                         ┆         ┆                     ┆                │
│ plof_consequences ┆ consequence_stop_gained     ┆ #FB9A99 ┆ VEP Stop Gained     ┆ 1              │
│ plof_consequences ┆ consequence_splice_donor_va ┆ #6A1B9A ┆ VEP Splice Donor    ┆ 1              │
│                   ┆ ria…                        ┆         ┆                     ┆                │
│ plof_consequences ┆ consequence_splice_acceptor ┆ #AB47BC ┆ VEP Splice Acceptor ┆ 1              │
│                   ┆ _va…                        ┆         ┆                     ┆                │
│ …                 ┆ …                           ┆ …       ┆ …                   ┆ …              │
│ vep_consequences  ┆ consequence_stop_lost       ┆ #FFB300 ┆ VEP Stop Lost       ┆ 1              │
│ vep_consequences  ┆ consequence_missense_varian ┆ #1E90FF ┆ VEP Missense        ┆ 1              │
│                   ┆ t                           ┆         ┆                     ┆                │
│ vep_consequences  ┆ consequence_synonymous_vari ┆ #C6DBEF ┆ VEP Synonymous      ┆ 1              │
│                   ┆ ant                         ┆         ┆                     ┆                │
│ naive             ┆ relative_cds_position       ┆ #b5de2b ┆ Relative CDS        ┆ -1             │
│                   ┆                             ┆         ┆ Position            ┆                │
│ regulatory_nondir ┆ abexp_abs_max               ┆ #80CBC4 ┆ AbExp abs max       ┆ 1              │
└───────────────────┴─────────────────────────────┴─────────┴─────────────────────┴────────────────┘

In [2]:
# Get gene trait associations
RAP_DIR = 'project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results'

# ASSOC_FILE = 'loftee_mac20_associations_bh_corrected.parquet'
# ASSOC_FILE = 'regenie_127phenotypes_lofteeHC_mac20_EUR.parquet'
ASSOC_FILE = 'regenie_127phenotypes_lofteeHC_mac20_EUR_miss20per.parquet'

LOCAL_DIR = '/home/dnanexus/data_dir/'

!dx download {RAP_DIR}/{ASSOC_FILE} -o {LOCAL_DIR}

gene_trait_df = (
    pl.read_parquet(f'{LOCAL_DIR}/{ASSOC_FILE}')
    .filter(pl.col('pval_fdr')<=0.05)
    .select(['region', 'phenotype', 'pval_fdr'])
)

# CORR_FILE = 'regenie_127phenotypes_mac20_lofteeHC_EUR_correlations.parquet'
CORR_FILE = "regenie_127phenotypes_lofteeHC_mac20_EUR_miss20per_correlations.parquet"
!dx download {RAP_DIR}/{CORR_FILE} -o {LOCAL_DIR}

loftee_corrs = (
    pl.read_parquet(f'{LOCAL_DIR}/{CORR_FILE}')
    .with_columns(
        loftee_corr = pl.col('correlation'),
        loftee_corr_abs = pl.col('correlation').abs(),
        loftee_corr_dir = pl.col('correlation')/pl.col('correlation').abs(),
    )
    .select(['region', 'phenotype', 'loftee_corr', 'loftee_corr_abs', 'loftee_corr_dir']) 
)

gene_trait_df = (
    gene_trait_df
    .join(loftee_corrs, on=['region', 'phenotype'], how='inner')
    .drop_nans()
    .sort('loftee_corr_abs', descending=True)
    .unique(subset=["region"], keep="first", maintain_order=True)
)
gene_trait_df

Error: path "/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20_EUR_
miss20per.parquet" already exists but -f/--overwrite was not set
[===========================================================>] Completed 33,369 of 33,369 bytes (100%) /home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20_EUR_miss20per_correlations.parquett

shape: (670, 6)
┌─────────────────┬─────────────────┬─────────────┬─────────────┬─────────────────┬────────────────┐
│ region          ┆ phenotype       ┆ pval_fdr    ┆ loftee_corr ┆ loftee_corr_abs ┆ loftee_corr_di │
│ ---             ┆ ---             ┆ ---         ┆ ---         ┆ ---             ┆ r              │
│ str             ┆ str             ┆ f64         ┆ f64         ┆ f64             ┆ ---            │
│                 ┆                 ┆             ┆             ┆                 ┆ f64            │
╞═════════════════╪═════════════════╪═════════════╪═════════════╪═════════════════╪════════════════╡
│ ENSG00000084674 ┆ ldl_direct_int  ┆ 2.2543e-301 ┆ -0.12678    ┆ 0.12678         ┆ -1.0           │
│ ENSG00000167701 ┆ alanine_aminotr ┆ 1.2234e-144 ┆ -0.106424   ┆ 0.106424        ┆ -1.0           │
│                 ┆ ansferase_int   ┆             ┆             ┆                 ┆                │
│ ENSG00000105610 ┆ mean_corpuscula ┆ 9.8993e-24  ┆ -0.100921   ┆ 0.100921        ┆ -1.0           │
│                 ┆ r_haemoglobin_i ┆             ┆             ┆                 ┆                │
│                 ┆ …               ┆             ┆             ┆                 ┆                │
│ ENSG00000141505 ┆ alkaline_phosph ┆ 8.4146e-35  ┆ 0.089171    ┆ 0.089171        ┆ 1.0            │
│                 ┆ atase_int       ┆             ┆             ┆                 ┆                │
│ ENSG00000101162 ┆ platelet_distri ┆ 1.5335e-83  ┆ 0.08869     ┆ 0.08869         ┆ 1.0            │
│                 ┆ bution_width_in ┆             ┆             ┆                 ┆                │
│                 ┆ …               ┆             ┆             ┆                 ┆                │
│ …               ┆ …               ┆ …           ┆ …           ┆ …               ┆ …              │
│ ENSG00000115977 ┆ sitting_height_ ┆ 0.021257    ┆ -0.001496   ┆ 0.001496        ┆ -1.0           │
│                 ┆ int             ┆             ┆             ┆                 ┆                │
│ ENSG00000119574 ┆ standing_height ┆ 0.025535    ┆ -0.001317   ┆ 0.001317        ┆ -1.0           │
│                 ┆ _int            ┆             ┆             ┆                 ┆                │
│ ENSG00000115325 ┆ platelet_distri ┆ 0.01277     ┆ -0.001204   ┆ 0.001204        ┆ -1.0           │
│                 ┆ bution_width_in ┆             ┆             ┆                 ┆                │
│                 ┆ …               ┆             ┆             ┆                 ┆                │
│ ENSG00000155052 ┆ arm_fat_percent ┆ 0.048579    ┆ 0.000558    ┆ 0.000558        ┆ 1.0            │
│                 ┆ age_right_int   ┆             ┆             ┆                 ┆                │
│ ENSG00000134030 ┆ leg_fat_percent ┆ 0.020839    ┆ 0.000383    ┆ 0.000383        ┆ 1.0            │
│                 ┆ age_left_int    ┆             ┆             ┆                 ┆                │
└─────────────────┴─────────────────┴─────────────┴─────────────┴─────────────────┴────────────────┘

In [ ]:
RAP_ANNO_DIR = "project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated"
LOCAL_ANNO_DIR = "/home/dnanexus/data_dir"

# ANNO_FILE = "annotations_fillna_ukbgym_with_mane.parquet"
ANNO_FILE = "annotations_with_all.parquet"

!dx download {RAP_ANNO_DIR}/{ANNO_FILE} -o {LOCAL_ANNO_DIR}/{ANNO_FILE}
anno = pl.scan_parquet(f"{LOCAL_ANNO_DIR}/{ANNO_FILE}")

anno = (
    anno
    .filter(
        # Filter to gene regions of interest
        (pl.col('region').is_in(gene_trait_df['region'].unique())),
        
        # Choose Gene Body
        # ((pl.col('consequence_upstream_gene_variant') == False) & (pl.col('consequence_downstream_gene_variant') == False)),

        # Choose CDS
        # (pl.col('vep_cds_relaxed')==True),
        # ((pl.col('vep_cds_relaxed')==True) | (pl.col('mane_cds')==True)),
        # (pl.col('non_mane_cds')==False),

        # Choose non CDS only
        # ((pl.col('vep_cds_relaxed')==False) & (pl.col('mane_cds')==False) & (pl.col('non_mane_cds')==False)),

        # Choose VEP consequence
        # (pl.col('consequence_missense_variant') == True),
        # (pl.col('consequence_synonymous_variant') == True),
        # (pl.col('consequence_5_prime_utr_variant') == True),
        # (pl.col('consequence_upstream_gene_variant') == True),
        # (pl.col('consequence_downstream_gene_variant') == True),
        # (pl.col('consequence_intron_variant') == True),

        # Choose MobiDB region
        # (pl.col('mobi_lip_full') == True),
        # (pl.col('mobi_disorder_full') == True),

        # Custom variant class filter
        # (pl.col('relative_cds_position')>=0.5),

        # Choose regulatory region
        # (pl.col('encode_eh_pr') == True),
        # (pl.col('encode_all_tf') == True),
        
        # Proximity to TSS
        # (pl.col('dist_to_tss') >= min_range),
        # (pl.col('dist_to_tss') <= max_range),

        # Only SNPs
        (pl.col('ref').str.len_chars()==1) & (pl.col('alt').str.len_chars()==1)
    )
    # ADD TO ANNOTATIONS NOTEBOOK
    # .with_columns(
    #     core_promoter = pl.col('dist_to_tss').abs() <= 50,
    #     encode_annotated = pl.col('not_annotated_in_encode') == False,
    #     encode_eh_pr = pl.any_horizontal((pl.col(c) == 1) for c in ['encode_pls', 'encode_pels', 'encode_dels']),
    #     encode_all_tf = pl.any_horizontal((pl.col(c) == 1) for c in ['encode_tf', 'encode_ca_tf']),
    # )
    .with_columns(
        loftee_disorder = pl.all_horizontal((pl.col(c) == True) for c in ['loftee_hc', 'mobi_curated_disorder_priority']),
        loftee_lip = pl.all_horizontal((pl.col(c) == True) for c in ['loftee_hc', 'mobi_full_lip_priority']),
        loftee_ted = pl.all_horizontal((pl.col(c) == True) for c in ['loftee_hc', 'ted_domain']),
        loftee_low_complexity = pl.all_horizontal((pl.col(c) == True) for c in ['loftee_hc', 'low_complexity_domain']),
    )
)

# selected_categories = ['vep_consequences'] # VEP CDS consequences
# selected_categories = ['plof_consequences'] # VEP plof consequences
selected_categories = ['plof', 'missense', 'conservation', 'splicing'] # Gene-Body
# selected_categories = ['missense'] # missense
# selected_categories = ['protein_domains'] # protein domains
# selected_categories = ['loftee_protein_domains'] # protein domains
# selected_categories = ['splicing', 'genetic_diversity', 'conservation'] # splicing
# selected_categories = ['splicing', 'genetic_diversity', 'conservation'] # synonymous
# selected_categories = ['splicing', 'conservation', 'regulatory_nondir', 'genetic_diversity'] # non coding
# selected_categories = ['encode_regions'] # encode regions
# selected_categories = ['encode_custom'] # encode regions custom
# selected_categories = ['conservation', 'regulatory_nondir', 'genetic_diversity'] # 5UTR

selected_annos = anno_config_df.filter(
    pl.col('category').is_in(selected_categories)
)['annotation'].to_list()

existing_annos = [c for c in all_annotation_list if c in anno.collect_schema().names()]
selected_annos = list(set(selected_annos).intersection(set(existing_annos)))
fillna_cols = [c+'_is_na' for c in selected_annos]

anno = (
    anno
    .select(
        set(['id', 'region']).union(set(selected_annos))
    )
    .collect(engine='streaming')
    # .drop_nulls()
    .fill_null(0) # For CPT1 LLR, ESM1B LLR, and REVEL
)

anno

Error: path "/home/dnanexus/data_dir/annotations_with_all.parquet" already
exists but -f/--overwrite was not set

/tmp/ipykernel_411136/552782131.py:85: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
/tmp/ipykernel_411136/552782131.py:94: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.

shape: (20_042_767, 14)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ loftee_hc ┆ cpt1_llr ┆ pangolin_ ┆ delta_sco ┆ … ┆ am_pathog ┆ region    ┆ id        ┆ gpn_score │
│ ---       ┆ ---      ┆ score     ┆ re        ┆   ┆ enicity   ┆ ---       ┆ ---       ┆ ---       │
│ i8        ┆ f64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ f32       │
│           ┆          ┆ f32       ┆ f32       ┆   ┆ f32       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr4:1132 ┆ -2.08     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 145362    ┆ 11828:C:A ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr2:1577 ┆ -1.38     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 115170    ┆ 47637:T:C ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr1:2145 ┆ 1.08      │
│           ┆          ┆           ┆           ┆   ┆           ┆ 152104    ┆ 08142:C:G ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr6:1284 ┆ -1.17     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 152894    ┆ 04170:G:A ┆           │
│ 0         ┆ 0.0      ┆ 0.01      ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr7:8601 ┆ -5.31     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 164828    ┆ 60:C:A    ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr7:9074 ┆ -5.51     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 058091    ┆ 7506:T:A  ┆           │
│ 0         ┆ 0.094604 ┆ 0.0       ┆ 0.01      ┆ … ┆ 0.1618    ┆ ENSG00000 ┆ chr9:1209 ┆ -3.92     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 106804    ┆ 81935:G:A ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr17:645 ┆ -0.02     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 108854    ┆ 41107:C:T ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr17:645 ┆ -0.02     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 108854    ┆ 41107:C:T ┆           │
│ 0         ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ ENSG00000 ┆ chr12:100 ┆ -1.38     │
│           ┆          ┆           ┆           ┆   ┆           ┆ 151572    ┆ 814760:G: ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ T         ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘