In [1]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm
from scipy import stats

from plotnine import *
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

In [2]:
lofcorr_df = pl.read_parquet("/home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_EUR_genebass1e6coding_maf1e3.parquet")

lofcorr_df.filter(pl.col('top_plof_var_count')>50)

shape: (77_975, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ region    ┆ gene_name ┆ phenotype ┆ n_variant ┆ … ┆ top_plof_ ┆ plof_prop ┆ t_stat    ┆ corr_pva │
│ ---       ┆ ---       ┆ ---       ┆ s         ┆   ┆ var_count ┆ ---       ┆ ---       ┆ l        │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ u64       ┆   ┆ u32       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ ABCG8     ┆ seated_he ┆ 999       ┆ … ┆ 88        ┆ 0.067067  ┆ 0.714092  ┆ 0.475337 │
│ 143921    ┆           ┆ ight_int  ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ G6PC2     ┆ forced_ex ┆ 247       ┆ … ┆ 52        ┆ 0.117409  ┆ 0.047484  ┆ 0.962166 │
│ 152254    ┆           ┆ piratory_ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ volume_in ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _1s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ SLC22A3   ┆ total_bil ┆ 460       ┆ … ┆ 55        ┆ 0.082609  ┆ -0.681318 ┆ 0.496015 │
│ 146477    ┆           ┆ irubin_in ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ t         ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ AGER      ┆ whole_bod ┆ 340       ┆ … ┆ 257       ┆ 0.141176  ┆ 1.0145    ┆ 0.31107  │
│ 204305    ┆           ┆ y_fat_mas ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ s_int     ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ ELOVL7    ┆ platelet_ ┆ 183       ┆ … ┆ 347       ┆ 0.125683  ┆ 0.592506  ┆ 0.554251 │
│ 164181    ┆           ┆ crit_int  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ CGN       ┆ hip_circu ┆ 935       ┆ … ┆ 448       ┆ 0.115508  ┆ -1.437983 ┆ 0.150774 │
│ 143375    ┆           ┆ mference_ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ int       ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ GSS       ┆ calcium_i ┆ 306       ┆ … ┆ 70        ┆ 0.084967  ┆ -1.350014 ┆ 0.178016 │
│ 100983    ┆           ┆ nt        ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ TET2      ┆ whole_bod ┆ 2182      ┆ … ┆ 396       ┆ 0.315765  ┆ 0.863271  ┆ 0.388083 │
│ 168769    ┆           ┆ y_water_m ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ass_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ IFIH1     ┆ age_at_de ┆ 258       ┆ … ┆ 549       ┆ 0.124031  ┆ -1.360302 ┆ 0.174931 │
│ 115267    ┆           ┆ ath_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ TSBP1     ┆ mothers_a ┆ 239       ┆ … ┆ 54        ┆ 0.104603  ┆ 1.397913  ┆ 0.163446 │
│ 204296    ┆           ┆ ge_at_dea ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ th_int    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Read the full Genebass results
pval_cutoffs = {'burden': 6.7e-7, 'skato': 2.5e-7}

# Convert the pandas operations into a single Polars expression
gb_pl = (
    pl.read_parquet('/home/dnanexus/data_dir/association_files/genebass_all_associations_p_e-5.parquet')
    .with_columns(
        significant = (pl.col('Pvalue') < pval_cutoffs['skato']) | (pl.col('Pvalue_Burden') < pval_cutoffs['burden']),
        phenotype = pl.col('description').str.replace_all(r"\(", "").str.replace_all(r"\)", "").str.replace_all(' ', '_').str.to_lowercase() + '_int',
        region = pl.col('gene_id'),
        gene_name = pl.col('gene_symbol'),
    )
    .filter(
        (pl.col('significant') == True) &
        (pl.col('modifier') != 'custom') &
        # (pl.col('annotation').str.contains('pLoF'))
        (pl.col('annotation') == 'pLoF')
    )
    .select(['region', 'gene_name', 'phenotype', 'trait_type'])
    .unique()
)

# Keep the top hit per gene
# gb_pl = gb_pl.sort("Pvalue").unique(subset=["region"], keep="first")

gene_trait_df = gb_pl[['region', 'gene_name', 'phenotype', 'trait_type']].unique()

plof = pl.read_parquet('/home/dnanexus/data_dir/association_files/rvat_EUR_500k_regenie.parquet').with_columns(
    phenotype = (pl.col('trait') + '_int'),
    region = pl.col('gene_id'),
    rvat_pval = (10** -pl.col("neg_log10p")),
).filter(
    (pl.col('trait_type') == 'quantitative')
)

lofcorr_df = pl.read_parquet("/home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_EUR_genebass1e6coding_maf1e3.parquet")

gene_trait_df = gb_pl.join(plof[['region', 'phenotype', 'beta', 'rvat_pval']], on=['region', 'phenotype'], how='inner')
gene_trait_df = gene_trait_df.join(lofcorr_df, on=['region', 'gene_name', 'phenotype'], how='left').with_columns(
    sign_agreement = (pl.col('loftee_corr')*pl.col('beta') > 0) & (pl.col('loftee_corr').is_not_nan()),
    corr_dir = (pl.col('loftee_corr')/pl.col('loftee_corr').abs())
)

# TODO: We don't cover all genebass significant genes, so we need to filter out nans (LOFTEE correlations missing)
# gene_trait_df = gene_trait_df.filter(pl.col('sign_agreement')==1)
gene_trait_df

shape: (1_148, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ region    ┆ gene_name ┆ phenotype ┆ trait_typ ┆ … ┆ t_stat    ┆ corr_pval ┆ sign_agre ┆ corr_dir │
│ ---       ┆ ---       ┆ ---       ┆ e         ┆   ┆ ---       ┆ ---       ┆ ement     ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f32      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ PYGM      ┆ lymphocyt ┆ continuou ┆ … ┆ 0.869438  ┆ 0.384879  ┆ true      ┆ 1.0      │
│ 068976    ┆           ┆ e_percent ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ age_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ CHD2      ┆ lymphocyt ┆ continuou ┆ … ┆ 9.021569  ┆ 9.9693e-1 ┆ true      ┆ 1.0      │
│ 173575    ┆           ┆ e_percent ┆ s         ┆   ┆           ┆ 9         ┆           ┆          │
│           ┆           ┆ age_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ NF1       ┆ lymphocyt ┆ continuou ┆ … ┆ -8.94808  ┆ 9.7538e-1 ┆ true      ┆ -1.0     │
│ 196712    ┆           ┆ e_percent ┆ s         ┆   ┆           ┆ 9         ┆           ┆          │
│           ┆           ┆ age_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ SLC4A1    ┆ lymphocyt ┆ continuou ┆ … ┆ -5.601924 ┆ 3.0966e-8 ┆ true      ┆ -1.0     │
│ 004939    ┆           ┆ e_percent ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ age_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ ANKRD12   ┆ lymphocyt ┆ continuou ┆ … ┆ -5.714913 ┆ 1.3285e-8 ┆ true      ┆ -1.0     │
│ 101745    ┆           ┆ e_percent ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ age_int   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ RHAG      ┆ reticuloc ┆ continuou ┆ … ┆ 3.136737  ┆ 0.001871  ┆ true      ┆ 1.0      │
│ 112077    ┆           ┆ yte_count ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _int      ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ ANK1      ┆ reticuloc ┆ continuou ┆ … ┆ 10.431616 ┆ 1.3985e-2 ┆ true      ┆ 1.0      │
│ 029534    ┆           ┆ yte_count ┆ s         ┆   ┆           ┆ 4         ┆           ┆          │
│           ┆           ┆ _int      ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ VPS13A    ┆ reticuloc ┆ continuou ┆ … ┆ 1.627776  ┆ 0.103726  ┆ true      ┆ 1.0      │
│ 197969    ┆           ┆ yte_count ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _int      ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ LRP5      ┆ heel_bone ┆ continuou ┆ … ┆ -4.663647 ┆ 0.000004  ┆ true      ┆ -1.0     │
│ 162337    ┆           ┆ _mineral_ ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ density_b ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ md_…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ SMAD6     ┆ heel_bone ┆ continuou ┆ … ┆ -3.963041 ┆ 0.000084  ┆ true      ┆ -1.0     │
│ 137834    ┆           ┆ _mineral_ ┆ s         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ density_b ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ md_…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
from anngeno import AnnGeno

# --- 2. Read anngeno and get genotypes ---
ag = AnnGeno('/home/dnanexus/data_dir/genebass_1e6_coding_variants.ag', low_mem=True)

phenotype = 'ldl_direct_int'
gene_id = 'ENSG00000130164'
gdata = ag.get_many_regions([gene_id])[gene_id]

plof_burdens = pl.DataFrame({
    'individual': ag.samples,
    'burden': gdata['genotypes'].T @ gdata['annotations']['loftee_hc'].to_numpy()
})#.filter(pl.col('burden') < 2)

config_path = f'/home/dnanexus/ukbgym/config.yaml'
with open(config_path) as f:
    config = yaml.safe_load(f)
cov_list = config.get("covariates", [])

# --- 2. Read and merge data ---
pheno_path = '/home/dnanexus/data_dir/phenotypes/phenotypes190_missing20_unique2_int.parquet'
prs_path = '/home/dnanexus/data_dir/phenotypes/PRS190_EUR_missing20_unique2_int.parquet'
cov_path = '/home/dnanexus/data_dir/phenotypes/250709_quant_phenotypes_covariates_genetic_pcs_prs_corrected.parquet'

pheno_lazy = pl.scan_parquet(pheno_path).select("IID", phenotype).rename({"IID": "individual"}).with_columns(pl.col("individual").cast(pl.String)) # Cast to String
prs_lazy = pl.scan_parquet(prs_path).select("IID", f"{phenotype}_prs").rename({"IID": "individual"}).with_columns(pl.col("individual").cast(pl.String)) # Cast to String
cov_lazy = pl.scan_parquet(cov_path).select("sample", *cov_list).rename({"sample": "individual"})

# Join everything and collect into a pandas DataFrame for the regression
merged_pd = (
    pheno_lazy
    .join(prs_lazy, on="individual", how="inner")
    .join(cov_lazy, on="individual", how="inner")
    .drop_nulls()
    .drop_nans()
    .collect()
    .to_pandas()
)

# --- 3. Compute residuals for the single phenotype ---
# Define the dependent (y) and independent (X) variables
y = merged_pd[phenotype]
X = merged_pd[[f"{phenotype}_prs"] + cov_list]
X = sm.add_constant(X) # Add an intercept

# Fit the linear model and get the residuals
model = sm.OLS(y, X).fit()
residuals = model.resid

# --- 4. Create the final long-format DataFrame ---
p_df = pl.DataFrame({
    "individual": merged_pd["individual"].astype(str),
    "phenotype": phenotype,
    "pheno_value": residuals
})

# 4. Join with gene burdens
plot_gp_df = plof_burdens.join(p_df, on='individual', how='inner')
plot_gp_df

/home/dnanexus/anngeno/anngeno/anngeno.py:14: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
/home/dnanexus/deeprvat2-env/lib/python3.11/site-packages/zarr/codecs/vlen_utf8.py:44: UserWarning: The codec `vlen-utf8` is currently not part in the Zarr format 3 specification. It may not be supported by other zarr implementations and may change in the future.
/home/dnanexus/deeprvat2-env/lib/python3.11/site-packages/zarr/codecs/vlen_utf8.py:44: UserWarning: The codec `vlen-utf8` is currently not part in the Zarr format 3 specification. It may not be supported by other zarr implementations and may change in the future.

shape: (345_960, 4)
┌────────────┬────────┬────────────────┬─────────────┐
│ individual ┆ burden ┆ phenotype      ┆ pheno_value │
│ ---        ┆ ---    ┆ ---            ┆ ---         │
│ str        ┆ i8     ┆ str            ┆ f64         │
╞════════════╪════════╪════════════════╪═════════════╡
│ 3834985    ┆ 0      ┆ ldl_direct_int ┆ -0.016527   │
│ 1649233    ┆ 0      ┆ ldl_direct_int ┆ 0.400111    │
│ 5689749    ┆ 0      ┆ ldl_direct_int ┆ -0.761904   │
│ 1160905    ┆ 0      ┆ ldl_direct_int ┆ 2.267405    │
│ 5102203    ┆ 0      ┆ ldl_direct_int ┆ 0.03693     │
│ …          ┆ …      ┆ …              ┆ …           │
│ 2864227    ┆ 0      ┆ ldl_direct_int ┆ -0.894074   │
│ 5733954    ┆ 0      ┆ ldl_direct_int ┆ 0.548599    │
│ 3923515    ┆ 0      ┆ ldl_direct_int ┆ -0.737069   │
│ 1732136    ┆ 0      ┆ ldl_direct_int ┆ -0.684545   │
│ 5618419    ┆ 0      ┆ ldl_direct_int ┆ -0.940109   │
└────────────┴────────┴────────────────┴─────────────┘