In [1]:
import polars as pl
from tqdm import tqdm

In [2]:
appv = pl.scan_parquet("/home/dnanexus/data_dir/appv_files/avg_pheno_per_var_quantitative_EUR_genebass1e6_PRScorr.parquet")

# Chain the filter and the much faster semi join
# appv = (
#     appv
#     .with_columns(
#         mean_pheno_value_rank = pl.col('mean_pheno_value').rank(method="average").over(["phenotype"]),
#         mean_pheno_value_count = pl.len().over(["phenotype"])
#     )
#     .with_columns(
#         mean_pheno_value_ptile = pl.col('mean_pheno_value_rank') / pl.col('mean_pheno_value_count')
#     )
#     .drop(['mean_pheno_value_count'])
# )

# appv.head().collect(engine='streaming')

In [3]:
unique_phenotypes = appv.select('phenotype').unique().collect(engine='streaming').to_series().sort()
unique_phenotypes

shape: (127,)
Series: 'phenotype' [str]
[
	"age_at_death_int"
	"age_at_hysterectomy_int"
	"age_last_used_hormonereplaceme…
	"age_started_hormonereplacement…
	"age_started_wearing_glasses_or…
	…
	"weight_int"
	"white_blood_cell_leukocyte_cou…
	"whole_body_fat_mass_int"
	"whole_body_fatfree_mass_int"
	"whole_body_water_mass_int"
]

In [11]:
(
    appv
    .filter(pl.col('phenotype') == unique_phenotypes[0])
    .with_columns(
        mean_pheno_value_rank = pl.col('mean_pheno_value').rank(method="average").cast(pl.Float32)
    )
    .with_columns(
        mean_pheno_value_ptile = (pl.col('mean_pheno_value_rank') / pl.len()).cast(pl.Float32)
    )
    .collect(engine='streaming')
)

shape: (16_609_307, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ id           ┆ phenotype   ┆ n_individua ┆ mean_pheno_ ┆ std_pheno_v ┆ mean_pheno_ ┆ mean_pheno_ │
│ ---          ┆ ---         ┆ ls          ┆ value       ┆ alue        ┆ value_rank  ┆ value_ptile │
│ str          ┆ str         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ u32         ┆ f32         ┆ f32         ┆ f32         ┆ f32         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ chr1:1366008 ┆ age_at_deat ┆ 6142        ┆ 0.000776    ┆ 0.527588    ┆ 8.179128e6  ┆ 0.492442    │
│ :A:G         ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr1:1365723 ┆ age_at_deat ┆ 14          ┆ -0.078654   ┆ 0.688095    ┆ 6.194531e6  ┆ 0.372955    │
│ :G:C         ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr1:1360989 ┆ age_at_deat ┆ 3443        ┆ 0.007729    ┆ 0.52576     ┆ 8.598257e6  ┆ 0.517677    │
│ :GACAC:G     ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr1:1362470 ┆ age_at_deat ┆ 3576        ┆ 0.008641    ┆ 0.525432    ┆ 8.63319e6   ┆ 0.51978     │
│ :AT:A        ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr1:1363031 ┆ age_at_deat ┆ 3402        ┆ 0.007385    ┆ 0.526906    ┆ 8.583263e6  ┆ 0.516774    │
│ :C:T         ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ chr22:505789 ┆ age_at_deat ┆ 1           ┆ 0.453231    ┆ null        ┆ 1.452058e7  ┆ 0.874244    │
│ 90:T:C       ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr22:505790 ┆ age_at_deat ┆ 1           ┆ -0.658198   ┆ null        ┆ 1.148782e6  ┆ 0.069165    │
│ 04:G:C       ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr22:505790 ┆ age_at_deat ┆ 2           ┆ -0.359511   ┆ 1.148125    ┆ 2.938968e6  ┆ 0.176947    │
│ 09:T:A       ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr22:505790 ┆ age_at_deat ┆ 1           ┆ -0.046495   ┆ null        ┆ 6.759032e6  ┆ 0.406942    │
│ 13:G:C       ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
│ chr22:505790 ┆ age_at_deat ┆ 1           ┆ 0.327366    ┆ null        ┆ 1.3352024e7 ┆ 0.803888    │
│ 28:G:T       ┆ h_int       ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [4]:
output_dir = "/home/dnanexus/data_dir/appv_files/ptile_pheno_file"

for phenotype in tqdm(unique_phenotypes):
    (
        appv
        .filter(pl.col('phenotype') == phenotype)
        .with_columns(
            mean_pheno_value_rank=pl.col('mean_pheno_value')
                .rank(method="average")
                .cast(pl.Float32)
        )
        .with_columns(
            mean_pheno_value_ptile=(
                pl.col('mean_pheno_value_rank') / pl.len()
            ).cast(pl.Float32)
        )
        .sink_parquet(
            f"{output_dir}/avg_pheno_per_var_quantitative_EUR_genebass1e6_PRScorr_with_percentiles_{phenotype}.parquet",
            compression="zstd",  # Better compression
            row_group_size=100_000  # Optimize for reading
        )
    )

# Combine all files
(
    pl.scan_parquet(f"{output_dir}/*.parquet")
    .sink_parquet(
        "/home/dnanexus/data_dir/appv_files/avg_pheno_per_var_quantitative_EUR_genebass1e6_PRScorr_with_percentiles.parquet",
        compression="zstd"
    )
)

100%|██████████| 127/127 [19:58<00:00,  9.44s/it]