In [2]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm

## Variant diff

In [3]:
gb_vars = pl.read_parquet('/home/dnanexus/data_dir/genebass1e6_394genes_10kb_variants.parquet')
gb_vars

shape: (15_358_373, 7)
┌─────────────────────┬───────┬───────────┬────────────────────┬─────┬─────────────────┬───────────┐
│ id                  ┆ chrom ┆ pos       ┆ ref                ┆ alt ┆ region          ┆ gene_name │
│ ---                 ┆ ---   ┆ ---       ┆ ---                ┆ --- ┆ ---             ┆ ---       │
│ str                 ┆ str   ┆ i32       ┆ str                ┆ str ┆ str             ┆ str       │
╞═════════════════════╪═══════╪═══════════╪════════════════════╪═════╪═════════════════╪═══════════╡
│ chr2:169197167:T:G  ┆ chr2  ┆ 169197167 ┆ T                  ┆ G   ┆ ENSG00000081479 ┆ LRP2      │
│ chr2:169204292:A:T  ┆ chr2  ┆ 169204292 ┆ A                  ┆ T   ┆ ENSG00000081479 ┆ LRP2      │
│ chr2:169030531:C:T  ┆ chr2  ┆ 169030531 ┆ C                  ┆ T   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168910825:T:G  ┆ chr2  ┆ 168910825 ┆ T                  ┆ G   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168969544:T:C  ┆ chr2  ┆ 168969544 ┆ T                  ┆ C   ┆ ENSG00000073734 ┆ ABCB11    │
│ …                   ┆ …     ┆ …         ┆ …                  ┆ …   ┆ …               ┆ …         │
│ chr6:30150733:A:C   ┆ chr6  ┆ 30150733  ┆ A                  ┆ C   ┆ ENSG00000204614 ┆ TRIM40    │
│ chr15:34974609:ACTT ┆ chr15 ┆ 34974609  ┆ ACTTCT             ┆ A   ┆ ENSG00000198146 ┆ ZNF770    │
│ CT:A                ┆       ┆           ┆                    ┆     ┆                 ┆           │
│ chr9:132358570:C:A  ┆ chr9  ┆ 132358570 ┆ C                  ┆ A   ┆ ENSG00000107290 ┆ SETX      │
│ chr8:13200986:C:CA  ┆ chr8  ┆ 13200986  ┆ C                  ┆ CA  ┆ ENSG00000164741 ┆ DLC1      │
│ chr5:180321761:GGTT ┆ chr5  ┆ 180321761 ┆ GGTTTTGTTTTGTTTTGT ┆ G   ┆ ENSG00000131459 ┆ GFPT2     │
│ TTGTTTTGTTT…        ┆       ┆           ┆ TTTGTTTT           ┆     ┆                 ┆           │
└─────────────────────┴───────┴───────────┴────────────────────┴─────┴─────────────────┴───────────┘

In [4]:
olink_genes = pl.read_csv('/home/dnanexus/data_dir/olink_genebass1e6_371genes.tsv', separator='\t')['region'].to_list()

olink_var_ids = pl.scan_parquet(f"/home/dnanexus/data_dir/genebass1e6_genes_10kb_allvars_annotated_250925.parquet").filter(pl.col('region').is_in(olink_genes)).select(gb_vars.columns).collect(engine='streaming')
# olink_var_ids.write_parquet('/home/dnanexus/data_dir/olink_371genes_10kb_variants.parquet')
olink_var_ids

shape: (13_815_087, 7)
┌─────────────────────┬───────┬───────────┬─────┬─────┬─────────────────┬───────────┐
│ id                  ┆ chrom ┆ pos       ┆ ref ┆ alt ┆ region          ┆ gene_name │
│ ---                 ┆ ---   ┆ ---       ┆ --- ┆ --- ┆ ---             ┆ ---       │
│ str                 ┆ str   ┆ i32       ┆ str ┆ str ┆ str             ┆ str       │
╞═════════════════════╪═══════╪═══════════╪═════╪═════╪═════════════════╪═══════════╡
│ chr2:169197167:T:G  ┆ chr2  ┆ 169197167 ┆ T   ┆ G   ┆ ENSG00000081479 ┆ LRP2      │
│ chr2:169204292:A:T  ┆ chr2  ┆ 169204292 ┆ A   ┆ T   ┆ ENSG00000081479 ┆ LRP2      │
│ chr2:169175752:G:A  ┆ chr2  ┆ 169175752 ┆ G   ┆ A   ┆ ENSG00000081479 ┆ LRP2      │
│ chr2:165362262:G:T  ┆ chr2  ┆ 165362262 ┆ G   ┆ T   ┆ ENSG00000136531 ┆ SCN2A     │
│ chr2:165386841:G:T  ┆ chr2  ┆ 165386841 ┆ G   ┆ T   ┆ ENSG00000136531 ┆ SCN2A     │
│ …                   ┆ …     ┆ …         ┆ …   ┆ …   ┆ …               ┆ …         │
│ chr11:10328313:TC:T ┆ chr11 ┆ 10328313  ┆ TC  ┆ T   ┆ ENSG00000133805 ┆ AMPD3     │
│ chr3:112330970:C:G  ┆ chr3  ┆ 112330970 ┆ C   ┆ G   ┆ ENSG00000091972 ┆ CD200     │
│ chr1:156890114:C:T  ┆ chr1  ┆ 156890114 ┆ C   ┆ T   ┆ ENSG00000187800 ┆ PEAR1     │
│ chr2:162173574:AC:A ┆ chr2  ┆ 162173574 ┆ AC  ┆ A   ┆ ENSG00000078098 ┆ FAP       │
│ chr12:122065447:G:A ┆ chr12 ┆ 122065447 ┆ G   ┆ A   ┆ ENSG00000110987 ┆ BCL7A     │
└─────────────────────┴───────┴───────────┴─────┴─────┴─────────────────┴───────────┘

In [ ]:
# olink_var_ids.join(gb_vars, on=gb_vars.columns, how='anti')#.write_parquet('/home/dnanexus/data_dir/olink371genes_genebass394genes_variants_diff.parquet')

#.write_parquet('/home/dnanexus/data_dir/olink371genes_genebass394genes_variants_union.parquet')

shape: (10_015_304, 7)
┌─────────────────────┬───────┬───────────┬─────┬─────┬─────────────────┬───────────┐
│ id                  ┆ chrom ┆ pos       ┆ ref ┆ alt ┆ region          ┆ gene_name │
│ ---                 ┆ ---   ┆ ---       ┆ --- ┆ --- ┆ ---             ┆ ---       │
│ str                 ┆ str   ┆ i32       ┆ str ┆ str ┆ str             ┆ str       │
╞═════════════════════╪═══════╪═══════════╪═════╪═════╪═════════════════╪═══════════╡
│ chr2:165362262:G:T  ┆ chr2  ┆ 165362262 ┆ G   ┆ T   ┆ ENSG00000136531 ┆ SCN2A     │
│ chr2:165386841:G:T  ┆ chr2  ┆ 165386841 ┆ G   ┆ T   ┆ ENSG00000136531 ┆ SCN2A     │
│ chr2:165365630:A:G  ┆ chr2  ┆ 165365630 ┆ A   ┆ G   ┆ ENSG00000136531 ┆ SCN2A     │
│ chr2:165367163:T:C  ┆ chr2  ┆ 165367163 ┆ T   ┆ C   ┆ ENSG00000136531 ┆ SCN2A     │
│ chr2:165383236:T:G  ┆ chr2  ┆ 165383236 ┆ T   ┆ G   ┆ ENSG00000136531 ┆ SCN2A     │
│ …                   ┆ …     ┆ …         ┆ …   ┆ …   ┆ …               ┆ …         │
│ chr20:54166734:TA:T ┆ chr20 ┆ 54166734  ┆ TA  ┆ T   ┆ ENSG00000019186 ┆ CYP24A1   │
│ chr11:10328313:TC:T ┆ chr11 ┆ 10328313  ┆ TC  ┆ T   ┆ ENSG00000133805 ┆ AMPD3     │
│ chr3:112330970:C:G  ┆ chr3  ┆ 112330970 ┆ C   ┆ G   ┆ ENSG00000091972 ┆ CD200     │
│ chr2:162173574:AC:A ┆ chr2  ┆ 162173574 ┆ AC  ┆ A   ┆ ENSG00000078098 ┆ FAP       │
│ chr12:122065447:G:A ┆ chr12 ┆ 122065447 ┆ G   ┆ A   ┆ ENSG00000110987 ┆ BCL7A     │
└─────────────────────┴───────┴───────────┴─────┴─────┴─────────────────┴───────────┘

In [8]:
gb_olink_vars = pl.concat([gb_vars.join(olink_var_ids, on=gb_vars.columns, how='anti'), olink_var_ids.join(gb_vars, on=gb_vars.columns, how='anti'), gb_vars.join(olink_var_ids, on=gb_vars.columns, how='inner')])

gb_olink_vars

shape: (25_373_677, 7)
┌───────────────────────┬───────┬───────────┬──────┬─────┬─────────────────┬───────────┐
│ id                    ┆ chrom ┆ pos       ┆ ref  ┆ alt ┆ region          ┆ gene_name │
│ ---                   ┆ ---   ┆ ---       ┆ ---  ┆ --- ┆ ---             ┆ ---       │
│ str                   ┆ str   ┆ i32       ┆ str  ┆ str ┆ str             ┆ str       │
╞═══════════════════════╪═══════╪═══════════╪══════╪═════╪═════════════════╪═══════════╡
│ chr2:169030531:C:T    ┆ chr2  ┆ 169030531 ┆ C    ┆ T   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168910825:T:G    ┆ chr2  ┆ 168910825 ┆ T    ┆ G   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168969544:T:C    ┆ chr2  ┆ 168969544 ┆ T    ┆ C   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:169007174:C:T    ┆ chr2  ┆ 169007174 ┆ C    ┆ T   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:169018732:A:G    ┆ chr2  ┆ 169018732 ┆ A    ┆ G   ┆ ENSG00000073734 ┆ ABCB11    │
│ …                     ┆ …     ┆ …         ┆ …    ┆ …   ┆ …               ┆ …         │
│ chr15:98793613:CAG:C  ┆ chr15 ┆ 98793613  ┆ CAG  ┆ C   ┆ ENSG00000140443 ┆ IGF1R     │
│ chr1:156892240:C:T    ┆ chr1  ┆ 156892240 ┆ C    ┆ T   ┆ ENSG00000187800 ┆ PEAR1     │
│ chr1:156917808:T:C    ┆ chr1  ┆ 156917808 ┆ T    ┆ C   ┆ ENSG00000187800 ┆ PEAR1     │
│ chr6:160658867:TAGG:T ┆ chr6  ┆ 160658867 ┆ TAGG ┆ T   ┆ ENSG00000198670 ┆ LPA       │
│ chr1:156890114:C:T    ┆ chr1  ┆ 156890114 ┆ C    ┆ T   ┆ ENSG00000187800 ┆ PEAR1     │
└───────────────────────┴───────┴───────────┴──────┴─────┴─────────────────┴───────────┘

In [ ]:
# gb_olink_vars.write_parquet('/home/dnanexus/data_dir/olink371genes_genebass394genes_variants_union.parquet')

In [3]:
all_vars = pl.scan_parquet(f"/home/dnanexus/data_dir/genebass1e6_genes_10kb_allvars_annotated_250925.parquet")
all_vars.head().collect()

shape: (5, 385)
┌───────┬───────────┬─────┬─────┬───┬───────────┬────────────────┬────────────────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ … ┆ abexp_min ┆ promoterai_abs ┆ promoterai_ove ┆ promoterai_und │
│ ---   ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---            ┆ r              ┆ er             │
│ str   ┆ i32       ┆ str ┆ str ┆   ┆ f64       ┆ f32            ┆ ---            ┆ ---            │
│       ┆           ┆     ┆     ┆   ┆           ┆                ┆ f32            ┆ f32            │
╞═══════╪═══════════╪═════╪═════╪═══╪═══════════╪════════════════╪════════════════╪════════════════╡
│ chr2  ┆ 134144266 ┆ C   ┆ T   ┆ … ┆ -0.012463 ┆ 0.0            ┆ 0.0            ┆ 0.0            │
│ chr2  ┆ 134192587 ┆ C   ┆ T   ┆ … ┆ -0.006189 ┆ 0.0            ┆ 0.0            ┆ 0.0            │
│ chr2  ┆ 134389573 ┆ T   ┆ C   ┆ … ┆ -0.013111 ┆ 0.0            ┆ 0.0            ┆ 0.0            │
│ chr2  ┆ 127525503 ┆ G   ┆ A   ┆ … ┆ -0.006438 ┆ 0.0            ┆ 0.0            ┆ 0.0            │
│ chr2  ┆ 134155422 ┆ C   ┆ T   ┆ … ┆ -0.006189 ┆ 0.0            ┆ 0.0            ┆ 0.0            │
└───────┴───────────┴─────┴─────┴───┴───────────┴────────────────┴────────────────┴────────────────┘

In [ ]:
gb_olink_vars = pl.scan_parquet('/home/dnanexus/data_dir/genebass394genes_olink371genes_variants_union.parquet')
id_cols = gb_olink_vars.collect_schema().names()
print(id_cols)
gb_olink_vars.head().collect()

['id', 'chrom', 'pos', 'ref', 'alt', 'region', 'gene_name']

shape: (5, 7)
┌────────────────────┬───────┬───────────┬─────┬─────┬─────────────────┬───────────┐
│ id                 ┆ chrom ┆ pos       ┆ ref ┆ alt ┆ region          ┆ gene_name │
│ ---                ┆ ---   ┆ ---       ┆ --- ┆ --- ┆ ---             ┆ ---       │
│ str                ┆ str   ┆ i32       ┆ str ┆ str ┆ str             ┆ str       │
╞════════════════════╪═══════╪═══════════╪═════╪═════╪═════════════════╪═══════════╡
│ chr2:169030531:C:T ┆ chr2  ┆ 169030531 ┆ C   ┆ T   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168910825:T:G ┆ chr2  ┆ 168910825 ┆ T   ┆ G   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:168969544:T:C ┆ chr2  ┆ 168969544 ┆ T   ┆ C   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:169007174:C:T ┆ chr2  ┆ 169007174 ┆ C   ┆ T   ┆ ENSG00000073734 ┆ ABCB11    │
│ chr2:169018732:A:G ┆ chr2  ┆ 169018732 ┆ A   ┆ G   ┆ ENSG00000073734 ┆ ABCB11    │
└────────────────────┴───────┴───────────┴─────┴─────┴─────────────────┴───────────┘

In [7]:
gb_olink_vars_anno = all_vars.join(gb_olink_vars, on=['id', 'region'], how='semi').collect(engine='streaming')
gb_olink_vars_anno

shape: (25_373_677, 385)
┌───────┬───────────┬──────────────┬─────┬───┬───────────┬─────────────┬─────────────┬─────────────┐
│ chrom ┆ pos       ┆ ref          ┆ alt ┆ … ┆ abexp_min ┆ promoterai_ ┆ promoterai_ ┆ promoterai_ │
│ ---   ┆ ---       ┆ ---          ┆ --- ┆   ┆ ---       ┆ abs         ┆ over        ┆ under       │
│ str   ┆ i32       ┆ str          ┆ str ┆   ┆ f64       ┆ ---         ┆ ---         ┆ ---         │
│       ┆           ┆              ┆     ┆   ┆           ┆ f32         ┆ f32         ┆ f32         │
╞═══════╪═══════════╪══════════════╪═════╪═══╪═══════════╪═════════════╪═════════════╪═════════════╡
│ chr2  ┆ 169197167 ┆ T            ┆ G   ┆ … ┆ -0.006063 ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr2  ┆ 169204292 ┆ A            ┆ T   ┆ … ┆ -0.026342 ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr2  ┆ 169030531 ┆ C            ┆ T   ┆ … ┆ -0.005501 ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr2  ┆ 168910825 ┆ T            ┆ G   ┆ … ┆ -0.019354 ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr2  ┆ 168969544 ┆ T            ┆ C   ┆ … ┆ -0.053713 ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ …     ┆ …         ┆ …            ┆ …   ┆ … ┆ …         ┆ …           ┆ …           ┆ …           │
│ chr15 ┆ 34974609  ┆ ACTTCT       ┆ A   ┆ … ┆ null      ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr9  ┆ 132358570 ┆ C            ┆ A   ┆ … ┆ null      ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr8  ┆ 13200986  ┆ C            ┆ CA  ┆ … ┆ null      ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr12 ┆ 122065447 ┆ G            ┆ A   ┆ … ┆ null      ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTTG ┆ G   ┆ … ┆ null      ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│       ┆           ┆ TTTTGTTTTGTT ┆     ┆   ┆           ┆             ┆             ┆             │
│       ┆           ┆ TT           ┆     ┆   ┆           ┆             ┆             ┆             │
└───────┴───────────┴──────────────┴─────┴───┴───────────┴─────────────┴─────────────┴─────────────┘

In [8]:
gb_olink_vars_anno['region'].value_counts(sort=True)

shape: (649, 2)
┌─────────────────┬────────┐
│ region          ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u64    │
╞═════════════════╪════════╡
│ ENSG00000113448 ┆ 608129 │
│ ENSG00000187323 ┆ 533458 │
│ ENSG00000178568 ┆ 484385 │
│ ENSG00000169855 ┆ 480249 │
│ ENSG00000171587 ┆ 352544 │
│ …               ┆ …      │
│ ENSG00000169469 ┆ 4699   │
│ ENSG00000132703 ┆ 4693   │
│ ENSG00000169877 ┆ 4172   │
│ ENSG00000072694 ┆ 3943   │
│ ENSG00000203618 ┆ 3389   │
└─────────────────┴────────┘

In [ ]:
# gb_olink_vars_anno.write_parquet('/home/dnanexus/data_dir/genebass394genes_olink371genes_variants_union_annotated.parquet')

## coding variants

In [2]:
anngeno_path = '/home/dnanexus/data_dir/genebass_1e6_coding_variants.ag'
eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'
# olink_path = '/home/dnanexus/data_dir/olink/protrider_lite_output/log2fc.csv'
olink_path = "/home/dnanexus/data_dir/olink/olink_corrected_rint_90_pcs.parquet"

In [3]:
sample_ids = zarr.open(f'{anngeno_path}/zarr_store/samples', mode='r')[:]
var_ids = pl.read_parquet(f'{anngeno_path}/variant_metadata.parquet', columns=['id'])['id'].to_numpy()
geno = zarr.open(f'{anngeno_path}/zarr_store/genotypes', mode='r')

eur_samples = pl.read_csv(eur_samples_path).rename({'eid': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
)['individual'].to_list()

/home/dnanexus/deeprvat2-env/lib/python3.11/site-packages/zarr/codecs/vlen_utf8.py:44: UserWarning: The codec `vlen-utf8` is currently not part in the Zarr format 3 specification. It may not be supported by other zarr implementations and may change in the future.
  return cls(**configuration_parsed)

In [4]:
olink_df = pl.read_parquet(olink_path).rename({'sample': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
).filter(
    pl.col("individual").is_in(eur_samples)
).fill_nan(None)

unique_phenotypes = [pheno for pheno in olink_df.columns if pheno != 'individual']

olink_melt = (
    olink_df.unpivot(
        index=['individual'],
        on=unique_phenotypes,
        variable_name='phenotype',
        value_name='pheno_value',
    )
    .with_columns(
        phenotype = pl.col('phenotype') + '_olink'
    )
)

olink_melt

shape: (14_987_658, 3)
┌────────────┬───────────────────────┬─────────────┐
│ individual ┆ phenotype             ┆ pheno_value │
│ ---        ┆ ---                   ┆ ---         │
│ str        ┆ str                   ┆ f64         │
╞════════════╪═══════════════════════╪═════════════╡
│ 1000107    ┆ ENSG00000120053_olink ┆ -0.592022   │
│ 1001193    ┆ ENSG00000120053_olink ┆ 0.061036    │
│ 1001694    ┆ ENSG00000120053_olink ┆ 0.228713    │
│ 1001715    ┆ ENSG00000120053_olink ┆ 0.674837    │
│ 1002486    ┆ ENSG00000120053_olink ┆ 1.153924    │
│ …          ┆ …                     ┆ …           │
│ 6019565    ┆ ENSG00000066468_olink ┆ 0.72708     │
│ 6019855    ┆ ENSG00000066468_olink ┆ -0.327369   │
│ 6021528    ┆ ENSG00000066468_olink ┆ 0.991073    │
│ 6022842    ┆ ENSG00000066468_olink ┆ -1.81022    │
│ 6023199    ┆ ENSG00000066468_olink ┆ 1.16358     │
└────────────┴───────────────────────┴─────────────┘

In [5]:
# Optimized approach to find indices of olink_samples in sample_ids
# Step A: Create a lookup dictionary mapping each ID in the large array to its original index. This takes O(N) time, where N is the size of sample_ids.
olink_sids = olink_df['individual'].to_numpy()
sample_id_to_index = {sid: i for i, sid in enumerate(sample_ids)}

# Step B: Iterate through the smaller array and find the index for each element if it exists in our lookup dictionary. This takes O(M) time, where M is the size of olink_sids.
found_indices = []
for sid in olink_sids:
    if sid in sample_id_to_index:
        found_indices.append(sample_id_to_index[sid])
print(f"Found {len(found_indices)} matching IDs.")

# Step C: Convert the list of indices to a NumPy array and sort it.
# Sorting ensures the output is identical to the original np.where approach, which returns indices in ascending order.
olink_indices = np.sort(found_indices)
olink_indices

Found 40398 matching IDs.

array([    17,     23,     45, ..., 490517, 490532, 490535],
      shape=(40398,))

In [8]:
sample_ids[olink_indices]

array(['5102203', '3741733', '4072771', ..., '5141119', '5145210',
       '5733954'], shape=(40398,), dtype=StringDType())

In [9]:
len(set(olink_lazy['individual'].to_list()).intersection(set(sample_ids[olink_indices])))

NameError: name 'olink_lazy' is not defined

In [10]:
@numba.njit(parallel=True, fastmath=True)
def _fast_clip_and_sum_allels(arr):
    # Get the shape of the input array
    # Using specific dimensions for clarity with this problem
    n_samples, n_variants, _ = arr.shape
    
    # The sum of two positive int8s can be up to 254. 
    # An int16 is a safe and fast output type.
    output = np.empty((n_samples, n_variants), dtype=np.int8)
    
    # Numba's prange enables automatic parallelization across all your CPU cores
    for i in numba.prange(n_samples):
        for j in range(n_variants):
            # Read two values, perform logic, write one value.
            # This is the "fused" operation.
            val1 = arr[i, j, 0]
            val2 = arr[i, j, 1]
            
            s = 0
            # Since input is int8, this check is faster than max(0, val)
            if val1 > 0:
                s += val1
            if val2 > 0:
                s += val2
            
            output[i, j] = s
            
    return output

def process_genotype_chunk(
    geno: np.array, 
    var_ids: np.array, 
    sample_list: np.array,
    melted_pheno_df: pl.LazyFrame,
    homozygous: bool = False,
    debug: bool = False,
) -> pl.LazyFrame:
    """
    Extract genotypes for a specific gene and return as lazy DataFrame
    """
    geno_clipped = _fast_clip_and_sum_allels(geno)
    # Find heterozygous genotypes (genotype == 1)
    rows, cols = np.where(geno_clipped == 1)
    geno_melt = pl.DataFrame({
        'id': var_ids[rows],
        'individual': sample_list[cols],
        'genotype': 1
    })
    
    # Find homozygous genotypes (genotype == 2)
    if homozygous:
        rows, cols = np.where(geno_clipped == 2)
        hom = pl.DataFrame({
            'id': var_ids[rows],
            'individual': sample_list[cols],
            'genotype': 2
        })
        geno_melt = pl.concat([geno_melt, hom])

    var_pheno_df = geno_melt.lazy().join(melted_pheno_df, on='individual', how='left')
    if debug:
        # Return intermediate dataframe if debugging
        return var_pheno_df
    
    var_pheno_df = var_pheno_df.group_by(
           ['id', 'phenotype']
           ).agg([
                pl.len().alias('n_individuals'),
                pl.col('pheno_value').mean().cast(pl.Float32).alias('mean_pheno_value'),
                pl.col('pheno_value').std().cast(pl.Float32).alias('std_pheno_value'),
            ]).drop_nulls(subset=['mean_pheno_value'])
    return var_pheno_df

In [16]:
output_dir = "/home/dnanexus/data_dir/var_pheno_EUR_chunks"
chunk_size = 10_000

for chunk_num in tqdm(range(var_ids.shape[0]//chunk_size + 1)):
    tmp = process_genotype_chunk(
        geno=geno[chunk_num*chunk_size:(chunk_num+1)*chunk_size, olink_indices],
        var_ids=var_ids[chunk_num*chunk_size:(chunk_num+1)*chunk_size],
        sample_list=sample_ids[olink_indices],
        melted_pheno_df=olink_melt.lazy(),
        homozygous=False,
    ).collect()
    break

tmp

  0%|          | 0/183 [00:17<?, ?it/s]

shape: (810_348, 5)
┌────────────────────┬───────────────────────┬───────────────┬──────────────────┬─────────────────┐
│ id                 ┆ phenotype             ┆ n_individuals ┆ mean_pheno_value ┆ std_pheno_value │
│ ---                ┆ ---                   ┆ ---           ┆ ---              ┆ ---             │
│ str                ┆ str                   ┆ u64           ┆ f32              ┆ f32             │
╞════════════════════╪═══════════════════════╪═══════════════╪══════════════════╪═════════════════╡
│ chr1:3467169:C:G   ┆ ENSG00000081800_olink ┆ 1             ┆ -0.363691        ┆ null            │
│ chr1:2229364:A:G   ┆ ENSG00000135218_olink ┆ 1             ┆ 0.408683         ┆ null            │
│ chr1:8967768:C:T   ┆ ENSG00000082074_olink ┆ 7             ┆ 0.198808         ┆ 1.265288        │
│ chr1:6213135:C:T   ┆ ENSG00000065361_olink ┆ 4             ┆ 0.381372         ┆ 1.242684        │
│ chr1:3480477:GGA:G ┆ ENSG00000124678_olink ┆ 1             ┆ 1.095063         ┆ null            │
│ …                  ┆ …                     ┆ …             ┆ …                ┆ …               │
│ chr1:2519307:T:C   ┆ ENSG00000168769_olink ┆ 1             ┆ -0.429507        ┆ null            │
│ chr1:1374025:T:C   ┆ ENSG00000019991_olink ┆ 1496          ┆ -0.004606        ┆ 1.019444        │
│ chr1:10105685:T:C  ┆ ENSG00000120889_olink ┆ 1             ┆ -0.988386        ┆ null            │
│ chr1:10179536:C:T  ┆ ENSG00000069702_olink ┆ 2             ┆ 0.965469         ┆ 1.521465        │
│ chr1:10178779:G:A  ┆ ENSG00000048462_olink ┆ 1             ┆ 0.882108         ┆ null            │
└────────────────────┴───────────────────────┴───────────────┴──────────────────┴─────────────────┘

In [17]:
tmp['id'].value_counts(sort=True)

shape: (2_319, 2)
┌────────────────────┬───────┐
│ id                 ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u64   │
╞════════════════════╪═══════╡
│ chr1:2229364:A:G   ┆ 371   │
│ chr1:8967768:C:T   ┆ 371   │
│ chr1:6213135:C:T   ┆ 371   │
│ chr1:3480477:GGA:G ┆ 371   │
│ chr1:2519857:C:T   ┆ 371   │
│ …                  ┆ …     │
│ chr1:11059839:C:A  ┆ 123   │
│ chr1:2518220:C:T   ┆ 99    │
│ chr1:11056741:G:C  ┆ 63    │
│ chr1:3732885:G:A   ┆ 63    │
│ chr1:10179473:T:C  ┆ 54    │
└────────────────────┴───────┘

## Debug

In [18]:
geno_clipped = _fast_clip_and_sum_allels(geno[:10_000, olink_indices])
geno_clipped

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10000, 40398), dtype=int8)

In [25]:
sum(geno_clipped.sum(axis=1) > 0)

np.int64(2338)

In [19]:
rows, cols = np.where(geno_clipped == 1)

In [20]:
sample_list=sample_ids[olink_indices]
geno_melt = pl.DataFrame({
        'id': var_ids[rows],
        'individual': sample_list[cols],
        'genotype': 1
    })

geno_melt

shape: (352_717, 3)
┌───────────────────┬────────────┬──────────┐
│ id                ┆ individual ┆ genotype │
│ ---               ┆ ---        ┆ ---      │
│ str               ┆ str        ┆ i32      │
╞═══════════════════╪════════════╪══════════╡
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        │
│ chr1:1373805:T:C  ┆ 3540179    ┆ 1        │
│ chr1:1373805:T:C  ┆ 3991045    ┆ 1        │
│ chr1:1373805:T:C  ┆ 3130113    ┆ 1        │
│ chr1:1373805:T:C  ┆ 4471351    ┆ 1        │
│ …                 ┆ …          ┆ …        │
│ chr1:11231009:G:A ┆ 2259790    ┆ 1        │
│ chr1:11231013:G:A ┆ 2141582    ┆ 1        │
│ chr1:11231040:T:C ┆ 2938277    ┆ 1        │
│ chr1:11231047:C:T ┆ 3658207    ┆ 1        │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        │
└───────────────────┴────────────┴──────────┘

In [21]:
var_pheno_df = geno_melt.join(olink_melt, on='individual', how='left')
var_pheno_df

shape: (130_858_007, 5)
┌───────────────────┬────────────┬──────────┬───────────────────────┬─────────────┐
│ id                ┆ individual ┆ genotype ┆ phenotype             ┆ pheno_value │
│ ---               ┆ ---        ┆ ---      ┆ ---                   ┆ ---         │
│ str               ┆ str        ┆ i32      ┆ str                   ┆ f64         │
╞═══════════════════╪════════════╪══════════╪═══════════════════════╪═════════════╡
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        ┆ ENSG00000120053_olink ┆ -1.273965   │
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        ┆ ENSG00000140443_olink ┆ 1.564473    │
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        ┆ ENSG00000084674_olink ┆ -0.164796   │
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        ┆ ENSG00000015475_olink ┆ -1.803142   │
│ chr1:1373805:T:C  ┆ 3622589    ┆ 1        ┆ ENSG00000117748_olink ┆ -0.09892    │
│ …                 ┆ …          ┆ …        ┆ …                     ┆ …           │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        ┆ ENSG00000124678_olink ┆ 0.442166    │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        ┆ ENSG00000109062_olink ┆ 1.012175    │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        ┆ ENSG00000167186_olink ┆ 0.72797     │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        ┆ ENSG00000025708_olink ┆ -0.757016   │
│ chr1:11231048:G:A ┆ 3611469    ┆ 1        ┆ ENSG00000066468_olink ┆ -1.374467   │
└───────────────────┴────────────┴──────────┴───────────────────────┴─────────────┘

In [23]:
var_pheno_df['id'].value_counts(sort=True)

shape: (2_337, 2)
┌───────────────────┬─────────┐
│ id                ┆ count   │
│ ---               ┆ ---     │
│ str               ┆ u64     │
╞═══════════════════╪═════════╡
│ chr1:8949385:A:C  ┆ 7447825 │
│ chr1:8949347:C:T  ┆ 7087584 │
│ chr1:2512975:G:A  ┆ 7044548 │
│ chr1:6218354:A:G  ┆ 6735134 │
│ chr1:8957145:A:G  ┆ 6316646 │
│ …                 ┆ …       │
│ chr1:11231009:G:A ┆ 371     │
│ chr1:11231013:G:A ┆ 371     │
│ chr1:11231040:T:C ┆ 371     │
│ chr1:11231047:C:T ┆ 371     │
│ chr1:11231048:G:A ┆ 371     │
└───────────────────┴─────────┘

In [26]:
vm = var_pheno_df.group_by(
           ['id', 'phenotype']
           ).agg([
                pl.len().alias('n_individuals'),
                pl.col('pheno_value').mean().cast(pl.Float32).alias('mean_pheno_value'),
                pl.col('pheno_value').std().cast(pl.Float32).alias('std_pheno_value'),
            ])#.drop_nulls(subset=['mean_pheno_value'])
vm

shape: (867_027, 5)
┌───────────────────┬───────────────────────┬───────────────┬──────────────────┬─────────────────┐
│ id                ┆ phenotype             ┆ n_individuals ┆ mean_pheno_value ┆ std_pheno_value │
│ ---               ┆ ---                   ┆ ---           ┆ ---              ┆ ---             │
│ str               ┆ str                   ┆ u64           ┆ f32              ┆ f32             │
╞═══════════════════╪═══════════════════════╪═══════════════╪══════════════════╪═════════════════╡
│ chr1:11204686:C:A ┆ ENSG00000055955_olink ┆ 1             ┆ -0.891984        ┆ null            │
│ chr1:3469480:G:A  ┆ ENSG00000188211_olink ┆ 1             ┆ -1.286588        ┆ null            │
│ chr1:2306115:C:T  ┆ ENSG00000019186_olink ┆ 2             ┆ -1.203303        ┆ 0.789745        │
│ chr1:2512947:C:T  ┆ ENSG00000081800_olink ┆ 3             ┆ -0.992049        ┆ 0.70909         │
│ chr1:3478504:T:C  ┆ ENSG00000169194_olink ┆ 1             ┆ -0.871757        ┆ null            │
│ …                 ┆ …                     ┆ …             ┆ …                ┆ …               │
│ chr1:3477964:C:T  ┆ ENSG00000089902_olink ┆ 1             ┆ -0.079269        ┆ null            │
│ chr1:3463171:G:A  ┆ ENSG00000165471_olink ┆ 2             ┆ 0.296308         ┆ 0.593581        │
│ chr1:1374732:G:A  ┆ ENSG00000132703_olink ┆ 1             ┆ null             ┆ null            │
│ chr1:10126853:T:C ┆ ENSG00000204381_olink ┆ 2             ┆ 0.872165         ┆ 0.02158         │
│ chr1:1373877:C:A  ┆ ENSG00000132703_olink ┆ 1             ┆ null             ┆ null            │
└───────────────────┴───────────────────────┴───────────────┴──────────────────┴─────────────────┘

In [29]:
vm.drop_nulls(subset=['mean_pheno_value'])['id'].value_counts(sort=True)

shape: (2_319, 2)
┌───────────────────┬───────┐
│ id                ┆ count │
│ ---               ┆ ---   │
│ str               ┆ u64   │
╞═══════════════════╪═══════╡
│ chr1:3469480:G:A  ┆ 371   │
│ chr1:2306115:C:T  ┆ 371   │
│ chr1:2512947:C:T  ┆ 371   │
│ chr1:8945887:A:G  ┆ 371   │
│ chr1:1374375:C:T  ┆ 371   │
│ …                 ┆ …     │
│ chr1:11059839:C:A ┆ 123   │
│ chr1:2518220:C:T  ┆ 99    │
│ chr1:3732885:G:A  ┆ 63    │
│ chr1:11056741:G:C ┆ 63    │
│ chr1:10179473:T:C ┆ 54    │
└───────────────────┴───────┘

## WGS debug

In [4]:
anngeno_path = '/home/dnanexus/data_dir/genebass_1e6.ag'
eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'
# olink_path = '/home/dnanexus/data_dir/olink/protrider_lite_output/log2fc.csv'
olink_path = "/home/dnanexus/data_dir/olink/olink_corrected_rint_90_pcs.parquet"

In [5]:
sample_ids = zarr.open(f'{anngeno_path}/zarr_store/samples', mode='r')[:]
var_ids = pl.read_parquet(f'{anngeno_path}/variant_metadata.parquet', columns=['id'])['id'].to_numpy()
geno = zarr.open(f'{anngeno_path}/zarr_store/genotypes', mode='r')

eur_samples = pl.read_csv(eur_samples_path).rename({'eid': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
)['individual'].to_list()

In [6]:
olink_df = pl.read_parquet(olink_path).rename({'sample': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
).filter(
    pl.col("individual").is_in(eur_samples)
).fill_nan(None)

unique_phenotypes = [pheno for pheno in olink_df.columns if pheno != 'individual']

olink_melt = (
    olink_df.unpivot(
        index=['individual'],
        on=unique_phenotypes,
        variable_name='phenotype',
        value_name='pheno_value',
    )
    .with_columns(
        phenotype = pl.col('phenotype') + '_olink'
    )
)

olink_melt

shape: (14_987_658, 3)
┌────────────┬───────────────────────┬─────────────┐
│ individual ┆ phenotype             ┆ pheno_value │
│ ---        ┆ ---                   ┆ ---         │
│ str        ┆ str                   ┆ f64         │
╞════════════╪═══════════════════════╪═════════════╡
│ 1000107    ┆ ENSG00000120053_olink ┆ -0.592022   │
│ 1001193    ┆ ENSG00000120053_olink ┆ 0.061036    │
│ 1001694    ┆ ENSG00000120053_olink ┆ 0.228713    │
│ 1001715    ┆ ENSG00000120053_olink ┆ 0.674837    │
│ 1002486    ┆ ENSG00000120053_olink ┆ 1.153924    │
│ …          ┆ …                     ┆ …           │
│ 6019565    ┆ ENSG00000066468_olink ┆ 0.72708     │
│ 6019855    ┆ ENSG00000066468_olink ┆ -0.327369   │
│ 6021528    ┆ ENSG00000066468_olink ┆ 0.991073    │
│ 6022842    ┆ ENSG00000066468_olink ┆ -1.81022    │
│ 6023199    ┆ ENSG00000066468_olink ┆ 1.16358     │
└────────────┴───────────────────────┴─────────────┘

In [9]:
region_list = [g[:-6] for g in olink_melt['phenotype'].unique().to_list()]
len(region_list)

371

In [11]:
# Optimized approach to find indices of olink_samples in sample_ids
# Step A: Create a lookup dictionary mapping each ID in the large array to its original index. This takes O(N) time, where N is the size of sample_ids.
olink_sids = olink_df['individual'].to_numpy()
sample_id_to_index = {sid: i for i, sid in enumerate(sample_ids)}

# Step B: Iterate through the smaller array and find the index for each element if it exists in our lookup dictionary. This takes O(M) time, where M is the size of olink_sids.
found_indices = []
for sid in olink_sids:
    if sid in sample_id_to_index:
        found_indices.append(sample_id_to_index[sid])
print(f"Found {len(found_indices)} matching IDs.")

# Step C: Convert the list of indices to a NumPy array and sort it.
# Sorting ensures the output is identical to the original np.where approach, which returns indices in ascending order.
olink_indices = np.sort(found_indices)

Found 40398 matching IDs.

In [12]:
found_indices

[192701,
 179743,
 234538,
 452916,
 221385,
 12142,
 366951,
 40441,
 357078,
 171701,
 362876,
 431476,
 402558,
 395145,
 148779,
 22357,
 376940,
 289660,
 568,
 365464,
 411572,
 210410,
 81605,
 171708,
 411518,
 452881,
 327493,
 351496,
 433356,
 92197,
 156509,
 146220,
 487659,
 355664,
 394012,
 359466,
 459929,
 17007,
 371537,
 252293,
 391108,
 98590,
 174864,
 124300,
 130239,
 149835,
 128247,
 171344,
 95055,
 179270,
 332008,
 17030,
 167350,
 69328,
 418672,
 374426,
 290813,
 427985,
 473786,
 359379,
 373226,
 240143,
 420990,
 462300,
 442224,
 34241,
 192832,
 471995,
 25845,
 419077,
 404354,
 310964,
 292464,
 128991,
 18174,
 11247,
 110055,
 177898,
 419401,
 200689,
 380549,
 435216,
 64634,
 370879,
 339062,
 190257,
 26373,
 19453,
 306444,
 229225,
 405742,
 478623,
 286172,
 6345,
 314175,
 81720,
 402953,
 483576,
 317441,
 64218,
 365629,
 233531,
 112074,
 278820,
 271200,
 6789,
 464404,
 67696,
 323078,
 77770,
 158331,
 218918,
 182294,
 464474,
 329926,
 169205,
 152013,
 282222,
 65397,
 243148,
 354913,
 459745,
 340698,
 375405,
 469484,
 372501,
 213382,
 380963,
 479913,
 82519,
 314989,
 286488,
 316083,
 385765,
 156816,
 298962,
 400861,
 400978,
 51277,
 239234,
 449332,
 475024,
 190004,
 83412,
 385051,
 297548,
 114958,
 334206,
 102535,
 35489,
 427704,
 184111,
 434710,
 18198,
 138895,
 14535,
 304286,
 138379,
 129456,
 263276,
 49677,
 351447,
 286193,
 429754,
 69857,
 60681,
 385597,
 409024,
 266541,
 399704,
 327091,
 32099,
 375389,
 30971,
 404630,
 372094,
 231816,
 440698,
 390181,
 407778,
 393904,
 136117,
 50694,
 113801,
 186827,
 285076,
 483675,
 200658,
 46278,
 453566,
 334290,
 225598,
 404266,
 141482,
 42594,
 417925,
 286472,
 50397,
 161238,
 309486,
 38916,
 341564,
 4001,
 399115,
 462349,
 139099,
 181433,
 395098,
 184609,
 286623,
 425456,
 203521,
 29864,
 78850,
 168140,
 265753,
 291522,
 323479,
 42486,
 459769,
 462217,
 460482,
 398809,
 447411,
 46753,
 272629,
 103190,
 397446,
 116551,
 89088,
 176558,
 305344,
 119460,
 77462,
 350363,
 231433,
 325763,
 319685,
 283792,
 189855,
 23972,
 482328,
 231972,
 450209,
 159783,
 310436,
 308191,
 302614,
 203102,
 113495,
 440736,
 420933,
 465654,
 292571,
 160051,
 243403,
 199254,
 282077,
 69595,
 41546,
 70223,
 125673,
 432377,
 36100,
 368507,
 240470,
 6338,
 224303,
 95278,
 313170,
 87025,
 152410,
 146588,
 85853,
 481532,
 199234,
 236896,
 474588,
 245066,
 315037,
 62695,
 454487,
 233389,
 119108,
 152842,
 301166,
 419700,
 296952,
 390438,
 147888,
 459041,
 238882,
 237606,
 243514,
 330815,
 313221,
 239933,
 456371,
 201105,
 91719,
 163006,
 214162,
 261812,
 454449,
 257984,
 434819,
 136740,
 462023,
 150265,
 387763,
 171585,
 129250,
 98488,
 273874,
 307268,
 211478,
 123967,
 4941,
 153581,
 237531,
 309097,
 381838,
 377476,
 187146,
 56123,
 268482,
 57609,
 388608,
 219522,
 382610,
 422372,
 74568,
 466872,
 311834,
 125297,
 115909,
 412725,
 345323,
 307849,
 100894,
 199331,
 424847,
 24272,
 289519,
 358846,
 127608,
 472433,
 120803,
 167267,
 327429,
 343169,
 47246,
 84204,
 426674,
 440111,
 394596,
 448639,
 137396,
 325719,
 163270,
 444247,
 131718,
 279986,
 451198,
 182640,
 382748,
 194041,
 317000,
 63253,
 184543,
 112005,
 7457,
 40947,
 427732,
 325121,
 221646,
 263018,
 175536,
 412948,
 138370,
 155435,
 137423,
 478907,
 340486,
 409969,
 68074,
 219903,
 161265,
 457614,
 77406,
 128482,
 365369,
 134385,
 160872,
 179300,
 263674,
 221079,
 323449,
 423239,
 97274,
 134044,
 402522,
 476652,
 385837,
 446741,
 325616,
 452610,
 470786,
 82191,
 19879,
 24773,
 41787,
 349567,
 155787,
 213791,
 301797,
 297901,
 78084,
 214249,
 195410,
 88503,
 54935,
 370233,
 346204,
 303085,
 144543,
 299821,
 164262,
 63410,
 302038,
 19615,
 17655,
 302708,
 65072,
 32462,
 118476,
 343430,
 41803,
 65369,
 442298,
 336643,
 333277,
 476362,
 473422,
 188225,
 235761,
 132318,
 411495,
 465876,
 422512,
 405776,
 63875,
 256805,
 294983,
 409720,
 391835,
 256350,
 70254,
 277155,
 78929,
 270115,
 194531,
 153841,
 88078,
 295551,
 451340,
 487980,
 432609,
 332741,
 398428,
 291768,
 138833,
 263000,
 25487,
 474886,
 164075,
 354271,
 51599,
 152915,
 239131,
 214132,
 85157,
 313377,
 141305,
 223229,
 453080,
 276544,
 448330,
 105457,
 365147,
 85156,
 446670,
 443271,
 326363,
 293970,
 425460,
 344855,
 454561,
 145186,
 391962,
 60696,
 273581,
 67736,
 467189,
 6959,
 24165,
 424370,
 469555,
 149438,
 153984,
 157372,
 489550,
 356330,
 71295,
 490491,
 326225,
 53496,
 138574,
 377857,
 278393,
 442579,
 253430,
 380640,
 348212,
 321920,
 355234,
 422266,
 416332,
 450860,
 55593,
 12507,
 216217,
 361136,
 306917,
 220900,
 345212,
 397519,
 341061,
 228471,
 166315,
 274006,
 480947,
 113894,
 154015,
 220350,
 484362,
 129610,
 175265,
 94265,
 2050,
 37207,
 427169,
 154702,
 429014,
 297055,
 75071,
 111185,
 2013,
 78511,
 32447,
 280517,
 35473,
 176090,
 183289,
 49979,
 458462,
 436455,
 215149,
 207302,
 240911,
 257896,
 390250,
 107282,
 431833,
 168456,
 172126,
 128485,
 459236,
 415133,
 315911,
 487362,
 416697,
 48399,
 355126,
 473321,
 16020,
 489795,
 74629,
 454814,
 459538,
 93152,
 346770,
 469120,
 236522,
 13302,
 110632,
 111134,
 426823,
 479596,
 297244,
 421569,
 32709,
 434179,
 68505,
 326920,
 377314,
 15421,
 251087,
 377412,
 75956,
 289306,
 391820,
 451630,
 9809,
 419189,
 331719,
 207138,
 342313,
 26576,
 356382,
 72632,
 135513,
 394654,
 65804,
 309609,
 139997,
 185101,
 489997,
 261152,
 353036,
 155864,
 156287,
 16082,
 120716,
 294292,
 122980,
 308376,
 184910,
 214515,
 158229,
 219166,
 171790,
 158409,
 29049,
 448775,
 418044,
 134995,
 189240,
 165058,
 25841,
 407154,
 80431,
 77729,
 260297,
 367217,
 120608,
 305053,
 131194,
 116936,
 209455,
 170404,
 20401,
 295126,
 89400,
 49756,
 249868,
 474677,
 341836,
 403772,
 370540,
 264254,
 151561,
 427856,
 342370,
 254353,
 249456,
 142443,
 314899,
 358528,
 441455,
 423929,
 183713,
 56885,
 253163,
 138500,
 209727,
 309742,
 22677,
 2528,
 85368,
 475184,
 247215,
 327240,
 303654,
 318228,
 13287,
 297306,
 148359,
 160393,
 105258,
 243582,
 430313,
 14606,
 432925,
 352178,
 344052,
 59957,
 354193,
 131995,
 210626,
 297119,
 394183,
 202943,
 460623,
 92133,
 90690,
 319885,
 378901,
 281496,
 224768,
 73048,
 217165,
 418520,
 277937,
 355971,
 2024,
 138058,
 327929,
 86688,
 8250,
 334364,
 8489,
 59802,
 273200,
 34502,
 262649,
 8675,
 76403,
 82503,
 29048,
 393439,
 85043,
 76827,
 222204,
 343263,
 421229,
 400762,
 234146,
 130095,
 462496,
 393795,
 440102,
 249439,
 116613,
 260641,
 41306,
 457553,
 420382,
 201861,
 136341,
 11708,
 183849,
 275968,
 95925,
 213851,
 41178,
 471454,
 340275,
 376734,
 362651,
 160360,
 259450,
 467046,
 251100,
 236977,
 404350,
 195465,
 207380,
 475205,
 151486,
 249541,
 461606,
 167468,
 316677,
 130992,
 453708,
 46529,
 180010,
 399584,
 445100,
 485391,
 324833,
 293984,
 189827,
 21508,
 255748,
 69428,
 476321,
 450252,
 229090,
 252076,
 322177,
 165610,
 268281,
 297688,
 239787,
 375124,
 299788,
 343804,
 249194,
 261308,
 433945,
 422087,
 434805,
 431107,
 362323,
 413061,
 74305,
 344343,
 156152,
 320281,
 120113,
 330264,
 27438,
 370726,
 10373,
 168901,
 203712,
 318846,
 279481,
 270233,
 89503,
 313681,
 274572,
 468109,
 344730,
 465607,
 130795,
 142387,
 276095,
 223678,
 120830,
 429518,
 189961,
 50270,
 390169,
 360123,
 65646,
 55890,
 6884,
 6250,
 73392,
 256035,
 100291,
 152850,
 300277,
 320260,
 186950,
 262000,
 355252,
 352108,
 241518,
 275109,
 96085,
 434472,
 106081,
 448471,
 342641,
 291294,
 403028,
 157983,
 249119,
 233011,
 279702,
 71485,
 144578,
 431430,
 262714,
 433333,
 458266,
 437571,
 467215,
 469779,
 284529,
 20908,
 113282,
 74809,
 341474,
 239651,
 23959,
 279594,
 395254,
 157307,
 441828,
 70079,
 482178,
 387096,
 238730,
 283626,
 157312,
 272262,
 263356,
 27613,
 350667,
 99804,
 278759,
 418873,
 172654,
 265399,
 397902,
 263905,
 445109,
 192323,
 183122,
 219416,
 395868,
 397055,
 187296,
 169844,
 272103,
 378395,
 115313,
 127154,
 185747,
 128886,
 485459,
 393813,
 426582,
 297277,
 429064,
 348436,
 135663,
 374867,
 248358,
 450904,
 210435,
 181645,
 275598,
 283728,
 350545,
 157397,
 315983,
 354135,
 400240,
 345251,
 301081,
 482634,
 481194,
 387063,
 20876,
 45434,
 72569,
 215642,
 2092,
 292387,
 330251,
 364430,
 329443,
 114328,
 318398,
 182766,
 323985,
 379992,
 474276,
 409364,
 384545,
 413380,
 49673,
 211323,
 110590,
 313257,
 142777,
 436524,
 72157,
 96585,
 33636,
 123983,
 277896,
 214537,
 341984,
 78853,
 328165,
 267699,
 298936,
 333634,
 213354,
 201697,
 271341,
 191266,
 153181,
 416008,
 328450,
 315930,
 216062,
 16615,
 28140,
 486808,
 68668,
 273992,
 466959,
 ...]

In [13]:
olink_indices

array([    17,     23,     45, ..., 490517, 490532, 490535],
      shape=(40398,))

In [14]:
gene_name = 'LDLR'
anno = pl.scan_parquet(f"/home/dnanexus/data_dir/genebass1e6_genes_10kb_allvars_annotated_250925.parquet").filter(pl.col('gene_name') == gene_name).select(['id']).unique().collect(engine='streaming')
anno

shape: (23_997, 1)
┌───────────────────────────┐
│ id                        │
│ ---                       │
│ str                       │
╞═══════════════════════════╡
│ chr19:11091529:G:C        │
│ chr19:11136598:G:A        │
│ chr19:11122444:G:T        │
│ chr19:11095648:G:C        │
│ chr19:11099942:T:C        │
│ …                         │
│ chr19:11104240:A:AAGG     │
│ chr19:11091225:CT:C       │
│ chr19:11097504:C:CAAAAACA │
│ chr19:11088080:T:C        │
│ chr19:11085336:G:A        │
└───────────────────────────┘

In [18]:
pl.scan_parquet(f"/home/dnanexus/data_dir/genebass1e6_genes_10kb_allvars_annotated_250925.parquet").filter(pl.col('region').is_in(unique_phenotypes)).select(['id']).unique().collect(engine='streaming')

shape: (13_787_158, 1)
┌────────────────────┐
│ id                 │
│ ---                │
│ str                │
╞════════════════════╡
│ chr2:105843356:G:C │
│ chr2:105778273:T:G │
│ chr2:53777089:C:A  │
│ chr2:120142458:G:A │
│ chr2:157293678:C:T │
│ …                  │
│ chr2:212280225:A:C │
│ chr2:212051994:G:A │
│ chr2:212113335:A:C │
│ chr6:152089625:C:A │
│ chr2:212209605:T:G │
└────────────────────┘

In [24]:
anno_var_ids = np.concatenate((anno['id'].to_numpy(), ['chr19:11093738:G:A']))
anno_var_ids

array(['chr19:11093738:G:A', 'chr19:11110949:G:A', 'chr19:11137687:A:C',
       ..., 'chr19:11097297:CG:C', 'chr19:11126535:AG:A',
       'chr19:11093738:G:A'], shape=(23998,), dtype=object)

In [10]:
# Optimized approach to find indices of olink_samples in sample_ids
# Step A: Create a lookup dictionary mapping each ID in the large array to its original index. This takes O(N) time, where N is the size of sample_ids.
var_ids_to_index = {sid: i for i, sid in enumerate(var_ids)}

# Step B: Iterate through the smaller array and find the index for each element if it exists in our lookup dictionary. This takes O(M) time, where M is the size of olink_sids.
found_indices = []
for sid in anno_var_ids:
    if sid in var_ids_to_index:
        found_indices.append(var_ids_to_index[sid])
print(f"Found {len(found_indices)} matching IDs.")

# Step C: Convert the list of indices to a NumPy array and sort it.
# Sorting ensures the output is identical to the original np.where approach, which returns indices in ascending order.
indices_vars2keep = np.sort(found_indices)
indices_vars2keep

Found 23997 matching IDs.

array([81565377, 81565403, 81565404, ..., 81589396, 81589397, 81589398],
      shape=(23997,))

In [12]:
var_ids[indices_vars2keep]

array(['chr19:11084366:TTGGCTCATGTCTGTAATCCCAGCACGTTGGGAGGCTGAGGCGGGTGGATCACAAGGTCAGGAGATCCAGACCATCCTGGCTAACAAAGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGGCTGGGCGTGG:T',
       'chr19:11084419:A:G', 'chr19:11084420:A:G', ...,
       'chr19:11138810:C:A', 'chr19:11138812:G:C', 'chr19:11138814:C:A'],
      shape=(23997,), dtype=object)

In [19]:
chunk_size = 1_000

for chunk_num in range(indices_vars2keep.shape[0] // chunk_size + 1):
    indices_vars2keep_chunk = indices_vars2keep[chunk_num*chunk_size:(chunk_num+1)*chunk_size]
    tmp_geno = geno.oindex[indices_vars2keep_chunk, olink_indices]
    tmp_vars = var_ids[indices_vars2keep_chunk]
    break

In [18]:
olink_indices

array([    17,     23,     45, ..., 490517, 490532, 490535],
      shape=(40398,))

In [20]:
indices_vars2keep_chunk

array([81565377, 81565403, 81565404, 81565405, 81565406, 81565407,
       81565408, 81565409, 81565410, 81565411, 81565412, 81565413,
       81565414, 81565415, 81565416, 81565417, 81565418, 81565419,
       81565420, 81565421, 81565422, 81565423, 81565424, 81565425,
       81565426, 81565427, 81565428, 81565429, 81565430, 81565431,
       81565432, 81565433, 81565434, 81565435, 81565436, 81565437,
       81565438, 81565439, 81565440, 81565441, 81565442, 81565443,
       81565444, 81565445, 81565446, 81565447, 81565448, 81565449,
       81565450, 81565451, 81565452, 81565453, 81565454, 81565455,
       81565456, 81565457, 81565458, 81565459, 81565460, 81565461,
       81565462, 81565463, 81565464, 81565465, 81565466, 81565467,
       81565468, 81565469, 81565470, 81565471, 81565472, 81565473,
       81565474, 81565475, 81565476, 81565477, 81565478, 81565479,
       81565480, 81565481, 81565482, 81565483, 81565484, 81565485,
       81565486, 81565487, 81565488, 81565489, 81565490, 81565491,
       81565492, 81565493, 81565494, 81565495, 81565496, 81565497,
       81565498, 81565499, 81565500, 81565501, 81565502, 81565503,
       81565504, 81565505, 81565506, 81565507, 81565508, 81565509,
       81565510, 81565511, 81565512, 81565513, 81565514, 81565515,
       81565516, 81565517, 81565518, 81565519, 81565520, 81565521,
       81565522, 81565523, 81565524, 81565525, 81565526, 81565527,
       81565528, 81565529, 81565530, 81565531, 81565532, 81565533,
       81565534, 81565535, 81565536, 81565537, 81565538, 81565539,
       81565540, 81565541, 81565542, 81565543, 81565544, 81565545,
       81565546, 81565547, 81565548, 81565549, 81565550, 81565551,
       81565552, 81565553, 81565554, 81565555, 81565556, 81565557,
       81565558, 81565559, 81565560, 81565561, 81565562, 81565563,
       81565564, 81565565, 81565566, 81565567, 81565568, 81565569,
       81565570, 81565571, 81565572, 81565573, 81565574, 81565575,
       81565576, 81565577, 81565578, 81565579, 81565580, 81565581,
       81565582, 81565583, 81565584, 81565585, 81565586, 81565587,
       81565588, 81565589, 81565590, 81565591, 81565592, 81565593,
       81565594, 81565595, 81565596, 81565597, 81565598, 81565599,
       81565600, 81565601, 81565602, 81565603, 81565604, 81565605,
       81565606, 81565607, 81565608, 81565609, 81565610, 81565611,
       81565612, 81565613, 81565614, 81565615, 81565616, 81565617,
       81565618, 81565619, 81565620, 81565621, 81565622, 81565623,
       81565624, 81565625, 81565626, 81565627, 81565628, 81565629,
       81565630, 81565631, 81565632, 81565633, 81565634, 81565635,
       81565636, 81565637, 81565638, 81565639, 81565640, 81565641,
       81565642, 81565643, 81565644, 81565645, 81565646, 81565647,
       81565648, 81565649, 81565650, 81565651, 81565652, 81565653,
       81565654, 81565655, 81565656, 81565657, 81565658, 81565659,
       81565660, 81565661, 81565662, 81565663, 81565664, 81565665,
       81565666, 81565667, 81565668, 81565669, 81565670, 81565671,
       81565672, 81565673, 81565674, 81565675, 81565676, 81565677,
       81565678, 81565679, 81565680, 81565681, 81565682, 81565683,
       81565684, 81565685, 81565686, 81565687, 81565688, 81565689,
       81565690, 81565691, 81565692, 81565693, 81565694, 81565695,
       81565696, 81565697, 81565698, 81565699, 81565700, 81565701,
       81565702, 81565703, 81565704, 81565705, 81565706, 81565707,
       81565708, 81565709, 81565710, 81565711, 81565712, 81565713,
       81565714, 81565715, 81565716, 81565717, 81565718, 81565719,
       81565720, 81565721, 81565722, 81565723, 81565724, 81565725,
       81565726, 81565727, 81565728, 81565729, 81565730, 81565731,
       81565732, 81565733, 81565734, 81565735, 81565736, 81565737,
       81565738, 81565739, 81565740, 81565741, 81565742, 81565743,
       81565744, 81565745, 81565746, 81565747, 81565748, 81565749,
       81565750, 81565751, 81565752, 81565753, 81565754, 81565755,
       81565756, 81565757, 81565758, 81565759, 81565760, 81565761,
       81565762, 81565763, 81565764, 81565765, 81565766, 81565767,
       81565768, 81565769, 81565770, 81565771, 81565772, 81565773,
       81565774, 81565775, 81565776, 81565777, 81565778, 81565779,
       81565780, 81565781, 81565782, 81565783, 81565784, 81565785,
       81565786, 81565787, 81565788, 81565789, 81565790, 81565791,
       81565792, 81565793, 81565794, 81565795, 81565796, 81565797,
       81565798, 81565799, 81565800, 81565801, 81565802, 81565803,
       81565804, 81565805, 81565806, 81565807, 81565808, 81565809,
       81565810, 81565811, 81565812, 81565813, 81565814, 81565815,
       81565816, 81565817, 81565818, 81565819, 81565820, 81565821,
       81565822, 81565823, 81565824, 81565825, 81565826, 81565827,
       81565828, 81565829, 81565830, 81565831, 81565832, 81565833,
       81565834, 81565835, 81565836, 81565837, 81565838, 81565839,
       81565840, 81565841, 81565842, 81565843, 81565844, 81565845,
       81565846, 81565847, 81565848, 81565849, 81565850, 81565851,
       81565852, 81565853, 81565854, 81565855, 81565856, 81565857,
       81565858, 81565859, 81565860, 81565861, 81565862, 81565863,
       81565864, 81565865, 81565866, 81565867, 81565868, 81565869,
       81565870, 81565871, 81565872, 81565873, 81565874, 81565875,
       81565876, 81565877, 81565878, 81565879, 81565880, 81565881,
       81565882, 81565883, 81565884, 81565885, 81565886, 81565887,
       81565888, 81565889, 81565890, 81565891, 81565892, 81565893,
       81565894, 81565895, 81565896, 81565897, 81565898, 81565899,
       81565900, 81565901, 81565902, 81565903, 81565904, 81565905,
       81565906, 81565907, 81565908, 81565909, 81565910, 81565911,
       81565912, 81565913, 81565914, 81565915, 81565916, 81565917,
       81565918, 81565919, 81565920, 81565921, 81565922, 81565923,
       81565924, 81565925, 81565926, 81565927, 81565928, 81565929,
       81565930, 81565931, 81565932, 81565933, 81565934, 81565935,
       81565936, 81565937, 81565938, 81565939, 81565940, 81565941,
       81565942, 81565943, 81565944, 81565945, 81565946, 81565947,
       81565948, 81565949, 81565950, 81565951, 81565952, 81565953,
       81565954, 81565955, 81565956, 81565957, 81565958, 81565959,
       81565960, 81565961, 81565962, 81565963, 81565964, 81565965,
       81565966, 81565967, 81565968, 81565969, 81565970, 81565971,
       81565972, 81565973, 81565974, 81565975, 81565976, 81565977,
       81565978, 81565979, 81565980, 81565981, 81565982, 81565983,
       81565984, 81565985, 81565986, 81565987, 81565988, 81565989,
       81565990, 81565991, 81565992, 81565993, 81565994, 81565995,
       81565996, 81565997, 81565998, 81565999, 81566000, 81566001,
       81566002, 81566003, 81566004, 81566005, 81566006, 81566007,
       81566008, 81566009, 81566010, 81566011, 81566012, 81566013,
       81566014, 81566015, 81566016, 81566017, 81566018, 81566019,
       81566020, 81566021, 81566022, 81566023, 81566024, 81566025,
       81566026, 81566027, 81566028, 81566029, 81566030, 81566031,
       81566032, 81566033, 81566034, 81566035, 81566036, 81566037,
       81566038, 81566039, 81566040, 81566041, 81566042, 81566043,
       81566044, 81566045, 81566046, 81566047, 81566048, 81566049,
       81566050, 81566051, 81566052, 81566053, 81566054, 81566055,
       81566056, 81566057, 81566058, 81566059, 81566060, 81566061,
       81566062, 81566063, 81566064, 81566065, 81566066, 81566067,
       81566068, 81566069, 81566070, 81566071, 81566072, 81566073,
       81566074, 81566075, 81566076, 81566077, 81566078, 81566079,
       81566080, 81566081, 81566082, 81566083, 81566084, 81566085,
       81566086, 81566087, 81566088, 81566089, 81566090, 81566091,
       81566092, 81566093, 81566094, 81566095, 81566096, 81566097,
       81566098, 81566099, 81566100, 81566101, 81566102, 81566103,
       81566104, 81566105, 81566106, 81566107, 81566108, 81566109,
       81566110, 81566111, 81566112, 81566113, 81566114, 81566115,
       81566116, 81566117, 81566118, 81566119, 81566120, 81566121,
       81566122, 81566123, 81566124, 81566125, 81566126, 81566127,
       81566128, 81566129, 81566130, 81566131, 81566132, 81566133,
       81566134, 81566135, 81566136, 81566137, 81566138, 81566139,
       81566140, 81566141, 81566142, 81566143, 81566144, 81566145,
       81566146, 81566147, 81566148, 81566149, 81566150, 81566151,
       81566152, 81566153, 81566154, 81566155, 81566156, 81566157,
       81566158, 81566159, 81566160, 81566161, 81566162, 81566163,
       81566164, 81566165, 81566166, 81566167, 81566168, 81566169,
       81566170, 81566171, 81566172, 81566173, 81566174, 81566175,
       81566176, 81566177, 81566178, 81566179, 81566180, 81566181,
       81566182, 81566183, 81566184, 81566185, 81566186, 81566187,
       81566188, 81566189, 81566190, 81566191, 81566192, 81566193,
       81566194, 81566195, 81566196, 81566197, 81566198, 81566199,
       81566200, 81566201, 81566202, 81566203, 81566204, 81566205,
       81566206, 81566207, 81566208, 81566209, 81566210, 81566211,
       81566212, 81566213, 81566214, 81566215, 81566216, 81566217,
       81566218, 81566219, 81566220, 81566221, 81566222, 81566223,
       81566224, 81566225, 81566226, 81566227, 81566228, 81566229,
       81566230, 81566231, 81566232, 81566233, 81566234, 81566235,
       81566236, 81566237, 81566238, 81566239, 81566240, 81566241,
       81566242, 81566243, 81566244, 81566245, 81566246, 81566247,
       81566248, 81566249, 81566250, 81566251, 81566252, 81566253,
       81566254, 81566255, 81566256, 81566257, 81566258, 81566259,
       81566260, 81566261, 81566262, 81566263, 81566264, 81566265,
       81566266, 81566267, 81566268, 81566269, 81566270, 81566271,
       81566272, 81566273, 81566274, 81566275, 81566276, 81566277,
       81566278, 81566279, 81566280, 81566281, 81566282, 81566283,
       81566284, 81566285, 81566286, 81566287, 81566288, 81566289,
       81566290, 81566291, 81566292, 81566293, 81566294, 81566295,
       81566296, 81566297, 81566298, 81566299, 81566300, 81566301,
       81566302, 81566303, 81566304, 81566305, 81566306, 81566307,
       81566308, 81566309, 81566310, 81566311, 81566312, 81566313,
       81566314, 81566315, 81566316, 81566317, 81566318, 81566319,
       81566320, 81566321, 81566322, 81566323, 81566324, 81566325,
       81566326, 81566327, 81566328, 81566329, 81566330, 81566331,
       81566332, 81566333, 81566334, 81566335, 81566336, 81566337,
       81566338, 81566339, 81566340, 81566341, 81566342, 81566343,
       81566344, 81566345, 81566346, 81566347, 81566348, 81566349,
       81566350, 81566351, 81566352, 81566353, 81566354, 81566355,
       81566356, 81566357, 81566358, 81566359, 81566360, 81566361,
       81566362, 81566363, 81566364, 81566365, 81566366, 81566367,
       81566368, 81566369, 81566370, 81566371, 81566372, 81566373,
       81566374, 81566375, 81566376, 81566377, 81566378, 81566379,
       81566380, 81566381, 81566382, 81566383, 81566384, 81566385,
       81566386, 81566387, 81566388, 81566389, 81566390, 81566391,
       81566392, 81566393, 81566394, 81566395, 81566396, 81566397,
       81566398, 81566399, 81566400, 81566401])

## Debug results

In [ ]:
output_dir = "/home/dnanexus/data_dir/olink_appv_chunks_EUR_smarter"

files = [f"{output_dir}/{filename}" for filename in os.listdir(output_dir) if filename.endswith(".parquet")]

# lazy_frames = [pl.scan_parquet(f) for f in files]
# combined = pl.concat(lazy_frames)

# combined.sink_parquet(f"{output_dir}/avg_pheno_per_var_371olink_EUR_corrected90pcs.parquet", engine='streaming')

In [2]:
ch_wgs = pl.scan_parquet("/home/dnanexus/data_dir/olink_appv_chunks_EUR/variant_pheno_chunk9.parquet")
ch_wgs.head().collect()

shape: (5, 5)
┌──────────────────────┬──────────────────────┬───────────────┬──────────────────┬─────────────────┐
│ id                   ┆ phenotype            ┆ n_individuals ┆ mean_pheno_value ┆ std_pheno_value │
│ ---                  ┆ ---                  ┆ ---           ┆ ---              ┆ ---             │
│ str                  ┆ str                  ┆ u64           ┆ f32              ┆ f32             │
╞══════════════════════╪══════════════════════╪═══════════════╪══════════════════╪═════════════════╡
│ chr1:3672476:CGGCCCC ┆ ENSG00000019186_olin ┆ 1             ┆ -1.209683        ┆ null            │
│ A:C                  ┆ k                    ┆               ┆                  ┆                 │
│ chr1:3689403:C:G     ┆ ENSG00000019186_olin ┆ 2             ┆ 0.758827         ┆ 0.727729        │
│                      ┆ k                    ┆               ┆                  ┆                 │
│ chr1:3640236:C:T     ┆ ENSG00000019186_olin ┆ 5             ┆ -0.642613        ┆ 1.180599        │
│                      ┆ k                    ┆               ┆                  ┆                 │
│ chr1:3645018:A:G     ┆ ENSG00000161944_olin ┆ 12            ┆ -0.715548        ┆ 1.401296        │
│                      ┆ k                    ┆               ┆                  ┆                 │
│ chr1:3682246:C:T     ┆ ENSG00000161944_olin ┆ 21            ┆ -0.153775        ┆ 0.802043        │
│                      ┆ k                    ┆               ┆                  ┆                 │
└──────────────────────┴──────────────────────┴───────────────┴──────────────────┴─────────────────┘

In [4]:
odf = pl.scan_parquet(f"/home/dnanexus/data_dir/olink_appv_chunks_EUR_smarter/avg_pheno_per_var_371olink_EUR_corrected90pcs.parquet")
odf.head().collect()

shape: (5, 5)
┌──────────────────┬───────────────────────┬───────────────┬──────────────────┬─────────────────┐
│ id               ┆ phenotype             ┆ n_individuals ┆ mean_pheno_value ┆ std_pheno_value │
│ ---              ┆ ---                   ┆ ---           ┆ ---              ┆ ---             │
│ str              ┆ str                   ┆ u64           ┆ f32              ┆ f32             │
╞══════════════════╪═══════════════════════╪═══════════════╪══════════════════╪═════════════════╡
│ chr1:3664499:C:T ┆ ENSG00000134352_olink ┆ 3             ┆ -0.272098        ┆ 1.556659        │
│ chr1:3690579:C:T ┆ ENSG00000134352_olink ┆ 4             ┆ -0.183986        ┆ 0.678737        │
│ chr1:3663475:G:T ┆ ENSG00000134352_olink ┆ 3             ┆ 0.647399         ┆ 1.883861        │
│ chr1:3706937:G:A ┆ ENSG00000134352_olink ┆ 1             ┆ -0.580956        ┆ null            │
│ chr1:3678411:G:A ┆ ENSG00000134352_olink ┆ 2             ┆ -0.301727        ┆ null            │
└──────────────────┴───────────────────────┴───────────────┴──────────────────┴─────────────────┘

In [6]:
ch_wgs.join(odf.head(), on=['id', 'phenotype'], how='semi').collect()

shape: (5, 5)
┌──────────────────┬───────────────────────┬───────────────┬──────────────────┬─────────────────┐
│ id               ┆ phenotype             ┆ n_individuals ┆ mean_pheno_value ┆ std_pheno_value │
│ ---              ┆ ---                   ┆ ---           ┆ ---              ┆ ---             │
│ str              ┆ str                   ┆ u64           ┆ f32              ┆ f32             │
╞══════════════════╪═══════════════════════╪═══════════════╪══════════════════╪═════════════════╡
│ chr1:3663475:G:T ┆ ENSG00000134352_olink ┆ 3             ┆ 0.647399         ┆ 1.883861        │
│ chr1:3678411:G:A ┆ ENSG00000134352_olink ┆ 2             ┆ -0.301727        ┆ null            │
│ chr1:3706937:G:A ┆ ENSG00000134352_olink ┆ 1             ┆ -0.580956        ┆ null            │
│ chr1:3690579:C:T ┆ ENSG00000134352_olink ┆ 4             ┆ -0.183986        ┆ 0.678737        │
│ chr1:3664499:C:T ┆ ENSG00000134352_olink ┆ 3             ┆ -0.272098        ┆ 1.556659        │
└──────────────────┴───────────────────────┴───────────────┴──────────────────┴─────────────────┘