In [1]:
import polars as pl

In [2]:
a = pl.read_parquet('burdens_wes_loftee_hc.parquet')
a

shape: (469_835, 18_054)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ ENSG000001 ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ sample  │
│ 35424      ┆ 187569    ┆ 244025    ┆ 162959    ┆   ┆ 065559    ┆ 114346    ┆ 154217    ┆ ---     │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str     │
│ f32        ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ f32       ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 3468504 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1888842 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 3436434 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4103000 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4672695 │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4757082 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 5603185 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4722664 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4237956 │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2033950 │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [21]:
samples_file = "/home/dnanexus/regenie_files/scores_bgen_lofteeHC.sample"

samples = pl.read_csv(samples_file, separator=' ', skip_lines=2, ignore_errors=True, has_header=False, new_columns=['IID', 'FID', 'missing'])
samples

shape: (469_835, 3)
┌─────────┬─────────┬─────────┐
│ IID     ┆ FID     ┆ missing │
│ ---     ┆ ---     ┆ ---     │
│ i64     ┆ i64     ┆ i64     │
╞═════════╪═════════╪═════════╡
│ 3468504 ┆ 3468504 ┆ 0       │
│ 1888842 ┆ 1888842 ┆ 0       │
│ 3436434 ┆ 3436434 ┆ 0       │
│ 4103000 ┆ 4103000 ┆ 0       │
│ 4672695 ┆ 4672695 ┆ 0       │
│ …       ┆ …       ┆ …       │
│ 4757082 ┆ 4757082 ┆ 0       │
│ 5603185 ┆ 5603185 ┆ 0       │
│ 4722664 ┆ 4722664 ┆ 0       │
│ 4237956 ┆ 4237956 ┆ 0       │
│ 2033950 ┆ 2033950 ┆ 0       │
└─────────┴─────────┴─────────┘

## Phenotypes

In [15]:
p = pl.read_parquet('/home/dnanexus/data_dir/phenotypes/phenotypes190_missing20_unique2_int.parquet')
p

shape: (488_185, 192)
┌─────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ FID     ┆ IID     ┆ red_blood_ ┆ mean_plate ┆ … ┆ jurgens_he ┆ jurgens_p ┆ jurgens_e ┆ jurgens_b │
│ ---     ┆ ---     ┆ cell_eryth ┆ let_thromb ┆   ┆ art_failur ┆ rostate_c ┆ pilepsy   ┆ ladder_ca │
│ i32     ┆ i32     ┆ rocyte_dis ┆ ocyte_volu ┆   ┆ e          ┆ ancer     ┆ ---       ┆ ncer      │
│         ┆         ┆ …          ┆ …          ┆   ┆ ---        ┆ ---       ┆ f32       ┆ ---       │
│         ┆         ┆ ---        ┆ ---        ┆   ┆ f32        ┆ f32       ┆           ┆ f32       │
│         ┆         ┆ f32        ┆ f32        ┆   ┆            ┆           ┆           ┆           │
╞═════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ -244    ┆ -244    ┆ 0.31253    ┆ -0.570486  ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ -234    ┆ -234    ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ -229    ┆ -229    ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ -222    ┆ -222    ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ -210    ┆ -210    ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ …       ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 9999995 ┆ 9999995 ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9999996 ┆ 9999996 ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9999997 ┆ 9999997 ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9999998 ┆ 9999998 ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9999999 ┆ 9999999 ┆ NaN        ┆ NaN        ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
└─────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [24]:
p_new = (
    p
    .join(
        samples.select(['IID']), 
        on='IID', 
        how='semi'
    )
    .fill_nan('NA')
    .select([col for col in p.columns if not col.startswith('jurgens')])
)

p_new

shape: (469_382, 129)
┌─────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ FID     ┆ IID     ┆ red_blood_ ┆ mean_plate ┆ … ┆ glycated_h ┆ total_bil ┆ sitting_h ┆ platelet_ │
│ ---     ┆ ---     ┆ cell_eryth ┆ let_thromb ┆   ┆ aemoglobin ┆ irubin_in ┆ eight_int ┆ count_int │
│ i32     ┆ i32     ┆ rocyte_dis ┆ ocyte_volu ┆   ┆ _hba1c_int ┆ t         ┆ ---       ┆ ---       │
│         ┆         ┆ …          ┆ …          ┆   ┆ ---        ┆ ---       ┆ str       ┆ str       │
│         ┆         ┆ ---        ┆ ---        ┆   ┆ str        ┆ str       ┆           ┆           │
│         ┆         ┆ str        ┆ str        ┆   ┆            ┆           ┆           ┆           │
╞═════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1000018 ┆ 1000018 ┆ -0.523548  ┆ -1.1141539 ┆ … ┆ -2.503798  ┆ 0.6476316 ┆ 0.1919443 ┆ -0.341132 │
│         ┆         ┆            ┆            ┆   ┆            ┆ 5         ┆ 9         ┆ 34        │
│ 1000020 ┆ 1000020 ┆ 1.2978923  ┆ -0.2098895 ┆ … ┆ 0.4074728  ┆ -0.249384 ┆ 0.7730731 ┆ 0.2171490 │
│         ┆         ┆            ┆ 6          ┆   ┆            ┆ 16        ┆           ┆ 2         │
│ 1000037 ┆ 1000037 ┆ 0.8906152  ┆ 0.03680458 ┆ … ┆ -0.0107348 ┆ -0.843470 ┆ 1.8227332 ┆ 1.0203526 │
│         ┆         ┆            ┆ 7          ┆   ┆ 14         ┆ 93        ┆           ┆           │
│ 1000043 ┆ 1000043 ┆ -0.6857645 ┆ -1.0474743 ┆ … ┆ 0.2244514  ┆ -0.513805 ┆ -1.323158 ┆ 0.2283622 │
│         ┆         ┆ 5          ┆            ┆   ┆            ┆ 57        ┆ 9         ┆ 5         │
│ 1000051 ┆ 1000051 ┆ 0.00979701 ┆ 0.81824404 ┆ … ┆ 0.2244514  ┆ 0.3189802 ┆ 1.6067163 ┆ 0.7607273 │
│         ┆         ┆ 15         ┆            ┆   ┆            ┆ 5         ┆           ┆ 5         │
│ …       ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 6023653 ┆ 6023653 ┆ 1.8196217  ┆ -1.2386417 ┆ … ┆ 1.5705322  ┆ -0.703325 ┆ 1.1785145 ┆ 0.4912256 │
│         ┆         ┆            ┆            ┆   ┆            ┆ 6         ┆           ┆           │
│ 6023662 ┆ 6023662 ┆ -1.14969   ┆ 0.40342918 ┆ … ┆ 0.63022935 ┆ -0.947205 ┆ -0.002281 ┆ 0.3564073 │
│         ┆         ┆            ┆            ┆   ┆            ┆ 8         ┆ 0418      ┆           │
│ 6023671 ┆ 6023671 ┆ 0.455222   ┆ 0.21985576 ┆ … ┆ 0.19402264 ┆ 0.6637866 ┆ 1.3909836 ┆ 0.3838720 │
│         ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆ 3         │
│ 6023686 ┆ 6023686 ┆ 0.48322892 ┆ -0.8278841 ┆ … ┆ 1.3571942  ┆ -0.052216 ┆ 0.9720715 ┆ 0.5796124 │
│         ┆         ┆            ┆ 4          ┆   ┆            ┆ 17        ┆           ┆ 3         │
│ 6023704 ┆ 6023704 ┆ -1.0908942 ┆ 0.13441756 ┆ … ┆ -0.3722435 ┆ 0.6993432 ┆ -1.088254 ┆ 0.7178899 │
│         ┆         ┆            ┆            ┆   ┆ 8          ┆ 6         ┆ 8         ┆ 6         │
└─────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [26]:
p_new.write_csv('/home/dnanexus/regenie_files/quant_phenotypes129_missing20_int_regenie_caucasian.txt', separator=' ')

## Covariates

In [27]:
c = pl.read_csv('/home/dnanexus/data_dir/phenotypes/covariates_caucasian.txt', separator=' ')
c

shape: (445_014, 26)
┌─────────┬─────────┬───────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ FID     ┆ IID     ┆ age       ┆ age2      ┆ … ┆ genetic_PC ┆ genetic_PC ┆ genetic_PC ┆ genetic_P │
│ ---     ┆ ---     ┆ ---       ┆ ---       ┆   ┆ _17        ┆ _18        ┆ _19        ┆ C_20      │
│ i64     ┆ i64     ┆ f64       ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│         ┆         ┆           ┆           ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64       │
╞═════════╪═════════╪═══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 5262577 ┆ 5262577 ┆ -1.9202   ┆ -1.764284 ┆ … ┆ 0.320307   ┆ -2.093087  ┆ 0.35918    ┆ 1.577824  │
│ 2041866 ┆ 2041866 ┆ -1.302347 ┆ -1.278911 ┆ … ┆ 0.285821   ┆ 0.101211   ┆ 1.661634   ┆ -1.422016 │
│ 1293286 ┆ 1293286 ┆ -0.560924 ┆ -0.62282  ┆ … ┆ 0.389143   ┆ 0.004344   ┆ -0.07751   ┆ -0.283974 │
│ 2519258 ┆ 2519258 ┆ 1.045493  ┆ 1.074313  ┆ … ┆ -0.842587  ┆ 0.382721   ┆ 0.341772   ┆ 0.028906  │
│ 1546882 ┆ 1546882 ┆ -0.066642 ┆ -0.140794 ┆ … ┆ 1.08971    ┆ 0.91382    ┆ -0.112894  ┆ -1.563644 │
│ …       ┆ …       ┆ …         ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 5303814 ┆ 5303814 ┆ -0.066642 ┆ -0.140794 ┆ … ┆ -0.666749  ┆ -0.991172  ┆ -0.106864  ┆ 0.348586  │
│ 2387859 ┆ 2387859 ┆ 0.674781  ┆ 0.649193  ┆ … ┆ 1.051597   ┆ 0.799844   ┆ 0.713325   ┆ 1.423562  │
│ 2143691 ┆ 2143691 ┆ 0.42764   ┆ 0.376938  ┆ … ┆ -0.469564  ┆ -1.773185  ┆ -0.043424  ┆ -0.358034 │
│ 5051153 ┆ 5051153 ┆ -0.684494 ┆ -0.737747 ┆ … ┆ 0.935362   ┆ -0.204919  ┆ -0.768182  ┆ -2.02777  │
│ 5539809 ┆ 5539809 ┆ 1.292634  ┆ 1.368885  ┆ … ┆ 0.504097   ┆ -1.213539  ┆ 0.205611   ┆ -0.048935 │
└─────────┴─────────┴───────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘