In [1]:
import polars as pl

In [ ]:
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/sample_lists/unrelated_cauc_samples_3rd_degree.csv -o /home/dnanexus/data_dir/

In [4]:
eur_list = (
    pl.read_csv('/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv')
    .with_columns(
        SAMPLE = pl.col('eid').cast(pl.Utf8)
    )
    .select('SAMPLE')
)
eur_list

shape: (379_645, 1)
┌─────────┐
│ SAMPLE  │
│ ---     │
│ str     │
╞═════════╡
│ 1000020 │
│ 1000107 │
│ 1000161 │
│ 1000172 │
│ 1000221 │
│ …       │
│ 6023513 │
│ 6023597 │
│ 6023640 │
│ 6023671 │
│ 6023704 │
└─────────┘

In [3]:
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes.parquet -o /home/dnanexus/data_dir/

var_df = pl.scan_parquet("/home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes.parquet")
var_df.head().collect()

[===========================================================>] Completed 37,819,413,378 of 37,819,413,378 bytes (100%) /home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes.parquett                                                        ] Downloaded 503,316,480 of 37,819,413,378 bytes (1%) /home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes.parquet[=====================>                                      ] Downloaded 13,891,534,848 of 37,819,413,378 bytes (36%) /home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes.parquet[==========================>                                 ] Downloaded 16,710,107,136 of 37,819,413,378 bytes (44%) /home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes.parquet

shape: (5, 6)
┌───────┬──────────┬───────────┬─────┬─────────┬─────┐
│ CHROM ┆ POS      ┆ REF       ┆ ALT ┆ SAMPLE  ┆ GT  │
│ ---   ┆ ---      ┆ ---       ┆ --- ┆ ---     ┆ --- │
│ str   ┆ i64      ┆ str       ┆ str ┆ str     ┆ i8  │
╞═══════╪══════════╪═══════════╪═════╪═════════╪═════╡
│ chr10 ┆ 20020006 ┆ C         ┆ T   ┆ 5317620 ┆ 1   │
│ chr10 ┆ 20020007 ┆ TTTTCTTGC ┆ T   ┆ 5546988 ┆ 1   │
│ chr10 ┆ 20020010 ┆ T         ┆ C   ┆ 2793793 ┆ 1   │
│ chr10 ┆ 20020013 ┆ T         ┆ G   ┆ 1314475 ┆ 1   │
│ chr10 ┆ 20020014 ┆ G         ┆ A   ┆ 1722739 ┆ 1   │
└───────┴──────────┴───────────┴─────┴─────────┴─────┘

In [6]:
(
    var_df
    .join(
        eur_list.lazy(),
        on='SAMPLE',
        how='semi'
    )
    .sink_parquet("/home/dnanexus/data_dir/qced_maf1e-3_loftee_olink_genes_EUR.parquet", engine='streaming')
)