In [1]:
import polars as pl
import pandas as pd
import pyranges as pr

/opt/modules/i12g/anaconda/envs/sl-ukg/lib/python3.12/site-packages/sorted_nearest/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

## Polars only code

In [2]:
gtf_path = "/s/project/deeprvat/ukb_gym/gencode/gencode.v49.annotation.gtf.gz"

gtf_pl = pl.read_csv(
    gtf_path,
    separator="\t",
    comment_prefix="#",
    has_header=False,
    new_columns=["Chromosome", "source", "Feature", "Start", "End", "score", "Strand", "frame", "attributes"]
)

gtf_pl = gtf_pl.with_row_index("row_nr")
gtf_pl

shape: (7_750_154, 10)
┌─────────┬────────────┬─────────┬────────────┬───┬───────┬────────┬───────┬───────────────────────┐
│ row_nr  ┆ Chromosome ┆ source  ┆ Feature    ┆ … ┆ score ┆ Strand ┆ frame ┆ attributes            │
│ ---     ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---   ┆ ---    ┆ ---   ┆ ---                   │
│ u32     ┆ str        ┆ str     ┆ str        ┆   ┆ str   ┆ str    ┆ str   ┆ str                   │
╞═════════╪════════════╪═════════╪════════════╪═══╪═══════╪════════╪═══════╪═══════════════════════╡
│ 0       ┆ chr1       ┆ HAVANA  ┆ gene       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000290825.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ g…                    │
│ 1       ┆ chr1       ┆ HAVANA  ┆ transcript ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000290825.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 2       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000290825.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 3       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000290825.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 4       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000290825.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ …       ┆ …          ┆ …       ┆ …          ┆ … ┆ …     ┆ …      ┆ …     ┆ …                     │
│ 7750149 ┆ chrM       ┆ ENSEMBL ┆ transcript ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000210195.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 7750150 ┆ chrM       ┆ ENSEMBL ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000210195.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 7750151 ┆ chrM       ┆ ENSEMBL ┆ gene       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000210196.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ g…                    │
│ 7750152 ┆ chrM       ┆ ENSEMBL ┆ transcript ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000210196.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
│ 7750153 ┆ chrM       ┆ ENSEMBL ┆ exon       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id               │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000210196.2";  │
│         ┆            ┆         ┆            ┆   ┆       ┆        ┆       ┆ t…                    │
└─────────┴────────────┴─────────┴────────────┴───┴───────┴────────┴───────┴───────────────────────┘

In [3]:
atts = (
    gtf_pl.select("row_nr", "attributes")
    
    .with_columns(
        attrs_list=pl.col("attributes").str.split("; ")
    )
    .explode("attrs_list")
    
    .with_columns(
        pl.col("attrs_list")
        .str.split_exact(" ", 1)
        .struct.rename_fields(["attribute", "value"])
        .alias("fields")
    ).unnest("fields")

    .with_columns(
        pl.col("value").str.strip_chars('"')
    )

    .pivot(
        index="row_nr",
        on="attribute",
        values="value",
        aggregate_function=pl.element().implode()
    )

    .with_columns(
        pl.col(pl.List).list.join(", ").str.strip_chars(";").replace("", None)
    )

    .with_columns(
        level = pl.col('level').cast(pl.Int32),
        exon_number = pl.col('exon_number').cast(pl.Int32),
    )
)

atts

shape: (7_750_154, 19)
┌─────────┬──────────────────┬───────────┬───────────┬───┬──────┬────────────┬────────┬────────────┐
│ row_nr  ┆ gene_id          ┆ gene_type ┆ gene_name ┆ … ┆ ont  ┆ protein_id ┆ ccdsid ┆ artif_dupl │
│ ---     ┆ ---              ┆ ---       ┆ ---       ┆   ┆ ---  ┆ ---        ┆ ---    ┆ ---        │
│ u32     ┆ str              ┆ str       ┆ str       ┆   ┆ str  ┆ str        ┆ str    ┆ str        │
╞═════════╪══════════════════╪═══════════╪═══════════╪═══╪══════╪════════════╪════════╪════════════╡
│ 0       ┆ ENSG00000290825. ┆ lncRNA    ┆ DDX11L16  ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 1       ┆ ENSG00000290825. ┆ lncRNA    ┆ DDX11L16  ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 2       ┆ ENSG00000290825. ┆ lncRNA    ┆ DDX11L16  ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 3       ┆ ENSG00000290825. ┆ lncRNA    ┆ DDX11L16  ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 4       ┆ ENSG00000290825. ┆ lncRNA    ┆ DDX11L16  ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ …       ┆ …                ┆ …         ┆ …         ┆ … ┆ …    ┆ …          ┆ …      ┆ …          │
│ 7750149 ┆ ENSG00000210195. ┆ Mt_tRNA   ┆ MT-TT     ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 7750150 ┆ ENSG00000210195. ┆ Mt_tRNA   ┆ MT-TT     ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 7750151 ┆ ENSG00000210196. ┆ Mt_tRNA   ┆ MT-TP     ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 7750152 ┆ ENSG00000210196. ┆ Mt_tRNA   ┆ MT-TP     ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
│ 7750153 ┆ ENSG00000210196. ┆ Mt_tRNA   ┆ MT-TP     ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│         ┆ 2                ┆           ┆           ┆   ┆      ┆            ┆        ┆            │
└─────────┴──────────────────┴───────────┴───────────┴───┴──────┴────────────┴────────┴────────────┘

In [4]:
gtf_exp = gtf_pl.join(atts, on='row_nr')
gtf_exp

shape: (7_750_154, 28)
┌─────────┬────────────┬─────────┬────────────┬───┬──────┬────────────┬────────┬────────────┐
│ row_nr  ┆ Chromosome ┆ source  ┆ Feature    ┆ … ┆ ont  ┆ protein_id ┆ ccdsid ┆ artif_dupl │
│ ---     ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---  ┆ ---        ┆ ---    ┆ ---        │
│ u32     ┆ str        ┆ str     ┆ str        ┆   ┆ str  ┆ str        ┆ str    ┆ str        │
╞═════════╪════════════╪═════════╪════════════╪═══╪══════╪════════════╪════════╪════════════╡
│ 0       ┆ chr1       ┆ HAVANA  ┆ gene       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 1       ┆ chr1       ┆ HAVANA  ┆ transcript ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 2       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 3       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 4       ┆ chr1       ┆ HAVANA  ┆ exon       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ …       ┆ …          ┆ …       ┆ …          ┆ … ┆ …    ┆ …          ┆ …      ┆ …          │
│ 7750149 ┆ chrM       ┆ ENSEMBL ┆ transcript ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 7750150 ┆ chrM       ┆ ENSEMBL ┆ exon       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 7750151 ┆ chrM       ┆ ENSEMBL ┆ gene       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 7750152 ┆ chrM       ┆ ENSEMBL ┆ transcript ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ 7750153 ┆ chrM       ┆ ENSEMBL ┆ exon       ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
└─────────┴────────────┴─────────┴────────────┴───┴──────┴────────────┴────────┴────────────┘

In [5]:
a = gtf_exp['gene_type'].value_counts(sort=True)
a

shape: (37, 2)
┌─────────────────────────────────┬─────────┐
│ gene_type                       ┆ count   │
│ ---                             ┆ ---     │
│ str                             ┆ u32     │
╞═════════════════════════════════╪═════════╡
│ protein_coding                  ┆ 6731674 │
│ lncRNA                          ┆ 932062  │
│ processed_pseudogene            ┆ 29949   │
│ transcribed_unprocessed_pseudo… ┆ 12212   │
│ unprocessed_pseudogene          ┆ 8511    │
│ …                               ┆ …       │
│ TR_J_pseudogene                 ┆ 12      │
│ IG_J_pseudogene                 ┆ 9       │
│ translated_processed_pseudogen… ┆ 8       │
│ Mt_rRNA                         ┆ 6       │
│ IG_pseudogene                   ┆ 3       │
└─────────────────────────────────┴─────────┘

In [6]:
mane_exons = (
    gtf_exp
    .filter(
        (pl.col('gene_type') == 'protein_coding') |
        (pl.col('gene_type').str.contains('pseudogene')) |
        (pl.col('Feature') == 'CDS')
    )
    .filter(pl.col('Feature') != 'transcript')
    .filter(pl.col('tag').str.contains('MANE_Select'))
)

mane_exons

shape: (480_590, 28)
┌─────────┬────────────┬────────┬─────────────┬───┬──────┬──────────────┬─────────────┬────────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature     ┆ … ┆ ont  ┆ protein_id   ┆ ccdsid      ┆ artif_dupl │
│ ---     ┆ ---        ┆ ---    ┆ ---         ┆   ┆ ---  ┆ ---          ┆ ---         ┆ ---        │
│ u32     ┆ str        ┆ str    ┆ str         ┆   ┆ str  ┆ str          ┆ str         ┆ str        │
╞═════════╪════════════╪════════╪═════════════╪═══╪══════╪══════════════╪═════════════╪════════════╡
│ 2488    ┆ chr1       ┆ HAVANA ┆ exon        ┆ … ┆ null ┆ ENSP00000493 ┆ CCDS30547.2 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 376.2        ┆             ┆            │
│ 2489    ┆ chr1       ┆ HAVANA ┆ exon        ┆ … ┆ null ┆ ENSP00000493 ┆ CCDS30547.2 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 376.2        ┆             ┆            │
│ 2490    ┆ chr1       ┆ HAVANA ┆ CDS         ┆ … ┆ null ┆ ENSP00000493 ┆ CCDS30547.2 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 376.2        ┆             ┆            │
│ 2491    ┆ chr1       ┆ HAVANA ┆ start_codon ┆ … ┆ null ┆ ENSP00000493 ┆ CCDS30547.2 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 376.2        ┆             ┆            │
│ 2492    ┆ chr1       ┆ HAVANA ┆ exon        ┆ … ┆ null ┆ ENSP00000493 ┆ CCDS30547.2 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 376.2        ┆             ┆            │
│ …       ┆ …          ┆ …      ┆ …           ┆ … ┆ …    ┆ …            ┆ …           ┆ …          │
│ 7749027 ┆ chrY       ┆ HAVANA ┆ exon        ┆ … ┆ null ┆ ENSP00000302 ┆ CCDS14801.1 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 968.4        ┆             ┆            │
│ 7749028 ┆ chrY       ┆ HAVANA ┆ CDS         ┆ … ┆ null ┆ ENSP00000302 ┆ CCDS14801.1 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 968.4        ┆             ┆            │
│ 7749029 ┆ chrY       ┆ HAVANA ┆ stop_codon  ┆ … ┆ null ┆ ENSP00000302 ┆ CCDS14801.1 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 968.4        ┆             ┆            │
│ 7749030 ┆ chrY       ┆ HAVANA ┆ UTR         ┆ … ┆ null ┆ ENSP00000302 ┆ CCDS14801.1 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 968.4        ┆             ┆            │
│ 7749031 ┆ chrY       ┆ HAVANA ┆ UTR         ┆ … ┆ null ┆ ENSP00000302 ┆ CCDS14801.1 ┆ null       │
│         ┆            ┆        ┆             ┆   ┆      ┆ 968.4        ┆             ┆            │
└─────────┴────────────┴────────┴─────────────┴───┴──────┴──────────────┴─────────────┴────────────┘

In [7]:
# One transcript per gene
mane_exons[['gene_id', 'gene_name', 'transcript_id']].unique()['transcript_id'].value_counts(sort=True)

shape: (19_226, 2)
┌───────────────────┬───────┐
│ transcript_id     ┆ count │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ ENST00000644903.1 ┆ 1     │
│ ENST00000646101.2 ┆ 1     │
│ ENST00000332853.9 ┆ 1     │
│ ENST00000629482.3 ┆ 1     │
│ ENST00000639785.2 ┆ 1     │
│ …                 ┆ …     │
│ ENST00000396403.9 ┆ 1     │
│ ENST00000302917.1 ┆ 1     │
│ ENST00000262215.8 ┆ 1     │
│ ENST00000529859.2 ┆ 1     │
│ ENST00000397583.8 ┆ 1     │
└───────────────────┴───────┘

In [8]:
a = mane_exons['gene_type'].value_counts(sort=True)
a

shape: (1, 2)
┌────────────────┬────────┐
│ gene_type      ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ protein_coding ┆ 480590 │
└────────────────┴────────┘

In [9]:
b = mane_exons['Feature'].value_counts(sort=True)
b

shape: (6, 2)
┌────────────────┬────────┐
│ Feature        ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ exon           ┆ 202056 │
│ CDS            ┆ 191762 │
│ UTR            ┆ 48232  │
│ start_codon    ┆ 19259  │
│ stop_codon     ┆ 19245  │
│ Selenocysteine ┆ 36     │
└────────────────┴────────┘

In [10]:
non_mane_exons = (
    gtf_exp
    .filter(
        (pl.col('gene_type') == 'protein_coding') |
        (pl.col('gene_type').str.contains('pseudogene')) |
        (pl.col('Feature') == 'CDS')
    )
    .filter(pl.col('Feature') != 'transcript')
    .filter(~pl.col('tag').str.contains('MANE_Select'))
)

non_mane_exons

shape: (5_548_804, 28)
┌─────────┬────────────┬─────────┬─────────────┬───┬────────────┬────────────┬────────┬────────────┐
│ row_nr  ┆ Chromosome ┆ source  ┆ Feature     ┆ … ┆ ont        ┆ protein_id ┆ ccdsid ┆ artif_dupl │
│ ---     ┆ ---        ┆ ---     ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---    ┆ ---        │
│ u32     ┆ str        ┆ str     ┆ str         ┆   ┆ str        ┆ str        ┆ str    ┆ str        │
╞═════════╪════════════╪═════════╪═════════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ 126     ┆ chr1       ┆ HAVANA  ┆ exon        ┆ … ┆ PGO:000000 ┆ null       ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆ 5, PGO:000 ┆            ┆        ┆            │
│         ┆            ┆         ┆             ┆   ┆ 0019       ┆            ┆        ┆            │
│ 127     ┆ chr1       ┆ HAVANA  ┆ exon        ┆ … ┆ PGO:000000 ┆ null       ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆ 5, PGO:000 ┆            ┆        ┆            │
│         ┆            ┆         ┆             ┆   ┆ 0019       ┆            ┆        ┆            │
│ 128     ┆ chr1       ┆ HAVANA  ┆ exon        ┆ … ┆ PGO:000000 ┆ null       ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆ 5, PGO:000 ┆            ┆        ┆            │
│         ┆            ┆         ┆             ┆   ┆ 0019       ┆            ┆        ┆            │
│ 129     ┆ chr1       ┆ HAVANA  ┆ exon        ┆ … ┆ PGO:000000 ┆ null       ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆ 5, PGO:000 ┆            ┆        ┆            │
│         ┆            ┆         ┆             ┆   ┆ 0019       ┆            ┆        ┆            │
│ 130     ┆ chr1       ┆ HAVANA  ┆ exon        ┆ … ┆ PGO:000000 ┆ null       ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆ 5, PGO:000 ┆            ┆        ┆            │
│         ┆            ┆         ┆             ┆   ┆ 0019       ┆            ┆        ┆            │
│ …       ┆ …          ┆ …       ┆ …           ┆ … ┆ …          ┆ …          ┆ …      ┆ …          │
│ 7750138 ┆ chrM       ┆ ENSEMBL ┆ CDS         ┆ … ┆ null       ┆ ENSP000003 ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆            ┆ 54665.2    ┆        ┆            │
│ 7750139 ┆ chrM       ┆ ENSEMBL ┆ start_codon ┆ … ┆ null       ┆ ENSP000003 ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆            ┆ 54665.2    ┆        ┆            │
│ 7750145 ┆ chrM       ┆ ENSEMBL ┆ exon        ┆ … ┆ null       ┆ ENSP000003 ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆            ┆ 54554.2    ┆        ┆            │
│ 7750146 ┆ chrM       ┆ ENSEMBL ┆ CDS         ┆ … ┆ null       ┆ ENSP000003 ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆            ┆ 54554.2    ┆        ┆            │
│ 7750147 ┆ chrM       ┆ ENSEMBL ┆ start_codon ┆ … ┆ null       ┆ ENSP000003 ┆ null   ┆ null       │
│         ┆            ┆         ┆             ┆   ┆            ┆ 54554.2    ┆        ┆            │
└─────────┴────────────┴─────────┴─────────────┴───┴────────────┴────────────┴────────┴────────────┘

In [11]:
non_mane_exons[['gene_id', 'gene_name', 'transcript_id']].unique()['transcript_id'].value_counts(sort=True)

shape: (234_396, 2)
┌───────────────────┬───────┐
│ transcript_id     ┆ count │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ null              ┆ 17373 │
│ ENST00000941635.1 ┆ 1     │
│ ENST00000597853.5 ┆ 1     │
│ ENST00000375375.7 ┆ 1     │
│ ENST00000686988.1 ┆ 1     │
│ …                 ┆ …     │
│ ENST00000457574.1 ┆ 1     │
│ ENST00000966798.1 ┆ 1     │
│ ENST00000967079.1 ┆ 1     │
│ ENST00000627895.2 ┆ 1     │
│ ENST00000893054.1 ┆ 1     │
└───────────────────┴───────┘

In [12]:
non_mane_cds = non_mane_exons.filter(pl.col('Feature') == 'CDS')

non_mane_exonic = non_mane_exons.filter(pl.col('Feature') == 'exon')
non_mane_exonic

shape: (2_453_590, 28)
┌─────────┬────────────┬─────────┬─────────┬───┬──────────────┬──────────────┬────────┬────────────┐
│ row_nr  ┆ Chromosome ┆ source  ┆ Feature ┆ … ┆ ont          ┆ protein_id   ┆ ccdsid ┆ artif_dupl │
│ ---     ┆ ---        ┆ ---     ┆ ---     ┆   ┆ ---          ┆ ---          ┆ ---    ┆ ---        │
│ u32     ┆ str        ┆ str     ┆ str     ┆   ┆ str          ┆ str          ┆ str    ┆ str        │
╞═════════╪════════════╪═════════╪═════════╪═══╪══════════════╪══════════════╪════════╪════════════╡
│ 126     ┆ chr1       ┆ HAVANA  ┆ exon    ┆ … ┆ PGO:0000005, ┆ null         ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆ PGO:0000019  ┆              ┆        ┆            │
│ 127     ┆ chr1       ┆ HAVANA  ┆ exon    ┆ … ┆ PGO:0000005, ┆ null         ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆ PGO:0000019  ┆              ┆        ┆            │
│ 128     ┆ chr1       ┆ HAVANA  ┆ exon    ┆ … ┆ PGO:0000005, ┆ null         ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆ PGO:0000019  ┆              ┆        ┆            │
│ 129     ┆ chr1       ┆ HAVANA  ┆ exon    ┆ … ┆ PGO:0000005, ┆ null         ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆ PGO:0000019  ┆              ┆        ┆            │
│ 130     ┆ chr1       ┆ HAVANA  ┆ exon    ┆ … ┆ PGO:0000005, ┆ null         ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆ PGO:0000019  ┆              ┆        ┆            │
│ …       ┆ …          ┆ …       ┆ …       ┆ … ┆ …            ┆ …            ┆ …      ┆ …          │
│ 7750110 ┆ chrM       ┆ ENSEMBL ┆ exon    ┆ … ┆ null         ┆ ENSP00000354 ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆              ┆ 728.1        ┆        ┆            │
│ 7750117 ┆ chrM       ┆ ENSEMBL ┆ exon    ┆ … ┆ null         ┆ ENSP00000354 ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆              ┆ 961.2        ┆        ┆            │
│ 7750131 ┆ chrM       ┆ ENSEMBL ┆ exon    ┆ … ┆ null         ┆ ENSP00000354 ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆              ┆ 813.2        ┆        ┆            │
│ 7750137 ┆ chrM       ┆ ENSEMBL ┆ exon    ┆ … ┆ null         ┆ ENSP00000354 ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆              ┆ 665.2        ┆        ┆            │
│ 7750145 ┆ chrM       ┆ ENSEMBL ┆ exon    ┆ … ┆ null         ┆ ENSP00000354 ┆ null   ┆ null       │
│         ┆            ┆         ┆         ┆   ┆              ┆ 554.2        ┆        ┆            │
└─────────┴────────────┴─────────┴─────────┴───┴──────────────┴──────────────┴────────┴────────────┘

### Convert regions to pyranges

In [13]:
mane_exons_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'exon').to_pandas()).merge()
mane_exons_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 65419     | 65433     | +            |
| chr1         | 65520     | 65573     | +            |
| chr1         | 69037     | 71585     | +            |
| chr1         | 923923    | 924948    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 25043946  | 25044064  | -            |
| chrY         | 25048474  | 25048610  | -            |
| chrY         | 25051676  | 25051798  | -            |
| chrY         | 25052074  | 25052104  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 201,732 rows and 4 columns from 24 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [14]:
mane_cds_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'CDS').to_pandas()).merge()
mane_utr_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'UTR').to_pandas()).merge()

mane_cds_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 65565     | 65573     | +            |
| chr1         | 69037     | 70005     | +            |
| chr1         | 924432    | 924948    | +            |
| chr1         | 925922    | 926013    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 25038101  | 25038116  | -            |
| chrY         | 25038809  | 25038914  | -            |
| chrY         | 25041769  | 25041886  | -            |
| chrY         | 25043946  | 25044023  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 191,598 rows and 4 columns from 24 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [15]:
non_mane_exons_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'exon').to_pandas()).merge()
non_mane_exons_pr = non_mane_exons_pr.subtract(mane_exons_pr)
non_mane_exons_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 12010     | 12057     | +            |
| chr1         | 12179     | 12227     | +            |
| chr1         | 12613     | 12697     | +            |
| chr1         | 12975     | 13052     | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 57213204  | 57213357  | -            |
| chrY         | 57213526  | 57213602  | -            |
| chrY         | 57213880  | 57213964  | -            |
| chrY         | 57214350  | 57214397  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 125,096 rows and 4 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [16]:
non_mane_cds_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'CDS').to_pandas()).merge()
non_mane_cds_pr = non_mane_cds_pr.subtract(mane_cds_pr)

non_mane_utr_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'UTR').to_pandas()).merge()
non_mane_utr_pr = non_mane_utr_pr.subtract(mane_utr_pr)

non_mane_cds_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 939272    | 939275    | +            |
| chr1         | 939412    | 939460    | +            |
| chr1         | 943808    | 943908    | +            |
| chr1         | 962286    | 962355    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 18770183  | 18770292  | -            |
| chrY         | 19723341  | 19723433  | -            |
| chrY         | 19741300  | 19741318  | -            |
| chrY         | 24045607  | 24045676  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 39,582 rows and 4 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

### Annotate UKBBGym variants

In [17]:
anno = (
    pl.read_parquet(
        '/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_genocode_251103.parquet', 
        columns=['id', 'chrom', 'pos', 'ref', 'alt', 'gene']
    )
    .with_columns(
        Chromosome = pl.col('chrom'),
        Start = pl.col('pos') - 1,
        End = pl.col('pos') - 1 + pl.col('ref').str.len_chars()
    )
    .select(['id', 'Chromosome', 'Start', 'End', 'ref', 'alt', 'gene'])
)

anno_pr = pr.PyRanges(anno.to_pandas())
anno_pr

+------------------------+--------------+-----------+-----------+-------+
| id                     | Chromosome   | Start     | End       | +3    |
| (object)               | (category)   | (int64)   | (int64)   | ...   |
|------------------------+--------------+-----------+-----------+-------|
| chr1:214626910:A:G     | chr1         | 214626909 | 214626910 | ...   |
| chr1:21556831:T:G      | chr1         | 21556830  | 21556831  | ...   |
| chr1:21569280:C:A      | chr1         | 21569279  | 21569280  | ...   |
| chr1:21556795:T:C      | chr1         | 21556794  | 21556795  | ...   |
| ...                    | ...          | ...       | ...       | ...   |
| chr22:36919903:GCATA:G | chr22        | 36919902  | 36919907  | ...   |
| chr22:41102783:GT:G    | chr22        | 41102782  | 41102784  | ...   |
| chr22:24508167:ATC:A   | chr22        | 24508166  | 24508169  | ...   |
| chr22:41106250:GT:G    | chr22        | 41106249  | 41106251  | ...   |
+------------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 25,373,677 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [18]:
mane_exons_pr_vars = anno_pr.overlap(mane_exons_pr)#.df['gene'].value_counts()
mane_cds_pr_vars = anno_pr.overlap(mane_cds_pr)
mane_utr_pr_vars = anno_pr.overlap(mane_utr_pr)

mane_cds_pr_vars

+-----------------------+--------------+-----------+-----------+-------+
| id                    | Chromosome   | Start     | End       | +3    |
| (object)              | (category)   | (int64)   | (int64)   | ...   |
|-----------------------+--------------+-----------+-----------+-------|
| chr1:214646777:A:G    | chr1         | 214646776 | 214646777 | ...   |
| chr1:214655398:A:G    | chr1         | 214655397 | 214655398 | ...   |
| chr1:214646100:C:A    | chr1         | 214646099 | 214646100 | ...   |
| chr1:21554093:A:G     | chr1         | 21554092  | 21554093  | ...   |
| ...                   | ...          | ...       | ...       | ...   |
| chr22:20787014:G:GC   | chr22        | 20787013  | 20787014  | ...   |
| chr22:36285713:T:TC   | chr22        | 36285712  | 36285713  | ...   |
| chr22:28687932:TG:T   | chr22        | 28687931  | 28687933  | ...   |
| chr22:36305032:CCAT:C | chr22        | 36305031  | 36305035  | ...   |
+-----------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 784,690 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [19]:
# Convert to polars and add MANE / non-MANE flags

non_mane_exons_pr_vars = anno_pr.overlap(non_mane_exons_pr)
non_mane_cds_pr_vars = anno_pr.overlap(non_mane_cds_pr)
non_mane_utr_pr_vars = anno_pr.overlap(non_mane_utr_pr)

non_mane_cds_pr_vars

+----------------------+--------------+-----------+-----------+-------+
| id                   | Chromosome   | Start     | End       | +3    |
| (object)             | (category)   | (int64)   | (int64)   | ...   |
|----------------------+--------------+-----------+-----------+-------|
| chr1:198256393:C:T   | chr1         | 198256392 | 198256393 | ...   |
| chr1:21547457:C:T    | chr1         | 21547456  | 21547457  | ...   |
| chr1:21547499:T:G    | chr1         | 21547498  | 21547499  | ...   |
| chr1:198277942:A:T   | chr1         | 198277941 | 198277942 | ...   |
| ...                  | ...          | ...       | ...       | ...   |
| chr22:37084218:A:AG  | chr22        | 37084217  | 37084218  | ...   |
| chr22:40847996:G:GA  | chr22        | 40847995  | 40847996  | ...   |
| chr22:24502475:CT:C  | chr22        | 24502474  | 24502476  | ...   |
| chr22:17773679:C:CCG | chr22        | 17773678  | 17773679  | ...   |
+----------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 59,861 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [20]:
# Convert to polars and add MANE / non-MANE flags

mane_exons_pl = pl.from_pandas(mane_exons_pr_vars.df).with_columns(MANE_exonic = True).select(['id', 'gene', 'MANE_exonic'])
mane_cds_pl = pl.from_pandas(mane_cds_pr_vars.df).with_columns(MANE_CDS = True).select(['id', 'gene', 'MANE_CDS'])
mane_utr_pl = pl.from_pandas(mane_utr_pr_vars.df).with_columns(MANE_UTR = True).select(['id', 'gene', 'MANE_UTR'])

non_mane_exons_pl = pl.from_pandas(non_mane_exons_pr_vars.df).with_columns(non_MANE_exonic = True).select(['id', 'gene', 'non_MANE_exonic'])
non_mane_cds_pl = pl.from_pandas(non_mane_cds_pr_vars.df).with_columns(non_MANE_CDS = True).select(['id', 'gene', 'non_MANE_CDS'])
non_mane_utr_pl = pl.from_pandas(non_mane_utr_pr_vars.df).with_columns(non_MANE_UTR = True).select(['id', 'gene', 'non_MANE_UTR'])

non_mane_exons_pl

shape: (692_546, 3)
┌─────────────────────────────────┬─────────────────┬─────────────────┐
│ id                              ┆ gene            ┆ non_MANE_exonic │
│ ---                             ┆ ---             ┆ ---             │
│ str                             ┆ str             ┆ bool            │
╞═════════════════════════════════╪═════════════════╪═════════════════╡
│ chr1:214652675:C:T              ┆ ENSG00000117724 ┆ true            │
│ chr1:198256393:C:T              ┆ ENSG00000151414 ┆ true            │
│ chr1:214608779:C:T              ┆ ENSG00000117724 ┆ true            │
│ chr1:198221715:T:A              ┆ ENSG00000151414 ┆ true            │
│ chr1:198198084:G:C              ┆ ENSG00000151414 ┆ true            │
│ …                               ┆ …               ┆ …               │
│ chr22:24495324:C:CGGGCCTGGGCGC… ┆ ENSG00000100024 ┆ true            │
│ chr22:36325562:CCAA:C           ┆ ENSG00000100345 ┆ true            │
│ chr22:17750219:T:TG             ┆ ENSG00000015475 ┆ true            │
│ chr22:28738166:CTG:C            ┆ ENSG00000183765 ┆ true            │
│ chr22:17093668:AGGTAAC:A        ┆ ENSG00000177663 ┆ true            │
└─────────────────────────────────┴─────────────────┴─────────────────┘

### Merge with annotations df

In [21]:
vep_CDS = [
    'consequence_coding_sequence_variant',
    'consequence_frameshift_variant',
    'consequence_inframe_deletion',
    'consequence_inframe_insertion',
    'consequence_missense_variant',
    'consequence_protein_altering_variant',
    'consequence_start_lost',
    'consequence_start_retained_variant',
    'consequence_stop_gained',
    'consequence_stop_lost',
    'consequence_stop_retained_variant',
    'consequence_synonymous_variant',
    'consequence_splice_acceptor_variant',
    'consequence_splice_donor_variant',
    # 'consequence_nmd_transcript_variant',
]

In [22]:
anno = pl.read_parquet('/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_genocode_251103.parquet').drop(['vep_coding', 'gencode_non_coding', 'vep_gencode_non_coding'])

anno

shape: (25_373_677, 386)
┌───────┬───────────┬─────────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ chrom ┆ pos       ┆ ref         ┆ alt ┆ … ┆ promoterai_ ┆ promoterai_ ┆ promoterai_ ┆ gpn_star_l │
│ ---   ┆ ---       ┆ ---         ┆ --- ┆   ┆ abs         ┆ over        ┆ under       ┆ lr_calibra │
│ str   ┆ i32       ┆ str         ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ted_mean   │
│       ┆           ┆             ┆     ┆   ┆ f32         ┆ f32         ┆ f32         ┆ ---        │
│       ┆           ┆             ┆     ┆   ┆             ┆             ┆             ┆ f64        │
╞═══════╪═══════════╪═════════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ chr2  ┆ 169197167 ┆ T           ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.153293   │
│ chr2  ┆ 169204292 ┆ A           ┆ T   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 1.684965   │
│ chr2  ┆ 169030531 ┆ C           ┆ T   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ -1.212965  │
│ chr2  ┆ 168910825 ┆ T           ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ -1.479978  │
│ chr2  ┆ 168969544 ┆ T           ┆ C   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ -2.904763  │
│ …     ┆ …         ┆ …           ┆ …   ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ chr15 ┆ 34974609  ┆ ACTTCT      ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ null       │
│ chr9  ┆ 132358570 ┆ C           ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ -1.033277  │
│ chr8  ┆ 13200986  ┆ C           ┆ CA  ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ null       │
│ chr12 ┆ 122065447 ┆ G           ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ -2.975401  │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTT ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ null       │
│       ┆           ┆ GTTTTGTTTTG ┆     ┆   ┆             ┆             ┆             ┆            │
│       ┆           ┆ TTTT        ┆     ┆   ┆             ┆             ┆             ┆            │
└───────┴───────────┴─────────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [23]:
# Merge all MANE and non-MANE annotations

mane_annos = (
    anno[['id', 'gene']]
    .join(mane_exons_pl, on=['id', 'gene'], how='left')
    .join(mane_cds_pl, on=['id', 'gene'], how='left')
    .join(mane_utr_pl, on=['id', 'gene'], how='left')
    .join(non_mane_exons_pl, on=['id', 'gene'], how='left')
    .join(non_mane_cds_pl, on=['id', 'gene'], how='left')
    .join(non_mane_utr_pl, on=['id', 'gene'], how='left')

    .fill_null(False)
)

mane_annos

shape: (25_373_677, 8)
┌────────────┬────────────┬────────────┬──────────┬──────────┬────────────┬────────────┬───────────┐
│ id         ┆ gene       ┆ MANE_exoni ┆ MANE_CDS ┆ MANE_UTR ┆ non_MANE_e ┆ non_MANE_C ┆ non_MANE_ │
│ ---        ┆ ---        ┆ c          ┆ ---      ┆ ---      ┆ xonic      ┆ DS         ┆ UTR       │
│ str        ┆ str        ┆ ---        ┆ bool     ┆ bool     ┆ ---        ┆ ---        ┆ ---       │
│            ┆            ┆ bool       ┆          ┆          ┆ bool       ┆ bool       ┆ bool      │
╞════════════╪════════════╪════════════╪══════════╪══════════╪════════════╪════════════╪═══════════╡
│ chr2:16919 ┆ ENSG000000 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 7167:T:G   ┆ 81479      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr2:16920 ┆ ENSG000000 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 4292:A:T   ┆ 81479      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr2:16903 ┆ ENSG000000 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 0531:C:T   ┆ 73734      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr2:16891 ┆ ENSG000000 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 0825:T:G   ┆ 73734      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr2:16896 ┆ ENSG000000 ┆ true       ┆ true     ┆ false    ┆ false      ┆ false      ┆ true      │
│ 9544:T:C   ┆ 73734      ┆            ┆          ┆          ┆            ┆            ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …        ┆ …          ┆ …          ┆ …         │
│ chr15:3497 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 4609:ACTTC ┆ 98146      ┆            ┆          ┆          ┆            ┆            ┆           │
│ T:A        ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr9:13235 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 8570:C:A   ┆ 07290      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr8:13200 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 986:C:CA   ┆ 64741      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr12:1220 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 65447:G:A  ┆ 10987      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr5:18032 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 1761:GGTTT ┆ 31459      ┆            ┆          ┆          ┆            ┆            ┆           │
│ TGTTTTGTTT ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ …          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
└────────────┴────────────┴────────────┴──────────┴──────────┴────────────┴────────────┴───────────┘

In [24]:
final_annos = (
    anno
    .join(mane_annos, on=['id', 'gene'], how='left')
    .with_columns(
        VEP_CDS = pl.sum_horizontal(vep_CDS) > 0,
    )
)

final_annos.write_parquet('/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_MANE_251104.parquet')
final_annos

shape: (25_373_677, 393)
┌───────┬───────────┬──────────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────┐
│ chrom ┆ pos       ┆ ref          ┆ alt ┆ … ┆ non_MANE_exo ┆ non_MANE_CDS ┆ non_MANE_UT ┆ VEP_CDS │
│ ---   ┆ ---       ┆ ---          ┆ --- ┆   ┆ nic          ┆ ---          ┆ R           ┆ ---     │
│ str   ┆ i32       ┆ str          ┆ str ┆   ┆ ---          ┆ bool         ┆ ---         ┆ bool    │
│       ┆           ┆              ┆     ┆   ┆ bool         ┆              ┆ bool        ┆         │
╞═══════╪═══════════╪══════════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════╡
│ chr2  ┆ 169197167 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169204292 ┆ A            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169030531 ┆ C            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168910825 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168969544 ┆ T            ┆ C   ┆ … ┆ false        ┆ false        ┆ true        ┆ true    │
│ …     ┆ …         ┆ …            ┆ …   ┆ … ┆ …            ┆ …            ┆ …           ┆ …       │
│ chr15 ┆ 34974609  ┆ ACTTCT       ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr9  ┆ 132358570 ┆ C            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr8  ┆ 13200986  ┆ C            ┆ CA  ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr12 ┆ 122065447 ┆ G            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTTG ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│       ┆           ┆ TTTTGTTTTGTT ┆     ┆   ┆              ┆              ┆             ┆         │
│       ┆           ┆ TT           ┆     ┆   ┆              ┆              ┆             ┆         │
└───────┴───────────┴──────────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────┘

## Debugging

In [2]:
final_annos = pl.read_parquet('/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_MANE_251104.parquet')
final_annos

shape: (25_373_677, 393)
┌───────┬───────────┬──────────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────┐
│ chrom ┆ pos       ┆ ref          ┆ alt ┆ … ┆ non_MANE_exo ┆ non_MANE_CDS ┆ non_MANE_UT ┆ VEP_CDS │
│ ---   ┆ ---       ┆ ---          ┆ --- ┆   ┆ nic          ┆ ---          ┆ R           ┆ ---     │
│ str   ┆ i32       ┆ str          ┆ str ┆   ┆ ---          ┆ bool         ┆ ---         ┆ bool    │
│       ┆           ┆              ┆     ┆   ┆ bool         ┆              ┆ bool        ┆         │
╞═══════╪═══════════╪══════════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════╡
│ chr2  ┆ 169197167 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169204292 ┆ A            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169030531 ┆ C            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168910825 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168969544 ┆ T            ┆ C   ┆ … ┆ false        ┆ false        ┆ true        ┆ true    │
│ …     ┆ …         ┆ …            ┆ …   ┆ … ┆ …            ┆ …            ┆ …           ┆ …       │
│ chr15 ┆ 34974609  ┆ ACTTCT       ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr9  ┆ 132358570 ┆ C            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr8  ┆ 13200986  ┆ C            ┆ CA  ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr12 ┆ 122065447 ┆ G            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTTG ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│       ┆           ┆ TTTTGTTTTGTT ┆     ┆   ┆              ┆              ┆             ┆         │
│       ┆           ┆ TT           ┆     ┆   ┆              ┆              ┆             ┆         │
└───────┴───────────┴──────────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────┘

In [3]:
final_annos.filter(
    pl.col('VEP_CDS') == (pl.col('MANE_CDS')) # | pl.col('non_MANE_CDS'))
)

shape: (25_186_390, 393)
┌───────┬───────────┬──────────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────┐
│ chrom ┆ pos       ┆ ref          ┆ alt ┆ … ┆ non_MANE_exo ┆ non_MANE_CDS ┆ non_MANE_UT ┆ VEP_CDS │
│ ---   ┆ ---       ┆ ---          ┆ --- ┆   ┆ nic          ┆ ---          ┆ R           ┆ ---     │
│ str   ┆ i32       ┆ str          ┆ str ┆   ┆ ---          ┆ bool         ┆ ---         ┆ bool    │
│       ┆           ┆              ┆     ┆   ┆ bool         ┆              ┆ bool        ┆         │
╞═══════╪═══════════╪══════════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════╡
│ chr2  ┆ 169197167 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169204292 ┆ A            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 169030531 ┆ C            ┆ T   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168910825 ┆ T            ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr2  ┆ 168969544 ┆ T            ┆ C   ┆ … ┆ false        ┆ false        ┆ true        ┆ true    │
│ …     ┆ …         ┆ …            ┆ …   ┆ … ┆ …            ┆ …            ┆ …           ┆ …       │
│ chr15 ┆ 34974609  ┆ ACTTCT       ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr9  ┆ 132358570 ┆ C            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr8  ┆ 13200986  ┆ C            ┆ CA  ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr12 ┆ 122065447 ┆ G            ┆ A   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTTG ┆ G   ┆ … ┆ false        ┆ false        ┆ false       ┆ false   │
│       ┆           ┆ TTTTGTTTTGTT ┆     ┆   ┆              ┆              ┆             ┆         │
│       ┆           ┆ TT           ┆     ┆   ┆              ┆              ┆             ┆         │
└───────┴───────────┴──────────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────┘

In [5]:
final_annos[['MANE_exonic', 'non_MANE_exonic', 'MANE_CDS', 'non_MANE_CDS', 'MANE_UTR', 'non_MANE_UTR', 'VEP_CDS']].describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ MANE_exoni ┆ non_MANE_e ┆ MANE_CDS  ┆ non_MANE_ ┆ MANE_UTR  ┆ non_MANE_ ┆ VEP_CDS   │
│ ---        ┆ c          ┆ xonic      ┆ ---       ┆ CDS       ┆ ---       ┆ UTR       ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ f64       ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│            ┆ f64        ┆ f64        ┆           ┆ f64       ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 2.5373677e ┆ 2.5373677e ┆ 2.5373677 ┆ 2.5373677 ┆ 2.5373677 ┆ 2.5373677 ┆ 2.5373677 │
│            ┆ 7          ┆ 7          ┆ e7        ┆ e7        ┆ e7        ┆ e7        ┆ e7        │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 0.059322   ┆ 0.027294   ┆ 0.030925  ┆ 0.002359  ┆ 0.028491  ┆ 0.022531  ┆ 0.027117  │
│ std        ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ min        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 25%        ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ 1.0        ┆ 1.0        ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘