In [1]:
import polars as pl
import matplotlib.pyplot as plt
from plotnine import *

In [3]:
anno_dir = '/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated/'

# Add UKBBGym annotations

1. VEP coding / non-coding
2. Amino acid position
3. Protein domains (MOBI db)

In [3]:
# Download variant metadata file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated_variant_metadata.parquet -o {anno_dir}

varmeta_df = pl.read_parquet(f'{anno_dir}/qced_maf1e-3_loftee_olink_genes_EURunrelated_variant_metadata.parquet')
varmeta_df.head()

Error: path "/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_lofte
e_olink_genes_EURunrelated/qced_maf1e-3_loftee_olink_genes_EURunrelated_varian
t_metadata.parquet" already exists but -f/--overwrite was not set

shape: (5, 8)
┌────────────────────┬────────┬────────┬───────┬──────────┬─────┬─────┬─────────┐
│ id                 ┆ sc_ukb ┆ ac_ukb ┆ chrom ┆ pos      ┆ ref ┆ alt ┆ mac_ukb │
│ ---                ┆ ---    ┆ ---    ┆ ---   ┆ ---      ┆ --- ┆ --- ┆ ---     │
│ str                ┆ u64    ┆ i64    ┆ str   ┆ str      ┆ str ┆ str ┆ i64     │
╞════════════════════╪════════╪════════╪═══════╪══════════╪═════╪═════╪═════════╡
│ chr10:20162746:G:C ┆ 1      ┆ 1      ┆ chr10 ┆ 20162746 ┆ G   ┆ C   ┆ 1       │
│ chr10:20164255:A:G ┆ 1      ┆ 1      ┆ chr10 ┆ 20164255 ┆ A   ┆ G   ┆ 1       │
│ chr10:20164674:G:C ┆ 1      ┆ 1      ┆ chr10 ┆ 20164674 ┆ G   ┆ C   ┆ 1       │
│ chr10:20165243:A:G ┆ 1      ┆ 1      ┆ chr10 ┆ 20165243 ┆ A   ┆ G   ┆ 1       │
│ chr10:20165245:C:T ┆ 1      ┆ 1      ┆ chr10 ┆ 20165245 ┆ C   ┆ T   ┆ 1       │
└────────────────────┴────────┴────────┴───────┴──────────┴─────┴─────┴─────────┘

In [4]:
# Download annotations file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations.parquet -o {anno_dir}

anno_df = pl.scan_parquet(f'{anno_dir}/annotations.parquet')
anno_df.head().collect()

Error: path "/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_lofte
e_olink_genes_EURunrelated/annotations.parquet" already exists but
-f/--overwrite was not set

shape: (5, 220)
┌─────────────┬────────────┬─────────────┬───────┬───┬───────────┬───────────┬────────┬────────────┐
│ id          ┆ ac_ukb_eur ┆ mac_ukb_eur ┆ chrom ┆ … ┆ verphcons ┆ verphylop ┆ domain ┆ ensemblere │
│ ---         ┆ ---        ┆ ---         ┆ ---   ┆   ┆ ---       ┆ ---       ┆ ---    ┆ gulatoryfe │
│ str         ┆ u64        ┆ u64         ┆ str   ┆   ┆ f32       ┆ f32       ┆ str    ┆ ature      │
│             ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆ ---        │
│             ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆ str        │
╞═════════════╪════════════╪═════════════╪═══════╪═══╪═══════════╪═══════════╪════════╪════════════╡
│ chr19:17122 ┆ 1          ┆ 1           ┆ chr19 ┆ … ┆ 0.007     ┆ 0.379     ┆ null   ┆ null       │
│ 403:G:A     ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
│ chr19:19643 ┆ 1          ┆ 1           ┆ chr19 ┆ … ┆ 0.009     ┆ -0.03     ┆ null   ┆ Promoter   │
│ 593:C:A     ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
│ chr1:228280 ┆ 1          ┆ 1           ┆ chr1  ┆ … ┆ 0.974     ┆ 3.098     ┆ lcompl ┆ null       │
│ 185:A:T     ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
│ chr1:228297 ┆ 1          ┆ 1           ┆ chr1  ┆ … ┆ 0.0       ┆ -0.071    ┆ null   ┆ null       │
│ 766:A:G     ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
│ chr1:228298 ┆ 1          ┆ 1           ┆ chr1  ┆ … ┆ null      ┆ null      ┆ null   ┆ null       │
│ 257:A:ATGTG ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
│ GGTGTGTG    ┆            ┆             ┆       ┆   ┆           ┆           ┆        ┆            │
└─────────────┴────────────┴─────────────┴───────┴───┴───────────┴───────────┴────────┴────────────┘

In [5]:
# Download annotations fill_na file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fill_na.parquet -o {anno_dir}

anno_fillna_df = pl.scan_parquet(f'{anno_dir}/annotations_fill_na.parquet')
anno_fillna_df.head().collect()

Error: path "/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_lofte
e_olink_genes_EURunrelated/annotations_fill_na.parquet" already exists but
-f/--overwrite was not set

shape: (5, 264)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ ac_ukb_eur ┆ mac_ukb_eu ┆ chrom ┆ … ┆ toverlapm ┆ targetsca ┆ verphcons ┆ verphylop │
│ ---        ┆ ---        ┆ r          ┆ ---   ┆   ┆ otifs_is_ ┆ n_is_na   ┆ _is_na    ┆ _is_na    │
│ str        ┆ u64        ┆ ---        ┆ str   ┆   ┆ na        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆ u64        ┆       ┆   ┆ ---       ┆ i8        ┆ i8        ┆ i8        │
│            ┆            ┆            ┆       ┆   ┆ i8        ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr18:5660 ┆ 1          ┆ 1          ┆ chr18 ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
│ 3287:T:G   ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ chr18:5661 ┆ 1          ┆ 1          ┆ chr18 ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
│ 1517:A:G   ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ chr19:3434 ┆ 1          ┆ 1          ┆ chr19 ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
│ 0475:G:A   ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ chr19:5256 ┆ 1          ┆ 1          ┆ chr19 ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
│ 210:T:C    ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
│ chr19:5257 ┆ 1          ┆ 1          ┆ chr19 ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0         │
│ 316:G:C    ┆            ┆            ┆       ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

## Drop abexp tissue columns

In [6]:
ab_exp_cols = [c for c in anno_fillna_df.columns if c.startswith('abexp_')]

drop_abexp_cols = list(set(ab_exp_cols) - {'abexp_abs_max', 'abexp_abs_max_is_na'})
drop_abexp_cols += ['ac_ukb_eur', 'mac_ukb_eur', 'mac_ukb']

anno_fillna_df = anno_fillna_df.drop(drop_abexp_cols)
anno_fillna_df.columns

/scratch/tmp/lond/ipykernel_368407/2930820859.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
/scratch/tmp/lond/ipykernel_368407/2930820859.py:7: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.

['id',
 'chrom',
 'pos',
 'ref',
 'alt',
 'region',
 'sift',
 'polyphen',
 'cadd_phred',
 'cadd_raw',
 'am_pathogenicity',
 'spliceai_pred',
 'loftee_hc',
 'loftee_lc',
 'relative_cds_position',
 'next_in_frame_relative',
 'spliceai_delta_score',
 'pangolin_score',
 'delta_score',
 'absplice_dna_max',
 'absplice2_max',
 'five_prime_utr_variant_consequence_uaug_gained',
 'five_prime_utr_variant_consequence_uaug_lost',
 'five_prime_utr_variant_consequence_uframeshift',
 'five_prime_utr_variant_consequence_ustop_gained',
 'five_prime_utr_variant_consequence_ustop_lost',
 'variant_length',
 'gpn_score',
 'promoterai',
 'score_pai3d',
 'abexp_abs_max',
 'gene_length',
 'dist_to_tss',
 'aparent2',
 'cdspos',
 'cpg',
 'dst2splice',
 'esmscoreframeshift',
 'esmscoreinframe',
 'esmscoremissense',
 'gc',
 'gerpn',
 'gerps',
 'grantham',
 'remapoverlapcl',
 'remapoverlaptf',
 'roulette-ar',
 'roulette-mr',
 'zoopriphylop',
 'zoouce',
 'zooverphylop',
 'bstatistic',
 'cdnapos',
 'dbscsnv-ada_score',
 'dbscsnv-rf_score',
 'mamphcons',
 'mamphylop',
 'mindisttse',
 'mindisttss',
 'mirsvr-aln',
 'mirsvr-e',
 'mirsvr-score',
 'motifdist',
 'motifecount',
 'motifehipos',
 'motifescorechng',
 'priphcons',
 'priphylop',
 'relcdspos',
 'relprotpos',
 'relcdnapos',
 'toverlapmotifs',
 'targetscan',
 'verphcons',
 'verphylop',
 'consequence_3_prime_utr_variant',
 'consequence_5_prime_utr_variant',
 'consequence_coding_sequence_variant',
 'consequence_downstream_gene_variant',
 'consequence_frameshift_variant',
 'consequence_incomplete_terminal_codon_variant',
 'consequence_inframe_deletion',
 'consequence_inframe_insertion',
 'consequence_intron_variant',
 'consequence_missense_variant',
 'consequence_protein_altering_variant',
 'consequence_splice_acceptor_variant',
 'consequence_splice_donor_5th_base_variant',
 'consequence_splice_donor_region_variant',
 'consequence_splice_donor_variant',
 'consequence_splice_polypyrimidine_tract_variant',
 'consequence_splice_region_variant',
 'consequence_start_lost',
 'consequence_start_retained_variant',
 'consequence_stop_gained',
 'consequence_stop_lost',
 'consequence_stop_retained_variant',
 'consequence_synonymous_variant',
 'consequence_upstream_gene_variant',
 'sift_is_na',
 'polyphen_is_na',
 'cadd_phred_is_na',
 'cadd_raw_is_na',
 'am_pathogenicity_is_na',
 'spliceai_pred_is_na',
 'loftee_hc_is_na',
 'loftee_lc_is_na',
 'relative_cds_position_is_na',
 'next_in_frame_relative_is_na',
 'spliceai_delta_score_is_na',
 'pangolin_score_is_na',
 'delta_score_is_na',
 'absplice_dna_max_is_na',
 'absplice2_max_is_na',
 'variant_length_is_na',
 'gpn_score_is_na',
 'promoterai_is_na',
 'score_pai3d_is_na',
 'abexp_abs_max_is_na',
 'gene_length_is_na',
 'dist_to_tss_is_na',
 'aparent2_is_na',
 'cdspos_is_na',
 'cpg_is_na',
 'dst2splice_is_na',
 'esmscoreframeshift_is_na',
 'esmscoreinframe_is_na',
 'esmscoremissense_is_na',
 'gc_is_na',
 'gerpn_is_na',
 'gerps_is_na',
 'grantham_is_na',
 'remapoverlapcl_is_na',
 'remapoverlaptf_is_na',
 'roulette-ar_is_na',
 'roulette-mr_is_na',
 'zoopriphylop_is_na',
 'zoouce_is_na',
 'zooverphylop_is_na',
 'bstatistic_is_na',
 'cdnapos_is_na',
 'dbscsnv-ada_score_is_na',
 'dbscsnv-rf_score_is_na',
 'mamphcons_is_na',
 'mamphylop_is_na',
 'mindisttse_is_na',
 'mindisttss_is_na',
 'mirsvr-aln_is_na',
 'mirsvr-e_is_na',
 'mirsvr-score_is_na',
 'motifdist_is_na',
 'motifecount_is_na',
 'motifehipos_is_na',
 'motifescorechng_is_na',
 'priphcons_is_na',
 'priphylop_is_na',
 'relcdspos_is_na',
 'relprotpos_is_na',
 'relcdnapos_is_na',
 'toverlapmotifs_is_na',
 'targetscan_is_na',
 'verphcons_is_na',
 'verphylop_is_na']

# Annotate UKB MAC and sample counts

In [7]:
anno_fillna_df = (
    anno_fillna_df

    .join(
        varmeta_df.select(['id', 'sc_ukb', 'ac_ukb', 'mac_ukb']).lazy(), 
        on='id', 
        how='inner'
    )
)

# Annotate VEP coding regions

In [8]:
vep_cds_relaxed = [
    # LoF variants
    'consequence_stop_gained',
    'consequence_frameshift_variant',

    # Missense and synonymous variants
    'consequence_synonymous_variant',
    'consequence_protein_altering_variant',
    'consequence_missense_variant',

    # Splicing variants
    'consequence_splice_region_variant',
    'consequence_splice_acceptor_variant',
    'consequence_splice_donor_variant',
    'consequence_splice_donor_region_variant',
    'consequence_splice_donor_5th_base_variant',
    'consequence_splice_polypyrimidine_tract_variant',

    # Other coding sequence variants
    'consequence_start_lost',
    'consequence_stop_lost',
    'consequence_start_retained_variant',
    'consequence_stop_retained_variant',
    'consequence_inframe_deletion',
    'consequence_inframe_insertion',
    'consequence_coding_sequence_variant',
]

anno_fillna_df = (
    anno_fillna_df
    .with_columns(
        vep_cds_relaxed = pl.sum_horizontal(vep_cds_relaxed) > 0,
    )
)

# Annotate protein domains

## Merge protein position, amino acid mutation

In [9]:
anno_fillna_df = (
    anno_fillna_df
    
    .join(
        anno_df.select(['id', 'region', 'protein_position', 'amino_acids']).lazy(), 
        on='id', 
        how='inner'
    )
)

In [10]:
# anno_fillna_df.sink_parquet(f'{anno_dir}/annotations_fillna_ukbgym_tmp.parquet', engine='streaming')

## Annotate protein domains

In [4]:
anno_ukbgym_df = pl.scan_parquet(f'{anno_dir}/annotations_fillna_ukbgym_tmp.parquet')

anno_ukbgym_df.head().collect()

shape: (5, 170)
┌─────────────┬───────┬───────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ id          ┆ chrom ┆ pos       ┆ ref ┆ … ┆ vep_cds_rel ┆ region_righ ┆ protein_pos ┆ amino_acid │
│ ---         ┆ ---   ┆ ---       ┆ --- ┆   ┆ axed        ┆ t           ┆ ition       ┆ s          │
│ str         ┆ str   ┆ i64       ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│             ┆       ┆           ┆     ┆   ┆ bool        ┆ str         ┆ str         ┆ str        │
╞═════════════╪═══════╪═══════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ chr1:228280 ┆ chr1  ┆ 228280185 ┆ A   ┆ … ┆ true        ┆ ENSG0000015 ┆ 2986/8925   ┆ E/V        │
│ 185:A:T     ┆       ┆           ┆     ┆   ┆             ┆ 4358        ┆             ┆            │
│ chr2:181886 ┆ chr2  ┆ 181886992 ┆ C   ┆ … ┆ false       ┆ ENSG0000013 ┆ null        ┆ null       │
│ 992:C:A     ┆       ┆           ┆     ┆   ┆             ┆ 8434        ┆             ┆            │
│ chr4:150790 ┆ chr4  ┆ 150790645 ┆ T   ┆ … ┆ false       ┆ ENSG0000019 ┆ null        ┆ null       │
│ 645:T:G     ┆       ┆           ┆     ┆   ┆             ┆ 8589        ┆             ┆            │
│ chr11:12880 ┆ chr11 ┆ 128809531 ┆ C   ┆ … ┆ false       ┆ ENSG0000015 ┆ null        ┆ null       │
│ 9531:C:A    ┆       ┆           ┆     ┆   ┆             ┆ 1702        ┆             ┆            │
│ chr14:52073 ┆ chr14 ┆ 52073025  ┆ T   ┆ … ┆ false       ┆ ENSG0000008 ┆ null        ┆ null       │
│ 025:T:C     ┆       ┆           ┆     ┆   ┆             ┆ 7303        ┆             ┆            │
└─────────────┴───────┴───────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [5]:
anno_coding = (
    anno_ukbgym_df
    .select(['id', 'region', 'protein_position'])
    .drop_nulls()
    .with_columns(
        pos_raw = pl.col('protein_position').str.split('/').list.get(0)
    )
    .with_columns(
        split_struct = pl.col('pos_raw').str.split_exact('-', 1)
    )
    .with_columns(
        aa_start = pl.col('split_struct').struct.field('field_0').cast(pl.Int32, strict=False),
        aa_end = (
            pl.col('split_struct').struct.field('field_1')
            .fill_null(pl.col('split_struct').struct.field('field_0'))
            .cast(pl.Int32, strict=False)
        )
    )
    .drop(['pos_raw', 'split_struct'])
    .collect(engine='streaming')
)

anno_coding

shape: (1_913_048, 5)
┌────────────────────┬─────────────────┬──────────────────┬──────────┬────────┐
│ id                 ┆ region          ┆ protein_position ┆ aa_start ┆ aa_end │
│ ---                ┆ ---             ┆ ---              ┆ ---      ┆ ---    │
│ str                ┆ str             ┆ str              ┆ i32      ┆ i32    │
╞════════════════════╪═════════════════╪══════════════════╪══════════╪════════╡
│ chr1:228280185:A:T ┆ ENSG00000154358 ┆ 2986/8925        ┆ 2986     ┆ 2986   │
│ chr2:151643165:A:G ┆ ENSG00000183091 ┆ 2715/8525        ┆ 2715     ┆ 2715   │
│ chr1:228309519:C:T ┆ ENSG00000154358 ┆ 5281/8925        ┆ 5281     ┆ 5281   │
│ chr1:205620731:A:G ┆ ENSG00000158711 ┆ 105/431          ┆ 105      ┆ 105    │
│ chr2:219634523:C:T ┆ ENSG00000114923 ┆ 555/1232         ┆ 555      ┆ 555    │
│ …                  ┆ …               ┆ …                ┆ …        ┆ …      │
│ chr9:99038673:G:A  ┆ ENSG00000204291 ┆ 805/1388         ┆ 805      ┆ 805    │
│ chr4:17492327:G:A  ┆ ENSG00000151552 ┆ 150/244          ┆ 150      ┆ 150    │
│ chr6:127289953:C:A ┆ ENSG00000093144 ┆ 274/301          ┆ 274      ┆ 274    │
│ chr1:33021699:C:A  ┆ ENSG00000004455 ┆ 75/239           ┆ 75       ┆ 75     │
│ chr19:7463858:C:T  ┆ ENSG00000104880 ┆ 892/1361         ┆ 892      ┆ 892    │
└────────────────────┴─────────────────┴──────────────────┴──────────┴────────┘

In [6]:
ginfo = (
    pl.read_parquet('/s/project/deeprvat/ukb_gym/genes_info_biomart.parquet')
    .filter(pl.col('ensembl_canonical') == True)
    .select(['gene_stable_id', 'gene_name', 'uniprotkb_gene_name_id', 'uniprotkb_gene_name_symbol', 'gene_type'])
    .rename({
        'gene_stable_id': 'region',
        'uniprotkb_gene_name_id': 'uniprot_id',
        'uniprotkb_gene_name_symbol': 'uniprot_name'
    })
    .filter(pl.col('gene_type') == 'protein_coding')
)
ginfo

shape: (93_361, 5)
┌─────────────────┬───────────┬────────────┬──────────────┬────────────────┐
│ region          ┆ gene_name ┆ uniprot_id ┆ uniprot_name ┆ gene_type      │
│ ---             ┆ ---       ┆ ---        ┆ ---          ┆ ---            │
│ str             ┆ str       ┆ str        ┆ str          ┆ str            │
╞═════════════════╪═══════════╪════════════╪══════════════╪════════════════╡
│ ENSG00000198888 ┆ MT-ND1    ┆ U5Z754     ┆ ND1          ┆ protein_coding │
│ ENSG00000198888 ┆ MT-ND1    ┆ P03886     ┆ MT-ND1       ┆ protein_coding │
│ ENSG00000198763 ┆ MT-ND2    ┆ P03891     ┆ MT-ND2       ┆ protein_coding │
│ ENSG00000198763 ┆ MT-ND2    ┆ Q7GXY9     ┆ ND2          ┆ protein_coding │
│ ENSG00000198804 ┆ MT-CO1    ┆ U5YWV7     ┆ COX1         ┆ protein_coding │
│ …               ┆ …         ┆ …          ┆ …            ┆ …              │
│ ENSG00000188157 ┆ AGRN      ┆ A0A087X208 ┆ AGRN         ┆ protein_coding │
│ ENSG00000152092 ┆ ASTN1     ┆ O14525     ┆ ASTN1        ┆ protein_coding │
│ ENSG00000152092 ┆ ASTN1     ┆ B1AJS1     ┆ ASTN1        ┆ protein_coding │
│ ENSG00000011021 ┆ CLCN6     ┆ P51797     ┆ CLCN6        ┆ protein_coding │
│ ENSG00000011021 ┆ CLCN6     ┆ A0A3B3IRY0 ┆ CLCN6        ┆ protein_coding │
└─────────────────┴───────────┴────────────┴──────────────┴────────────────┘

## Disorder - MobiDB

In [7]:
mobi_df_raw = pl.read_csv(
    "/s/project/deeprvat/wgs_preprocessing_rap/annotation/protein_regions/mobi_db/mobidb_search_2025-11-27-human_proteins.tsv",
    separator="\t",
    has_header=False,
    new_columns=[
        "uniprot_id",
        "feature",
        "protein_regions",
        "disorder_content",
        "disorder_count",
        "length"
    ]
)

mobi_df_raw

shape: (2_845_837, 6)
┌────────────┬────────────────────┬───────────────────┬──────────────────┬────────────────┬────────┐
│ uniprot_id ┆ feature            ┆ protein_regions   ┆ disorder_content ┆ disorder_count ┆ length │
│ ---        ┆ ---                ┆ ---               ┆ ---              ┆ ---            ┆ ---    │
│ str        ┆ str                ┆ str               ┆ f64              ┆ i64            ┆ i64    │
╞════════════╪════════════════════╪═══════════════════╪══════════════════╪════════════════╪════════╡
│ P31946     ┆ curated-disorder-i ┆ 1..2,71..75,233.. ┆ 0.085            ┆ 21             ┆ 246    │
│            ┆ deal               ┆ 246               ┆                  ┆                ┆        │
│ P31946     ┆ curated-disorder-m ┆ 233..246          ┆ 0.057            ┆ 14             ┆ 246    │
│            ┆ erge               ┆                   ┆                  ┆                ┆        │
│ P31946     ┆ curated-disorder-p ┆ 233..246          ┆ 0.057            ┆ 14             ┆ 246    │
│            ┆ riority            ┆                   ┆                  ┆                ┆        │
│ P31946     ┆ derived-observed-p ┆ 3..70,76..232     ┆ 0.915            ┆ 225            ┆ 246    │
│            ┆ riority            ┆                   ┆                  ┆                ┆        │
│ P31946     ┆ derived-observed-t ┆ 3..70,76..232     ┆ 0.915            ┆ 225            ┆ 246    │
│            ┆ h_90               ┆                   ┆                  ┆                ┆        │
│ …          ┆ …                  ┆ …                 ┆ …                ┆ …              ┆ …      │
│ B7ZMN7     ┆ prediction-disorde ┆ 148..173,1181..12 ┆ 0.062            ┆ 85             ┆ 1382   │
│            ┆ r-mobidb_lit…      ┆ 03,1221..1256     ┆                  ┆                ┆        │
│ B7ZMN7     ┆ prediction-polyamp ┆ 1181..1190        ┆ 0.007            ┆ 10             ┆ 1382   │
│            ┆ holyte-mobid…      ┆                   ┆                  ┆                ┆        │
│ B7ZMN7     ┆ prediction-negativ ┆ 1221..1238        ┆ 0.013            ┆ 18             ┆ 1382   │
│            ┆ e_polyelectr…      ┆                   ┆                  ┆                ┆        │
│ B7ZMN7     ┆ prediction-polar-m ┆ 1246..1256        ┆ 0.008            ┆ 11             ┆ 1382   │
│            ┆ obidb_lite_s…      ┆                   ┆                  ┆                ┆        │
│ B7ZMN7     ┆ prediction-extende ┆ 1221..1256        ┆ 0.027            ┆ 37             ┆ 1382   │
│            ┆ d-mobidb_lit…      ┆                   ┆                  ┆                ┆        │
└────────────┴────────────────────┴───────────────────┴──────────────────┴────────────────┴────────┘

In [8]:
a = mobi_df_raw.filter(pl.col('uniprot_id')=='P04637').filter(pl.col('feature').str.contains('disorder'))
a

shape: (19, 6)
┌────────────┬────────────────────┬───────────────────┬──────────────────┬────────────────┬────────┐
│ uniprot_id ┆ feature            ┆ protein_regions   ┆ disorder_content ┆ disorder_count ┆ length │
│ ---        ┆ ---                ┆ ---               ┆ ---              ┆ ---            ┆ ---    │
│ str        ┆ str                ┆ str               ┆ f64              ┆ i64            ┆ i64    │
╞════════════╪════════════════════╪═══════════════════╪══════════════════╪════════════════╪════════╡
│ P04637     ┆ curated-binding_mo ┆ 27..39            ┆ 0.033            ┆ 13             ┆ 393    │
│            ┆ de_disorder_…      ┆                   ┆                  ┆                ┆        │
│ P04637     ┆ curated-binding_mo ┆ 27..39            ┆ 0.033            ┆ 13             ┆ 393    │
│            ┆ de_disorder_…      ┆                   ┆                  ┆                ┆        │
│ P04637     ┆ curated-binding_mo ┆ 27..39            ┆ 0.033            ┆ 13             ┆ 393    │
│            ┆ de_disorder_…      ┆                   ┆                  ┆                ┆        │
│ P04637     ┆ curated-disorder-d ┆ 1..93,291..312,36 ┆ 0.377            ┆ 148            ┆ 393    │
│            ┆ isprot             ┆ 1..393            ┆                  ┆                ┆        │
│ P04637     ┆ curated-disorder-i ┆ 1..96,115..121,14 ┆ 0.481            ┆ 189            ┆ 393    │
│            ┆ deal               ┆ 4..145,153..1…    ┆                  ┆                ┆        │
│ …          ┆ …                  ┆ …                 ┆ …                ┆ …              ┆ …      │
│ P04637     ┆ prediction-disorde ┆ 1..23,25..27,30.. ┆ 0.532            ┆ 209            ┆ 393    │
│            ┆ r-iupl             ┆ 31,33..97,156…    ┆                  ┆                ┆        │
│ P04637     ┆ prediction-disorde ┆ 1..16,21..21,37.. ┆ 0.43             ┆ 169            ┆ 393    │
│            ┆ r-iups             ┆ 40,42..87,89.…    ┆                  ┆                ┆        │
│ P04637     ┆ prediction-disorde ┆ 50..96,282..325,3 ┆ 0.341            ┆ 134            ┆ 393    │
│            ┆ r-mobidb_lit…      ┆ 51..393           ┆                  ┆                ┆        │
│ P04637     ┆ prediction-disorde ┆ 313..325,354..360 ┆ 0.051            ┆ 20             ┆ 393    │
│            ┆ r-priority         ┆                   ┆                  ┆                ┆        │
│ P04637     ┆ prediction-disorde ┆ 1..23,25..27,30.. ┆ 0.501            ┆ 197            ┆ 393    │
│            ┆ r-th_50            ┆ 31,33..97,181…    ┆                  ┆                ┆        │
└────────────┴────────────────────┴───────────────────┴──────────────────┴────────────────┴────────┘

In [9]:
mobi_df = (
    mobi_df_raw
    .join(ginfo.select(['uniprot_id', 'region']).unique(), on='uniprot_id', how='inner')  # Keep only proteins present in ginfo
    # .join(anno_coding.select(['region']).unique(), on='region', how='semi')  # Keep only proteins present in anno_coding

    .with_columns(pl.col("protein_regions").str.split(",")) # Split "1..2,71..75" into list
    .explode("protein_regions")                             # Create new row for each region
    .with_columns(
        # Split "1..2" into separate Start and End columns
        pl.col("protein_regions")
        .str.split_exact("..", 1)
        .struct.rename_fields(["domain_start", "domain_end"])
        .alias("protein_region_struct")
    )
    .unnest("protein_region_struct")
    .with_columns([
        pl.col("domain_start").cast(pl.Int64),
        pl.col("domain_end").cast(pl.Int64)
    ])

    .with_columns(
        mobi_feature_source = pl.col("feature").str.split("-").list.get(0),
        mobi_feature_type = pl.col("feature").str.split("-").list.get(1),
        mobi_feature_subtype = pl.col("feature").str.split("-").list.get(2)
    )

    .with_columns(
        mobi_curated_disorder_priority = (pl.col('mobi_feature_source')=='curated') & (pl.col('mobi_feature_type')=='disorder') & (pl.col('mobi_feature_subtype')=='priority'),
        mobi_lip_full = (pl.col('mobi_feature_type')=='lip') & (pl.col('mobi_feature_subtype')=='priority'),
    )

    .filter(
        (pl.col('mobi_curated_disorder_priority') == True) |
        (pl.col('mobi_lip_full') == True)
    )

    .select(['region', 'uniprot_id', 'domain_start', 'domain_end', 'mobi_curated_disorder_priority', 'mobi_lip_full'])
    .unique()
    .sort(['uniprot_id', 'domain_start'])
)

mobi_df

shape: (239_525, 6)
┌─────────────────┬────────────┬──────────────┬────────────┬───────────────────────┬───────────────┐
│ region          ┆ uniprot_id ┆ domain_start ┆ domain_end ┆ mobi_curated_disorder ┆ mobi_lip_full │
│ ---             ┆ ---        ┆ ---          ┆ ---        ┆ _priority             ┆ ---           │
│ str             ┆ str        ┆ i64          ┆ i64        ┆ ---                   ┆ bool          │
│                 ┆            ┆              ┆            ┆ bool                  ┆               │
╞═════════════════╪════════════╪══════════════╪════════════╪═══════════════════════╪═══════════════╡
│ ENSG00000265241 ┆ A0A023T787 ┆ 1            ┆ 43         ┆ false                 ┆ true          │
│ ENSG00000265241 ┆ A0A023T787 ┆ 70           ┆ 80         ┆ false                 ┆ true          │
│ ENSG00000265241 ┆ A0A023T787 ┆ 96           ┆ 100        ┆ false                 ┆ true          │
│ ENSG00000265241 ┆ A0A023T787 ┆ 112          ┆ 121        ┆ false                 ┆ true          │
│ ENSG00000265241 ┆ A0A023T787 ┆ 142          ┆ 160        ┆ false                 ┆ true          │
│ …               ┆ …          ┆ …            ┆ …          ┆ …                     ┆ …             │
│ ENSG00000082805 ┆ X6RM00     ┆ 884          ┆ 908        ┆ false                 ┆ true          │
│ ENSG00000082805 ┆ X6RM00     ┆ 928          ┆ 929        ┆ false                 ┆ true          │
│ ENSG00000082805 ┆ X6RM00     ┆ 939          ┆ 955        ┆ false                 ┆ true          │
│ ENSG00000082805 ┆ X6RM00     ┆ 966          ┆ 976        ┆ false                 ┆ true          │
│ ENSG00000122643 ┆ X6RM59     ┆ 14           ┆ 34         ┆ false                 ┆ true          │
└─────────────────┴────────────┴──────────────┴────────────┴───────────────────────┴───────────────┘

## Structured domains - TED

In [10]:
ted_df_raw = pl.read_csv('/s/project/deeprvat/wgs_preprocessing_rap/annotation/protein_regions/filtered_human_TED_entries.txt', separator='\t', has_header=False)
ted_df_raw

shape: (39_504, 21)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ column_1  ┆ column_2  ┆ column_3 ┆ column_4  ┆ … ┆ column_18 ┆ column_19 ┆ column_20 ┆ column_21 │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AF-A0A024 ┆ 6e367bae1 ┆ high     ┆ 17-146    ┆ … ┆ 0.302     ┆ Human     ┆ Homo      ┆ cellular  │
│ RBG1-F1-m ┆ 738681098 ┆          ┆           ┆   ┆           ┆           ┆ sapiens   ┆ organisms │
│ odel_v4_T ┆ 78fea4930 ┆          ┆           ┆   ┆           ┆           ┆           ┆ , Eukaryo │
│ ED0…      ┆ 172…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ ta,…      │
│ AF-A0A024 ┆ 2cf0c523a ┆ high     ┆ 6-65      ┆ … ┆ 0.331     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ RCN7-F1-m ┆ 4e2f15d1a ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ odel_v4_T ┆ e55f74d02 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│ ED0…      ┆ 13e…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-A0A075 ┆ d8a952574 ┆ high     ┆ 3-9_36-13 ┆ … ┆ 0.311     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ B6H5-F1-m ┆ d69888c85 ┆          ┆ 0         ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ odel_v4_T ┆ 5edbde9d0 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│ ED0…      ┆ 82b…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-A0A075 ┆ 41418b51f ┆ medium   ┆ 48-116    ┆ … ┆ 0.343     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ B6H7-F1-m ┆ c976cc085 ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ odel_v4_T ┆ f77690210 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│ ED0…      ┆ 9ac…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-A0A075 ┆ 97a822941 ┆ medium   ┆ 53-117    ┆ … ┆ 0.343     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ B6H8-F1-m ┆ 55cb34997 ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ odel_v4_T ┆ faac73bb6 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│ ED0…      ┆ 9eb…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ AF-W5XKT8 ┆ 7afd72c7c ┆ high     ┆ 27-118    ┆ … ┆ 0.284     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ -F1-model ┆ 23c74e588 ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ _v4_TED01 ┆ f03eed21c ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│           ┆ 412…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-W5XKT8 ┆ c67696602 ┆ high     ┆ 157-246   ┆ … ┆ 0.305     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ -F1-model ┆ 57533b890 ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ _v4_TED02 ┆ d5170367e ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│           ┆ c84…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-W6CW81 ┆ 8e428499a ┆ medium   ┆ 2-45_57-8 ┆ … ┆ 0.316     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ -F1-model ┆ d22a6563d ┆          ┆ 1         ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ _v4_TED01 ┆ fe9176365 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│           ┆ 72f…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-X6R8R1 ┆ 9b16ce41d ┆ high     ┆ 200-322   ┆ … ┆ 0.299     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ -F1-model ┆ 98a667b7e ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ _v4_TED01 ┆ 9ec8d7886 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│           ┆ 06f…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
│ AF-X6R8R1 ┆ 11735c4e8 ┆ high     ┆ 334-469   ┆ … ┆ 0.315     ┆ Human     ┆ Homo_sapi ┆ cellular_ │
│ -F1-model ┆ 9659987b8 ┆          ┆           ┆   ┆           ┆           ┆ ens       ┆ organisms │
│ _v4_TED02 ┆ 967806839 ┆          ┆           ┆   ┆           ┆           ┆           ┆ ,Eukaryot │
│           ┆ c5e…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ a,O…      │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
ted_df = (
    ted_df_raw
    .with_columns(
        uniprot_id = pl.col('column_1').str.split('-').list.get(1),
        ted_id = pl.col('column_1').str.slice(-5),
    )
    .with_columns(pl.col("column_4").str.split("_")) # Split "1-2_71-75" into list
    .explode("column_4")                             # Create new row for each region
    .with_columns(
        # Split "1-2" into separate Start and End columns
        pl.col("column_4")
        .str.split_exact("-", 1)
        .struct.rename_fields(["domain_start", "domain_end"])
        .alias("protein_region_struct")
    )
    .unnest("protein_region_struct")
    .with_columns(
        [
            pl.col("domain_start").cast(pl.Int64),
            pl.col("domain_end").cast(pl.Int64)
        ],
        ted_domain = pl.lit(True)
    )
    .select(['uniprot_id', 'domain_start', 'domain_end', 'ted_domain'])
    .unique()
    .join(ginfo.select(['uniprot_id', 'region']).unique(), on='uniprot_id', how='inner')  # Keep only proteins present in ginfo
)

ted_df

shape: (53_916, 5)
┌────────────┬──────────────┬────────────┬────────────┬─────────────────┐
│ uniprot_id ┆ domain_start ┆ domain_end ┆ ted_domain ┆ region          │
│ ---        ┆ ---          ┆ ---        ┆ ---        ┆ ---             │
│ str        ┆ i64          ┆ i64        ┆ bool       ┆ str             │
╞════════════╪══════════════╪════════════╪════════════╪═════════════════╡
│ Q9BXW7     ┆ 124          ┆ 277        ┆ true       ┆ ENSG00000069998 │
│ Q9BXW7     ┆ 356          ┆ 419        ┆ true       ┆ ENSG00000069998 │
│ Q9BXW7     ┆ 48           ┆ 120        ┆ true       ┆ ENSG00000069998 │
│ Q9BXW7     ┆ 280          ┆ 341        ┆ true       ┆ ENSG00000069998 │
│ Q5T200     ┆ 1520         ┆ 1616       ┆ true       ┆ ENSG00000123200 │
│ …          ┆ …            ┆ …          ┆ …          ┆ …               │
│ P08476     ┆ 50           ┆ 114        ┆ true       ┆ ENSG00000122641 │
│ P08476     ┆ 286          ┆ 290        ┆ true       ┆ ENSG00000122641 │
│ Q6ZSS7     ┆ 64           ┆ 163        ┆ true       ┆ ENSG00000151690 │
│ Q6ZSS7     ┆ 438          ┆ 653        ┆ true       ┆ ENSG00000151690 │
│ Q6ZSS7     ┆ 275          ┆ 392        ┆ true       ┆ ENSG00000151690 │
└────────────┴──────────────┴────────────┴────────────┴─────────────────┘

## Low complexity regions

In [12]:
lc_df_raw = pl.read_csv('/s/project/deeprvat/wgs_preprocessing_rap/annotation/protein_regions/LowComplexity_Cascarina2021_SuppT3.tsv', separator='\t')
lc_df_raw

shape: (127_472, 8)
┌────────────┬───────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ Organism   ┆ LCD Class ┆ Protein ID ┆ Domain     ┆ Domain    ┆ AA Used   ┆ Final     ┆ Final Dis │
│ ---        ┆ ---       ┆ ---        ┆ Sequence   ┆ Boundarie ┆ in Search ┆ Comp of   ┆ persion   │
│ str        ┆ str       ┆ str        ┆ ---        ┆ s         ┆ ---       ┆ Search AA ┆ of Search │
│            ┆           ┆            ┆ str        ┆ ---       ┆ str       ┆ ---       ┆ AA        │
│            ┆           ┆            ┆            ┆ str       ┆           ┆ f64       ┆ ---       │
│            ┆           ┆            ┆            ┆           ┆           ┆           ┆ f64       │
╞════════════╪═══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ S.         ┆ A         ┆ P33890     ┆ AYIKIALLAA ┆ (2-18)    ┆ A         ┆ 47.06     ┆ 0.6906    │
│ cerevisiae ┆           ┆            ┆ IAALASA    ┆           ┆           ┆           ┆           │
│ S.         ┆ A         ┆ P33890     ┆ AAKAVIGMGA ┆ (232-248) ┆ A         ┆ 47.06     ┆ 0.4901    │
│ cerevisiae ┆           ┆            ┆ GVMAAAA    ┆           ┆           ┆           ┆           │
│ S.         ┆ A         ┆ Q12328     ┆ AGPQAALMGG ┆ (170-188) ┆ A         ┆ 42.11     ┆ 0.7108    │
│ cerevisiae ┆           ┆            ┆ AGFAAFSAA  ┆           ┆           ┆           ┆           │
│ S.         ┆ A         ┆ P27654     ┆ AIASLAVADT ┆ (12-31)   ┆ A         ┆ 40.0      ┆ 0.8492    │
│ cerevisiae ┆           ┆            ┆ SAAETAELQA ┆           ┆           ┆           ┆           │
│ S.         ┆ A         ┆ P27654     ┆ AAALASVSPA ┆ (105-125) ┆ A         ┆ 42.86     ┆ 0.6603    │
│ cerevisiae ┆           ┆            ┆ SSEAASSSEA ┆           ┆           ┆           ┆           │
│            ┆           ┆            ┆ A          ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ H. sapiens ┆ Y         ┆ Q9BTL3     ┆ YYPQQYGHYG ┆ (99-118)  ┆ Y         ┆ 40.0      ┆ 0.7251    │
│            ┆           ┆            ┆ YNQRPPYGYY ┆           ┆           ┆           ┆           │
│ H. sapiens ┆ Y         ┆ Q9H1X3     ┆ YDYMLDHPEE ┆ (120-138) ┆ Y         ┆ 42.11     ┆ 0.5459    │
│            ┆           ┆            ┆ YYSHYYHYY  ┆           ┆           ┆           ┆           │
│ H. sapiens ┆ Y         ┆ Q9NX07     ┆ YSQMYSYSYN ┆ (185-209) ┆ Y         ┆ 40.0      ┆ 0.8367    │
│            ┆           ┆            ┆ QYYQQYQNYY ┆           ┆           ┆           ┆           │
│            ┆           ┆            ┆ AQWGY      ┆           ┆           ┆           ┆           │
│ H. sapiens ┆ Y         ┆ Q9UKN7     ┆ YYGYPPEDPY ┆ (278-295) ┆ Y         ┆ 44.44     ┆ 0.6214    │
│            ┆           ┆            ┆ DYYHPDYY   ┆           ┆           ┆           ┆           │
│ H. sapiens ┆ Y         ┆ Q9UMX2     ┆ YLYPIWSPYA ┆ (24-41)   ┆ Y         ┆ 44.44     ┆ 0.7131    │
│            ┆           ┆            ┆ YYLYCYKY   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [13]:
lc_df = (
    lc_df_raw
    .filter(pl.col('Organism')=='H. sapiens')
    .rename({
        'Protein ID': 'uniprot_id',
    })
    .with_columns(
        # Split "1-2" into separate Start and End columns
        pl.col("Domain Boundaries")
        .str.strip_chars("()")
        .str.split_exact("-", 1)
        .struct.rename_fields(["domain_start", "domain_end"])
        .alias("protein_region_struct")
    )
    .unnest("protein_region_struct")
    .with_columns(
        [
            pl.col("domain_start").cast(pl.Int64),
            pl.col("domain_end").cast(pl.Int64)
        ],
        low_complexity_domain = pl.lit(True)
    )
    .select(['uniprot_id', 'domain_start', 'domain_end', 'low_complexity_domain'])
    .unique()
    .join(ginfo.select(['uniprot_id', 'region']).unique(), on='uniprot_id', how='inner')  # Keep only proteins present in ginfo
)

lc_df

shape: (24_156, 5)
┌────────────┬──────────────┬────────────┬───────────────────────┬─────────────────┐
│ uniprot_id ┆ domain_start ┆ domain_end ┆ low_complexity_domain ┆ region          │
│ ---        ┆ ---          ┆ ---        ┆ ---                   ┆ ---             │
│ str        ┆ i64          ┆ i64        ┆ bool                  ┆ str             │
╞════════════╪══════════════╪════════════╪═══════════════════════╪═════════════════╡
│ Q9UL42     ┆ 333          ┆ 351        ┆ true                  ┆ ENSG00000240694 │
│ P19835     ┆ 591          ┆ 694        ┆ true                  ┆ ENSG00000170835 │
│ Q7Z3I7     ┆ 513          ┆ 529        ┆ true                  ┆ ENSG00000180938 │
│ Q9BRK4     ┆ 37           ┆ 53         ┆ true                  ┆ ENSG00000107816 │
│ Q9BRK4     ┆ 269          ┆ 284        ┆ true                  ┆ ENSG00000107816 │
│ …          ┆ …            ┆ …          ┆ …                     ┆ …               │
│ Q9NX63     ┆ 39           ┆ 58         ┆ true                  ┆ ENSG00000106554 │
│ P57740     ┆ 897          ┆ 919        ┆ true                  ┆ ENSG00000111581 │
│ P57740     ┆ 848          ┆ 865        ┆ true                  ┆ ENSG00000111581 │
│ Q9NY15     ┆ 2467         ┆ 2496       ┆ true                  ┆ ENSG00000010327 │
│ Q9P0L2     ┆ 523          ┆ 546        ┆ true                  ┆ ENSG00000116141 │
└────────────┴──────────────┴────────────┴───────────────────────┴─────────────────┘

## Merge with annotations

In [14]:
all_df = pl.concat([mobi_df, ted_df, lc_df], how='diagonal').fill_null(False)
all_df

shape: (317_597, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ region     ┆ uniprot_id ┆ domain_sta ┆ domain_en ┆ mobi_cura ┆ mobi_lip_ ┆ ted_domai ┆ low_compl │
│ ---        ┆ ---        ┆ rt         ┆ d         ┆ ted_disor ┆ full      ┆ n         ┆ exity_dom │
│ str        ┆ str        ┆ ---        ┆ ---       ┆ der_prior ┆ ---       ┆ ---       ┆ ain       │
│            ┆            ┆ i64        ┆ i64       ┆ ity       ┆ bool      ┆ bool      ┆ ---       │
│            ┆            ┆            ┆           ┆ ---       ┆           ┆           ┆ bool      │
│            ┆            ┆            ┆           ┆ bool      ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ENSG000002 ┆ A0A023T787 ┆ 1          ┆ 43        ┆ false     ┆ true      ┆ false     ┆ false     │
│ 65241      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000002 ┆ A0A023T787 ┆ 70         ┆ 80        ┆ false     ┆ true      ┆ false     ┆ false     │
│ 65241      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000002 ┆ A0A023T787 ┆ 96         ┆ 100       ┆ false     ┆ true      ┆ false     ┆ false     │
│ 65241      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000002 ┆ A0A023T787 ┆ 112        ┆ 121       ┆ false     ┆ true      ┆ false     ┆ false     │
│ 65241      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000002 ┆ A0A023T787 ┆ 142        ┆ 160       ┆ false     ┆ true      ┆ false     ┆ false     │
│ 65241      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ ENSG000001 ┆ Q9NX63     ┆ 39         ┆ 58        ┆ false     ┆ false     ┆ false     ┆ true      │
│ 06554      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000001 ┆ P57740     ┆ 897        ┆ 919       ┆ false     ┆ false     ┆ false     ┆ true      │
│ 11581      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000001 ┆ P57740     ┆ 848        ┆ 865       ┆ false     ┆ false     ┆ false     ┆ true      │
│ 11581      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000000 ┆ Q9NY15     ┆ 2467       ┆ 2496      ┆ false     ┆ false     ┆ false     ┆ true      │
│ 10327      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ENSG000001 ┆ Q9P0L2     ┆ 523        ┆ 546       ┆ false     ┆ false     ┆ false     ┆ true      │
│ 16141      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [15]:
overlap_df = (
    anno_coding.lazy() # Use lazy for better performance on large joins
    .join(
        all_df.lazy(), 
        on="region", 
        how="inner"
    )
    .filter(
        # (Variant Start <= Region End) AND (Variant Start >= Region Start)
        ((pl.col("aa_start") <= pl.col("domain_end")) & (pl.col("aa_start") >= pl.col("domain_start"))) |

        # (Variant End <= Region End) AND (Variant End >= Region Start)
        ((pl.col("aa_end") <= pl.col("domain_end")) & (pl.col("aa_end") >= pl.col("domain_start")))
    )
    .group_by(['id', 'region', 'aa_start', 'aa_end'])
    .agg([
        pl.col('mobi_curated_disorder_priority').max().alias('mobi_curated_disorder_priority'),
        pl.col('mobi_lip_full').max().alias('mobi_lip_full'),
        pl.col('ted_domain').max().alias('ted_domain'),
        pl.col('low_complexity_domain').max().alias('low_complexity_domain'),
    ])
    .collect()
)

overlap_df

shape: (1_222_450, 8)
┌─────────────┬────────────┬──────────┬────────┬────────────┬────────────┬────────────┬────────────┐
│ id          ┆ region     ┆ aa_start ┆ aa_end ┆ mobi_curat ┆ mobi_lip_f ┆ ted_domain ┆ low_comple │
│ ---         ┆ ---        ┆ ---      ┆ ---    ┆ ed_disorde ┆ ull        ┆ ---        ┆ xity_domai │
│ str         ┆ str        ┆ i32      ┆ i32    ┆ r_priority ┆ ---        ┆ bool       ┆ n          │
│             ┆            ┆          ┆        ┆ ---        ┆ bool       ┆            ┆ ---        │
│             ┆            ┆          ┆        ┆ bool       ┆            ┆            ┆ bool       │
╞═════════════╪════════════╪══════════╪════════╪════════════╪════════════╪════════════╪════════════╡
│ chr19:44672 ┆ ENSG000001 ┆ 66       ┆ 66     ┆ false      ┆ false      ┆ true       ┆ false      │
│ 738:C:T     ┆ 86567      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr1:143707 ┆ ENSG000001 ┆ 75       ┆ 75     ┆ false      ┆ false      ┆ true       ┆ false      │
│ 6:C:G       ┆ 79403      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr1:587822 ┆ ENSG000001 ┆ 260      ┆ 260    ┆ false      ┆ true       ┆ false      ┆ false      │
│ 92:A:G      ┆ 77606      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr1:180053 ┆ ENSG000001 ┆ 1660     ┆ 1660   ┆ false      ┆ true       ┆ false      ┆ false      │
│ 155:T:G     ┆ 35837      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr1:236894 ┆ ENSG000001 ┆ 1081     ┆ 1081   ┆ false      ┆ false      ┆ true       ┆ false      │
│ 393:T:G     ┆ 16984      ┆          ┆        ┆            ┆            ┆            ┆            │
│ …           ┆ …          ┆ …        ┆ …      ┆ …          ┆ …          ┆ …          ┆ …          │
│ chr17:75130 ┆ ENSG000001 ┆ 196      ┆ 196    ┆ false      ┆ false      ┆ true       ┆ false      │
│ 507:C:T     ┆ 25458      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr9:112404 ┆ ENSG000001 ┆ 32       ┆ 32     ┆ false      ┆ false      ┆ true       ┆ true       │
│ 073:G:A     ┆ 19471      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr1:377529 ┆ ENSG000001 ┆ 441      ┆ 441    ┆ false      ┆ true       ┆ true       ┆ false      │
│ 11:G:T      ┆ 83317      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr10:43118 ┆ ENSG000001 ┆ 770      ┆ 770    ┆ false      ┆ false      ┆ true       ┆ false      │
│ 397:G:A     ┆ 65731      ┆          ┆        ┆            ┆            ┆            ┆            │
│ chr9:193349 ┆ ENSG000001 ┆ 826      ┆ 826    ┆ false      ┆ false      ┆ true       ┆ false      │
│ 92:G:A      ┆ 37145      ┆          ┆        ┆            ┆            ┆            ┆            │
└─────────────┴────────────┴──────────┴────────┴────────────┴────────────┴────────────┴────────────┘

In [16]:
all_df = (
    anno_ukbgym_df.join(
        overlap_df.drop(['aa_start', 'aa_end']).lazy(),
        on=['id', 'region'],
        how='left'
    )
    .with_columns(
        pl.col('mobi_curated_disorder_priority').fill_null(False),
        pl.col('mobi_lip_full').fill_null(False),
        pl.col('ted_domain').fill_null(False),
        pl.col('low_complexity_domain').fill_null(False)
    )
    .unique()
    .collect(engine='streaming')
)

all_df.write_parquet(f'{anno_dir}/annotations_fillna_ukbgym.parquet')
all_df

shape: (77_094_936, 174)
┌─────────────┬───────┬───────────┬─────┬───┬─────────────┬─────────────┬────────────┬─────────────┐
│ id          ┆ chrom ┆ pos       ┆ ref ┆ … ┆ mobi_curate ┆ mobi_lip_fu ┆ ted_domain ┆ low_complex │
│ ---         ┆ ---   ┆ ---       ┆ --- ┆   ┆ d_disorder_ ┆ ll          ┆ ---        ┆ ity_domain  │
│ str         ┆ str   ┆ i64       ┆ str ┆   ┆ priority    ┆ ---         ┆ bool       ┆ ---         │
│             ┆       ┆           ┆     ┆   ┆ ---         ┆ bool        ┆            ┆ bool        │
│             ┆       ┆           ┆     ┆   ┆ bool        ┆             ┆            ┆             │
╞═════════════╪═══════╪═══════════╪═════╪═══╪═════════════╪═════════════╪════════════╪═════════════╡
│ chr6:152335 ┆ chr6  ┆ 152335898 ┆ C   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 898:C:G     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr10:96644 ┆ chr10 ┆ 96644301  ┆ A   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 301:A:T     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr6:151089 ┆ chr6  ┆ 151089318 ┆ A   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 318:A:G     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr8:219128 ┆ chr8  ┆ 21912872  ┆ G   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 72:G:T      ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr10:71541 ┆ chr10 ┆ 71541565  ┆ G   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 565:G:A     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ …           ┆ …     ┆ …         ┆ …   ┆ … ┆ …           ┆ …           ┆ …          ┆ …           │
│ chr7:154539 ┆ chr7  ┆ 154539700 ┆ G   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 700:G:A     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr7:148631 ┆ chr7  ┆ 1486310   ┆ C   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 0:C:T       ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr11:22211 ┆ chr11 ┆ 22211354  ┆ A   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 354:A:G     ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr17:17454 ┆ chr17 ┆ 1745457   ┆ G   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 57:G:A      ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
│ chr6:316579 ┆ chr6  ┆ 31657991  ┆ C   ┆ … ┆ false       ┆ false       ┆ false      ┆ false       │
│ 91:C:T      ┆       ┆           ┆     ┆   ┆             ┆             ┆            ┆             │
└─────────────┴───────┴───────────┴─────┴───┴─────────────┴─────────────┴────────────┴─────────────┘

In [18]:
!dx upload {anno_dir}/annotations_fillna_ukbgym.parquet --path project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/

[===========================================================>] Uploaded 6,532,575,175 of 6,532,575,175 bytes (100%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet==========================================================> ] Uploaded 6,425,673,728 of 6,532,575,175 bytes (98%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[===========>                                                ] Uploaded 1,275,068,416 of 6,532,575,175 bytes (20%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[===========>                                                ] Uploaded 1,291,845,632 of 6,532,575,175 bytes (20%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=============>                                              ] Uploaded 1,543,503,872 of 6,532,575,175 bytes (24%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=============>                                              ] Uploaded 1,560,281,088 of 6,532,575,175 bytes (24%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=================>                                          ] Uploaded 1,929,379,840 of 6,532,575,175 bytes (30%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[======================>                                     ] Uploaded 2,499,805,184 of 6,532,575,175 bytes (38%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[====================================>                       ] Uploaded 3,976,200,192 of 6,532,575,175 bytes (61%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=======================================================>    ] Uploaded 6,140,461,056 of 6,532,575,175 bytes (94%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[========================================================>   ] Uploaded 6,157,238,272 of 6,532,575,175 bytes (94%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=========================================================>  ] Uploaded 6,341,787,648 of 6,532,575,175 bytes (97%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[=========================================================>  ] Uploaded 6,358,564,864 of 6,532,575,175 bytes (97%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet[==========================================================> ] Uploaded 6,442,450,944 of 6,532,575,175 bytes (99%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym.parquet
ID                                file-J5bf8PjJg0yPz5VxjXjXbKx3
Class                             file
Project                           project-Gyp4fvjJg0yFZ374KvP9bGFJ
Folder                            /processed_data/wgs/qced_maf1e-3_loftee_olink_genes
Name                              annotations_fillna_ukbgym.parquet
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Sat Jan 17 11:28:15 2026
Created by                        shubhankar
Last modified                     Sat Jan 17 11:29:08 2026
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"

In [17]:
anno_ukbgym_df.collect()

shape: (77_094_866, 170)
┌─────────────┬───────┬───────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ id          ┆ chrom ┆ pos       ┆ ref ┆ … ┆ vep_cds_rel ┆ region_righ ┆ protein_pos ┆ amino_acid │
│ ---         ┆ ---   ┆ ---       ┆ --- ┆   ┆ axed        ┆ t           ┆ ition       ┆ s          │
│ str         ┆ str   ┆ i64       ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│             ┆       ┆           ┆     ┆   ┆ bool        ┆ str         ┆ str         ┆ str        │
╞═════════════╪═══════╪═══════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ chr1:228280 ┆ chr1  ┆ 228280185 ┆ A   ┆ … ┆ true        ┆ ENSG0000015 ┆ 2986/8925   ┆ E/V        │
│ 185:A:T     ┆       ┆           ┆     ┆   ┆             ┆ 4358        ┆             ┆            │
│ chr2:181886 ┆ chr2  ┆ 181886992 ┆ C   ┆ … ┆ false       ┆ ENSG0000013 ┆ null        ┆ null       │
│ 992:C:A     ┆       ┆           ┆     ┆   ┆             ┆ 8434        ┆             ┆            │
│ chr4:150790 ┆ chr4  ┆ 150790645 ┆ T   ┆ … ┆ false       ┆ ENSG0000019 ┆ null        ┆ null       │
│ 645:T:G     ┆       ┆           ┆     ┆   ┆             ┆ 8589        ┆             ┆            │
│ chr11:12880 ┆ chr11 ┆ 128809531 ┆ C   ┆ … ┆ false       ┆ ENSG0000015 ┆ null        ┆ null       │
│ 9531:C:A    ┆       ┆           ┆     ┆   ┆             ┆ 1702        ┆             ┆            │
│ chr14:52073 ┆ chr14 ┆ 52073025  ┆ T   ┆ … ┆ false       ┆ ENSG0000008 ┆ null        ┆ null       │
│ 025:T:C     ┆       ┆           ┆     ┆   ┆             ┆ 7303        ┆             ┆            │
│ …           ┆ …     ┆ …         ┆ …   ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ chr11:10104 ┆ chr11 ┆ 101046805 ┆ T   ┆ … ┆ false       ┆ ENSG0000008 ┆ null        ┆ null       │
│ 6805:T:G    ┆       ┆           ┆     ┆   ┆             ┆ 2175        ┆             ┆            │
│ chr8:865519 ┆ chr8  ┆ 86551946  ┆ G   ┆ … ┆ false       ┆ ENSG0000017 ┆ null        ┆ null       │
│ 46:G:A      ┆       ┆           ┆     ┆   ┆             ┆ 0289        ┆             ┆            │
│ chr1:204894 ┆ chr1  ┆ 204894740 ┆ CT  ┆ … ┆ false       ┆ ENSG0000016 ┆ null        ┆ null       │
│ 740:CT:C    ┆       ┆           ┆     ┆   ┆             ┆ 3531        ┆             ┆            │
│ chr1:182869 ┆ chr1  ┆ 18286934  ┆ C   ┆ … ┆ false       ┆ ENSG0000011 ┆ null        ┆ null       │
│ 34:C:A      ┆       ┆           ┆     ┆   ┆             ┆ 7154        ┆             ┆            │
│ chr14:24160 ┆ chr14 ┆ 24160490  ┆ A   ┆ … ┆ false       ┆ ENSG0000009 ┆ null        ┆ null       │
│ 490:A:G     ┆       ┆           ┆     ┆   ┆             ┆ 2098        ┆             ┆            │
└─────────────┴───────┴───────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘