In [1]:
import polars as pl
import pandas as pd
import pyranges as pr

/opt/modules/i12g/anaconda/envs/sl-ukg/lib/python3.12/site-packages/sorted_nearest/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

## Parse GTF

In [2]:
gtf_path = "/s/genomes/Gencode/Gencode_human/release_40/gencode.v40.annotation.gtf.gz"

gtf_pl = pl.read_csv(
    gtf_path,
    separator="\t",
    comment_prefix="#",
    has_header=False,
    new_columns=["Chromosome", "source", "Feature", "Start", "End", "score", "Strand", "frame", "attributes"]
)

gtf_pl = gtf_pl.with_row_index("row_nr")
gtf_pl

shape: (3_283_862, 10)
┌─────────┬────────────┬────────┬────────────┬───┬───────┬────────┬───────┬────────────────────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature    ┆ … ┆ score ┆ Strand ┆ frame ┆ attributes             │
│ ---     ┆ ---        ┆ ---    ┆ ---        ┆   ┆ ---   ┆ ---    ┆ ---   ┆ ---                    │
│ u64     ┆ str        ┆ str    ┆ str        ┆   ┆ str   ┆ str    ┆ str   ┆ str                    │
╞═════════╪════════════╪════════╪════════════╪═══╪═══════╪════════╪═══════╪════════════════════════╡
│ 0       ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000223972.5";   │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ t…                     │
│ 1       ┆ chr1       ┆ HAVANA ┆ gene       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000223972.5";   │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ g…                     │
│ 2       ┆ chr1       ┆ HAVANA ┆ transcript ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000223972.5";   │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ t…                     │
│ 3       ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000223972.5";   │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ t…                     │
│ 4       ┆ chr1       ┆ HAVANA ┆ transcript ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ "ENSG00000223972.5";   │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ t…                     │
│ …       ┆ …          ┆ …      ┆ …          ┆ … ┆ …     ┆ …      ┆ …     ┆ …                      │
│ 3283857 ┆ chrY       ┆ HAVANA ┆ transcript ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id "ENSG000002271 │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ 59.8_PAR…              │
│ 3283858 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id "ENSG000002271 │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ 59.8_PAR…              │
│ 3283859 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id "ENSG000002271 │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ 59.8_PAR…              │
│ 3283860 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id "ENSG000002271 │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ 59.8_PAR…              │
│ 3283861 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id "ENSG000002271 │
│         ┆            ┆        ┆            ┆   ┆       ┆        ┆       ┆ 59.8_PAR…              │
└─────────┴────────────┴────────┴────────────┴───┴───────┴────────┴───────┴────────────────────────┘

In [3]:
atts = (
    gtf_pl.select("row_nr", "attributes")
    
    .with_columns(
        attrs_list=pl.col("attributes").str.split("; ")
    )
    .explode("attrs_list")
    
    .with_columns(
        pl.col("attrs_list")
        .str.split_exact(" ", 1)
        .struct.rename_fields(["attribute", "value"])
        .alias("fields")
    ).unnest("fields")

    .with_columns(
        pl.col("value").str.strip_chars('"')
    )

    .pivot(
        index="row_nr",
        on="attribute",
        values="value",
        aggregate_function=pl.element().implode()
    )

    .with_columns(
        pl.col(pl.List).list.join(", ").str.strip_chars(";").replace("", None)
    )

    .with_columns(
        level = pl.col('level').cast(pl.Int32),
        exon_number = pl.col('exon_number').cast(pl.Int32),
    )
)

atts

shape: (3_283_862, 18)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬────────┐
│ row_nr  ┆ gene_id    ┆ transcript ┆ gene_type  ┆ … ┆ havana_tra ┆ ont       ┆ protein_i ┆ ccdsid │
│ ---     ┆ ---        ┆ _id        ┆ ---        ┆   ┆ nscript    ┆ ---       ┆ d         ┆ ---    │
│ u64     ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ str       ┆ ---       ┆ str    │
│         ┆            ┆ str        ┆            ┆   ┆ str        ┆           ┆ str       ┆        │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪════════╡
│ 0       ┆ ENSG000002 ┆ ENST000004 ┆ transcribe ┆ … ┆ OTTHUMT000 ┆ null      ┆ null      ┆ null   │
│         ┆ 23972.5    ┆ 56328.2    ┆ d_unproces ┆   ┆ 00362751.1 ┆           ┆           ┆        │
│         ┆            ┆            ┆ sed_pseudo ┆   ┆ "          ┆           ┆           ┆        │
│         ┆            ┆            ┆ …          ┆   ┆            ┆           ┆           ┆        │
│ 1       ┆ ENSG000002 ┆ null       ┆ transcribe ┆ … ┆ null       ┆ null      ┆ null      ┆ null   │
│         ┆ 23972.5    ┆            ┆ d_unproces ┆   ┆            ┆           ┆           ┆        │
│         ┆            ┆            ┆ sed_pseudo ┆   ┆            ┆           ┆           ┆        │
│         ┆            ┆            ┆ …          ┆   ┆            ┆           ┆           ┆        │
│ 2       ┆ ENSG000002 ┆ ENST000004 ┆ transcribe ┆ … ┆ OTTHUMT000 ┆ null      ┆ null      ┆ null   │
│         ┆ 23972.5    ┆ 56328.2    ┆ d_unproces ┆   ┆ 00362751.1 ┆           ┆           ┆        │
│         ┆            ┆            ┆ sed_pseudo ┆   ┆ "          ┆           ┆           ┆        │
│         ┆            ┆            ┆ …          ┆   ┆            ┆           ┆           ┆        │
│ 3       ┆ ENSG000002 ┆ ENST000004 ┆ transcribe ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 23972.5    ┆ 50305.2    ┆ d_unproces ┆   ┆ 00002844.2 ┆ 05, PGO:0 ┆           ┆        │
│         ┆            ┆            ┆ sed_pseudo ┆   ┆ "          ┆ 000019    ┆           ┆        │
│         ┆            ┆            ┆ …          ┆   ┆            ┆           ┆           ┆        │
│ 4       ┆ ENSG000002 ┆ ENST000004 ┆ transcribe ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 23972.5    ┆ 50305.2    ┆ d_unproces ┆   ┆ 00002844.2 ┆ 05, PGO:0 ┆           ┆        │
│         ┆            ┆            ┆ sed_pseudo ┆   ┆ "          ┆ 000019    ┆           ┆        │
│         ┆            ┆            ┆ …          ┆   ┆            ┆           ┆           ┆        │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …      │
│ 3283857 ┆ ENSG000002 ┆ ENST000005 ┆ unprocesse ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 27159.8_PA ┆ 07418.6_PA ┆ d_pseudoge ┆   ┆ 00058841.1 ┆ 05        ┆           ┆        │
│         ┆ R_Y        ┆ R_Y        ┆ ne         ┆   ┆ "          ┆           ┆           ┆        │
│ 3283858 ┆ ENSG000002 ┆ ENST000005 ┆ unprocesse ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 27159.8_PA ┆ 07418.6_PA ┆ d_pseudoge ┆   ┆ 00058841.1 ┆ 05        ┆           ┆        │
│         ┆ R_Y        ┆ R_Y        ┆ ne         ┆   ┆ "          ┆           ┆           ┆        │
│ 3283859 ┆ ENSG000002 ┆ ENST000005 ┆ unprocesse ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 27159.8_PA ┆ 07418.6_PA ┆ d_pseudoge ┆   ┆ 00058841.1 ┆ 05        ┆           ┆        │
│         ┆ R_Y        ┆ R_Y        ┆ ne         ┆   ┆ "          ┆           ┆           ┆        │
│ 3283860 ┆ ENSG000002 ┆ ENST000005 ┆ unprocesse ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 27159.8_PA ┆ 07418.6_PA ┆ d_pseudoge ┆   ┆ 00058841.1 ┆ 05        ┆           ┆        │
│         ┆ R_Y        ┆ R_Y        ┆ ne         ┆   ┆ "          ┆           ┆           ┆        │
│ 3283861 ┆ ENSG000002 ┆ ENST000005 ┆ unprocesse ┆ … ┆ OTTHUMT000 ┆ PGO:00000 ┆ null      ┆ null   │
│         ┆ 27159.8_PA ┆ 07418.6_PA ┆ d_pseudoge ┆   ┆ 00058841.1 ┆ 05        ┆           ┆        │
│         ┆ R_Y        ┆ R_Y        ┆ ne         ┆   ┆ "          ┆           ┆           ┆        │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴────────┘

In [5]:
gtf_exp = gtf_pl.join(atts, on='row_nr')
gtf_exp

shape: (3_283_862, 27)
┌─────────┬────────────┬────────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature    ┆ … ┆ havana_tran ┆ ont         ┆ protein_id ┆ ccdsid │
│ ---     ┆ ---        ┆ ---    ┆ ---        ┆   ┆ script      ┆ ---         ┆ ---        ┆ ---    │
│ u64     ┆ str        ┆ str    ┆ str        ┆   ┆ ---         ┆ str         ┆ str        ┆ str    │
│         ┆            ┆        ┆            ┆   ┆ str         ┆             ┆            ┆        │
╞═════════╪════════════╪════════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════╡
│ 0       ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ null        ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0362751.1"  ┆             ┆            ┆        │
│ 1       ┆ chr1       ┆ HAVANA ┆ gene       ┆ … ┆ null        ┆ null        ┆ null       ┆ null   │
│ 2       ┆ chr1       ┆ HAVANA ┆ transcript ┆ … ┆ OTTHUMT0000 ┆ null        ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0362751.1"  ┆             ┆            ┆        │
│ 3       ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0002844.2"  ┆ ,           ┆            ┆        │
│         ┆            ┆        ┆            ┆   ┆             ┆ PGO:0000019 ┆            ┆        │
│ 4       ┆ chr1       ┆ HAVANA ┆ transcript ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0002844.2"  ┆ ,           ┆            ┆        │
│         ┆            ┆        ┆            ┆   ┆             ┆ PGO:0000019 ┆            ┆        │
│ …       ┆ …          ┆ …      ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …      │
│ 3283857 ┆ chrY       ┆ HAVANA ┆ transcript ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0058841.1"  ┆             ┆            ┆        │
│ 3283858 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0058841.1"  ┆             ┆            ┆        │
│ 3283859 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0058841.1"  ┆             ┆            ┆        │
│ 3283860 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0058841.1"  ┆             ┆            ┆        │
│ 3283861 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT0000 ┆ PGO:0000005 ┆ null       ┆ null   │
│         ┆            ┆        ┆            ┆   ┆ 0058841.1"  ┆             ┆            ┆        │
└─────────┴────────────┴────────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────┘

In [6]:
a = gtf_exp['gene_type'].value_counts(sort=True)
a

shape: (40, 2)
┌─────────────────────────────────┬─────────┐
│ gene_type                       ┆ count   │
│ ---                             ┆ ---     │
│ str                             ┆ u64     │
╞═════════════════════════════════╪═════════╡
│ protein_coding                  ┆ 2909967 │
│ lncRNA                          ┆ 258393  │
│ processed_pseudogene            ┆ 32087   │
│ transcribed_unprocessed_pseudo… ┆ 27286   │
│ unprocessed_pseudogene          ┆ 13080   │
│ …                               ┆ …       │
│ translated_processed_pseudogen… ┆ 8       │
│ Mt_rRNA                         ┆ 6       │
│ IG_pseudogene                   ┆ 3       │
│ scRNA                           ┆ 3       │
│ vault_RNA                       ┆ 3       │
└─────────────────────────────────┴─────────┘

In [10]:
mane_exons = (
    gtf_exp
    .filter(
        (pl.col('gene_type') == 'protein_coding') |
        # (pl.col('gene_type').str.contains('pseudogene')) |
        (pl.col('Feature') == 'CDS')
    )
    .filter(pl.col('Feature') != 'transcript')
    .filter(pl.col('tag').str.contains('MANE_Select'))
    # .filter(pl.col('tag').str.contains('MANE_Select') | pl.col('tag').str.contains('Ensembl_canonical'))
)

mane_exons

shape: (467_200, 27)
┌─────────┬────────────┬────────┬────────────┬───┬──────────────┬──────┬─────────────┬─────────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature    ┆ … ┆ havana_trans ┆ ont  ┆ protein_id  ┆ ccdsid      │
│ ---     ┆ ---        ┆ ---    ┆ ---        ┆   ┆ cript        ┆ ---  ┆ ---         ┆ ---         │
│ u64     ┆ str        ┆ str    ┆ str        ┆   ┆ ---          ┆ str  ┆ str         ┆ str         │
│         ┆            ┆        ┆            ┆   ┆ str          ┆      ┆             ┆             │
╞═════════╪════════════╪════════╪════════════╪═══╪══════════════╪══════╪═════════════╪═════════════╡
│ 57      ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000049 ┆ null        │
│         ┆            ┆        ┆            ┆   ┆ 003223.4"    ┆      ┆ 3376.2      ┆             │
│ 60      ┆ chr1       ┆ HAVANA ┆ UTR        ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000049 ┆ null        │
│         ┆            ┆        ┆            ┆   ┆ 003223.4"    ┆      ┆ 3376.2      ┆             │
│ 61      ┆ chr1       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000049 ┆ null        │
│         ┆            ┆        ┆            ┆   ┆ 003223.4"    ┆      ┆ 3376.2      ┆             │
│ 62      ┆ chr1       ┆ HAVANA ┆ UTR        ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000049 ┆ null        │
│         ┆            ┆        ┆            ┆   ┆ 003223.4"    ┆      ┆ 3376.2      ┆             │
│ 63      ┆ chr1       ┆ HAVANA ┆ CDS        ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000049 ┆ null        │
│         ┆            ┆        ┆            ┆   ┆ 003223.4"    ┆      ┆ 3376.2      ┆             │
│ …       ┆ …          ┆ …      ┆ …          ┆ … ┆ …            ┆ …    ┆ …           ┆ …           │
│ 3283737 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000024 ┆ CCDS14771.4 │
│         ┆            ┆        ┆            ┆   ┆ 058981.1"    ┆      ┆ 4174.5      ┆             │
│ 3283742 ┆ chrY       ┆ HAVANA ┆ CDS        ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000024 ┆ CCDS14771.4 │
│         ┆            ┆        ┆            ┆   ┆ 058981.1"    ┆      ┆ 4174.5      ┆             │
│ 3283743 ┆ chrY       ┆ HAVANA ┆ exon       ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000024 ┆ CCDS14771.4 │
│         ┆            ┆        ┆            ┆   ┆ 058981.1"    ┆      ┆ 4174.5      ┆             │
│ 3283747 ┆ chrY       ┆ HAVANA ┆ stop_codon ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000024 ┆ CCDS14771.4 │
│         ┆            ┆        ┆            ┆   ┆ 058981.1"    ┆      ┆ 4174.5      ┆             │
│ 3283748 ┆ chrY       ┆ HAVANA ┆ UTR        ┆ … ┆ OTTHUMT00000 ┆ null ┆ ENSP0000024 ┆ CCDS14771.4 │
│         ┆            ┆        ┆            ┆   ┆ 058981.1"    ┆      ┆ 4174.5      ┆             │
└─────────┴────────────┴────────┴────────────┴───┴──────────────┴──────┴─────────────┴─────────────┘

In [11]:
# One transcript per gene
mane_exons[['gene_id', 'gene_name', 'transcript_id']].unique()['transcript_id'].value_counts(sort=True)

shape: (18_600, 2)
┌────────────────────┬───────┐
│ transcript_id      ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u64   │
╞════════════════════╪═══════╡
│ ENST00000561421.6  ┆ 1     │
│ ENST00000342136.9  ┆ 1     │
│ ENST00000397062.8  ┆ 1     │
│ ENST00000614987.5  ┆ 1     │
│ ENST00000683969.1  ┆ 1     │
│ …                  ┆ …     │
│ ENST00000444304.3  ┆ 1     │
│ ENST00000263736.5  ┆ 1     │
│ ENST00000184956.11 ┆ 1     │
│ ENST00000324631.13 ┆ 1     │
│ ENST00000329146.9  ┆ 1     │
└────────────────────┴───────┘

In [12]:
a = mane_exons['gene_type'].value_counts(sort=True)
a

shape: (1, 2)
┌────────────────┬────────┐
│ gene_type      ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u64    │
╞════════════════╪════════╡
│ protein_coding ┆ 467200 │
└────────────────┴────────┘

In [13]:
b = mane_exons['Feature'].value_counts(sort=True)
b

shape: (6, 2)
┌────────────────┬────────┐
│ Feature        ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u64    │
╞════════════════╪════════╡
│ exon           ┆ 196563 │
│ CDS            ┆ 186748 │
│ UTR            ┆ 46605  │
│ start_codon    ┆ 18631  │
│ stop_codon     ┆ 18619  │
│ Selenocysteine ┆ 34     │
└────────────────┴────────┘

In [14]:
non_mane_exons = (
    gtf_exp
    .filter(
        (pl.col('gene_type') == 'protein_coding') |
        # (pl.col('gene_type').str.contains('pseudogene')) |
        (pl.col('Feature') == 'CDS')
    )
    .filter(pl.col('Feature') != 'transcript')
    .filter(~pl.col('tag').str.contains('MANE_Select'))
)

non_mane_exons

shape: (1_841_042, 27)
┌─────────┬────────────┬────────┬─────────────┬───┬────────────────┬──────┬───────────────┬────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature     ┆ … ┆ havana_transcr ┆ ont  ┆ protein_id    ┆ ccdsid │
│ ---     ┆ ---        ┆ ---    ┆ ---         ┆   ┆ ipt            ┆ ---  ┆ ---           ┆ ---    │
│ u64     ┆ str        ┆ str    ┆ str         ┆   ┆ ---            ┆ str  ┆ str           ┆ str    │
│         ┆            ┆        ┆             ┆   ┆ str            ┆      ┆               ┆        │
╞═════════╪════════════╪════════╪═════════════╪═══╪════════════════╪══════╪═══════════════╪════════╡
│ 941     ┆ chr1       ┆ HAVANA ┆ exon        ┆ … ┆ null           ┆ null ┆ ENSP000004806 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 78.2          ┆        │
│ 946     ┆ chr1       ┆ HAVANA ┆ UTR         ┆ … ┆ null           ┆ null ┆ ENSP000004806 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 78.2          ┆        │
│ 948     ┆ chr1       ┆ HAVANA ┆ CDS         ┆ … ┆ null           ┆ null ┆ ENSP000004806 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 78.2          ┆        │
│ 950     ┆ chr1       ┆ HAVANA ┆ start_codon ┆ … ┆ null           ┆ null ┆ ENSP000004806 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 78.2          ┆        │
│ 951     ┆ chr1       ┆ HAVANA ┆ exon        ┆ … ┆ OTTHUMT0000009 ┆ null ┆ ENSP000003931 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆ 7862.5"        ┆      ┆ 81.1          ┆        │
│ …       ┆ …          ┆ …      ┆ …           ┆ … ┆ …              ┆ …    ┆ …             ┆ …      │
│ 3283850 ┆ chrY       ┆ HAVANA ┆ exon        ┆ … ┆ OTTHUMT0000005 ┆ null ┆ null          ┆ null   │
│         ┆            ┆        ┆             ┆   ┆ 8837.1"        ┆      ┆               ┆        │
│ 3283851 ┆ chrY       ┆ HAVANA ┆ exon        ┆ … ┆ OTTHUMT0000005 ┆ null ┆ null          ┆ null   │
│         ┆            ┆        ┆             ┆   ┆ 8839.1"        ┆      ┆               ┆        │
│ 3283852 ┆ chrY       ┆ HAVANA ┆ exon        ┆ … ┆ OTTHUMT0000005 ┆ null ┆ null          ┆ null   │
│         ┆            ┆        ┆             ┆   ┆ 8838.1"        ┆      ┆               ┆        │
│ 3283853 ┆ chrY       ┆ HAVANA ┆ stop_codon  ┆ … ┆ null           ┆ null ┆ ENSP000005045 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 57.1          ┆        │
│ 3283854 ┆ chrY       ┆ HAVANA ┆ UTR         ┆ … ┆ null           ┆ null ┆ ENSP000005045 ┆ null   │
│         ┆            ┆        ┆             ┆   ┆                ┆      ┆ 57.1          ┆        │
└─────────┴────────────┴────────┴─────────────┴───┴────────────────┴──────┴───────────────┴────────┘

In [15]:
non_mane_exons[['gene_id', 'gene_name', 'transcript_id']].unique()['transcript_id'].value_counts(sort=True)

shape: (93_089, 2)
┌────────────────────┬───────┐
│ transcript_id      ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u64   │
╞════════════════════╪═══════╡
│ null               ┆ 6695  │
│ ENST00000392884.2  ┆ 1     │
│ ENST00000457869.1  ┆ 1     │
│ ENST00000534943.5  ┆ 1     │
│ ENST00000299613.10 ┆ 1     │
│ …                  ┆ …     │
│ ENST00000688981.1  ┆ 1     │
│ ENST00000295868.6  ┆ 1     │
│ ENST00000632951.1  ┆ 1     │
│ ENST00000585315.5  ┆ 1     │
│ ENST00000695476.1  ┆ 1     │
└────────────────────┴───────┘

In [17]:
non_mane_cds = non_mane_exons.filter(pl.col('Feature') == 'CDS')
non_mane_cds

shape: (622_568, 27)
┌─────────┬────────────┬────────┬─────────┬───┬─────────────────┬──────┬─────────────────┬─────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature ┆ … ┆ havana_transcri ┆ ont  ┆ protein_id      ┆ ccdsid  │
│ ---     ┆ ---        ┆ ---    ┆ ---     ┆   ┆ pt              ┆ ---  ┆ ---             ┆ ---     │
│ u64     ┆ str        ┆ str    ┆ str     ┆   ┆ ---             ┆ str  ┆ str             ┆ str     │
│         ┆            ┆        ┆         ┆   ┆ str             ┆      ┆                 ┆         │
╞═════════╪════════════╪════════╪═════════╪═══╪═════════════════╪══════╪═════════════════╪═════════╡
│ 948     ┆ chr1       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000480678 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .2              ┆         │
│ 958     ┆ chr1       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000480678 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .2              ┆         │
│ 965     ┆ chr1       ┆ HAVANA ┆ CDS     ┆ … ┆ OTTHUMT00000276 ┆ null ┆ ENSP00000342313 ┆ CCDS2.2 │
│         ┆            ┆        ┆         ┆   ┆ 866.3"          ┆      ┆ .3              ┆         │
│ 966     ┆ chr1       ┆ HAVANA ┆ CDS     ┆ … ┆ OTTHUMT00000097 ┆ null ┆ ENSP00000393181 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 862.5"          ┆      ┆ .1              ┆         │
│ 967     ┆ chr1       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000484643 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
│ …       ┆ …          ┆ …      ┆ …       ┆ … ┆ …               ┆ …    ┆ …               ┆ …       │
│ 3283809 ┆ chrY       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000504557 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
│ 3283819 ┆ chrY       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000504557 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
│ 3283835 ┆ chrY       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000504557 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
│ 3283840 ┆ chrY       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000504557 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
│ 3283846 ┆ chrY       ┆ HAVANA ┆ CDS     ┆ … ┆ null            ┆ null ┆ ENSP00000504557 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .1              ┆         │
└─────────┴────────────┴────────┴─────────┴───┴─────────────────┴──────┴─────────────────┴─────────┘

In [18]:
non_mane_exonic = non_mane_exons.filter(pl.col('Feature') == 'exon')
non_mane_exonic

shape: (831_695, 27)
┌─────────┬────────────┬────────┬─────────┬───┬─────────────────┬──────┬─────────────────┬─────────┐
│ row_nr  ┆ Chromosome ┆ source ┆ Feature ┆ … ┆ havana_transcri ┆ ont  ┆ protein_id      ┆ ccdsid  │
│ ---     ┆ ---        ┆ ---    ┆ ---     ┆   ┆ pt              ┆ ---  ┆ ---             ┆ ---     │
│ u64     ┆ str        ┆ str    ┆ str     ┆   ┆ ---             ┆ str  ┆ str             ┆ str     │
│         ┆            ┆        ┆         ┆   ┆ str             ┆      ┆                 ┆         │
╞═════════╪════════════╪════════╪═════════╪═══╪═════════════════╪══════╪═════════════════╪═════════╡
│ 941     ┆ chr1       ┆ HAVANA ┆ exon    ┆ … ┆ null            ┆ null ┆ ENSP00000480678 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆                 ┆      ┆ .2              ┆         │
│ 951     ┆ chr1       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000097 ┆ null ┆ ENSP00000393181 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 862.5"          ┆      ┆ .1              ┆         │
│ 954     ┆ chr1       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000276 ┆ null ┆ ENSP00000342313 ┆ CCDS2.2 │
│         ┆            ┆        ┆         ┆   ┆ 866.3"          ┆      ┆ .3              ┆         │
│ 959     ┆ chr1       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000276 ┆ null ┆ ENSP00000342313 ┆ CCDS2.2 │
│         ┆            ┆        ┆         ┆   ┆ 866.3"          ┆      ┆ .3              ┆         │
│ 960     ┆ chr1       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000097 ┆ null ┆ ENSP00000393181 ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 862.5"          ┆      ┆ .1              ┆         │
│ …       ┆ …          ┆ …      ┆ …       ┆ … ┆ …               ┆ …    ┆ …               ┆ …       │
│ 3283848 ┆ chrY       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000058 ┆ null ┆ null            ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 835.1"          ┆      ┆                 ┆         │
│ 3283849 ┆ chrY       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000058 ┆ null ┆ null            ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 834.1"          ┆      ┆                 ┆         │
│ 3283850 ┆ chrY       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000058 ┆ null ┆ null            ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 837.1"          ┆      ┆                 ┆         │
│ 3283851 ┆ chrY       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000058 ┆ null ┆ null            ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 839.1"          ┆      ┆                 ┆         │
│ 3283852 ┆ chrY       ┆ HAVANA ┆ exon    ┆ … ┆ OTTHUMT00000058 ┆ null ┆ null            ┆ null    │
│         ┆            ┆        ┆         ┆   ┆ 838.1"          ┆      ┆                 ┆         │
└─────────┴────────────┴────────┴─────────┴───┴─────────────────┴──────┴─────────────────┴─────────┘

### Convert regions to pyranges

In [19]:
mane_exons_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'exon').to_pandas()).merge()
mane_exons_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 65419     | 65433     | +            |
| chr1         | 65520     | 65573     | +            |
| chr1         | 69037     | 71585     | +            |
| chr1         | 923923    | 924948    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 25043946  | 25044064  | -            |
| chrY         | 25048474  | 25048610  | -            |
| chrY         | 25051676  | 25051798  | -            |
| chrY         | 25052074  | 25052104  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 196,317 rows and 4 columns from 24 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [20]:
mane_cds_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'CDS').to_pandas()).merge()
mane_utr_pr = pr.PyRanges(mane_exons.filter(pl.col('Feature') == 'UTR').to_pandas()).merge()

mane_cds_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 65565     | 65573     | +            |
| chr1         | 69037     | 70005     | +            |
| chr1         | 924432    | 924948    | +            |
| chr1         | 925922    | 926013    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 25038101  | 25038116  | -            |
| chrY         | 25038809  | 25038914  | -            |
| chrY         | 25041769  | 25041886  | -            |
| chrY         | 25043946  | 25044023  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 186,596 rows and 4 columns from 24 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [21]:
non_mane_exons_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'exon').to_pandas()).merge()
non_mane_exons_pr = non_mane_exons_pr.subtract(mane_exons_pr)
non_mane_exons_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 925150    | 925189    | +            |
| chr1         | 925731    | 925800    | +            |
| chr1         | 939272    | 939275    | +            |
| chr1         | 939412    | 939460    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 24045229  | 24045676  | -            |
| chrY         | 24813393  | 24813492  | -            |
| chrY         | 25052151  | 25052219  | -            |
| chrY         | 25062393  | 25062548  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 70,224 rows and 4 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

In [22]:
non_mane_cds_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'CDS').to_pandas()).merge()
non_mane_cds_pr = non_mane_cds_pr.subtract(mane_cds_pr)

non_mane_utr_pr = pr.PyRanges(non_mane_exons.filter(pl.col('Feature') == 'UTR').to_pandas()).merge()
non_mane_utr_pr = non_mane_utr_pr.subtract(mane_utr_pr)

non_mane_cds_pr

+--------------+-----------+-----------+--------------+
| Chromosome   | Start     | End       | Strand       |
| (category)   | (int64)   | (int64)   | (category)   |
|--------------+-----------+-----------+--------------|
| chr1         | 939272    | 939275    | +            |
| chr1         | 939412    | 939460    | +            |
| chr1         | 943808    | 943908    | +            |
| chr1         | 963032    | 963109    | +            |
| ...          | ...       | ...       | ...          |
| chrY         | 23682010  | 23682265  | -            |
| chrY         | 23691757  | 23691872  | -            |
| chrY         | 23694459  | 23694527  | -            |
| chrY         | 24045607  | 24045676  | -            |
+--------------+-----------+-----------+--------------+
Stranded PyRanges object has 33,718 rows and 4 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.

## Merge with UKBBGym annotations

In [42]:
# Download annotations file

anno_dir = '/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated/'
anno_file = "annotations_fillna_ukbgym"

!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fillna_ukbgym.parquet -o {anno_dir}

anno_df = pl.scan_parquet(f'{anno_dir}/{anno_file}.parquet')
anno_df.head().collect()

Error: path "/s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_lofte
e_olink_genes_EURunrelated/annotations_fillna_ukbgym.parquet" already exists
but -f/--overwrite was not set

shape: (5, 188)
┌──────────────┬───────┬───────────┬─────┬───┬───────────┬──────────────┬─────────────┬────────────┐
│ id           ┆ chrom ┆ pos       ┆ ref ┆ … ┆ encode_tf ┆ encode_ca-tf ┆ encode_pels ┆ encode_pls │
│ ---          ┆ ---   ┆ ---       ┆ --- ┆   ┆ ---       ┆ ---          ┆ ---         ┆ ---        │
│ str          ┆ str   ┆ i64       ┆ str ┆   ┆ bool      ┆ bool         ┆ bool        ┆ bool       │
╞══════════════╪═══════╪═══════════╪═════╪═══╪═══════════╪══════════════╪═════════════╪════════════╡
│ chr2:2613652 ┆ chr2  ┆ 26136528  ┆ A   ┆ … ┆ false     ┆ false        ┆ false       ┆ false      │
│ 8:A:G        ┆       ┆           ┆     ┆   ┆           ┆              ┆             ┆            │
│ chr2:2337711 ┆ chr2  ┆ 233771145 ┆ C   ┆ … ┆ false     ┆ false        ┆ false       ┆ false      │
│ 45:C:T       ┆       ┆           ┆     ┆   ┆           ┆              ┆             ┆            │
│ chr12:101117 ┆ chr12 ┆ 101117325 ┆ T   ┆ … ┆ false     ┆ false        ┆ false       ┆ false      │
│ 325:T:G      ┆       ┆           ┆     ┆   ┆           ┆              ┆             ┆            │
│ chr10:252359 ┆ chr10 ┆ 25235985  ┆ T   ┆ … ┆ false     ┆ false        ┆ false       ┆ false      │
│ 85:T:G       ┆       ┆           ┆     ┆   ┆           ┆              ┆             ┆            │
│ chr7:8044742 ┆ chr7  ┆ 80447426  ┆ C   ┆ … ┆ false     ┆ false        ┆ false       ┆ false      │
│ 6:C:CA       ┆       ┆           ┆     ┆   ┆           ┆              ┆             ┆            │
└──────────────┴───────┴───────────┴─────┴───┴───────────┴──────────────┴─────────────┴────────────┘

In [29]:
anno = (
    anno_df
    .with_columns(
        Chromosome = pl.col('chrom'),
        Start = pl.col('pos') - 1,
        End = pl.col('pos') - 1 + pl.col('ref').str.len_chars(),
        gene = pl.col('region')
    )
    .select(['id', 'Chromosome', 'Start', 'End', 'ref', 'alt', 'gene'])
    .collect(engine='streaming')
)

anno_pr = pr.PyRanges(anno.to_pandas())
anno_pr

+----------------------+--------------+-----------+-----------+-------+
| id                   | Chromosome   | Start     | End       | +3    |
| (object)             | (category)   | (int64)   | (int64)   | ...   |
|----------------------+--------------+-----------+-----------+-------|
| chr1:39747598:G:A    | chr1         | 39747597  | 39747598  | ...   |
| chr1:183587665:G:A   | chr1         | 183587664 | 183587665 | ...   |
| chr1:231540122:C:CA  | chr1         | 231540121 | 231540122 | ...   |
| chr1:14401409:C:A    | chr1         | 14401408  | 14401409  | ...   |
| ...                  | ...          | ...       | ...       | ...   |
| chr22:49768435:C:T   | chr22        | 49768434  | 49768435  | ...   |
| chr22:41397712:A:G   | chr22        | 41397711  | 41397712  | ...   |
| chr22:20115089:TCA:T | chr22        | 20115088  | 20115091  | ...   |
| chr22:24232667:C:T   | chr22        | 24232666  | 24232667  | ...   |
+----------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 77,094,936 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [30]:
mane_exons_pr_vars = anno_pr.overlap(mane_exons_pr)#.df['gene'].value_counts()
mane_cds_pr_vars = anno_pr.overlap(mane_cds_pr)
mane_utr_pr_vars = anno_pr.overlap(mane_utr_pr)

mane_cds_pr_vars

+--------------------+--------------+-----------+-----------+-------+
| id                 | Chromosome   | Start     | End       | +3    |
| (object)           | (category)   | (int64)   | (int64)   | ...   |
|--------------------+--------------+-----------+-----------+-------|
| chr1:185734879:G:A | chr1         | 185734878 | 185734879 | ...   |
| chr1:154176167:T:C | chr1         | 154176166 | 154176167 | ...   |
| chr1:236835683:C:G | chr1         | 236835682 | 236835683 | ...   |
| chr1:202752969:G:A | chr1         | 202752968 | 202752969 | ...   |
| ...                | ...          | ...       | ...       | ...   |
| chr22:50521562:A:G | chr22        | 50521561  | 50521562  | ...   |
| chr22:41117603:G:T | chr22        | 41117602  | 41117603  | ...   |
| chr22:50455525:A:G | chr22        | 50455524  | 50455525  | ...   |
| chr22:24186085:A:G | chr22        | 24186084  | 24186085  | ...   |
+--------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 2,259,804 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [31]:
# Convert to polars and add MANE / non-MANE flags

non_mane_exons_pr_vars = anno_pr.overlap(non_mane_exons_pr)
non_mane_cds_pr_vars = anno_pr.overlap(non_mane_cds_pr)
non_mane_utr_pr_vars = anno_pr.overlap(non_mane_utr_pr)

non_mane_cds_pr_vars

+---------------------+--------------+-----------+-----------+-------+
| id                  | Chromosome   | Start     | End       | +3    |
| (object)            | (category)   | (int64)   | (int64)   | ...   |
|---------------------+--------------+-----------+-----------+-------|
| chr1:186375156:C:T  | chr1         | 186375155 | 186375156 | ...   |
| chr1:21868891:C:T   | chr1         | 21868890  | 21868891  | ...   |
| chr1:205073509:G:A  | chr1         | 205073508 | 205073509 | ...   |
| chr1:109622212:TG:T | chr1         | 109622211 | 109622213 | ...   |
| ...                 | ...          | ...       | ...       | ...   |
| chr22:20126484:G:A  | chr22        | 20126483  | 20126484  | ...   |
| chr22:37142564:G:A  | chr22        | 37142563  | 37142564  | ...   |
| chr22:44679837:G:A  | chr22        | 44679836  | 44679837  | ...   |
| chr22:50447874:C:G  | chr22        | 50447873  | 50447874  | ...   |
+---------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 196,813 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [32]:
# Convert to polars and add MANE / non-MANE flags

mane_exons_pl = pl.from_pandas(mane_exons_pr_vars.df).with_columns(MANE_exonic = True).select(['id', 'gene', 'MANE_exonic'])
mane_cds_pl = pl.from_pandas(mane_cds_pr_vars.df).with_columns(MANE_CDS = True).select(['id', 'gene', 'MANE_CDS'])
mane_utr_pl = pl.from_pandas(mane_utr_pr_vars.df).with_columns(MANE_UTR = True).select(['id', 'gene', 'MANE_UTR'])

non_mane_exons_pl = pl.from_pandas(non_mane_exons_pr_vars.df).with_columns(non_MANE_exonic = True).select(['id', 'gene', 'non_MANE_exonic'])
non_mane_cds_pl = pl.from_pandas(non_mane_cds_pr_vars.df).with_columns(non_MANE_CDS = True).select(['id', 'gene', 'non_MANE_CDS'])
non_mane_utr_pl = pl.from_pandas(non_mane_utr_pr_vars.df).with_columns(non_MANE_UTR = True).select(['id', 'gene', 'non_MANE_UTR'])

non_mane_exons_pl

shape: (1_563_712, 3)
┌────────────────────┬─────────────────┬─────────────────┐
│ id                 ┆ gene            ┆ non_MANE_exonic │
│ ---                ┆ ---             ┆ ---             │
│ str                ┆ str             ┆ bool            │
╞════════════════════╪═════════════════╪═════════════════╡
│ chr1:28539295:A:AC ┆ ENSG00000180198 ┆ true            │
│ chr1:75727382:T:C  ┆ ENSG00000117054 ┆ true            │
│ chr1:206769609:G:A ┆ ENSG00000136634 ┆ true            │
│ chr1:169106528:A:T ┆ ENSG00000143153 ┆ true            │
│ chr1:207768516:A:G ┆ ENSG00000117335 ┆ true            │
│ …                  ┆ …               ┆ …               │
│ chr22:26292317:G:A ┆ ENSG00000100095 ┆ true            │
│ chr22:44679837:G:A ┆ ENSG00000186654 ┆ true            │
│ chr22:50447874:C:G ┆ ENSG00000100241 ┆ true            │
│ chr22:50455940:G:C ┆ ENSG00000100241 ┆ true            │
│ chr22:39963933:A:G ┆ ENSG00000100351 ┆ true            │
└────────────────────┴─────────────────┴─────────────────┘

In [41]:
mane_annos = (
    anno_df
    .with_columns(
        gene = pl.col('region').cast(pl.Utf8)
    )
    .select(['id', 'gene'])
    .collect(engine='streaming')

    .join(mane_exons_pl, on=['id', 'gene'], how='left')
    .join(mane_cds_pl, on=['id', 'gene'], how='left')
    .join(mane_utr_pl, on=['id', 'gene'], how='left')
    .join(non_mane_exons_pl, on=['id', 'gene'], how='left')
    .join(non_mane_cds_pl, on=['id', 'gene'], how='left')
    .join(non_mane_utr_pl, on=['id', 'gene'], how='left')

    .fill_null(False)
)

mane_annos = (
    mane_annos
    .unique()
    .rename({c:c.lower() for c in mane_annos.columns})
    .rename({'gene':'region'})
)

mane_annos

shape: (74_534_850, 8)
┌────────────┬────────────┬────────────┬──────────┬──────────┬────────────┬────────────┬───────────┐
│ id         ┆ region     ┆ mane_exoni ┆ mane_cds ┆ mane_utr ┆ non_mane_e ┆ non_mane_c ┆ non_mane_ │
│ ---        ┆ ---        ┆ c          ┆ ---      ┆ ---      ┆ xonic      ┆ ds         ┆ utr       │
│ str        ┆ str        ┆ ---        ┆ bool     ┆ bool     ┆ ---        ┆ ---        ┆ ---       │
│            ┆            ┆ bool       ┆          ┆          ┆ bool       ┆ bool       ┆ bool      │
╞════════════╪════════════╪════════════╪══════════╪══════════╪════════════╪════════════╪═══════════╡
│ chr19:4341 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 3945:G:T   ┆ 31126      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr10:5170 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 8452:A:G   ┆ 85532      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr10:2535 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 7798:A:T   ┆ 51025      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr3:12429 ┆ ENSG000001 ┆ true       ┆ true     ┆ false    ┆ false      ┆ false      ┆ false     │
│ 8887:C:T   ┆ 60145      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr21:3634 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 0861:TTCTG ┆ 59256      ┆            ┆          ┆          ┆            ┆            ┆           │
│ :T         ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …        ┆ …          ┆ …          ┆ …         │
│ chr1:32794 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 941:T:C    ┆ 34684      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr7:37919 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 147:C:T    ┆ 06483      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr20:5901 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 9884:G:A   ┆ 01162      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr11:2226 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 9447:A:C   ┆ 71714      ┆            ┆          ┆          ┆            ┆            ┆           │
│ chr11:1021 ┆ ENSG000001 ┆ false      ┆ false    ┆ false    ┆ false      ┆ false      ┆ false     │
│ 98759:C:T  ┆ 37693      ┆            ┆          ┆          ┆            ┆            ┆           │
└────────────┴────────────┴────────────┴──────────┴──────────┴────────────┴────────────┴───────────┘

In [43]:
anno_df.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u64      │
╞══════════╡
│ 77094936 │
└──────────┘

In [44]:
anno_df = anno_df.join(mane_annos.lazy(), on=['id', 'region'], how='left').fill_null(False)

anno_df.sink_parquet(f'{anno_dir}/{anno_file}_with_mane.parquet')

In [45]:
!dx upload {anno_dir}/{anno_file}_with_mane.parquet --path project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/

[===========================================================>] Uploaded 7,239,965,276 of 7,239,965,276 bytes (100%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym_with_mane.parquet=========>                                                  ] Uploaded 1,207,959,552 of 7,239,965,276 bytes (17%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym_with_mane.parquet[=========>                                                  ] Uploaded 1,224,736,768 of 7,239,965,276 bytes (17%) /s/project/deeprvat_wgs/input_data/annotations/qced_maf1e-3_loftee_olink_genes_EURunrelated//annotations_fillna_ukbgym_with_mane.parquet
ID                                file-J5y8yXjJg0yBkzQPFg1Ky0B0
Class                             file
Project                           project-Gyp4fvjJg0yFZ374KvP9bGFJ
Folder                            /processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_l
                                  oftee_olink_genes_EURunrelated
Name                              annotations_fillna_ukbgym_with_mane.parquet
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Fri Jan 30 12:00:27 2026
Created by                        shubhankar
Last modified                     Fri Jan 30 12:00:56 2026
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"