In [1]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm

from plotnine import *
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from scipy.stats import spearmanr

In [ ]:
anno = pl.read_parquet('/home/dnanexus/data_dir/genebass394genes_olink371genes_annotated_MANE_CADD_251110.parquet')
anno

shape: (25_373_614, 163)
┌────────────┬────────────┬───────────┬───────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id         ┆ region     ┆ gene_name ┆ chrom ┆ … ┆ pangolin_s ┆ delta_sco ┆ absplice_ ┆ absplice2 │
│ ---        ┆ ---        ┆ ---       ┆ ---   ┆   ┆ core       ┆ re        ┆ dna_max   ┆ _max      │
│ str        ┆ str        ┆ str       ┆ str   ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆           ┆       ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪═══════════╪═══════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ chr1:15862 ┆ ENSG000001 ┆ SPTA1     ┆ chr1  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.001     ┆ 0.000033  │
│ 9580:T:C   ┆ 63554      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr1:15861 ┆ ENSG000001 ┆ SPTA1     ┆ chr1  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.001     ┆ 0.000033  │
│ 8272:G:A   ┆ 63554      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr1:15861 ┆ ENSG000001 ┆ SPTA1     ┆ chr1  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.001     ┆ 0.000033  │
│ 8428:C:T   ┆ 63554      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr1:15862 ┆ ENSG000001 ┆ SPTA1     ┆ chr1  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.001     ┆ 0.000033  │
│ 2449:T:G   ┆ 63554      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr1:15862 ┆ ENSG000001 ┆ SPTA1     ┆ chr1  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.001     ┆ 0.000033  │
│ 4418:C:T   ┆ 63554      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …     ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ chr2:23371 ┆ ENSG000002 ┆ UGT1A9    ┆ chr2  ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 3631:ATGCT ┆ 41119      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ C:A        ┆            ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr9:13723 ┆ ENSG000001 ┆ SLC34A3   ┆ chr9  ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 0376:CT:C  ┆ 98569      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr14:7458 ┆ ENSG000001 ┆ LTBP2     ┆ chr14 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 5160:CCTGC ┆ 19681      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ CCATGAACA: ┆            ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr2:65311 ┆ ENSG000001 ┆ SPRED2    ┆ chr2  ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 406:G:GT   ┆ 98369      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ chr2:23368 ┆ ENSG000002 ┆ UGT1A9    ┆ chr2  ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 4956:TGAAA ┆ 41119      ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
│ A:T        ┆            ┆           ┆       ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
a = pl.read_parquet('/home/dnanexus/data_dir/flashzoi_proximal_variants.parquet')
a

shape: (310_074, 13)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Chromosome ┆ Start    ┆ End      ┆ gene_name ┆ … ┆ gene_id   ┆ dist_to_t ┆ unique_id ┆ __index_l │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ss        ┆ ---       ┆ evel_0__  │
│ str        ┆ i64      ┆ i64      ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆           ┆ i64       ┆           ┆ i64       │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr1       ┆ 3390371  ┆ 3914659  ┆ TP73      ┆ … ┆ ENSG00000 ┆ -392      ┆ chr1:3652 ┆ 0         │
│            ┆          ┆          ┆           ┆   ┆ 078900    ┆           ┆ 123:G:A_E ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ NSG000000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 789…      ┆           │
│ chr1       ┆ 3390371  ┆ 3914659  ┆ TP73      ┆ … ┆ ENSG00000 ┆ -73       ┆ chr1:3652 ┆ 1         │
│            ┆          ┆          ┆           ┆   ┆ 078900    ┆           ┆ 442:G:T_E ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ NSG000000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 789…      ┆           │
│ chr1       ┆ 3390371  ┆ 3914659  ┆ TP73      ┆ … ┆ ENSG00000 ┆ 451       ┆ chr1:3652 ┆ 2         │
│            ┆          ┆          ┆           ┆   ┆ 078900    ┆           ┆ 966:G:T_E ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ NSG000000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 789…      ┆           │
│ chr1       ┆ 3390371  ┆ 3914659  ┆ TP73      ┆ … ┆ ENSG00000 ┆ -100      ┆ chr1:3652 ┆ 3         │
│            ┆          ┆          ┆           ┆   ┆ 078900    ┆           ┆ 415:C:G_E ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ NSG000000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 789…      ┆           │
│ chr1       ┆ 3390371  ┆ 3914659  ┆ TP73      ┆ … ┆ ENSG00000 ┆ 28        ┆ chr1:3652 ┆ 4         │
│            ┆          ┆          ┆           ┆   ┆ 078900    ┆           ┆ 543:C:G_E ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ NSG000000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 789…      ┆           │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ chr22      ┆ 50267888 ┆ 50792176 ┆ TYMP      ┆ … ┆ ENSG00000 ┆ -480      ┆ chr22:505 ┆ 310574    │
│            ┆          ┆          ┆           ┆   ┆ 025708    ┆           ┆ 30512:G:A ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ _ENSG0000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 002…      ┆           │
│ chr22      ┆ 50267888 ┆ 50792176 ┆ TYMP      ┆ … ┆ ENSG00000 ┆ -326      ┆ chr22:505 ┆ 310575    │
│            ┆          ┆          ┆           ┆   ┆ 025708    ┆           ┆ 30358:C:G ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ _ENSG0000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 002…      ┆           │
│ chr22      ┆ 50267888 ┆ 50792176 ┆ TYMP      ┆ … ┆ ENSG00000 ┆ 249       ┆ chr22:505 ┆ 310576    │
│            ┆          ┆          ┆           ┆   ┆ 025708    ┆           ┆ 29783:C:G ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ _ENSG0000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 002…      ┆           │
│ chr22      ┆ 50267888 ┆ 50792176 ┆ TYMP      ┆ … ┆ ENSG00000 ┆ 424       ┆ chr22:505 ┆ 310577    │
│            ┆          ┆          ┆           ┆   ┆ 025708    ┆           ┆ 29608:C:T ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ _ENSG0000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 002…      ┆           │
│ chr22      ┆ 50267888 ┆ 50792176 ┆ TYMP      ┆ … ┆ ENSG00000 ┆ -96       ┆ chr22:505 ┆ 310578    │
│            ┆          ┆          ┆           ┆   ┆ 025708    ┆           ┆ 30128:C:G ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ _ENSG0000 ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 002…      ┆           │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
import pandas as pd
tracks_df = pd.read_table('/home/dnanexus/data_dir/targets.txt')
descriptions = tracks_df.loc[(tracks_df.description.str.contains("RNA:")) & (~tracks_df.identifier.str.endswith("-")) ][['description', 'strand_pair']]
descriptions['description_unique'] = descriptions['description'] + '_' + descriptions['strand_pair'].astype(str)
descriptions

,description,strand_pair,description_unique
6068,RNA:aortic smooth muscle cell male adult (21 y...,6069,RNA:aortic smooth muscle cell male adult (21 y...
6070,RNA:bladder microvascular endothelial cell mal...,6071,RNA:bladder microvascular endothelial cell mal...
6072,RNA:smooth muscle cell of bladder female adult...,6073,RNA:smooth muscle cell of bladder female adult...
6074,RNA:bronchial epithelial cell female adult (40...,6075,RNA:bronchial epithelial cell female adult (40...
6076,RNA:bronchial smooth muscle cell male adult (5...,6077,RNA:bronchial smooth muscle cell male adult (5...
...,...,...,...
7606,RNA:uterus,7606,RNA:uterus_7606
7607,RNA:uterus,7607,RNA:uterus_7607
7608,RNA:vagina,7608,RNA:vagina_7608
7609,RNA:vagina,7609,RNA:vagina_7609
7610,RNA:vagina,7610,RNA:vagina_7610

In [13]:
import torch

ft = torch.load('/home/dnanexus/data_dir/flashzoi_proximal_variant_outputs.pt')
ft.shape

/tmp/ipykernel_55971/4049591451.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

torch.Size([310074, 955])

In [30]:
ftd = pd.DataFrame(ft.numpy(), columns=descriptions['description_unique'])
ftd

description_unique,RNA:aortic smooth muscle cell male adult (21 years) and male adult (54 years)_6069,RNA:bladder microvascular endothelial cell male adult (46 years) and male adult (60 years)_6071,RNA:smooth muscle cell of bladder female adult (53 years) and male adult (62 years)_6073,RNA:bronchial epithelial cell female adult (40 years) and male adult (68 years)_6075,RNA:bronchial smooth muscle cell male adult (52 years) and male adult (59 years)_6077,RNA:endothelial cell of coronary artery female adult (41 years) and male adult (77 years)_6079,RNA:smooth muscle cell of the coronary artery female adult (53 years) and male adult (55 years)_6081,RNA:regular cardiac myocyte female adult (51 years) and male adult (48 years)_6083,RNA:dermis blood vessel endothelial cell female child (16 years) and male child (13 years)_6085,RNA:dermis lymphatic vessel endothelial cell female adult (45 years) and male child (6 years)_6087,...,RNA:testis_7601,RNA:testis_7602,RNA:thyroid_7603,RNA:thyroid_7604,RNA:thyroid_7605,RNA:uterus_7606,RNA:uterus_7607,RNA:vagina_7608,RNA:vagina_7609,RNA:vagina_7610
0,0.034328,0.046779,0.029266,0.018930,0.027340,0.049201,0.030734,0.035059,0.050680,0.042054,...,0.019011,0.013907,0.032822,0.027156,0.026651,0.026215,0.028254,0.020240,0.024141,0.024800
1,0.061503,0.064823,0.068303,0.046150,0.065969,0.072363,0.073093,0.070979,0.068923,0.048946,...,0.004907,0.003166,-0.001760,0.011598,0.014402,0.014343,0.021713,0.014768,0.018208,0.008674
2,-0.000403,-0.006661,-0.000273,-0.012164,0.001300,-0.002971,0.001024,0.001002,-0.008125,-0.007624,...,-0.005669,-0.003856,-0.008218,-0.009394,-0.011210,-0.003672,-0.004704,-0.008480,-0.008946,-0.003908
3,0.259402,0.387762,0.225835,0.177836,0.206945,0.376122,0.228665,0.255292,0.434194,0.376655,...,0.161996,0.124079,0.298116,0.258942,0.267526,0.227481,0.246082,0.151274,0.179441,0.229241
4,-0.046562,-0.025547,-0.060767,-0.125197,-0.060505,-0.026640,-0.069073,-0.046660,-0.022133,-0.017918,...,0.024920,0.026958,-0.025373,-0.024949,-0.036573,-0.028627,-0.028930,-0.095686,-0.082207,-0.036477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310069,0.183394,0.165695,0.171024,0.046899,0.167805,0.175961,0.178625,0.188574,0.152215,0.151775,...,0.038162,0.029827,0.103494,0.054255,0.154296,0.075524,0.067154,0.035153,0.041460,0.076723
310070,0.009981,0.019993,0.007681,0.006753,0.007712,0.020080,0.010772,0.009511,0.017371,0.019457,...,0.003962,0.004925,0.012860,0.008444,0.028191,0.002839,0.003494,0.001128,0.002009,0.003054
310071,0.094531,0.092633,0.090705,0.081014,0.082179,0.099227,0.095468,0.097542,0.084596,0.084488,...,0.013669,0.014178,0.068066,0.044685,0.097489,0.029965,0.027070,0.032641,0.035607,0.030158
310072,0.003645,0.001232,0.004523,-0.001240,0.002162,0.000324,0.002038,0.003483,0.002515,0.003353,...,0.002700,0.002316,0.000383,0.001087,-0.003839,0.004405,0.003215,0.002364,0.002618,0.004338
310073,0.139522,0.138382,0.126188,0.134146,0.128373,0.161190,0.146739,0.152030,0.118050,0.121867,...,0.033099,0.025124,-0.012306,-0.001328,-0.042569,0.037321,0.028463,0.012133,0.008931,0.027400

In [31]:
ftd['unique_id'] = a['unique_id'].to_numpy()
ftd['id'] = ftd['unique_id'].str.split('_').str[0]
ftd['region'] = ftd['unique_id'].str.split('_').str[1]

ftd

description_unique,RNA:aortic smooth muscle cell male adult (21 years) and male adult (54 years)_6069,RNA:bladder microvascular endothelial cell male adult (46 years) and male adult (60 years)_6071,RNA:smooth muscle cell of bladder female adult (53 years) and male adult (62 years)_6073,RNA:bronchial epithelial cell female adult (40 years) and male adult (68 years)_6075,RNA:bronchial smooth muscle cell male adult (52 years) and male adult (59 years)_6077,RNA:endothelial cell of coronary artery female adult (41 years) and male adult (77 years)_6079,RNA:smooth muscle cell of the coronary artery female adult (53 years) and male adult (55 years)_6081,RNA:regular cardiac myocyte female adult (51 years) and male adult (48 years)_6083,RNA:dermis blood vessel endothelial cell female child (16 years) and male child (13 years)_6085,RNA:dermis lymphatic vessel endothelial cell female adult (45 years) and male child (6 years)_6087,...,RNA:thyroid_7604,RNA:thyroid_7605,RNA:uterus_7606,RNA:uterus_7607,RNA:vagina_7608,RNA:vagina_7609,RNA:vagina_7610,unique_id,id,region
0,0.034328,0.046779,0.029266,0.018930,0.027340,0.049201,0.030734,0.035059,0.050680,0.042054,...,0.027156,0.026651,0.026215,0.028254,0.020240,0.024141,0.024800,chr1:3652123:G:A_ENSG00000078900,chr1:3652123:G:A,ENSG00000078900
1,0.061503,0.064823,0.068303,0.046150,0.065969,0.072363,0.073093,0.070979,0.068923,0.048946,...,0.011598,0.014402,0.014343,0.021713,0.014768,0.018208,0.008674,chr1:3652442:G:T_ENSG00000078900,chr1:3652442:G:T,ENSG00000078900
2,-0.000403,-0.006661,-0.000273,-0.012164,0.001300,-0.002971,0.001024,0.001002,-0.008125,-0.007624,...,-0.009394,-0.011210,-0.003672,-0.004704,-0.008480,-0.008946,-0.003908,chr1:3652966:G:T_ENSG00000078900,chr1:3652966:G:T,ENSG00000078900
3,0.259402,0.387762,0.225835,0.177836,0.206945,0.376122,0.228665,0.255292,0.434194,0.376655,...,0.258942,0.267526,0.227481,0.246082,0.151274,0.179441,0.229241,chr1:3652415:C:G_ENSG00000078900,chr1:3652415:C:G,ENSG00000078900
4,-0.046562,-0.025547,-0.060767,-0.125197,-0.060505,-0.026640,-0.069073,-0.046660,-0.022133,-0.017918,...,-0.024949,-0.036573,-0.028627,-0.028930,-0.095686,-0.082207,-0.036477,chr1:3652543:C:G_ENSG00000078900,chr1:3652543:C:G,ENSG00000078900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310069,0.183394,0.165695,0.171024,0.046899,0.167805,0.175961,0.178625,0.188574,0.152215,0.151775,...,0.054255,0.154296,0.075524,0.067154,0.035153,0.041460,0.076723,chr22:50530512:G:A_ENSG00000025708,chr22:50530512:G:A,ENSG00000025708
310070,0.009981,0.019993,0.007681,0.006753,0.007712,0.020080,0.010772,0.009511,0.017371,0.019457,...,0.008444,0.028191,0.002839,0.003494,0.001128,0.002009,0.003054,chr22:50530358:C:G_ENSG00000025708,chr22:50530358:C:G,ENSG00000025708
310071,0.094531,0.092633,0.090705,0.081014,0.082179,0.099227,0.095468,0.097542,0.084596,0.084488,...,0.044685,0.097489,0.029965,0.027070,0.032641,0.035607,0.030158,chr22:50529783:C:G_ENSG00000025708,chr22:50529783:C:G,ENSG00000025708
310072,0.003645,0.001232,0.004523,-0.001240,0.002162,0.000324,0.002038,0.003483,0.002515,0.003353,...,0.001087,-0.003839,0.004405,0.003215,0.002364,0.002618,0.004338,chr22:50529608:C:T_ENSG00000025708,chr22:50529608:C:T,ENSG00000025708
310073,0.139522,0.138382,0.126188,0.134146,0.128373,0.161190,0.146739,0.152030,0.118050,0.121867,...,-0.001328,-0.042569,0.037321,0.028463,0.012133,0.008931,0.027400,chr22:50530128:C:G_ENSG00000025708,chr22:50530128:C:G,ENSG00000025708

In [32]:
ftd.to_parquet('/home/dnanexus/data_dir/flashzoi_proximal_variant_outputs_annotated.parquet')